/**
 * ESSENTIALS OF MEDICAL PHYSIOLOGY - Endocrinology Chapters
 * Source: Sembulingam Textbook - Endocrinology section
 * Focus: General Endocrinology, Thyroid, Parathyroid, Calcium Metabolism
 */

export const physiologyTextbookMaterial = {
  title: 'Essentials of Medical Physiology - Endocrinology',
  fileType: 'pdf',
  wordCount: 6200,
  status: 'analyzed' as const,

  summary: {
    definitions: [
      { term: '## GENERAL ENDOCRINOLOGY', definition: 'Endocrinology is the study of hormones - chemical messengers secreted into the blood by glands or specialised cells. Hormones act on distant target cells via specific receptors.' },
      { term: 'Endocrine Gland', definition: 'Ductless gland that secretes hormones directly into the bloodstream. Examples: pituitary, thyroid, adrenal, pancreas, gonads. Distinguished from exocrine glands which secrete via ducts.' },
      { term: 'Hormone', definition: 'Chemical messenger synthesized and secreted by endocrine cells, transported via blood to target cells where it produces a specific physiological response. Term coined by Ernest Starling (1905).' },
      { term: '## THYROID GLAND', definition: 'The thyroid is the largest endocrine gland (~20g), located anterior to the trachea. It produces T₃ and T₄ (from follicular cells) and calcitonin (from parafollicular C cells).' },
      { term: 'Thyroid Gland', definition: 'Butterfly-shaped gland in the anterior neck. Largest endocrine gland (~20g). Two lobes connected by isthmus. Produces T₃ (triiodothyronine), T₄ (thyroxine), and calcitonin from parafollicular C cells.' },
      { term: 'Thyroid Follicle', definition: 'Functional unit of thyroid gland. Spherical structure lined by follicular epithelial cells surrounding a central colloid (thyroglobulin). Site of thyroid hormone synthesis and storage.' },
      { term: 'Thyroglobulin', definition: 'Large glycoprotein (660 kDa) stored in thyroid follicular colloid. Serves as the precursor and storage form of thyroid hormones. Contains tyrosine residues that are iodinated to form T₃ and T₄.' },
      { term: 'Iodide Trapping', definition: 'Active transport of iodide (I⁻) into thyroid follicular cells against a concentration gradient (20-40x plasma level). Mediated by Na⁺/I⁻ symporter (NIS). Rate-limiting step controlled by TSH.' },
      { term: 'Thyroid Peroxidase (TPO)', definition: 'Key enzyme in thyroid hormone synthesis. Catalyses: 1) Oxidation of I⁻ to I₂, 2) Iodination of tyrosine residues (organification), 3) Coupling of MIT + DIT to form T₃/T₄. Target of anti-TPO antibodies in Hashimoto\'s.' },
      { term: 'Wolff-Chaikoff Effect', definition: 'Temporary inhibition of thyroid hormone synthesis when exposed to high iodide concentrations. Protective mechanism against hyperthyroidism. Basis for using potassium iodide in thyroid storm.' },
      { term: '## PARATHYROID & CALCIUM METABOLISM', definition: 'Calcium homeostasis is tightly regulated by PTH, calcitonin, and vitamin D₃ acting on bone, kidney, and gut. The parathyroid glands are the primary sensors and regulators of serum calcium.' },
      { term: 'Parathyroid Glands', definition: 'Four small glands on the posterior surface of thyroid. Chief cells secrete PTH (parathyroid hormone). Oxyphil cells function unknown. Critical for calcium homeostasis.' },
      { term: 'Parathyroid Hormone (PTH)', definition: 'Peptide hormone (84 amino acids) from chief cells. The most important regulator of calcium homeostasis. Actions: ↑bone resorption, ↑renal Ca²⁺ reabsorption, ↑1,25-dihydroxyvitamin D₃ synthesis → ↑intestinal Ca²⁺ absorption.' },
      { term: 'Calcitonin', definition: 'Peptide hormone from parafollicular C cells of thyroid. Actions: ↓bone resorption (inhibits osteoclasts), ↓serum calcium. Physiologically less important than PTH. Used therapeutically in Paget\'s disease and osteoporosis.' },
      { term: 'Vitamin D₃ (Cholecalciferol)', definition: 'Secosteroid hormone. Synthesized in skin (UV light + 7-dehydrocholesterol) → liver (25-hydroxylation) → kidney (1α-hydroxylation by PTH). Active form: 1,25-(OH)₂D₃ (calcitriol). ↑Ca²⁺ and PO₄³⁻ absorption from gut.' },
      { term: 'Tetany', definition: 'Involuntary muscle spasms caused by hypocalcaemia. Signs: Trousseau sign (carpal spasm with BP cuff), Chvostek sign (facial twitch on tapping). Occurs when ionised Ca²⁺ drops below 4.3 mg/dL.' },
      { term: 'Graves\' Disease', definition: 'Autoimmune hyperthyroidism caused by thyroid-stimulating immunoglobulins (TSI) that activate TSH receptors. Features: diffuse goitre, exophthalmos, pretibial myxedema, weight loss, heat intolerance, tremor.' },
      { term: 'Hashimoto\'s Thyroiditis', definition: 'Autoimmune hypothyroidism. Most common cause of hypothyroidism in iodine-sufficient areas. Anti-TPO and anti-thyroglobulin antibodies. Gradual destruction of thyroid tissue → hypothyroidism.' },
      { term: 'Myxedema', definition: 'Severe hypothyroidism in adults. Features: non-pitting oedema (mucopolysaccharide accumulation), cold intolerance, weight gain, constipation, bradycardia, coarse dry skin, delayed reflexes, mental slowness.' },
      { term: 'Cretinism', definition: 'Hypothyroidism in infants/children. Features: mental retardation, growth failure, coarse facial features, large tongue, umbilical hernia, delayed bone age. Prevented by neonatal screening (TSH).' },
      { term: 'Deiodinase Enzymes', definition: 'Convert T₄ to T₃ (activation) or rT₃ (inactivation). Type I: liver/kidney (main peripheral conversion). Type II: brain/pituitary (local T₃ production). Type III: placenta/brain (inactivation, produces rT₃).' },
    ],

    keyPoints: [
      '## THYROID GLAND',
      '>> The thyroid produces hormones essential for metabolism, growth, and development. Thyroid hormone synthesis depends on iodine and is regulated by the hypothalamic-pituitary-thyroid axis.',
      '### Definition',
      'Largest endocrine gland (~20g). Butterfly-shaped. Located anterior to trachea at C5-T1 level',
      '### Basic Properties',
      '2 cell types: Follicular cells (produce T₃/T₄) and Parafollicular C cells (produce calcitonin)',
      'T₄ (thyroxine, 90% of output) is the major secretory product. T₃ (10%) is 3-5x more potent. Most T₃ from peripheral deiodination of T₄',
      'T₃ and T₄ are the ONLY hormones that require a trace element (iodine) for synthesis',
      'Synthesis (6 steps): 1) Iodide trapping (NIS), 2) Oxidation (TPO), 3) Organification (TPO), 4) Coupling (MIT+DIT=T₃, DIT+DIT=T₄), 5) Storage in colloid, 6) Proteolysis and release',
      'In blood: 99.97% of T₄ is protein-bound (TBG 70%, albumin 20%, TBPA 10%). Only FREE hormone is biologically active',
      'Receptor: NUCLEAR receptor (like steroids). Acts as a transcription factor, altering gene expression',
      '### Functions/Effects',
      'Thyroid hormone actions: ↑BMR (calorigenic effect - most important), ↑O₂ consumption, thermogenesis, growth and development, CNS maturation, ↑heart rate and contractility',
      '### Regulation',
      'TSH (anterior pituitary) is the main regulator. TRH (hypothalamus) stimulates TSH. T₃/T₄ provide negative feedback',
      'TSH actions on thyroid: ↑iodide trapping, ↑T₃/T₄ synthesis, ↑proteolysis and release, ↑vascularity, ↑gland size',
      '### Abnormalities',
      'Hyperthyroidism: Graves\' disease (autoimmune TSI antibodies). Hypothyroidism: Hashimoto\'s (anti-TPO antibodies)',
      'Cretinism = hypothyroidism in children (mental retardation). Myxedema = severe hypothyroidism in adults',
      '### Clinical Features',
      'Graves\': diffuse goitre, exophthalmos, pretibial myxedema, weight loss, heat intolerance, tremor',
      'Myxedema: non-pitting oedema, cold intolerance, weight gain, constipation, bradycardia, delayed reflexes',
      '### Diagnosis',
      'TSH (first-line), Free T₃/T₄, Anti-TPO antibodies (Hashimoto\'s), TSI antibodies (Graves\')',
      '### Treatment',
      'Graves\': antithyroid drugs, radioactive iodine, surgery. Hashimoto\'s: levothyroxine replacement',
      'Thyroid storm: propranolol, propylthiouracil, potassium iodide, hydrocortisone',

      '## PARATHYROID & CALCIUM METABOLISM',
      '>> Calcium is critical for nerve conduction, muscle contraction, and bone structure. PTH is the master regulator - it raises calcium by acting on bone, kidney, and (indirectly) gut via vitamin D₃.',
      '### Definition',
      'Four small glands on posterior surface of thyroid. Chief cells secrete PTH. Critical for calcium homeostasis',
      '### Basic Properties',
      'PTH: 84 amino acids, from chief cells. MOST IMPORTANT Ca²⁺ regulator',
      'Normal serum calcium: 9-11 mg/dL. 3 forms: ionised/free (50%), protein-bound (40%), complexed (10%)',
      'Vitamin D₃ pathway: Skin (UV + 7-DHC → D₃) → Liver (25-hydroxylase) → Kidney (1α-hydroxylase → calcitriol = ACTIVE form)',
      'Calcitonin from C cells opposes PTH: ↓bone resorption → ↓serum Ca²⁺. Less important in adults',
      '### Functions/Effects',
      'PTH on BONE: ↑osteoclast activity → bone resorption → ↑Ca²⁺ and PO₄³⁻ into blood',
      'PTH on KIDNEY: ↑Ca²⁺ reabsorption (distal tubule), ↓PO₄³⁻ reabsorption (phosphaturic), ↑1α-hydroxylase → ↑active vitamin D₃',
      'PTH on GUT: INDIRECT via vitamin D₃ → ↑intestinal Ca²⁺ absorption',
      'Net effect of PTH: ↑serum Ca²⁺, ↓serum PO₄³⁻',
      'Calcium functions: bone structure, muscle contraction, nerve conduction, blood clotting, enzyme activation, hormone secretion',
      '### Regulation',
      'PTH secreted in response to ↓ionised Ca²⁺ (detected by calcium-sensing receptor on chief cells)',
      '### Abnormalities',
      'Hypoparathyroidism: most commonly post-thyroidectomy. ↓Ca²⁺, ↑PO₄³⁻, ↓PTH → tetany',
      'Primary hyperparathyroidism: parathyroid adenoma (80%). ↑Ca²⁺, ↓PO₄³⁻, ↑PTH',
      '### Clinical Features',
      'Hypocalcaemia → tetany (Trousseau sign, Chvostek sign). Hypercalcaemia → "stones, bones, groans, moans"',
      '### Diagnosis',
      'Serum Ca²⁺, PO₄³⁻, PTH levels, 25-OH Vitamin D, alkaline phosphatase',
      '### Treatment',
      'Hypoparathyroidism: calcium + vitamin D supplements. Hyperparathyroidism: surgery (parathyroidectomy)',

      '## GENERAL ENDOCRINOLOGY PRINCIPLES',
      '>> Foundational concepts about hormone classification, transport, signalling, and control.',
      '### Basic Properties',
      'Classification: 1) Peptide/protein (insulin, GH, PTH), 2) Steroid (cortisol, aldosterone, sex hormones), 3) Amine (thyroid, catecholamines), 4) Eicosanoid (prostaglandins)',
      'Water-soluble hormones: surface receptors + second messengers. Rapid onset, short duration',
      'Lipid-soluble hormones: cross membrane → nuclear receptors → gene expression. Slow onset, long duration',
      'Transport: Water-soluble travel FREE in blood. Lipid-soluble bind carrier proteins. Only FREE hormone is active',
      '### Regulation',
      'Negative feedback = most common (↑hormone → ↓stimulating hormone). Positive feedback = rare (oxytocin, LH surge)',
      'Half-life varies: Catecholamines (seconds), Peptides (minutes), Steroids (hours), Thyroid hormones (days)',
    ],

    examHighlights: [
      '## THYROID GLAND',
      '>> These thyroid facts are the most commonly tested in physiology exams.',
      '### Hormone Potency & Production',
      'T₃ is 3-5x more potent than T₄ but T₄ is the major secretory product (90%). Most T₃ is from peripheral conversion.',
      'Only FREE (unbound) thyroid hormone is biologically active. Total T₄ changes with TBG changes but free T₄ remains constant.',
      'Thyroid hormones are the only hormones requiring iodine (a trace element) for synthesis.',
      '### Binding Protein Changes',
      'TBG levels ↑ in pregnancy, OCP use, hepatitis → ↑total T₄ but FREE T₄ normal → euthyroid.',
      '### Protective Mechanisms',
      'Wolff-Chaikoff effect: excess iodide temporarily blocks thyroid hormone synthesis. Protective.',
      '### Diseases to Know',
      'Graves\' disease: TSI antibodies stimulate TSH receptor. ONLY cause of true hyperthyroid exophthalmos.',
      'Hashimoto\'s = most common cause of hypothyroidism in iodine-sufficient areas. Anti-TPO antibodies.',
      'Cretinism = hypothyroidism in children. Myxedema = severe hypothyroidism in adults.',
      'Neonatal screening for TSH detects congenital hypothyroidism early to prevent cretinism.',
      '## PARATHYROID & CALCIUM METABOLISM',
      '>> PTH and vitamin D₃ are the highest-yield calcium topics.',
      '### Key Hormones',
      'PTH is the MOST IMPORTANT calcium regulator. PTH ↑Ca²⁺ and ↓PO₄³⁻. Calcitonin ↓Ca²⁺.',
      '### PTH Target Organs',
      'PTH acts on bone and kidney DIRECTLY but on gut INDIRECTLY (via vitamin D₃).',
      '### Clinical Signs',
      'Trousseau sign (carpal spasm) and Chvostek sign (facial twitch) = signs of hypocalcaemia/tetany.',
    ],

    clinicalCorrelations: [
      '## THYROID DISORDERS',
      '>> Clinical conditions of the thyroid range from goitre (iodine deficiency) to autoimmune diseases (Graves\', Hashimoto\'s) to thyroid emergencies (thyroid storm).',
      '### Iodine Deficiency',
      'Goitre: enlarged thyroid gland. Simple/endemic goitre = iodine deficiency → ↓T₃/T₄ → ↑TSH → thyroid hyperplasia. Prevented by iodised salt.',
      '### Autoimmune - Hyperthyroidism',
      'Graves\' disease: autoimmune hyperthyroidism. TSI (thyroid-stimulating immunoglobulin) mimics TSH. Diffuse goitre + exophthalmos + pretibial myxedema. Treatment: antithyroid drugs, radioactive iodine, surgery.',
      '### Autoimmune - Hypothyroidism',
      'Hashimoto\'s thyroiditis: autoimmune hypothyroidism. Anti-TPO and anti-thyroglobulin antibodies. Painless goitre → gradual destruction → hypothyroidism. Treatment: levothyroxine replacement.',
      '### Thyroid Emergencies',
      'Thyroid storm: life-threatening hyperthyroidism. Triggered by surgery/infection in uncontrolled Graves\'. Features: high fever, tachycardia, altered consciousness. Treatment: propranolol, propylthiouracil, potassium iodide, hydrocortisone.',
      '### Inflammatory',
      'De Quervain\'s thyroiditis: subacute granulomatous thyroiditis. Post-viral. Painful tender thyroid. Initially hyperthyroid → hypothyroid → recovery. Self-limiting.',
      '## PARATHYROID & CALCIUM DISORDERS',
      '>> Calcium disorders present with characteristic clinical features - "stones, bones, groans, and moans" for hyperparathyroidism, and tetany for hypoparathyroidism.',
      '### Hypoparathyroidism',
      'Hypoparathyroidism: most commonly post-thyroidectomy (accidental removal). ↓Ca²⁺, ↑PO₄³⁻, ↓PTH. Tetany, Trousseau, Chvostek. Treatment: calcium + vitamin D supplements.',
      '### Hyperparathyroidism',
      'Primary hyperparathyroidism: usually parathyroid adenoma (80%). ↑Ca²⁺, ↓PO₄³⁻, ↑PTH. "Stones (renal), bones (pain), abdominal groans (constipation), psychiatric moans (depression)."',
      '### Bone Diseases',
      'Osteoporosis: decreased bone density. Risk factors: postmenopausal (↓estrogen), ↓calcium/vitamin D, inactivity. Fractures of vertebrae, hip, wrist. Prevention: exercise, calcium, vitamin D.',
      'Rickets (children) / Osteomalacia (adults): vitamin D deficiency → ↓Ca²⁺ absorption → soft bones. Rickets: bowing of legs, rachitic rosary, craniotabes. Osteomalacia: bone pain, proximal myopathy.',
      'Paget\'s disease: excessive bone remodelling (osteoclast overactivity → osteoblast compensation). ↑alkaline phosphatase, normal Ca²⁺/PO₄³⁻. Skull enlargement, bone pain. Treatment: bisphosphonates, calcitonin.',
    ],

    processes: [
      {
        name: 'Thyroid Hormone Synthesis (6 Steps)',
        steps: [
          'Step 1 - Iodide Trapping: I⁻ actively transported into follicular cell by Na⁺/I⁻ symporter (NIS). 20-40x concentration gradient. TSH stimulated.',
          'Step 2 - Oxidation: I⁻ oxidised to I₂ by thyroid peroxidase (TPO) at the apical membrane.',
          'Step 3 - Organification: I₂ incorporated into tyrosine residues on thyroglobulin → MIT (monoiodotyrosine) and DIT (diiodotyrosine). TPO catalyses.',
          'Step 4 - Coupling: MIT + DIT = T₃. DIT + DIT = T₄. More T₄ is made than T₃. TPO catalyses.',
          'Step 5 - Storage: Iodinated thyroglobulin stored as colloid in follicular lumen. Enough for ~100 days.',
          'Step 6 - Release: TSH stimulates endocytosis of colloid → proteolysis → T₃ and T₄ released into blood. MIT and DIT recycled (deiodinated, iodine reused).',
        ],
      },
      {
        name: 'Vitamin D₃ Activation Pathway',
        steps: [
          'Skin: UV-B light converts 7-dehydrocholesterol → Cholecalciferol (Vitamin D₃)',
          'Liver: 25-hydroxylase converts Vitamin D₃ → 25-hydroxyvitamin D₃ (calcidiol) - storage form, used for clinical measurement',
          'Kidney: 1α-hydroxylase converts 25-(OH)D₃ → 1,25-dihydroxyvitamin D₃ (calcitriol) - ACTIVE form',
          'PTH stimulates 1α-hydroxylase activity (the renal activation step)',
          'Active vitamin D₃ acts on intestine (↑Ca²⁺ and PO₄³⁻ absorption), bone (↑mineralisation), and kidney (↑Ca²⁺ reabsorption)',
        ],
      },
      {
        name: 'PTH Response to Hypocalcaemia',
        steps: [
          'Serum ionised Ca²⁺ drops below normal',
          'Calcium-sensing receptor (CaSR) on parathyroid chief cells detects the drop',
          'PTH secretion increases within minutes',
          'Bone: PTH activates osteoclasts → bone resorption → Ca²⁺ and PO₄³⁻ released',
          'Kidney: PTH ↑Ca²⁺ reabsorption (distal tubule) + ↓PO₄³⁻ reabsorption (proximal tubule)',
          'Kidney: PTH ↑1α-hydroxylase → ↑active vitamin D₃ production',
          'Gut: Active vitamin D₃ → ↑intestinal Ca²⁺ absorption (indirect PTH effect)',
          'Result: serum Ca²⁺ rises back to normal. Negative feedback on PTH secretion.',
        ],
      },
    ],

    mnemonics: [
      { topic: 'Thyroid Hormone Synthesis', mnemonic: 'TOXIC - Trapping, Oxidation, eXchange (organification), Iodo-coupling, Collection (storage + release)', explanation: 'Steps of thyroid hormone synthesis in order: Trapping (NIS), Oxidation (TPO), Organification/exchange, Coupling (MIT+DIT), Collection/release by TSH.' },
      { topic: 'TBG Levels', mnemonic: 'TBG ↑ in Pregnancy and Pills (OCP), ↓ in Nephrosis and Androgens', explanation: 'Conditions that change TBG: Pregnancy/OCP/hepatitis → ↑TBG → ↑total T₄ (but free T₄ normal). Nephrotic syndrome/androgens/steroids → ↓TBG → ↓total T₄ (but free T₄ normal).' },
      { topic: 'PTH Actions', mnemonic: 'PTH = Phosphate Trashing Hormone', explanation: 'PTH TRASHES phosphate (↑phosphate excretion by kidneys) while raising calcium. Net effect: ↑Ca²⁺, ↓PO₄³⁻ in blood.' },
      { topic: 'Hyperparathyroidism Features', mnemonic: 'Stones, Bones, Abdominal Groans, Psychiatric Moans', explanation: 'Stones (renal calculi), Bones (bone pain/fractures), Abdominal groans (constipation, pancreatitis), Psychiatric moans (depression, confusion).' },
      { topic: 'Vitamin D Pathway', mnemonic: 'Skin → Liver → Kidney (SLK - "SaLaKa")', explanation: 'Vitamin D activation path: Skin (UV + 7-DHC → D₃) → Liver (25-hydroxylation) → Kidney (1α-hydroxylation → active calcitriol). PTH activates the kidney step.' },
      { topic: 'Hyperthyroidism Signs', mnemonic: 'THYROIDISM - Tremor, Heart rate↑, Yawning/fatigue, Restlessness, Oligomenorrhoea, Intolerance to heat, Diarrhoea, Irritability, Sweating, Muscle wasting', explanation: 'Common signs/symptoms of hyperthyroidism.' },
      { topic: 'Hypothyroidism Signs', mnemonic: 'SLOWNESS - Sleepy, Lethargic, Obesity, Weight gain, Numbness, Edema (non-pitting), Sensitivity to cold, Slow reflexes', explanation: 'Common signs/symptoms of hypothyroidism (myxedema).' },
    ],

    quickReview: [
      'Thyroid = largest endocrine gland. T₄ (90%) and T₃ (10%). T₃ is 3-5x more potent. Most T₃ from peripheral T₄ conversion.',
      'Thyroid hormone synthesis needs iodine + TPO. 6 steps: Trap → Oxidise → Organify → Couple → Store → Release.',
      'TSH is the main thyroid regulator. TRH → TSH → T₃/T₄. Negative feedback by T₃/T₄.',
      'Only FREE hormone is active. 99.97% of T₄ is protein-bound (TBG main carrier).',
      'PTH = most important Ca²⁺ regulator. ↑Ca²⁺, ↓PO₄³⁻. Acts on bone (directly) + kidney (directly) + gut (indirectly via vitamin D).',
      'Vitamin D₃: Skin → Liver → Kidney. PTH stimulates the final kidney activation step.',
      'Hypocalcaemia → tetany (Trousseau, Chvostek). Hypercalcaemia → stones, bones, groans, moans.',
      'Graves\' = autoimmune hyperthyroidism (TSI antibodies). Hashimoto\'s = autoimmune hypothyroidism (anti-TPO).',
      'Cretinism = hypothyroidism in children (mental retardation). Myxedema = hypothyroidism in adults.',
      'Calcitonin from C cells: ↓Ca²⁺ (opposes PTH). Less important in adults. Used in Paget\'s disease.',
    ],
  },

  questions: [
    // THYROID MCQs
    { questionType: 'mcq', question: 'The thyroid gland is the:', options: ['A) Smallest endocrine gland', 'B) Largest endocrine gland', 'C) Second largest endocrine gland', 'D) Third largest endocrine gland'], correctAnswer: 'B) Largest endocrine gland', explanation: 'The thyroid gland (~20g) is the largest endocrine gland in the body. It is butterfly-shaped and located anterior to the trachea at C5-T1 level.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which is the MOST potent thyroid hormone?', options: ['A) T₄ (thyroxine)', 'B) T₃ (triiodothyronine)', 'C) rT₃ (reverse T₃)', 'D) MIT'], correctAnswer: 'B) T₃ (triiodothyronine)', explanation: 'T₃ is 3-5 times more potent than T₄. However, T₄ is the major secretory product (90%). Most T₃ is produced by peripheral deiodination of T₄ in liver and kidney.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The Na⁺/I⁻ symporter (NIS) is responsible for:', options: ['A) Thyroid hormone coupling', 'B) Iodide trapping', 'C) Thyroglobulin synthesis', 'D) T₃ to T₄ conversion'], correctAnswer: 'B) Iodide trapping', explanation: 'The Na⁺/I⁻ symporter (NIS) actively transports iodide into thyroid follicular cells against a 20-40x concentration gradient. This is the first step in thyroid hormone synthesis.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Thyroid peroxidase (TPO) catalyses all EXCEPT:', options: ['A) Oxidation of I⁻ to I₂', 'B) Iodination of tyrosine (organification)', 'C) Coupling of MIT and DIT', 'D) Iodide trapping by NIS'], correctAnswer: 'D) Iodide trapping by NIS', explanation: 'TPO catalyses oxidation, organification, and coupling. Iodide trapping is done by NIS (Na⁺/I⁻ symporter), a separate transporter protein on the basolateral membrane.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The major carrier protein for thyroid hormones in blood is:', options: ['A) Albumin', 'B) TBPA (transthyretin)', 'C) TBG (thyroxine-binding globulin)', 'D) Sex hormone-binding globulin'], correctAnswer: 'C) TBG (thyroxine-binding globulin)', explanation: 'TBG carries ~70% of circulating T₄ and T₃. Albumin carries ~20% and TBPA (transthyretin) carries ~10%. Only free (unbound) hormone is biologically active.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The Wolff-Chaikoff effect refers to:', options: ['A) Thyroid hormone resistance', 'B) Temporary inhibition of thyroid hormone synthesis by excess iodide', 'C) Stimulation of thyroid by TSH', 'D) Autoimmune thyroid destruction'], correctAnswer: 'B) Temporary inhibition of thyroid hormone synthesis by excess iodide', explanation: 'The Wolff-Chaikoff effect is a protective autoregulatory mechanism. High iodide levels temporarily block organification, preventing excess thyroid hormone production. This is the basis for potassium iodide use in thyroid storm.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'The most important action of thyroid hormones is:', options: ['A) Growth promotion', 'B) Calorigenic effect (↑BMR)', 'C) Brain development', 'D) Bone maturation'], correctAnswer: 'B) Calorigenic effect (↑BMR)', explanation: 'The calorigenic effect (increasing basal metabolic rate and O₂ consumption) is the most important action. Thyroid hormones increase heat production in virtually all tissues except brain, spleen, and gonads.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Thyroid hormone receptors are located:', options: ['A) On the cell membrane', 'B) In the cytoplasm', 'C) In the nucleus', 'D) On mitochondria'], correctAnswer: 'C) In the nucleus', explanation: 'Thyroid hormone receptors (TR-alpha and TR-beta) are nuclear receptors that act as transcription factors. Despite being amine derivatives, thyroid hormones behave like steroids - they cross the cell membrane and bind nuclear receptors.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which condition causes an increase in TBG levels?', options: ['A) Nephrotic syndrome', 'B) Androgen therapy', 'C) Pregnancy', 'D) Chronic liver disease'], correctAnswer: 'C) Pregnancy', explanation: 'Pregnancy and OCP (estrogen) ↑TBG production by the liver. This ↑total T₄ but free T₄ remains normal → patient is euthyroid. Nephrotic syndrome and androgens ↓TBG.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Congenital hypothyroidism (cretinism) is prevented by:', options: ['A) Iodised salt', 'B) Neonatal TSH screening', 'C) Vitamin D supplementation', 'D) Calcium supplementation'], correctAnswer: 'B) Neonatal TSH screening', explanation: 'Neonatal TSH screening detects congenital hypothyroidism early (within first week). Early levothyroxine replacement prevents irreversible mental retardation. Iodised salt prevents endemic goitre, not congenital hypothyroidism.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'The enzyme that converts T₄ to T₃ in peripheral tissues is:', options: ['A) Thyroid peroxidase', 'B) Deiodinase', 'C) Monoamine oxidase', 'D) COMT'], correctAnswer: 'B) Deiodinase', explanation: 'Type I deiodinase (liver/kidney) is the main enzyme converting T₄ to T₃ peripherally. Type II (brain/pituitary) provides local T₃. Type III converts T₄ to inactive rT₃.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Graves\' disease is caused by:', options: ['A) TSH-secreting pituitary adenoma', 'B) Thyroid-stimulating immunoglobulins (TSI)', 'C) Anti-TPO antibodies', 'D) Iodine excess'], correctAnswer: 'B) Thyroid-stimulating immunoglobulins (TSI)', explanation: 'TSI (IgG antibodies) bind and stimulate TSH receptors on thyroid cells, causing unregulated thyroid hormone production. This is the only cause of hyperthyroid exophthalmos.', difficulty: 'medium' },

    // PARATHYROID / CALCIUM MCQs
    { questionType: 'mcq', question: 'The MOST IMPORTANT regulator of serum calcium is:', options: ['A) Calcitonin', 'B) Vitamin D₃', 'C) PTH', 'D) Thyroid hormone'], correctAnswer: 'C) PTH', explanation: 'PTH is the most important and immediate regulator of calcium homeostasis. It responds within minutes to ↓Ca²⁺. Calcitonin is less important in adults. Vitamin D₃ is slower acting.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'PTH acts on the gut:', options: ['A) Directly', 'B) Indirectly via vitamin D₃', 'C) Through calcitonin', 'D) PTH does not affect the gut'], correctAnswer: 'B) Indirectly via vitamin D₃', explanation: 'PTH acts on bone and kidney DIRECTLY. On gut, PTH acts INDIRECTLY: PTH → ↑1α-hydroxylase in kidney → ↑active vitamin D₃ → ↑intestinal Ca²⁺ absorption.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The net effect of PTH on serum phosphate is:', options: ['A) Increase', 'B) Decrease', 'C) No change', 'D) Variable'], correctAnswer: 'B) Decrease', explanation: 'PTH is called the "Phosphate Trashing Hormone". It ↓PO₄³⁻ reabsorption in the proximal tubule → phosphaturia → ↓serum PO₄³⁻. This occurs despite PO₄³⁻ release from bone resorption.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Trousseau sign (carpal spasm with BP cuff inflation) indicates:', options: ['A) Hypercalcaemia', 'B) Hypocalcaemia', 'C) Hypernatraemia', 'D) Hyperkalaemia'], correctAnswer: 'B) Hypocalcaemia', explanation: 'Trousseau sign is positive when inflating a BP cuff (above systolic) for 3 minutes causes carpal spasm. It indicates hypocalcaemia/latent tetany. Chvostek sign (facial twitch on tapping) is another sign.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The active form of vitamin D₃ is:', options: ['A) Cholecalciferol', 'B) 25-hydroxyvitamin D₃', 'C) 1,25-dihydroxyvitamin D₃ (calcitriol)', 'D) 7-dehydrocholesterol'], correctAnswer: 'C) 1,25-dihydroxyvitamin D₃ (calcitriol)', explanation: '1,25-(OH)₂D₃ (calcitriol) is the active form. Produced in kidney by 1α-hydroxylase (stimulated by PTH). 25-OH-D₃ (calcidiol) is the storage form measured clinically.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Calcitonin is secreted by:', options: ['A) Chief cells of parathyroid', 'B) Follicular cells of thyroid', 'C) Parafollicular C cells of thyroid', 'D) Oxyphil cells of parathyroid'], correctAnswer: 'C) Parafollicular C cells of thyroid', explanation: 'Parafollicular C cells (between thyroid follicles) secrete calcitonin when serum Ca²⁺ is HIGH. Calcitonin ↓bone resorption → ↓serum Ca²⁺. It opposes PTH.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Primary hyperparathyroidism is MOST COMMONLY caused by:', options: ['A) Parathyroid hyperplasia', 'B) Parathyroid carcinoma', 'C) Parathyroid adenoma', 'D) Ectopic PTH secretion'], correctAnswer: 'C) Parathyroid adenoma', explanation: 'Parathyroid adenoma (single gland) accounts for ~80% of primary hyperparathyroidism cases. Hyperplasia accounts for ~15%, carcinoma <5%. Features: "Stones, bones, abdominal groans, psychiatric moans."', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Rickets in children is caused by deficiency of:', options: ['A) Vitamin A', 'B) Vitamin B₁₂', 'C) Vitamin C', 'D) Vitamin D'], correctAnswer: 'D) Vitamin D', explanation: 'Vitamin D deficiency → ↓Ca²⁺ absorption → poor bone mineralisation. Rickets (children): bowing of legs, rachitic rosary, craniotabes, delayed fontanelle closure. Osteomalacia is the adult equivalent.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The calcium-sensing receptor (CaSR) is located on:', options: ['A) Thyroid follicular cells', 'B) Parathyroid chief cells', 'C) Osteoclasts', 'D) Intestinal epithelium'], correctAnswer: 'B) Parathyroid chief cells', explanation: 'The CaSR on parathyroid chief cells detects changes in ionised Ca²⁺. When Ca²⁺ drops, CaSR triggers ↑PTH secretion. When Ca²⁺ rises, CaSR suppresses PTH secretion.', difficulty: 'hard' },

    // GENERAL ENDOCRINOLOGY MCQs
    { questionType: 'mcq', question: 'Which hormone has the LONGEST half-life?', options: ['A) Epinephrine', 'B) Insulin', 'C) T₄ (thyroxine)', 'D) Cortisol'], correctAnswer: 'C) T₄ (thyroxine)', explanation: 'T₄ half-life is 6-7 days - the longest of common hormones. This is because T₄ is heavily protein-bound (99.97%). Epinephrine = seconds. Insulin = ~5 min. Cortisol = ~90 min.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Positive feedback in endocrinology occurs in all EXCEPT:', options: ['A) Oxytocin during labour', 'B) LH surge causing ovulation', 'C) Cortisol suppressing CRH', 'D) Estrogen surge before ovulation'], correctAnswer: 'C) Cortisol suppressing CRH', explanation: 'Cortisol suppressing CRH is NEGATIVE feedback (the most common). Positive feedback (rare): oxytocin during labour, LH surge from rising estrogen, and prolactin stimulating its own secretion during suckling.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Thyroid hormones are unique among amine hormones because they:', options: ['A) Act via surface receptors', 'B) Have very short half-lives', 'C) Bind nuclear receptors like steroid hormones', 'D) Are water-soluble'], correctAnswer: 'C) Bind nuclear receptors like steroid hormones', explanation: 'Despite being amine derivatives (from tyrosine), thyroid hormones are lipid-soluble, cross the cell membrane, and bind NUCLEAR receptors (like steroids). This is unique among amine hormones.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'An iodine-deficient diet leads to:', options: ['A) Hyperthyroidism', 'B) Endemic goitre', 'C) Thyroid cancer', 'D) Myxedema coma'], correctAnswer: 'B) Endemic goitre', explanation: 'Iodine deficiency → ↓T₃/T₄ synthesis → ↑TSH (loss of negative feedback) → thyroid hyperplasia → goitre. This is called simple/endemic/colloid goitre. Prevented by iodised salt.', difficulty: 'easy' },

    // CLINICAL SCENARIO MCQs
    { questionType: 'mcq', question: 'A 35-year-old woman presents with weight loss, tremor, palpitations, and protruding eyes. Lab shows: TSH suppressed, Free T₄ elevated. The MOST LIKELY diagnosis is:', options: ['A) Hashimoto\'s thyroiditis', 'B) Graves\' disease', 'C) Toxic multinodular goitre', 'D) De Quervain\'s thyroiditis'], correctAnswer: 'B) Graves\' disease', explanation: 'Young woman + weight loss + tremor + palpitations + exophthalmos (protruding eyes) + suppressed TSH + elevated free T₄ = Graves\' disease. Exophthalmos is almost pathognomonic for Graves\'. TSI antibodies are the cause.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A patient post-thyroidectomy develops perioral tingling, muscle cramps, and positive Trousseau sign. The MOST LIKELY cause is:', options: ['A) Hyperkalaemia', 'B) Hypocalcaemia from hypoparathyroidism', 'C) Hypothyroidism', 'D) Recurrent laryngeal nerve injury'], correctAnswer: 'B) Hypocalcaemia from hypoparathyroidism', explanation: 'Post-thyroidectomy tingling + muscle cramps + Trousseau sign = hypocalcaemia from accidental removal of parathyroid glands. This is the most common serious post-thyroidectomy complication.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A child from a rural area with iodine-poor soil has a large neck swelling, mental retardation, and short stature. The diagnosis is:', options: ['A) Graves\' disease', 'B) Endemic cretinism', 'C) Congenital adrenal hyperplasia', 'D) GH deficiency'], correctAnswer: 'B) Endemic cretinism', explanation: 'Iodine-poor area + goitre + mental retardation + growth failure = endemic cretinism. Iodine deficiency in pregnancy/infancy → inadequate thyroid hormones for brain development → irreversible damage.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A patient with primary hyperparathyroidism would show:', options: ['A) ↑Ca²⁺, ↑PO₄³⁻, ↑PTH', 'B) ↑Ca²⁺, ↓PO₄³⁻, ↑PTH', 'C) ↓Ca²⁺, ↑PO₄³⁻, ↓PTH', 'D) ↓Ca²⁺, ↓PO₄³⁻, ↑PTH'], correctAnswer: 'B) ↑Ca²⁺, ↓PO₄³⁻, ↑PTH', explanation: 'Primary hyperparathyroidism (usually adenoma): excess PTH → ↑bone resorption → ↑Ca²⁺. PTH is phosphaturic → ↓PO₄³⁻. PTH is elevated because the adenoma secretes autonomously.', difficulty: 'hard' },

    // TRUE/FALSE
    { questionType: 'true_false', question: 'T₄ is the major secretory product of the thyroid gland (90%). True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'The thyroid secretes mostly T₄ (90%) and some T₃ (10%). However, T₃ is the more potent form. Most circulating T₃ comes from peripheral conversion of T₄ by deiodinase enzymes.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'PTH acts directly on the intestine to increase calcium absorption. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'PTH acts on gut INDIRECTLY - via vitamin D₃. PTH → stimulates 1α-hydroxylase in kidney → ↑active vitamin D₃ → this vitamin D₃ then increases intestinal calcium absorption.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Calcitonin is more important than PTH in calcium regulation in adults. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'PTH is the most important calcium regulator. Calcitonin plays a minor role in adults. Total thyroidectomy (removing all C cells) does NOT cause significant calcium disturbance, proving calcitonin is not essential.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Olfaction is the only sensation that bypasses the thalamus. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Olfaction projects directly from olfactory bulb to olfactory cortex without thalamic relay. All other sensory modalities (vision, hearing, touch, taste) relay through specific thalamic nuclei.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Thyroid hormones are the only hormones that require a trace element (iodine) for synthesis. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Iodine is a trace element essential for T₃ and T₄ synthesis. No other hormone requires a trace element for its synthesis. Daily requirement is 150 μg for adults.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Hashimoto\'s thyroiditis initially presents as hypothyroidism. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Hashimoto\'s can initially present with a brief HASHItoxicosis phase (transient hyperthyroidism due to thyroid destruction releasing stored hormones), before progressing to permanent hypothyroidism.', difficulty: 'hard' },

    // FILL IN THE BLANK
    { questionType: 'fill_blank', question: 'The active form of vitamin D₃ is _____ (also called calcitriol).', options: [], correctAnswer: '1,25-dihydroxyvitamin D₃', explanation: '1,25-(OH)₂D₃ is the active form, produced in the kidney by 1α-hydroxylase. PTH stimulates this final activation step. 25-(OH)D₃ (calcidiol) is the storage form.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The enzyme _____ is the target of anti-TPO antibodies in Hashimoto\'s thyroiditis.', options: [], correctAnswer: 'Thyroid peroxidase (TPO)', explanation: 'Anti-TPO antibodies target thyroid peroxidase, the key enzyme in thyroid hormone synthesis. These antibodies cause gradual autoimmune destruction of the thyroid gland.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The mnemonic "Stones, Bones, Abdominal Groans, Psychiatric Moans" describes the features of _____.', options: [], correctAnswer: 'Hyperparathyroidism (primary)', explanation: 'Stones (renal calculi from hypercalciuria), Bones (bone pain/osteitis fibrosa cystica), Abdominal groans (constipation, pancreatitis, peptic ulcer), Psychiatric moans (depression, confusion, psychosis).', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'The Na⁺/I⁻ _____ (NIS) is responsible for iodide trapping in the thyroid.', options: [], correctAnswer: 'symporter', explanation: 'NIS (Na⁺/I⁻ symporter) is an active transporter that co-transports Na⁺ and I⁻ into thyroid follicular cells. This concentrates iodide 20-40 times above plasma levels.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The Wolff-Chaikoff effect is the temporary inhibition of thyroid hormone synthesis by excess _____.', options: [], correctAnswer: 'iodide', explanation: 'High iodide concentrations temporarily block organification (iodination step), protecting against hyperthyroidism. This autoregulatory mechanism is called the Wolff-Chaikoff effect.', difficulty: 'hard' },

    // ADDITIONAL THYROID MCQs
    { questionType: 'mcq', question: 'The rate-limiting step in thyroid hormone synthesis is:', options: ['A) Coupling', 'B) Organification', 'C) Iodide trapping by NIS', 'D) Proteolysis'], correctAnswer: 'C) Iodide trapping by NIS', explanation: 'Iodide trapping by the Na⁺/I⁻ symporter (NIS) is the first and rate-limiting step. It is stimulated by TSH and inhibited by perchlorate and thiocyanate ions.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which drug is used to block iodide trapping in the thyroid?', options: ['A) Propylthiouracil', 'B) Methimazole', 'C) Perchlorate', 'D) Propranolol'], correctAnswer: 'C) Perchlorate', explanation: 'Perchlorate competitively inhibits the NIS transporter, blocking iodide uptake. Propylthiouracil and methimazole inhibit TPO (organification/coupling). Propranolol is a beta-blocker used for symptoms.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'De Quervain\'s thyroiditis typically follows:', options: ['A) Pregnancy', 'B) A viral infection', 'C) Iodine excess', 'D) Surgery'], correctAnswer: 'B) A viral infection', explanation: 'De Quervain\'s (subacute granulomatous thyroiditis) follows a viral URI. Painful tender thyroid. Triphasic: hyperthyroid → hypothyroid → euthyroid. Self-limiting. ESR elevated.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Thyroid storm is treated with all EXCEPT:', options: ['A) Propranolol', 'B) Propylthiouracil', 'C) Radioactive iodine', 'D) Hydrocortisone'], correctAnswer: 'C) Radioactive iodine', explanation: 'Thyroid storm is a medical emergency requiring immediate control: propranolol (↓HR), PTU (blocks synthesis + peripheral conversion), KI (blocks release - Wolff-Chaikoff), hydrocortisone (↓conversion + treats relative adrenal insufficiency). Radioactive iodine is for elective treatment, NOT emergencies.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Type I deiodinase is mainly found in:', options: ['A) Brain', 'B) Placenta', 'C) Liver and kidney', 'D) Pituitary'], correctAnswer: 'C) Liver and kidney', explanation: 'Type I deiodinase (liver/kidney) is the main enzyme for peripheral T₄→T₃ conversion. Type II is in brain/pituitary (local T₃ supply). Type III is in placenta/brain (inactivation to rT₃).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'In Graves\' disease, TSH levels are:', options: ['A) Elevated', 'B) Normal', 'C) Suppressed', 'D) Variable'], correctAnswer: 'C) Suppressed', explanation: 'In Graves\', TSI antibodies stimulate thyroid → ↑T₃/T₄ → negative feedback → TSH is SUPPRESSED. This is a key distinguishing feature. If TSH were elevated, consider TSH-secreting pituitary adenoma.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The daily iodine requirement for adults is:', options: ['A) 50 μg', 'B) 150 μg', 'C) 500 μg', 'D) 1000 μg'], correctAnswer: 'B) 150 μg', explanation: 'Adults need 150 μg/day of iodine. Pregnancy requires more (~250 μg). The thyroid stores ~8000 μg, enough for ~100 days without dietary intake. Iodised salt provides adequate supplementation.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which tissue does NOT increase O₂ consumption in response to thyroid hormones?', options: ['A) Liver', 'B) Heart', 'C) Brain', 'D) Skeletal muscle'], correctAnswer: 'C) Brain', explanation: 'The calorigenic effect of thyroid hormones increases BMR in virtually all tissues EXCEPT brain, spleen, testes, and anterior pituitary. These tissues maintain constant metabolic rates.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Propylthiouracil (PTU) differs from methimazole in that PTU also:', options: ['A) Blocks iodide trapping', 'B) Inhibits peripheral T₄ to T₃ conversion', 'C) Destroys thyroid tissue', 'D) Blocks TSH secretion'], correctAnswer: 'B) Inhibits peripheral T₄ to T₃ conversion', explanation: 'Both PTU and methimazole inhibit TPO (organification and coupling). PTU additionally inhibits Type I deiodinase → blocks peripheral T₄→T₃ conversion. This makes PTU preferred in thyroid storm.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Exophthalmos is pathognomonic for:', options: ['A) Hashimoto\'s thyroiditis', 'B) Graves\' disease', 'C) Toxic multinodular goitre', 'D) Subacute thyroiditis'], correctAnswer: 'B) Graves\' disease', explanation: 'Exophthalmos (proptosis) is caused by GAG deposition + lymphocytic infiltration of retro-orbital tissue. It is specific to Graves\' disease and does not occur in other causes of hyperthyroidism.', difficulty: 'medium' },

    // ADDITIONAL CALCIUM/PARATHYROID MCQs
    { questionType: 'mcq', question: 'Which form of serum calcium is physiologically active?', options: ['A) Protein-bound', 'B) Complexed', 'C) Ionised (free)', 'D) Total calcium'], correctAnswer: 'C) Ionised (free)', explanation: 'Ionised (free) Ca²⁺ (50% of total) is the physiologically active form. Protein-bound (40%, mainly albumin) and complexed (10%, with phosphate/citrate) are inactive. Low albumin → low total Ca²⁺ but normal ionised Ca²⁺.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'PTH stimulates which enzyme in the kidney?', options: ['A) 25-hydroxylase', 'B) 1α-hydroxylase', 'C) Renin', 'D) ACE'], correctAnswer: 'B) 1α-hydroxylase', explanation: 'PTH stimulates 1α-hydroxylase in the proximal tubule of the kidney, converting 25-(OH)D₃ (calcidiol) to 1,25-(OH)₂D₃ (calcitriol = active vitamin D₃). This is how PTH indirectly increases gut Ca²⁺ absorption.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Hypoparathyroidism is most commonly caused by:', options: ['A) Autoimmune destruction', 'B) Accidental removal during thyroidectomy', 'C) Parathyroid adenoma', 'D) Vitamin D deficiency'], correctAnswer: 'B) Accidental removal during thyroidectomy', explanation: 'The most common cause of hypoparathyroidism is accidental removal or damage of the parathyroid glands during thyroid surgery. Features: ↓Ca²⁺, ↑PO₄³⁻, ↓PTH, tetany.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Paget\'s disease of bone shows:', options: ['A) ↑Ca²⁺, ↑PO₄³⁻, ↑ALP', 'B) Normal Ca²⁺, normal PO₄³⁻, ↑ALP', 'C) ↓Ca²⁺, ↓PO₄³⁻, ↓ALP', 'D) ↑Ca²⁺, ↓PO₄³⁻, normal ALP'], correctAnswer: 'B) Normal Ca²⁺, normal PO₄³⁻, ↑ALP', explanation: 'In Paget\'s, bone turnover is greatly increased (osteoclast overactivity + compensatory osteoblast activity). ALP is markedly elevated. Ca²⁺ and PO₄³⁻ are normal because resorption is balanced by formation.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Osteomalacia in adults is equivalent to _____ in children:', options: ['A) Scurvy', 'B) Rickets', 'C) Osteoporosis', 'D) Osteogenesis imperfecta'], correctAnswer: 'B) Rickets', explanation: 'Both rickets (children) and osteomalacia (adults) result from vitamin D deficiency → inadequate calcium absorption → poor bone mineralisation. Rickets affects growing bones (bowing, rachitic rosary). Osteomalacia affects mature bones.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Vitamin D₃ is synthesized in the skin from:', options: ['A) Cholesterol', 'B) 7-dehydrocholesterol', 'C) Ergosterol', 'D) Lanosterol'], correctAnswer: 'B) 7-dehydrocholesterol', explanation: 'UV-B light (290-315 nm) converts 7-dehydrocholesterol (provitamin D₃) in the skin to cholecalciferol (vitamin D₃). This then undergoes 25-hydroxylation in liver and 1α-hydroxylation in kidney.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The storage form of vitamin D₃ measured clinically is:', options: ['A) 1,25-(OH)₂D₃', 'B) 25-(OH)D₃', 'C) Cholecalciferol', 'D) 7-dehydrocholesterol'], correctAnswer: 'B) 25-(OH)D₃', explanation: '25-(OH)D₃ (calcidiol) is the major circulating form with a long half-life (~2-3 weeks). It is the best indicator of vitamin D status. 1,25-(OH)₂D₃ (calcitriol) is the active form but has a short half-life (~4-6 hours).', difficulty: 'medium' },

    // ADDITIONAL GENERAL ENDOCRINOLOGY MCQs
    { questionType: 'mcq', question: 'Peptide hormones act via:', options: ['A) Nuclear receptors', 'B) Cell surface receptors + second messengers', 'C) Intracellular receptors', 'D) Ion channels directly'], correctAnswer: 'B) Cell surface receptors + second messengers', explanation: 'Peptide hormones are water-soluble → cannot cross the cell membrane → bind surface receptors → activate second messenger systems (cAMP, IP₃/DAG, etc.). Onset is rapid but duration is short.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Steroid hormones act via:', options: ['A) Surface receptors + cAMP', 'B) Surface receptors + IP₃', 'C) Nuclear receptors → gene expression', 'D) Ion channel receptors'], correctAnswer: 'C) Nuclear receptors → gene expression', explanation: 'Steroid hormones are lipid-soluble → cross cell membrane → bind intracellular/nuclear receptors → act as transcription factors → alter gene expression. Onset is slow but duration is long.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The "term hormone" was coined by:', options: ['A) Claude Bernard', 'B) Ernest Starling', 'C) Hans Selye', 'D) Walter Cannon'], correctAnswer: 'B) Ernest Starling', explanation: 'Ernest Starling coined the term "hormone" in 1905 (from Greek "hormon" = to excite/arouse). He and William Bayliss discovered secretin, the first hormone identified.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which second messenger system does glucagon use?', options: ['A) IP₃/DAG', 'B) cAMP (adenylate cyclase)', 'C) cGMP', 'D) Tyrosine kinase'], correctAnswer: 'B) cAMP (adenylate cyclase)', explanation: 'Glucagon binds GPCR → stimulates adenylate cyclase → ↑cAMP → activates PKA → glycogenolysis + gluconeogenesis. Insulin uses a tyrosine kinase receptor (different mechanism).', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Negative feedback is the MOST COMMON regulatory mechanism for hormones. Which of the following is an example?', options: ['A) Oxytocin during labour', 'B) LH surge during ovulation', 'C) Cortisol suppressing ACTH', 'D) Prolactin during suckling'], correctAnswer: 'C) Cortisol suppressing ACTH', explanation: 'Cortisol inhibits CRH (hypothalamus) and ACTH (pituitary) = negative feedback. This is the most common hormonal regulatory mechanism. The others listed are positive feedback or have stimulatory components.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Hormones that bind carrier proteins in blood have:', options: ['A) Shorter half-life', 'B) Longer half-life', 'C) No change in half-life', 'D) Faster degradation'], correctAnswer: 'B) Longer half-life', explanation: 'Protein binding protects hormones from degradation and renal filtration, extending their half-life. Only the free (unbound) fraction is biologically active and available for degradation.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Permissive action of hormones means:', options: ['A) One hormone blocks another', 'B) One hormone is needed for another to exert its full effect', 'C) Two hormones have opposite effects', 'D) One hormone replaces another'], correctAnswer: 'B) One hormone is needed for another to exert its full effect', explanation: 'Permissive action: one hormone enables another\'s effect. Example: thyroid hormones are needed for epinephrine to have full calorigenic/lipolytic effects. Without T₃/T₄, catecholamines are less effective.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Synergism in hormones means:', options: ['A) Hormones oppose each other', 'B) Combined effect is greater than sum of individual effects', 'C) One hormone inhibits another', 'D) Hormones have no interaction'], correctAnswer: 'B) Combined effect is greater than sum of individual effects', explanation: 'Synergism: combined effect > sum of individual effects. Example: FSH + testosterone together produce much more spermatogenesis than either alone. This is distinct from additive effects.', difficulty: 'medium' },

    // ADDITIONAL TRUE/FALSE
    { questionType: 'true_false', question: 'Free T₄ levels change when TBG levels change in pregnancy. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'In pregnancy, estrogen → ↑TBG → ↑total T₄. But FREE T₄ remains normal (the body adjusts by making more T₄ to fill the extra binding sites). The patient remains euthyroid.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'PTH is secreted in response to high serum calcium. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'PTH is secreted in response to LOW serum Ca²⁺ (detected by CaSR on chief cells). HIGH Ca²⁺ suppresses PTH secretion. Calcitonin is secreted in response to high calcium.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Total thyroidectomy causes significant calcium disturbance due to loss of calcitonin. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Despite removing all C cells (calcitonin source), total thyroidectomy does NOT cause significant Ca²⁺ disturbance. This proves calcitonin is not essential in adults. Ca²⁺ problems post-thyroidectomy are from parathyroid damage, not calcitonin loss.', difficulty: 'hard' },
    { questionType: 'true_false', question: 'Thyroid hormones are essential for brain development in infants. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Thyroid hormones are critical for CNS development (myelination, neuronal migration, synaptogenesis) in the first 2-3 years of life. Deficiency causes cretinism with irreversible mental retardation if not treated early.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Vitamin D₃ can be obtained from both diet and skin synthesis. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Vitamin D₃ sources: (1) Skin - UV-B + 7-dehydrocholesterol (main source with adequate sun). (2) Diet - fatty fish, egg yolks, fortified foods, supplements. Both are cholecalciferol.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Osteoporosis and osteomalacia are the same condition. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Osteoporosis: decreased bone DENSITY (normal mineralisation but less bone). Osteomalacia: decreased bone MINERALISATION (adequate osteoid but poor calcium deposition). Different pathophysiology and treatment.', difficulty: 'medium' },

    // ADDITIONAL FILL IN THE BLANK
    { questionType: 'fill_blank', question: 'The most important action of thyroid hormones is the _____ effect (increasing BMR).', options: [], correctAnswer: 'calorigenic', explanation: 'The calorigenic effect (heat production via increased BMR and O₂ consumption) is the most important thyroid hormone action. It affects virtually all tissues except brain, spleen, and gonads.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'Graves\' disease is caused by _____ antibodies that stimulate the TSH receptor.', options: [], correctAnswer: 'TSI (thyroid-stimulating immunoglobulin)', explanation: 'TSI (also called TRAb - TSH receptor antibodies) are IgG antibodies that bind and activate TSH receptors, causing unregulated thyroid hormone production. They also cause retroorbital inflammation → exophthalmos.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The _____ cells of the parathyroid gland secrete PTH.', options: [], correctAnswer: 'chief', explanation: 'Chief cells (principal cells) are the functional cells of the parathyroid gland that secrete PTH. Oxyphil cells are also present but their function is unknown.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'Coupling of MIT + DIT produces _____, while DIT + DIT produces _____.', options: [], correctAnswer: 'T₃; T₄', explanation: 'MIT (1 iodine) + DIT (2 iodines) = T₃ (3 iodines). DIT (2 iodines) + DIT (2 iodines) = T₄ (4 iodines). More T₄ is produced than T₃. Both reactions are catalysed by TPO.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'Rickets in children and _____ in adults are both caused by vitamin D deficiency.', options: [], correctAnswer: 'osteomalacia', explanation: 'Rickets (children): bowing of legs, rachitic rosary, craniotabes, delayed fontanelle closure. Osteomalacia (adults): bone pain, proximal myopathy, pseudofractures. Both due to inadequate mineralisation from vitamin D deficiency.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'Hormones that bind carrier proteins have a _____ half-life compared to free hormones.', options: [], correctAnswer: 'longer', explanation: 'Protein binding protects hormones from enzymatic degradation and renal clearance, extending their half-life. Example: T₄ (99.97% bound) has a 6-7 day half-life vs catecholamines (unbound) with seconds.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'The interaction where one hormone is required for another to exert its full effect is called _____ action.', options: [], correctAnswer: 'permissive', explanation: 'Permissive action: one hormone enables another\'s full effect. Classic example: thyroid hormones are needed for epinephrine to have full calorigenic and lipolytic effects. Without T₃/T₄, catecholamine effects are blunted.', difficulty: 'medium' },

    // CLINICAL SCENARIO QUESTIONS
    { questionType: 'mcq', question: 'A 50-year-old woman presents with fatigue, weight gain, constipation, and non-pitting oedema. Her TSH is elevated and free T₄ is low. The MOST LIKELY diagnosis is:', options: ['A) Graves\' disease', 'B) Myxedema (severe hypothyroidism)', 'C) Cushing syndrome', 'D) Addison disease'], correctAnswer: 'B) Myxedema (severe hypothyroidism)', explanation: 'Fatigue + weight gain + constipation + non-pitting oedema + ↑TSH + ↓free T₄ = hypothyroidism. Non-pitting oedema (mucopolysaccharide deposition) is characteristic of myxedema. Most likely cause: Hashimoto\'s thyroiditis.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A patient with known Graves\' disease develops high fever (>40°C), tachycardia, altered consciousness after a stressful surgery. The MOST LIKELY diagnosis is:', options: ['A) Sepsis', 'B) Malignant hyperthermia', 'C) Thyroid storm', 'D) Pheochromocytoma crisis'], correctAnswer: 'C) Thyroid storm', explanation: 'Known Graves\' + surgery trigger + high fever + tachycardia + altered consciousness = thyroid storm (thyrotoxic crisis). Emergency management: propranolol, PTU, KI, hydrocortisone, cooling, IV fluids.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A patient has serum Ca²⁺ = 12.5 mg/dL, PO₄³⁻ = 2.0 mg/dL, PTH = 180 pg/mL (elevated). The diagnosis is:', options: ['A) Hypoparathyroidism', 'B) Primary hyperparathyroidism', 'C) Vitamin D deficiency', 'D) Secondary hyperparathyroidism'], correctAnswer: 'B) Primary hyperparathyroidism', explanation: '↑Ca²⁺ + ↓PO₄³⁻ + ↑PTH = primary hyperparathyroidism (usually parathyroid adenoma). In secondary HPT, Ca²⁺ would be low/normal. In vitamin D deficiency, Ca²⁺ would be low.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A 2-year-old child from a developing country has bowing of legs, enlarged wrists, and a "rachitic rosary". X-ray shows widened growth plates. The diagnosis is:', options: ['A) Scurvy', 'B) Rickets', 'C) Osteogenesis imperfecta', 'D) Achondroplasia'], correctAnswer: 'B) Rickets', explanation: 'Bowing of legs + enlarged wrists + rachitic rosary (beading at costochondral junctions) + widened growth plates = rickets (vitamin D deficiency in children). Treatment: vitamin D + calcium supplementation.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'A 45-year-old woman on lithium therapy develops a painless goitre. Her TSH is mildly elevated. The mechanism is:', options: ['A) Autoimmune destruction', 'B) Inhibition of thyroid hormone release', 'C) TSH-secreting pituitary adenoma', 'D) Iodine excess'], correctAnswer: 'B) Inhibition of thyroid hormone release', explanation: 'Lithium inhibits thyroid hormone release (and to a lesser extent, synthesis). This → ↓T₃/T₄ → ↑TSH → goitre. Lithium can cause hypothyroidism in up to 20% of patients. Monitor thyroid function regularly.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A patient on amiodarone develops hyperthyroidism. This is because amiodarone:', options: ['A) Stimulates TSH receptors', 'B) Contains large amounts of iodine', 'C) Destroys the thyroid', 'D) Blocks TBG'], correctAnswer: 'B) Contains large amounts of iodine', explanation: 'Amiodarone is 37% iodine by weight. It can cause both hyper- and hypothyroidism. Type 1 amiodarone-induced thyrotoxicosis: excess iodine → increased hormone synthesis. Type 2: destructive thyroiditis → hormone release.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Secondary hyperparathyroidism is MOST COMMONLY seen in:', options: ['A) Parathyroid adenoma', 'B) Chronic kidney disease', 'C) Thyroid cancer', 'D) Vitamin D excess'], correctAnswer: 'B) Chronic kidney disease', explanation: 'CKD → ↓1α-hydroxylase → ↓active vitamin D₃ → ↓Ca²⁺ absorption → ↓serum Ca²⁺ → compensatory ↑PTH (secondary). Also: ↑PO₄³⁻ retention in CKD further suppresses Ca²⁺ and stimulates PTH.', difficulty: 'medium' },

    // MORE TRUE/FALSE
    { questionType: 'true_false', question: 'Antithyroid drugs (PTU, methimazole) work by blocking iodide trapping. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'PTU and methimazole inhibit TPO (thyroid peroxidase), blocking organification and coupling steps. They do NOT block iodide trapping. Perchlorate and thiocyanate block iodide trapping (NIS).', difficulty: 'medium' },
    { questionType: 'true_false', question: 'In euthyroid sick syndrome, TSH levels are usually normal or low. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Euthyroid sick syndrome (non-thyroidal illness): severe illness → ↓T₃ (↓peripheral conversion), ↓/normal T₄, normal/low TSH. The patient is NOT truly hypothyroid. T₃ is the first to drop.', difficulty: 'hard' },
    { questionType: 'true_false', question: 'Pseudohypoparathyroidism is caused by PTH deficiency. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Pseudohypoparathyroidism is target organ RESISTANCE to PTH (not deficiency). PTH levels are actually HIGH but tissues don\'t respond. Features: ↓Ca²⁺, ↑PO₄³⁻, ↑PTH. Albright hereditary osteodystrophy phenotype.', difficulty: 'hard' },
    { questionType: 'true_false', question: 'Insulin uses the cAMP second messenger system. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Insulin uses a tyrosine kinase receptor pathway (autophosphorylation → IRS proteins → PI3K/Akt pathway). It does NOT use cAMP. Glucagon, ACTH, TSH, and LH use cAMP.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'The first hormone ever discovered was secretin. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Secretin was the first hormone discovered (1902) by Bayliss and Starling. They showed that acid in the duodenum caused a chemical substance (secretin) to stimulate pancreatic secretion, proving humoral signaling.', difficulty: 'medium' },

    // MORE FILL IN THE BLANK
    { questionType: 'fill_blank', question: 'The three types of deiodinase are Type I (_____ and kidney), Type II (brain and _____), and Type III (placenta and brain).', options: [], correctAnswer: 'liver; pituitary', explanation: 'Type I (liver/kidney): main peripheral T₄→T₃ conversion. Type II (brain/pituitary): local T₃ supply for these critical tissues. Type III (placenta/brain): inactivation (T₄→rT₃).', difficulty: 'hard' },
    { questionType: 'fill_blank', question: 'In primary hyperparathyroidism, ~80% of cases are caused by a parathyroid _____.', options: [], correctAnswer: 'adenoma', explanation: 'Parathyroid adenoma (single gland, benign tumour) accounts for ~80% of primary hyperparathyroidism. Hyperplasia (all 4 glands) ~15%. Carcinoma <5%.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'The sign where tapping the facial nerve causes facial muscle twitch is called _____ sign.', options: [], correctAnswer: 'Chvostek', explanation: 'Chvostek sign: tapping over the facial nerve (anterior to the ear) causes ipsilateral facial muscle twitch. Indicates neuromuscular hyperexcitability from hypocalcaemia. Trousseau sign (carpal spasm) is more specific.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'Insulin is unique among peptide hormones because its receptor is a _____ kinase.', options: [], correctAnswer: 'tyrosine', explanation: 'The insulin receptor is a tyrosine kinase receptor that autophosphorylates upon insulin binding, then phosphorylates IRS proteins. Most other peptide hormones use G-protein coupled receptors with second messengers.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The thyroid gland stores enough iodine for approximately _____ days without dietary intake.', options: [], correctAnswer: '100', explanation: 'The thyroid stores ~8000 μg of iodine in thyroglobulin within the colloid. With a daily requirement of 80 μg for hormone synthesis, this provides a ~100-day reserve - the largest hormone reserve in the body.', difficulty: 'medium' },

    // ADDITIONAL - REACHING 100+ QUESTIONS
    { questionType: 'mcq', question: 'Which of the following is NOT a function of calcium in the body?', options: ['A) Muscle contraction', 'B) Blood clotting', 'C) Hormone synthesis', 'D) Nerve conduction'], correctAnswer: 'C) Hormone synthesis', explanation: 'Calcium functions: muscle contraction (excitation-contraction coupling), blood clotting (Factor IV), nerve conduction, enzyme activation, hormone secretion, cell signaling. Calcium is not used to SYNTHESIZE hormones.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Thyroglobulin is stored in:', options: ['A) Thyroid follicular cells', 'B) Parafollicular C cells', 'C) Follicular colloid (lumen)', 'D) Blood'], correctAnswer: 'C) Follicular colloid (lumen)', explanation: 'Thyroglobulin (660 kDa glycoprotein) with iodinated tyrosine residues (MIT, DIT, T₃, T₄) is stored as colloid in the follicular lumen. TSH stimulates endocytosis and proteolysis to release T₃/T₄.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which condition presents with a PAINFUL thyroid?', options: ['A) Graves\' disease', 'B) Hashimoto\'s thyroiditis', 'C) De Quervain\'s thyroiditis', 'D) Papillary thyroid carcinoma'], correctAnswer: 'C) De Quervain\'s thyroiditis', explanation: 'De Quervain\'s (subacute granulomatous thyroiditis) is characteristically PAINFUL. Graves\' and Hashimoto\'s are typically painless. Thyroid cancers are usually painless nodules.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Cutting the pituitary stalk causes prolactin levels to decrease. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Cutting the pituitary stalk removes dopamine inhibition → prolactin INCREASES. This is unique because all other anterior pituitary hormones DECREASE when the stalk is cut (loss of stimulatory releasing hormones).', difficulty: 'hard' },
    { questionType: 'true_false', question: 'The thyroid gland develops from the foramen cecum of the tongue. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'The thyroid develops from the foramen cecum at the base of the tongue and descends to its final position via the thyroglossal duct. Remnants of this duct can form thyroglossal cysts (midline neck swelling that moves with swallowing and tongue protrusion).', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The condition where target organs are resistant to PTH despite elevated PTH levels is called _____.', options: [], correctAnswer: 'pseudohypoparathyroidism', explanation: 'Pseudohypoparathyroidism: end-organ resistance to PTH. Lab: ↓Ca²⁺, ↑PO₄³⁻, ↑PTH (the glands are working but tissues don\'t respond). Associated with Albright hereditary osteodystrophy (short stature, short 4th metacarpal, round face).', difficulty: 'hard' },
    { questionType: 'fill_blank', question: 'The first hormone ever discovered was _____, found by Bayliss and Starling in 1902.', options: [], correctAnswer: 'secretin', explanation: 'Secretin was discovered by Bayliss and Starling (1902). They showed that acid in the duodenum triggered a blood-borne chemical messenger that stimulated pancreatic secretion. Starling later coined the term "hormone" in 1905.', difficulty: 'medium' },
  ],

  flashcards: [
    { front: 'T₃ vs T₄ - which is more potent and which is secreted more?', back: 'T₃ is 3-5x more potent. T₄ is the major secretory product (90%). Most circulating T₃ comes from peripheral conversion of T₄ by deiodinase in liver/kidney.', difficulty: 'easy' },
    { front: 'Steps of thyroid hormone synthesis?', back: '1) Iodide trapping (NIS) → 2) Oxidation (TPO) → 3) Organification (TPO) → 4) Coupling (MIT+DIT→T₃, DIT+DIT→T₄) → 5) Storage in colloid → 6) Proteolysis and release (TSH stimulated).', difficulty: 'medium' },
    { front: 'What is the Wolff-Chaikoff effect?', back: 'Excess iodide temporarily blocks organification → ↓thyroid hormone synthesis. Protective against hyperthyroidism. Basis for KI use in thyroid storm.', difficulty: 'hard' },
    { front: 'PTH actions - bone, kidney, gut?', back: 'Bone: ↑osteoclast activity → ↑Ca²⁺ release. Kidney: ↑Ca²⁺ reabsorption, ↓PO₄³⁻ reabsorption, ↑1α-hydroxylase. Gut: INDIRECT only (via active vitamin D₃ → ↑Ca²⁺ absorption).', difficulty: 'medium' },
    { front: 'PTH net effect on Ca²⁺ and PO₄³⁻?', back: '↑serum Ca²⁺ and ↓serum PO₄³⁻. PTH = "Phosphate Trashing Hormone". Despite releasing PO₄³⁻ from bone, the phosphaturic effect at the kidney dominates.', difficulty: 'medium' },
    { front: 'Vitamin D₃ activation pathway?', back: 'Skin (UV + 7-DHC → D₃) → Liver (25-hydroxylase → calcidiol) → Kidney (1α-hydroxylase → calcitriol = ACTIVE). PTH stimulates the kidney step.', difficulty: 'medium' },
    { front: 'Graves\' disease vs Hashimoto\'s thyroiditis?', back: 'Graves\': TSI antibodies → hyperthyroidism + exophthalmos. Hashimoto\'s: anti-TPO/anti-Tg antibodies → hypothyroidism. Both are autoimmune thyroid diseases.', difficulty: 'medium' },
    { front: 'Trousseau sign vs Chvostek sign?', back: 'Both indicate hypocalcaemia. Trousseau: carpal spasm after BP cuff inflated >systolic for 3 min. Chvostek: facial muscle twitch on tapping over facial nerve.', difficulty: 'easy' },
    { front: 'Cretinism vs Myxedema?', back: 'Cretinism: hypothyroidism in infants/children → mental retardation + growth failure + coarse features. Myxedema: severe hypothyroidism in adults → non-pitting oedema + cold intolerance + bradycardia.', difficulty: 'easy' },
    { front: 'TBG changes - what increases and decreases it?', back: '↑TBG: Pregnancy, OCP (estrogen), hepatitis. ↓TBG: Nephrotic syndrome, androgens, glucocorticoids. Changes in TBG alter total T₄ but NOT free T₄ (patient remains euthyroid).', difficulty: 'hard' },
    { front: 'Hyperparathyroidism features mnemonic?', back: 'Stones (renal), Bones (pain/fractures), Abdominal Groans (constipation/pancreatitis), Psychiatric Moans (depression/confusion). Lab: ↑Ca²⁺, ↓PO₄³⁻, ↑PTH.', difficulty: 'medium' },
    { front: 'Calcitonin - where from and what does it do?', back: 'From parafollicular C cells of thyroid. Secreted when Ca²⁺ is HIGH. ↓bone resorption (inhibits osteoclasts) → ↓serum Ca²⁺. Opposes PTH. Less important in adults.', difficulty: 'easy' },
    { front: 'What makes thyroid hormones unique among amine hormones?', back: 'Despite being amines (from tyrosine), T₃/T₄ are lipid-soluble, bind NUCLEAR receptors (like steroids), and require iodine (trace element) for synthesis. No other amine acts this way.', difficulty: 'hard' },
  ],
};
