-- ============================================================
-- Study Hub Login Tokens
-- One-time tokens for bot users to access Study Hub
-- Generated by !study command, expire after 10 minutes or 1 use
-- ============================================================

CREATE TABLE IF NOT EXISTS study_login_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token TEXT NOT NULL UNIQUE,
  phone_number TEXT NOT NULL,
  session_id UUID REFERENCES public.bot_sessions(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  used BOOLEAN DEFAULT false,
  used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_study_login_tokens_token ON study_login_tokens(token);
CREATE INDEX idx_study_login_tokens_phone ON study_login_tokens(phone_number);

-- RLS
ALTER TABLE study_login_tokens ENABLE ROW LEVEL SECURITY;

-- Service role can manage all tokens
CREATE POLICY study_login_tokens_service_policy ON study_login_tokens
  FOR ALL USING (true) WITH CHECK (true);

-- Users can only see their own tokens
CREATE POLICY study_login_tokens_user_policy ON study_login_tokens
  FOR SELECT USING (auth.uid() = user_id);
