export interface FixPage {
  slug: string;
  title: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  keywords: string[];
}

export const fixPages: FixPage[] = [
  {
    slug: 'whatsapp-bot-disconnected',
    title: 'WhatsApp Bot Keeps Disconnecting',
    description: 'Why your WhatsApp bot session disconnects and how to fix it. Covers QR expiry, 401 auth errors, 428 rate limits, and network issues.',
    seoTitle: 'Fix: WhatsApp Bot Keeps Disconnecting - Troubleshooting Guide',
    seoDescription: 'Why your WhatsApp bot keeps disconnecting and how to fix it. Covers session expiry, auth errors, rate limits, multi-device conflicts.',
    keywords: ['whatsapp bot disconnecting', 'fix whatsapp bot connection', 'whatsapp bot reconnect', 'whatsapp session expired'],
  },
  {
    slug: 'whatsapp-bot-banned',
    title: 'WhatsApp Bot Got Banned',
    description: 'Why WhatsApp bans bots and how BotWave prevents it. Anti-ban system explained with recovery steps.',
    seoTitle: 'Fix: WhatsApp Bot Got Banned - Prevention and Recovery',
    seoDescription: 'Why WhatsApp bots get banned and how to prevent it. BotWave anti-ban system with human-like behavior, session warmup, and rate limiting.',
    keywords: ['whatsapp bot banned', 'prevent whatsapp bot ban', 'whatsapp anti ban', 'whatsapp bot ban fix'],
  },
  {
    slug: 'whatsapp-qr-not-scanning',
    title: 'WhatsApp QR Code Not Scanning',
    description: 'Troubleshoot QR code scanning issues during bot setup. Camera problems, expired QR, and pairing code alternatives.',
    seoTitle: 'Fix: WhatsApp QR Code Not Scanning - Setup Troubleshooting',
    seoDescription: 'Fix QR code scanning issues when connecting WhatsApp bot. Camera tips, QR expiry, pairing code method, and browser compatibility.',
    keywords: ['whatsapp qr not scanning', 'whatsapp bot qr code fix', 'whatsapp qr expired', 'whatsapp pairing code'],
  },
  {
    slug: 'whatsapp-auto-reply-not-working',
    title: 'WhatsApp Auto-Reply Not Working',
    description: 'Fix auto-reply issues including session disconnection, command not recognized, and permission problems.',
    seoTitle: 'Fix: WhatsApp Auto-Reply Not Working - Troubleshooting',
    seoDescription: 'Fix WhatsApp bot auto-reply issues. Check session status, command syntax, permissions, and rate limits.',
    keywords: ['whatsapp auto reply not working', 'whatsapp bot not responding', 'whatsapp bot commands not working'],
  },
  {
    slug: 'whatsapp-bot-slow-response',
    title: 'WhatsApp Bot Responding Slowly',
    description: 'Why bot responses are delayed. Covers anti-ban delays, server load, rate limiting, and session warmup.',
    seoTitle: 'Fix: WhatsApp Bot Slow Response - Why Bot Replies Are Delayed',
    seoDescription: 'Why your WhatsApp bot responds slowly. Anti-ban delays are intentional. Learn about typing simulation and rate limiting.',
    keywords: ['whatsapp bot slow', 'whatsapp bot delay', 'why bot reply slow', 'whatsapp bot response time'],
  },
  {
    slug: 'whatsapp-bot-not-reading-messages',
    title: 'WhatsApp Bot Not Reading Messages',
    description: 'Bot not responding to messages. Check session status, prefix, admin permissions, and message types.',
    seoTitle: 'Fix: WhatsApp Bot Not Reading Messages',
    seoDescription: 'Fix WhatsApp bot not responding to messages. Check if session is active, correct prefix used, and permissions set.',
    keywords: ['whatsapp bot not reading messages', 'bot not responding whatsapp', 'whatsapp bot ignore messages'],
  },
  {
    slug: 'whatsapp-sticker-not-sending',
    title: 'WhatsApp Sticker Command Not Working',
    description: 'Fix sticker creation issues. Media format, file size limits, and correct command syntax.',
    seoTitle: 'Fix: WhatsApp Sticker Bot Not Working',
    seoDescription: 'Fix !sticker command issues. Check media format, file size (under 1MB for static, 500KB for animated), and reply to correct media type.',
    keywords: ['whatsapp sticker bot not working', 'sticker command fail', 'whatsapp bot sticker error'],
  },
  {
    slug: 'telegram-bot-not-responding',
    title: 'Telegram Bot Not Responding',
    description: 'Troubleshoot Telegram bot connection issues. Token validity, webhook setup, and group permissions.',
    seoTitle: 'Fix: Telegram Bot Not Responding - Connection Troubleshooting',
    seoDescription: 'Fix Telegram bot not responding. Check bot token, webhook status, group privacy settings, and admin permissions.',
    keywords: ['telegram bot not responding', 'telegram bot not working', 'fix telegram bot', 'telegram bot offline'],
  },
  {
    slug: 'telegram-userbot-session-expired',
    title: 'Telegram Userbot Session Expired',
    description: 'Fix userbot authentication issues. MTProto session renewal, 2FA verification, and flood wait errors.',
    seoTitle: 'Fix: Telegram Userbot Session Expired',
    seoDescription: 'Fix Telegram userbot session expiry. Re-authenticate MTProto session, handle flood wait errors, and 2FA issues.',
    keywords: ['telegram userbot session expired', 'mtproto session fix', 'telegram userbot auth error'],
  },
  {
    slug: 'whatsapp-download-not-working',
    title: 'WhatsApp Download Command Not Working',
    description: 'Fix video download issues. Supported platforms, URL format, file size limits, and geo-restrictions.',
    seoTitle: 'Fix: WhatsApp Download Bot Not Working',
    seoDescription: 'Fix !download command issues. Supported platforms (TikTok, YouTube, Instagram), URL format, and file size limits.',
    keywords: ['whatsapp download bot not working', 'tiktok download bot error', 'youtube download whatsapp fix'],
  },
  {
    slug: 'whatsapp-bot-not-joining-group',
    title: 'WhatsApp Bot Not Working in Group',
    description: 'Bot works in private but not in groups. Check admin status, group settings, and invite link.',
    seoTitle: 'Fix: WhatsApp Bot Not Working in Group',
    seoDescription: 'Fix WhatsApp bot not responding in groups. Check if bot number is admin, group privacy settings, and message visibility.',
    keywords: ['whatsapp bot not working in group', 'bot not responding in group', 'whatsapp group bot fix'],
  },
  {
    slug: 'whatsapp-ai-not-responding',
    title: 'WhatsApp AI Command Not Working',
    description: 'Fix !ai command issues. Daily limit reached, server load, and quota resets.',
    seoTitle: 'Fix: WhatsApp AI Bot Not Responding',
    seoDescription: 'Fix !ai command not working. Check daily query limit (10/day free), server status, and syntax.',
    keywords: ['whatsapp ai bot not working', 'ai command not responding', 'whatsapp ai limit'],
  },
  // ── Programmatic SEO: Additional fix/troubleshooting pages ──
  { slug: 'whatsapp-bot-not-responding', title: 'WhatsApp Bot Not Responding', description: 'How to fix "WhatsApp Bot Not Responding". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot Not Responding - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot not responding. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot not responding', 'fix whatsapp bot'] },
  { slug: 'whatsapp-bot-slow', title: 'WhatsApp Bot Responding Slowly', description: 'How to fix "WhatsApp Bot Responding Slowly". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot Responding Slowly - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot responding slowly. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot slow', 'bot slow response'] },
  { slug: 'whatsapp-sticker-not-working', title: 'WhatsApp Sticker Command Not Working', description: 'How to fix "WhatsApp Sticker Command Not Working". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Sticker Command Not Working - Troubleshooting Guide', seoDescription: 'Fix whatsapp sticker command not working. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp sticker not working', 'fix sticker bot'] },
  { slug: 'whatsapp-download-failed', title: 'WhatsApp Download Command Failed', description: 'How to fix "WhatsApp Download Command Failed". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Download Command Failed - Troubleshooting Guide', seoDescription: 'Fix whatsapp download command failed. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp download failed', 'fix download bot'] },
  { slug: 'whatsapp-bot-403-error', title: 'WhatsApp Bot 403 Forbidden Error', description: 'How to fix "WhatsApp Bot 403 Forbidden Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot 403 Forbidden Error - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot 403 forbidden error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot 403', 'fix 403 error'] },
  { slug: 'whatsapp-bot-401-error', title: 'WhatsApp Bot 401 Authentication Error', description: 'How to fix "WhatsApp Bot 401 Authentication Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot 401 Authentication Error - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot 401 authentication error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot 401', 'fix auth error'] },
  { slug: 'whatsapp-bot-428-error', title: 'WhatsApp Bot 428 Rate Limit Error', description: 'How to fix "WhatsApp Bot 428 Rate Limit Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot 428 Rate Limit Error - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot 428 rate limit error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot 428', 'fix rate limit'] },
  { slug: 'whatsapp-bot-515-error', title: 'WhatsApp Bot 515 Restart Error', description: 'How to fix "WhatsApp Bot 515 Restart Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot 515 Restart Error - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot 515 restart error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot 515', 'fix restart error'] },
  { slug: 'whatsapp-pairing-code-expired', title: 'WhatsApp Pairing Code Expired', description: 'How to fix "WhatsApp Pairing Code Expired". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Pairing Code Expired - Troubleshooting Guide', seoDescription: 'Fix whatsapp pairing code expired. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp pairing code expired', 'fix pairing code'] },
  { slug: 'whatsapp-session-conflict', title: 'WhatsApp Session Conflict Error', description: 'How to fix "WhatsApp Session Conflict Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Session Conflict Error - Troubleshooting Guide', seoDescription: 'Fix whatsapp session conflict error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp session conflict', 'fix session conflict'] },
  { slug: 'whatsapp-multi-device-issue', title: 'WhatsApp Multi-Device Bot Issue', description: 'How to fix "WhatsApp Multi-Device Bot Issue". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Multi-Device Bot Issue - Troubleshooting Guide', seoDescription: 'Fix whatsapp multi-device bot issue. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp multi device issue', 'fix multi device bot'] },
  { slug: 'whatsapp-group-bot-not-admin', title: 'WhatsApp Bot Not Admin in Group', description: 'How to fix "WhatsApp Bot Not Admin in Group". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot Not Admin in Group - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot not admin in group. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot not admin', 'bot admin permissions'] },
  { slug: 'whatsapp-media-not-sending', title: 'WhatsApp Bot Not Sending Media', description: 'How to fix "WhatsApp Bot Not Sending Media". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot Not Sending Media - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot not sending media. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot media failed', 'fix media sending'] },
  { slug: 'whatsapp-bot-duplicate-messages', title: 'WhatsApp Bot Sending Duplicate Messages', description: 'How to fix "WhatsApp Bot Sending Duplicate Messages". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot Sending Duplicate Messages - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot sending duplicate messages. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot duplicate', 'fix duplicate messages'] },
  { slug: 'whatsapp-bot-wrong-language', title: 'WhatsApp Bot Responding in Wrong Language', description: 'How to fix "WhatsApp Bot Responding in Wrong Language". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot Responding in Wrong Language - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot responding in wrong language. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot wrong language', 'change bot language'] },
  { slug: 'telegram-bot-kicked', title: 'Telegram Bot Kicked from Group', description: 'How to fix "Telegram Bot Kicked from Group". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Kicked from Group - Troubleshooting Guide', seoDescription: 'Fix telegram bot kicked from group. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot kicked', 'fix telegram bot kicked'] },
  { slug: 'telegram-bot-no-permissions', title: 'Telegram Bot Missing Permissions', description: 'How to fix "Telegram Bot Missing Permissions". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Missing Permissions - Troubleshooting Guide', seoDescription: 'Fix telegram bot missing permissions. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot permissions', 'fix telegram bot admin'] },
  { slug: 'telegram-bot-flood-wait', title: 'Telegram Bot Flood Wait Error', description: 'How to fix "Telegram Bot Flood Wait Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Flood Wait Error - Troubleshooting Guide', seoDescription: 'Fix telegram bot flood wait error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram flood wait', 'fix telegram rate limit'] },
  { slug: 'telegram-userbot-2fa-error', title: 'Telegram Userbot 2FA Error', description: 'How to fix "Telegram Userbot 2FA Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Userbot 2FA Error - Troubleshooting Guide', seoDescription: 'Fix telegram userbot 2fa error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram userbot 2fa', 'fix userbot authentication'] },
  { slug: 'telegram-userbot-disconnected', title: 'Telegram Userbot Keeps Disconnecting', description: 'How to fix "Telegram Userbot Keeps Disconnecting". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Userbot Keeps Disconnecting - Troubleshooting Guide', seoDescription: 'Fix telegram userbot keeps disconnecting. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram userbot disconnecting', 'fix userbot connection'] },
  { slug: 'bot-commands-not-working', title: 'Bot Commands Not Working', description: 'How to fix "Bot Commands Not Working". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Bot Commands Not Working - Troubleshooting Guide', seoDescription: 'Fix bot commands not working. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['bot commands not working', 'fix bot commands'] },
  { slug: 'bot-dashboard-not-loading', title: 'BotWave Dashboard Not Loading', description: 'How to fix "BotWave Dashboard Not Loading". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: BotWave Dashboard Not Loading - Troubleshooting Guide', seoDescription: 'Fix botwave dashboard not loading. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['botwave dashboard not loading', 'fix dashboard'] },
  { slug: 'bot-session-needs-reauth', title: 'Bot Session Needs Re-authentication', description: 'How to fix "Bot Session Needs Re-authentication". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Bot Session Needs Re-authentication - Troubleshooting Guide', seoDescription: 'Fix bot session needs re-authentication. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['bot needs reauth', 'fix bot authentication'] },
  { slug: 'whatsapp-bot-logged-out', title: 'WhatsApp Bot Logged Out Automatically', description: 'How to fix "WhatsApp Bot Logged Out Automatically". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: WhatsApp Bot Logged Out Automatically - Troubleshooting Guide', seoDescription: 'Fix whatsapp bot logged out automatically. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['whatsapp bot logged out', 'fix auto logout'] },
  { slug: 'whatsapp-evolution-api-error', title: 'Evolution API Connection Error', description: 'How to fix "Evolution API Connection Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Evolution API Connection Error - Troubleshooting Guide', seoDescription: 'Fix evolution api connection error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['evolution api error', 'fix evolution api'] },
];
