export interface FixPage {
  slug: string;
  title: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  keywords: string[];
}

export const fixPages: FixPage[] = [
  {
    slug: 'telegram-bot-disconnected',
    title: 'Telegram Bot Keeps Disconnecting',
    description: 'Why your Telegram bot session disconnects and how to fix it. Covers QR expiry, 401 auth errors, 428 rate limits, and network issues.',
    seoTitle: 'Fix: Telegram Bot Keeps Disconnecting - Troubleshooting Guide',
    seoDescription: 'Why your Telegram bot keeps disconnecting and how to fix it. Covers session expiry, auth errors, rate limits, multi-device conflicts.',
    keywords: ['telegram bot disconnecting', 'fix telegram bot connection', 'telegram bot reconnect', 'telegram session expired'],
  },
  {
    slug: 'telegram-bot-banned',
    title: 'Telegram Bot Got Banned',
    description: 'Why Telegram bans bots and how BotWave prevents it. Anti-ban system explained with recovery steps.',
    seoTitle: 'Fix: Telegram Bot Got Banned - Prevention and Recovery',
    seoDescription: 'Why Telegram bots get banned and how to prevent it. BotWave anti-ban system with human-like behavior, session warmup, and rate limiting.',
    keywords: ['telegram bot banned', 'prevent telegram bot ban', 'telegram anti ban', 'telegram bot ban fix'],
  },
  {
    slug: 'telegram-qr-not-scanning',
    title: 'Telegram QR Code Not Scanning',
    description: 'Troubleshoot QR code scanning issues during bot setup. Camera problems, expired QR, and pairing code alternatives.',
    seoTitle: 'Fix: Telegram QR Code Not Scanning - Setup Troubleshooting',
    seoDescription: 'Fix QR code scanning issues when connecting Telegram bot. Camera tips, QR expiry, pairing code method, and browser compatibility.',
    keywords: ['telegram qr not scanning', 'telegram bot qr code fix', 'telegram qr expired', 'telegram pairing code'],
  },
  {
    slug: 'telegram-auto-reply-not-working',
    title: 'Telegram Auto-Reply Not Working',
    description: 'Fix auto-reply issues including session disconnection, command not recognized, and permission problems.',
    seoTitle: 'Fix: Telegram Auto-Reply Not Working - Troubleshooting',
    seoDescription: 'Fix Telegram bot auto-reply issues. Check session status, command syntax, permissions, and rate limits.',
    keywords: ['telegram auto reply not working', 'telegram bot not responding', 'telegram bot commands not working'],
  },
  {
    slug: 'telegram-bot-slow-response',
    title: 'Telegram Bot Responding Slowly',
    description: 'Why bot responses are delayed. Covers anti-ban delays, server load, rate limiting, and session warmup.',
    seoTitle: 'Fix: Telegram Bot Slow Response - Why Bot Replies Are Delayed',
    seoDescription: 'Why your Telegram bot responds slowly. Anti-ban delays are intentional. Learn about typing simulation and rate limiting.',
    keywords: ['telegram bot slow', 'telegram bot delay', 'why bot reply slow', 'telegram bot response time'],
  },
  {
    slug: 'telegram-bot-not-reading-messages',
    title: 'Telegram Bot Not Reading Messages',
    description: 'Bot not responding to messages. Check session status, prefix, admin permissions, and message types.',
    seoTitle: 'Fix: Telegram Bot Not Reading Messages',
    seoDescription: 'Fix Telegram bot not responding to messages. Check if session is active, correct prefix used, and permissions set.',
    keywords: ['telegram bot not reading messages', 'bot not responding telegram', 'telegram bot ignore messages'],
  },
  {
    slug: 'telegram-sticker-not-sending',
    title: 'Telegram Sticker Command Not Working',
    description: 'Fix sticker creation issues. Media format, file size limits, and correct command syntax.',
    seoTitle: 'Fix: Telegram Sticker Bot Not Working',
    seoDescription: 'Fix !sticker command issues. Check media format, file size (under 1MB for static, 500KB for animated), and reply to correct media type.',
    keywords: ['telegram sticker bot not working', 'sticker command fail', 'telegram bot sticker error'],
  },
  {
    slug: 'telegram-bot-not-responding',
    title: 'Telegram Bot Not Responding',
    description: 'Troubleshoot Telegram bot connection issues. Token validity, webhook setup, and group permissions.',
    seoTitle: 'Fix: Telegram Bot Not Responding - Connection Troubleshooting',
    seoDescription: 'Fix Telegram bot not responding. Check bot token, webhook status, group privacy settings, and admin permissions.',
    keywords: ['telegram bot not responding', 'telegram bot not working', 'fix telegram bot', 'telegram bot offline'],
  },
  {
    slug: 'telegram-bot-session-expired',
    title: 'Telegram Bot Session Expired',
    description: 'Fix userbot authentication issues. MTProto session renewal, 2FA verification, and flood wait errors.',
    seoTitle: 'Fix: Telegram Bot Session Expired',
    seoDescription: 'Fix Telegram userbot session expiry. Re-authenticate MTProto session, handle flood wait errors, and 2FA issues.',
    keywords: ['telegram userbot session expired', 'mtproto session fix', 'telegram userbot auth error'],
  },
  {
    slug: 'telegram-download-not-working',
    title: 'Telegram Download Command Not Working',
    description: 'Fix video download issues. Supported platforms, URL format, file size limits, and geo-restrictions.',
    seoTitle: 'Fix: Telegram Download Bot Not Working',
    seoDescription: 'Fix !download command issues. Supported platforms (TikTok, YouTube, Instagram), URL format, and file size limits.',
    keywords: ['telegram download bot not working', 'tiktok download bot error', 'youtube download telegram fix'],
  },
  {
    slug: 'telegram-bot-not-joining-group',
    title: 'Telegram Bot Not Working in Group',
    description: 'Bot works in private but not in groups. Check admin status, group settings, and invite link.',
    seoTitle: 'Fix: Telegram Bot Not Working in Group',
    seoDescription: 'Fix Telegram bot not responding in groups. Check if bot number is admin, group privacy settings, and message visibility.',
    keywords: ['telegram bot not working in group', 'bot not responding in group', 'telegram group bot fix'],
  },
  {
    slug: 'telegram-ai-not-responding',
    title: 'Telegram AI Command Not Working',
    description: 'Fix !ai command issues. Daily limit reached, server load, and quota resets.',
    seoTitle: 'Fix: Telegram AI Bot Not Responding',
    seoDescription: 'Fix !ai command not working. Check daily query limit (10/day free), server status, and syntax.',
    keywords: ['telegram ai bot not working', 'ai command not responding', 'telegram ai limit'],
  },
  // ── Programmatic SEO: Additional fix/troubleshooting pages ──
  { slug: 'telegram-bot-not-responding', title: 'Telegram Bot Not Responding', description: 'How to fix "Telegram Bot Not Responding". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Not Responding - Troubleshooting Guide', seoDescription: 'Fix telegram bot not responding. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot not responding', 'fix telegram bot'] },
  { slug: 'telegram-bot-slow', title: 'Telegram Bot Responding Slowly', description: 'How to fix "Telegram Bot Responding Slowly". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Responding Slowly - Troubleshooting Guide', seoDescription: 'Fix telegram bot responding slowly. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot slow', 'bot slow response'] },
  { slug: 'telegram-sticker-not-working', title: 'Telegram Sticker Command Not Working', description: 'How to fix "Telegram Sticker Command Not Working". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Sticker Command Not Working - Troubleshooting Guide', seoDescription: 'Fix telegram sticker command not working. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram sticker not working', 'fix sticker bot'] },
  { slug: 'telegram-download-failed', title: 'Telegram Download Command Failed', description: 'How to fix "Telegram Download Command Failed". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Download Command Failed - Troubleshooting Guide', seoDescription: 'Fix telegram download command failed. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram download failed', 'fix download bot'] },
  { slug: 'telegram-bot-403-error', title: 'Telegram Bot 403 Forbidden Error', description: 'How to fix "Telegram Bot 403 Forbidden Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot 403 Forbidden Error - Troubleshooting Guide', seoDescription: 'Fix telegram bot 403 forbidden error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot 403', 'fix 403 error'] },
  { slug: 'telegram-bot-401-error', title: 'Telegram Bot 401 Authentication Error', description: 'How to fix "Telegram Bot 401 Authentication Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot 401 Authentication Error - Troubleshooting Guide', seoDescription: 'Fix telegram bot 401 authentication error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot 401', 'fix auth error'] },
  { slug: 'telegram-bot-428-error', title: 'Telegram Bot 428 Rate Limit Error', description: 'How to fix "Telegram Bot 428 Rate Limit Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot 428 Rate Limit Error - Troubleshooting Guide', seoDescription: 'Fix telegram bot 428 rate limit error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot 428', 'fix rate limit'] },
  { slug: 'telegram-bot-515-error', title: 'Telegram Bot 515 Restart Error', description: 'How to fix "Telegram Bot 515 Restart Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot 515 Restart Error - Troubleshooting Guide', seoDescription: 'Fix telegram bot 515 restart error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot 515', 'fix restart error'] },
  { slug: 'telegram-pairing-code-expired', title: 'Telegram Pairing Code Expired', description: 'How to fix "Telegram Pairing Code Expired". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Pairing Code Expired - Troubleshooting Guide', seoDescription: 'Fix telegram pairing code expired. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram pairing code expired', 'fix pairing code'] },
  { slug: 'telegram-session-conflict', title: 'Telegram Session Conflict Error', description: 'How to fix "Telegram Session Conflict Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Session Conflict Error - Troubleshooting Guide', seoDescription: 'Fix telegram session conflict error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram session conflict', 'fix session conflict'] },
  { slug: 'telegram-multi-device-issue', title: 'Telegram Multi-Device Bot Issue', description: 'How to fix "Telegram Multi-Device Bot Issue". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Multi-Device Bot Issue - Troubleshooting Guide', seoDescription: 'Fix telegram multi-device bot issue. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram multi device issue', 'fix multi device bot'] },
  { slug: 'telegram-group-bot-not-admin', title: 'Telegram Bot Not Admin in Group', description: 'How to fix "Telegram Bot Not Admin in Group". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Not Admin in Group - Troubleshooting Guide', seoDescription: 'Fix telegram bot not admin in group. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot not admin', 'bot admin permissions'] },
  { slug: 'telegram-media-not-sending', title: 'Telegram Bot Not Sending Media', description: 'How to fix "Telegram Bot Not Sending Media". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Not Sending Media - Troubleshooting Guide', seoDescription: 'Fix telegram bot not sending media. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot media failed', 'fix media sending'] },
  { slug: 'telegram-bot-duplicate-messages', title: 'Telegram Bot Sending Duplicate Messages', description: 'How to fix "Telegram Bot Sending Duplicate Messages". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Sending Duplicate Messages - Troubleshooting Guide', seoDescription: 'Fix telegram bot sending duplicate messages. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot duplicate', 'fix duplicate messages'] },
  { slug: 'telegram-bot-wrong-language', title: 'Telegram Bot Responding in Wrong Language', description: 'How to fix "Telegram Bot Responding in Wrong Language". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Responding in Wrong Language - Troubleshooting Guide', seoDescription: 'Fix telegram bot responding in wrong language. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot wrong language', 'change bot language'] },
  { slug: 'telegram-bot-kicked', title: 'Telegram Bot Kicked from Group', description: 'How to fix "Telegram Bot Kicked from Group". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Kicked from Group - Troubleshooting Guide', seoDescription: 'Fix telegram bot kicked from group. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot kicked', 'fix telegram bot kicked'] },
  { slug: 'telegram-bot-no-permissions', title: 'Telegram Bot Missing Permissions', description: 'How to fix "Telegram Bot Missing Permissions". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Missing Permissions - Troubleshooting Guide', seoDescription: 'Fix telegram bot missing permissions. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot permissions', 'fix telegram bot admin'] },
  { slug: 'telegram-bot-flood-wait', title: 'Telegram Bot Flood Wait Error', description: 'How to fix "Telegram Bot Flood Wait Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Flood Wait Error - Troubleshooting Guide', seoDescription: 'Fix telegram bot flood wait error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram flood wait', 'fix telegram rate limit'] },
  { slug: 'telegram-bot-2fa-error', title: 'Telegram Bot 2FA Error', description: 'How to fix "Telegram Bot 2FA Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot 2FA Error - Troubleshooting Guide', seoDescription: 'Fix telegram userbot 2fa error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram userbot 2fa', 'fix userbot authentication'] },
  { slug: 'telegram-bot-disconnected', title: 'Telegram Bot Keeps Disconnecting', description: 'How to fix "Telegram Bot Keeps Disconnecting". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Keeps Disconnecting - Troubleshooting Guide', seoDescription: 'Fix telegram userbot keeps disconnecting. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram userbot disconnecting', 'fix userbot connection'] },
  { slug: 'bot-commands-not-working', title: 'Bot Commands Not Working', description: 'How to fix "Bot Commands Not Working". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Bot Commands Not Working - Troubleshooting Guide', seoDescription: 'Fix bot commands not working. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['bot commands not working', 'fix bot commands'] },
  { slug: 'bot-dashboard-not-loading', title: 'BotWave Dashboard Not Loading', description: 'How to fix "BotWave Dashboard Not Loading". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: BotWave Dashboard Not Loading - Troubleshooting Guide', seoDescription: 'Fix botwave dashboard not loading. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['botwave dashboard not loading', 'fix dashboard'] },
  { slug: 'bot-session-needs-reauth', title: 'Bot Session Needs Re-authentication', description: 'How to fix "Bot Session Needs Re-authentication". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Bot Session Needs Re-authentication - Troubleshooting Guide', seoDescription: 'Fix bot session needs re-authentication. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['bot needs reauth', 'fix bot authentication'] },
  { slug: 'telegram-bot-logged-out', title: 'Telegram Bot Logged Out Automatically', description: 'How to fix "Telegram Bot Logged Out Automatically". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Telegram Bot Logged Out Automatically - Troubleshooting Guide', seoDescription: 'Fix telegram bot logged out automatically. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['telegram bot logged out', 'fix auto logout'] },
  { slug: 'telegram-evolution-api-error', title: 'Evolution API Connection Error', description: 'How to fix "Evolution API Connection Error". Step-by-step troubleshooting guide with solutions.', seoTitle: 'Fix: Evolution API Connection Error - Troubleshooting Guide', seoDescription: 'Fix evolution api connection error. Step-by-step troubleshooting with solutions. Common causes and fixes.', keywords: ['evolution api error', 'fix evolution api'] },
];
