/**
 * BotWave Response Variation Pools
 *
 * Every command has 50-100 response variations to avoid identical
 * message fingerprints. Dynamic variables {name}, {time}, {date}
 * are injected at send time.
 */

// ─── Sticker Replies ──────────────────────────────────────────────────────────
export const stickerReplies: string[] = [
  "Here's your sticker!",
  'Sticker created!',
  'Done! Your sticker is ready',
  'Sticker delivered, {name}!',
  'Here you go, {name}!',
  'Fresh sticker for you!',
  'Got your sticker right here!',
  'Sticker incoming!',
  'Your sticker is ready!',
  'Made at {time} just for you!',
  'Sticker done, {name}!',
  'One sticker, coming up!',
  'Enjoy your sticker!',
  'Your custom sticker!',
  'Sticker created for {name}',
  'Check out your sticker!',
  'Brand new sticker!',
  'Here it is, {name}!',
  'Done! Sticker sent',
  'Your sticker, served fresh!',
  'Sticker made at {time}',
  'Ready! Your sticker',
  'Sticker is done!',
  'Sent your sticker, {name}!',
  'Sticker complete!',
  'A sticker for {name}!',
  'Got it! Sticker ready',
  'Sticker crafted!',
  'Your sticker has landed!',
  'Here, {name}! Your sticker',
  'Sticker processed!',
  'Done! Here ya go',
  'Your image is now a sticker!',
  'Converted to sticker!',
  'Sticker for you, {name}!',
  'Quick sticker for you!',
  'All done! Sticker ready',
  'Your sticker awaits!',
  'Hot off the press!',
  'Your sticker, as requested!',
  '{name}, your sticker!',
  'New sticker alert!',
  'Sticker mode activated!',
  'One sticker done!',
  'Image converted!',
  'Your sticker is served!',
  'Boom! Sticker ready',
  'Sticker magic done!',
  'Freshly made sticker!',
  'Sticker sent, {name}!',
  'There you go, {name}!',
  'Sticker delivered at {time}!',
  'Look what I made, {name}!',
  'Another sticker for the collection!',
  'Sticker factory says: Done!',
  'Got your sticker ready!',
  'Fresh out of the sticker oven!',
  'Sticker game strong, {name}!',
  '{name}, sticker is locked and loaded!',
  'And boom, sticker!',
  'Your sticker just dropped!',
  'Created on {date} at {time}',
  'Sticker secured!',
  'Made this one just for you, {name}!',
  'Express sticker delivery!',
  'Sticker report: Ready!',
  'Custom sticker for {name} at {time}!',
  'Freshly baked sticker!',
  '{name} sticker is here!',
  'Here comes your sticker!',
  'Sticker loaded and sent!',
  'Your daily sticker, {name}!',
  'Sticker dispatch complete!',
  'Quick delivery for {name}!',
  'Serving up a fresh sticker!',
  'Your sticker request: Fulfilled!',
  'Sticker crafted at {time} for {name}!',
  'Done and dusted, sticker sent!',
  'Art delivered!',
  'Sticker acquired!',
];

// ─── AFK Replies ──────────────────────────────────────────────────────────────
export const afkReplies: string[] = [
  'Hey! {name} is away right now',
  '{name} stepped out, message noted',
  "They're unavailable right now, will notify them",
  '{name} is currently away',
  '{name} is AFK at the moment',
  'Heads up: {name} is not available',
  '{name} went offline for a bit',
  '{name} is busy right now',
  'Message received! {name} is away',
  "{name} can't respond right now",
  '{name} is taking a break',
  '{name} stepped away for a moment',
  "{name} isn't here right now",
  'Got your message! {name} is AFK',
  '{name} is offline temporarily',
  '{name} will be back soon',
  'Noted! {name} is currently away',
  '{name} is unavailable right now',
  'Message saved! {name} is AFK',
  '{name} has gone AFK',
  'Hey, {name} is not around',
  '{name} is out right now',
  "I'll let {name} know!",
  '{name} went AFK a while ago',
  '{name} is doing something else',
  "Don't worry, {name} will see this later",
  '{name} stepped out at {time}',
  '{name} is away since a while',
  'Away notice: {name} is not here',
  '{name} set their status to away',
  'Ping! {name} is offline',
  '{name} has been away for a bit',
  '{name} is currently occupied',
  'Message logged! {name} is AFK',
  'Hey there! {name} is away',
  '{name} is on a break right now',
  '{name} will reply when back',
  'Auto-reply: {name} is away',
  '{name} is not available currently',
  "I'll pass your message to {name}",
  '{name} will get back to you',
  "Heads up, {name} isn't online",
  '{name} left at {time}',
  '{name} is temporarily away',
  '{name} will respond later',
  'Quick note: {name} is AFK',
  '{name} went offline',
  'Away: {name} is not here',
  'Hold tight! {name} is away',
  '{name} is currently AFK',
  '{name} has stepped away. Will notify them!',
  '{name} is not available. Try again later!',
  'Looks like {name} is away at the moment',
  '{name} went AFK. Message stored!',
  'Just a heads up, {name} is away right now',
  'Message received for {name}. They are AFK!',
  '{name} can\'t come to the phone right now',
  'Away alert: {name} is not here at {time}',
  '{name} is offline. Your message was saved',
  '{name} is taking time off. Noted your message!',
  'FYI: {name} is currently not available',
  '{name} is away. I\'ll make sure they see this!',
  '{name} went away at {time}. Message recorded.',
  'Quick update: {name} is AFK right now',
  '{name} is on a break. Will pass your message!',
  'Hey! {name} went AFK. Try later!',
  '{name} is away. Your message is queued!',
  '{name} has gone quiet for now',
  'Notification sent to {name}! They\'re away',
  '{name} is off the grid right now',
];

// ─── Joke Pool ────────────────────────────────────────────────────────────────
export const jokePool: string[] = [
  'Why do programmers prefer dark mode? Because light attracts bugs!',
  "Why was the JavaScript developer sad? Because he didn't Node how to Express himself!",
  "How many programmers does it take to change a light bulb? None, that's a hardware problem!",
  "Why do Java developers wear glasses? Because they can't C#!",
  'A SQL query walks into a bar, walks up to two tables and asks... "Can I join you?"',
  'Why did the developer go broke? Because he used up all his cache!',
  "What's a programmer's favorite hangout place? Foo Bar!",
  'Why do programmers hate nature? It has too many bugs!',
  '!false — it\'s funny because it\'s true',
  'There are 10 types of people: those who understand binary and those who don\'t',
  'A programmer was found dead in the shower. The instructions on the shampoo read: Lather, Rinse, Repeat.',
  "What's a computer's least favorite food? Spam!",
  'Why did the functions stop calling each other? They got into an argument!',
  "I'd tell you a UDP joke, but you might not get it.",
  'I told my computer I needed a break, and now it won\'t stop sending me Kit-Kat ads.',
  "What's the object-oriented way to become rich? Inheritance!",
  'Why do Python programmers have low self-esteem? They\'re constantly comparing themselves to others.',
  'What do you call 8 hobbits? A hobbyte.',
  "An SEO expert walks into a bar, pub, inn, tavern, public house, Irish bar...",
  'How do you comfort a JavaScript bug? You console it!',
  "What's a programmer's favorite tea? Chai-nese tea.",
  'Why was the computer cold? It left its Windows open!',
  'What do computers snack on? Microchips!',
  'Why did the computer go to the doctor? It had a virus!',
  'What did the spider do on the internet? Built a website!',
  "How does a computer get drunk? It takes screenshots!",
  "What do you call a computer that sings? A-Dell!",
  "Why couldn't the computer take its hat off? Because it had its CAPS LOCK on!",
  "What do you call a group of unorganized cats? A cat-alogue!",
  "Why did the PowerPoint cross the road? To get to the other slide!",
  "What's the best way to carve wood? Whittle by whittle.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I asked my dog what's two minus two. He said nothing.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I used to hate facial hair, but then it grew on me.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why do bees hum? Because they don't know the words!",
  "What do you call a fake noodle? An impasta!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I couldn't figure out how to put my seatbelt on. Then it clicked!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Did you hear about the claustrophobic astronaut? He needed more space.",
  "Why don't eggs tell jokes? They'd crack each other up!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a sleeping dinosaur? A dino-snore!",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the scarecrow win an award? He was outstanding in his field!",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I'm friends with 25 letters of the alphabet. I don't know Y.",
  "What do you call a belt made of watches? A waist of time!",
  "Why do cows have hooves instead of feet? Because they lactose!",
  "How does Moses make tea? Hebrews it!",
  "Why can't your nose be 12 inches long? Because then it would be a foot!",
  "What do you call a fish without eyes? A fsh!",
  "Why don't oysters donate? Because they are shellfish!",
  "I just flew in from New York. Boy, are my arms tired!",
  "What's orange and sounds like a parrot? A carrot!",
  "Why did the bicycle fall over? It was two-tired!",
  "I told my friend she drew her eyebrows too high. She seemed surprised.",
  "What do you call a dog that does magic tricks? A Labracadabrador!",
  "Why don't calendars ever get stressed? Because they know their days are numbered!",
  "I have a joke about construction, but I'm still working on it.",
  "What do you call a boomerang that doesn't come back? A stick!",
  "Why did the mushroom go to the party? Because he was a fun-guy!",
  "What's the best thing about Switzerland? The flag is a big plus!",
  "I told a chemistry joke. There was no reaction.",
  "How do trees access the internet? They log in!",
];

// ─── Quote Pool ───────────────────────────────────────────────────────────────
export const quotePool: string[] = [
  '"The only way to do great work is to love what you do." — Steve Jobs',
  '"Innovation distinguishes between a leader and a follower." — Steve Jobs',
  '"Stay hungry, stay foolish." — Steve Jobs',
  '"The future belongs to those who believe in the beauty of their dreams." — Eleanor Roosevelt',
  '"It does not matter how slowly you go as long as you do not stop." — Confucius',
  '"Life is what happens when you\'re busy making other plans." — John Lennon',
  '"In the middle of every difficulty lies opportunity." — Albert Einstein',
  '"The best time to plant a tree was 20 years ago. The second best time is now." — Chinese Proverb',
  '"Be the change you wish to see in the world." — Mahatma Gandhi',
  '"Your time is limited, don\'t waste it living someone else\'s life." — Steve Jobs',
  '"Believe you can and you\'re halfway there." — Theodore Roosevelt',
  '"The only impossible journey is the one you never begin." — Tony Robbins',
  '"Success is not final, failure is not fatal: It is the courage to continue that counts." — Winston Churchill',
  '"What you get by achieving your goals is not as important as what you become by achieving your goals." — Zig Ziglar',
  '"If you want to lift yourself up, lift up someone else." — Booker T. Washington',
  '"Strive not to be a success, but rather to be of value." — Albert Einstein',
  '"You miss 100% of the shots you don\'t take." — Wayne Gretzky',
  '"The purpose of life is not to be happy. It is to be useful." — Ralph Waldo Emerson',
  '"Do what you can, with what you have, where you are." — Theodore Roosevelt',
  '"Act as if what you do makes a difference. It does." — William James',
  '"The mind is everything. What you think you become." — Buddha',
  '"An unexamined life is not worth living." — Socrates',
  '"Everything you\'ve ever wanted is on the other side of fear." — George Addair',
  '"What lies behind us and what lies before us are tiny matters compared to what lies within us." — Ralph Waldo Emerson',
  '"Happiness is not something ready made. It comes from your own actions." — Dalai Lama',
  '"Keep your face always toward the sunshine—and shadows will fall behind you." — Walt Whitman',
  '"If you look at what you have in life, you\'ll always have more." — Oprah Winfrey',
  '"You only live once, but if you do it right, once is enough." — Mae West',
  '"The best revenge is massive success." — Frank Sinatra',
  '"Life is 10% what happens to me and 90% of how I react to it." — Charles Swindoll',
  '"Not all who wander are lost." — J.R.R. Tolkien',
  '"The greatest glory in living lies not in never falling, but in rising every time we fall." — Nelson Mandela',
  '"Life is really simple, but we insist on making it complicated." — Confucius',
  '"It is never too late to be what you might have been." — George Eliot',
  '"When one door of happiness closes, another opens." — Helen Keller',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." — Robert Frost',
  '"Dream big and dare to fail." — Norman Vaughan',
  '"Turn your wounds into wisdom." — Oprah Winfrey',
  '"Simplicity is the ultimate sophistication." — Leonardo da Vinci',
  '"What we think, we become." — Buddha',
  '"Doubt kills more dreams than failure ever will." — Suzy Kassem',
  '"The harder I work, the luckier I get." — Gary Player',
  '"Start where you are. Use what you have. Do what you can." — Arthur Ashe',
  '"The only limit to our realization of tomorrow will be our doubts of today." — Franklin D. Roosevelt',
  '"Don\'t count the days, make the days count." — Muhammad Ali',
  '"Quality is not an act, it is a habit." — Aristotle',
  '"The way to get started is to quit talking and begin doing." — Walt Disney',
  '"Everything has beauty, but not everyone sees it." — Confucius',
  '"Education is the most powerful weapon which you can use to change the world." — Nelson Mandela',
  '"Creativity is intelligence having fun." — Albert Einstein',
  '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." — Aristotle',
  '"The only person you are destined to become is the person you decide to be." — Ralph Waldo Emerson',
  '"Go confidently in the direction of your dreams." — Henry David Thoreau',
  '"Well done is better than well said." — Benjamin Franklin',
  '"Try not to become a person of success, but rather a person of value." — Albert Einstein',
  '"The secret of getting ahead is getting started." — Mark Twain',
  '"It always seems impossible until it is done." — Nelson Mandela',
  '"Nothing is impossible. The word itself says I\'m possible!" — Audrey Hepburn',
  '"Opportunities don\'t happen. You create them." — Chris Grosser',
  '"Don\'t wait. The time will never be just right." — Napoleon Hill',
  '"Hard work beats talent when talent doesn\'t work hard." — Tim Notke',
  '"Success usually comes to those who are too busy to be looking for it." — Henry David Thoreau',
  '"If you really look closely, most overnight successes took a long time." — Steve Jobs',
  '"The only place where success comes before work is in the dictionary." — Vidal Sassoon',
  '"Don\'t be afraid to give up the good to go for the great." — John D. Rockefeller',
  '"I find that the harder I work, the more luck I seem to have." — Thomas Jefferson',
  '"Success is walking from failure to failure with no loss of enthusiasm." — Winston Churchill',
  '"A person who never made a mistake never tried anything new." — Albert Einstein',
  '"Life shrinks or expands in proportion to one\'s courage." — Anais Nin',
  '"Twenty years from now you will be more disappointed by the things you didn\'t do." — Mark Twain',
];

// ─── Horoscope Data ───────────────────────────────────────────────────────────
export const horoscopeSigns: Record<string, { emoji: string; element: string }> = {
  aries:       { emoji: '', element: 'Fire' },
  taurus:      { emoji: '', element: 'Earth' },
  gemini:      { emoji: '', element: 'Air' },
  cancer:      { emoji: '', element: 'Water' },
  leo:         { emoji: '', element: 'Fire' },
  virgo:       { emoji: '', element: 'Earth' },
  libra:       { emoji: '', element: 'Air' },
  scorpio:     { emoji: '', element: 'Water' },
  sagittarius: { emoji: '', element: 'Fire' },
  capricorn:   { emoji: '', element: 'Earth' },
  aquarius:    { emoji: '', element: 'Air' },
  pisces:      { emoji: '', element: 'Water' },
};

export const horoscopeReadings: string[] = [
  'Today is a great day for new beginnings. Trust your instincts and take that first step.',
  'The stars align in your favor. Focus on personal growth and creative expression.',
  'A surprising opportunity may come your way today. Stay open-minded.',
  'Communication is key today. Express your feelings honestly and listen carefully.',
  'Financial matters require attention. Be cautious with spending today.',
  'Love is in the air! If single, keep your eyes open. If taken, plan something special.',
  'Your energy levels are high today. Channel that into productive activities.',
  'Take a moment to reflect on your goals. Adjust your path if needed.',
  'Social connections bring joy today. Reach out to old friends.',
  'Patience is your greatest ally today. Good things come to those who wait.',
  'Your creativity is peaking. Use it to solve a lingering problem.',
  'Health matters deserve your attention today. Take a walk or try something new.',
  'A mentor figure may appear in your life. Be receptive to their guidance.',
  'Today favors collaboration over solo efforts. Teamwork makes the dream work.',
  'Let go of past grudges. Forgiveness will bring you peace.',
  'An unexpected conversation could change your perspective today.',
  'Trust the process. What feels uncertain now will make sense soon.',
  'Your determination is your superpower today. Push through obstacles.',
  'Romance and passion are highlighted. Express your feelings boldly.',
  'Financial decisions made today will have long-term impact. Choose wisely.',
  'Adventure calls! Step out of your comfort zone.',
  'Family matters need attention. Show your loved ones you care.',
  'Your intuition is particularly strong today. Trust your gut feelings.',
  'A creative project could gain momentum. Dedicate time to your passions.',
  'Balance work and play. Burnout is a real risk if you push too hard.',
  'Positive energy surrounds you. Spread it to those around you.',
  'Learning something new today could open unexpected doors.',
  'Your kindness will be rewarded. Keep being generous.',
  'Change is coming. Embrace it rather than resist.',
  'Today is perfect for setting long-term goals. Dream big!',
  'Spiritual growth is favored. Meditate or spend time in nature.',
  'Your words carry extra power today. Use them wisely.',
  'A financial surprise could brighten your day. Stay positive.',
  'Relationships deepen when you show vulnerability. Be authentic.',
  'Physical activity will boost your mood and clarity today.',
  'Old patterns may resurface. Choose differently this time.',
  'A chance encounter could lead to a lasting connection.',
  'Focus on self-care. You deserve time to recharge.',
  'Your hard work is about to pay off. Keep going!',
  'Today brings clarity to a confusing situation. Answers emerge.',
  'Be mindful of your spending habits today.',
  'A friend needs your support. Be there for them.',
  'Travel plans or adventures are favored today.',
  'Your charm is magnetic today. Use it for good.',
  'Take a leap of faith. The universe has your back.',
  'Organize your space, organize your mind. Declutter today.',
  'A creative breakthrough awaits. Keep experimenting.',
  'Gratitude shifts your energy. Count your blessings.',
  'Exciting news could arrive. Stay alert and ready.',
  'Today is about progress, not perfection. Move forward.',
  'New friendships may blossom if you open up to new experiences.',
  'A minor setback is actually redirecting you to something better.',
  'Your emotional intelligence is your gift today. Use it wisely.',
  'Career opportunities are knocking. Prepare to answer.',
  'A heartfelt conversation can heal old wounds today.',
  'Numbers are lucky for you today. Pay attention to patterns.',
  'Rest is productive too. Allow yourself to slow down.',
  'Someone from your past may reach out. Handle with grace.',
  'Your natural leadership shines today. Guide others confidently.',
  'Today favors bold moves and brave decisions.',
];

// ─── Promo Messages ───────────────────────────────────────────────────────────
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://botwave-tx86.onrender.com';

export const promoMessages: string[] = [
  `\n─────────────────────────────\nWant your own WhatsApp bot?\nCreate yours FREE at ${APP_URL}/signup`,
  `\n─────────────────────────────\nLove this feature?\nGet your own bot FREE at ${APP_URL}/signup`,
  `\n─────────────────────────────\nPowered by BotWave\nCreate yours FREE at ${APP_URL}/signup`,
  `\n─────────────────────────────\nMade with BotWave\nGet your own bot at ${APP_URL}/signup`,
  `\n─────────────────────────────\nBotWave — Free WhatsApp Bot\nStart yours at ${APP_URL}/signup`,
  `\n─────────────────────────────\nImpressed? Build your own!\nFREE at ${APP_URL}/signup`,
  `\n─────────────────────────────\nThis bot runs on BotWave\nMake yours: ${APP_URL}/signup`,
  `\n─────────────────────────────\nBotWave powers this bot\nYour own bot: ${APP_URL}/signup`,
  `\n─────────────────────────────\nAutomate WhatsApp for free\n${APP_URL}/signup`,
  `\n─────────────────────────────\nBotWave — by Decisive Analyst\nGet started: ${APP_URL}/signup`,
];

// ─── Ping Replies ─────────────────────────────────────────────────────────────
export const pingReplies: string[] = [
  'PONG! Bot is online and running',
  'I\'m alive! Responding from BotWave HQ',
  'Online and ready, {name}!',
  'PONG! All systems operational',
  'Hey {name}! Bot is active',
  'I\'m here! Latency looking good',
  'System check: All green!',
  'Bot is running smoothly!',
  'Connected and ready!',
  'PONG! Response time excellent',
  'I\'m awake and working!',
  'Status: Operational',
  'All systems go, {name}!',
  'Bot reporting for duty!',
  'Here and ready!',
  'Systems online, {name}!',
  'Active and listening!',
  'PONG! Everything is good',
  'Running strong!',
  'Bot status: Online',
  'I read you loud and clear!',
  'Here! What do you need?',
  'PONG! Running at {time}',
  'Up and running since startup!',
  'Bot is healthy and responsive!',
  'Present and accounted for!',
  'All engines running!',
  'PONG! Quick response!',
  'Bot is live, {name}!',
  'Check complete: All OK',
  'Still here, still working!',
  'PONG! No issues detected',
  'Bot health: Excellent',
  'Online status confirmed!',
  'System heartbeat: Normal',
  'Running without issues!',
  'Here and operational!',
  'PONG! Server time: {time}',
  'All good on my end!',
  'Active since last restart!',
  'Yep, I\'m here!',
  'PONG! Ready for commands',
  'Still kicking!',
  'Bot engine running fine!',
  'Operational at {time}',
  'PONG! All clear',
  'I\'m online, {name}!',
  'Working perfectly!',
  'PONG! Everything\'s fine',
  'Bot is responsive!',
];

// ─── Help Intro Lines ─────────────────────────────────────────────────────────
export const helpIntros: string[] = [
  'Here are all available commands, {name}!',
  'Command list coming up!',
  'Check out what I can do, {name}!',
  'Here\'s everything I can do!',
  'Your command menu, {name}!',
  'All commands at your service, {name}!',
  'Here\'s the full list of what I offer!',
  'Need help? Here are all my commands!',
  'BotWave commands for you, {name}!',
  'Here\'s my feature list!',
  'What can I do? Let me show you, {name}!',
  'Your BotWave guide, {name}!',
  'Commands ready! Here you go, {name}!',
  'The full command list, {name}!',
  'Everything I can do, {name}:',
  'My capabilities for you, {name}!',
  'Check these out, {name}!',
  'Command reference ready!',
  '{name}, here\'s what\'s available!',
  'All features and commands, {name}!',
  'Here\'s your BotWave manual!',
  'My full feature list, {name}!',
  '{name}, here\'s what I can do for you!',
  'Command guide coming right up!',
  'Here\'s your help menu!',
  'Available commands, {name}:',
  'Let me show you everything!',
  'Your BotWave cheat sheet!',
  'Here\'s the full menu, {name}!',
  '{name}, check out all these features!',
  'Ready to help! Here are the commands:',
  'BotWave feature guide for {name}!',
  'All systems and commands listed below!',
  'Here you go, {name}! Full command list:',
  'BotWave help menu ready!',
  'What I can do for you, {name}:',
  'Full list of available commands:',
  'Need something? Here\'s what I\'ve got!',
  'Check it, {name}! All my commands:',
  '{name}, your help guide is here!',
  'Here\'s every command I know!',
  'Bot commands at a glance, {name}!',
  'All features unlocked, {name}!',
  'Help menu loaded!',
  'Commands, features, and more:',
  'Your personal command guide!',
  'Here\'s the rundown, {name}!',
  '{name}, take a look at my commands!',
  'Everything I\'m capable of!',
  'BotWave: Full command list for {name}!',
];

// ─── Unknown Command Replies ──────────────────────────────────────────────────
export const unknownCommandReplies: string[] = [
  'Hmm, I don\'t know that command. Try !help',
  'Unknown command! Use !help to see available commands',
  'That\'s not a command I recognize. Type !help',
  'Sorry, didn\'t catch that. Try !help for the full list',
  'Command not found. Check !help for options',
  'I don\'t understand that one. Use !help',
  'That command doesn\'t exist yet! Try !help',
  'Oops, unknown command. !help has the full list',
  'Hmm? Try !help to see what I can do',
  'Not sure what you mean. !help might help!',
  'Can\'t find that command, {name}. Try !help',
  'Invalid command! Type !help for options',
  '{name}, that\'s not a valid command. Use !help',
  'Nope, don\'t have that one. Check !help',
  'That one\'s not in my playbook. Try !help',
  'I wish I could do that! For now, try !help',
  'Command not recognized, {name}. Use !help',
  'Hmm, never heard of that. Try !help?',
  'I\'m confused! Try !help for my command list',
  'That doesn\'t ring a bell. Type !help',
  'Not a valid command. !help to the rescue!',
  'I can\'t do that one. Check !help, {name}!',
  'Doesn\'t look like a command. Try !help',
  '{name}, use !help to see what I can do!',
  'Command what? Try !help for the menu',
  'I don\'t have that feature. See !help',
  'Sorry {name}, unknown command. !help works!',
  'That\'s new to me! Check out !help',
  'Unknown input. Type !help for commands',
  'Hmm, nope. But !help has everything!',
  '{name}, check !help for all my commands',
  'Not in my repertoire! Try !help',
  'I can\'t process that. Use !help, {name}',
  'That command is missing. Try !help',
  'Unrecognized! See !help for the list',
  'What was that? !help shows everything I do',
  'Command error. Type !help for the menu',
  'I don\'t know that yet. Try !help!',
  'Lost? !help will show you the way, {name}!',
  'Can\'t find it. Use !help for guidance',
  'Not a thing! But !help has plenty of things',
  'Sorry, that\'s not available. !help for options',
  'Draw a blank on that one. Try !help',
  'No match found. Type !help for commands',
  '{name}, try !help to discover my features',
  'That went over my head. Use !help!',
  'Unknown territory! Navigate with !help',
  'I didn\'t get that, {name}. Use !help',
  'What? Use !help for command options',
  'That\'s beyond me for now. Check !help!',
];

// ─── Doc Created Replies ──────────────────────────────────────────────────────
export const docReplies: string[] = [
  'Your document is ready, {name}!',
  'Document created successfully!',
  'Here\'s your document!',
  'Doc generated at {time}',
  'Your .docx file is ready!',
  'Document created for {name}!',
  'File ready! Here you go',
  'Document done!',
  'Your formatted document',
  '{name}, here\'s your doc!',
  'Created your document!',
  'Document is served!',
  'Fresh document for you!',
  'File created at {time}',
  'Your document, as requested!',
  'Doc ready, {name}!',
  'Done! Here\'s your document',
  'Document prepared!',
  'Your file is ready!',
  'Doc generated for {name}!',
  'Text converted to document!',
  'Your .docx is ready!',
  'Document complete!',
  'Here\'s your file, {name}!',
  'Document delivered!',
  'Created at {time}',
  'Your formatted doc!',
  'File is ready, {name}!',
  'Document made!',
  'Here you go, {name}!',
  'Fresh doc incoming!',
  'Your text as a document!',
  'Done! Document attached',
  '{name}\'s document is ready!',
  'File generated successfully!',
  'Document for {name}, done!',
  'Ready! Your .docx file',
  'Text to doc complete!',
  'Your new document!',
  'Doc is done, {name}!',
  'Created your file!',
  'Your document was created!',
  'Document exported!',
  'File created for {name}!',
  'Doc generated!',
  'Formatted and ready!',
  'Your doc file!',
  'Done, {name}! Document attached',
  'Document saved!',
  'Here it is, {name}! Your document',
  'Hot off the press, {name}! Your doc',
  'Doc file delivered at {time}!',
  'Your professional document is here!',
  'Converted to .docx for {name}!',
  '{name}, document incoming!',
  'Check your document, {name}!',
  'File packaged and sent!',
  'Your text, now a proper document!',
  'Document created on {date}!',
  'Your .docx has been generated!',
];

// ─── Translate Replies ────────────────────────────────────────────────────────
export const translateReplies: string[] = [
  'Translation ready!',
  'Here\'s your translation, {name}!',
  'Translated at {time}',
  'Translation complete!',
  'Done! Here\'s the translation',
  'Your translated text:',
  'Translation for {name}!',
  'Translated successfully!',
  'Here you go, {name}! Translated:',
  'Translation done!',
  'Text translated for {name}!',
  'Your translation is ready!',
  'Language converted!',
  '{name}, here\'s the translation!',
  'Translated in a flash!',
  'Quick translation ready!',
  'Your text, translated:',
  'Translation completed at {time}!',
  '{name}, translation delivered!',
  'Here\'s what it says:',
  'Language barrier broken!',
  'Translated just for you, {name}!',
  'Translation served at {time}!',
  'Got the translation!',
  'Your translated message:',
  'Words translated successfully!',
  'Translated and ready, {name}!',
  '{name}\'s translation is here!',
  'Quick translate done!',
  'Conversion complete!',
  'Here\'s your text in the new language:',
  'Translation magic done!',
  'Linguistically converted, {name}!',
  'Text transformed!',
  'Your multilingual message:',
  'Fresh translation, {name}!',
  'Translation output ready!',
  'Done translating for {name}!',
  'Translation express delivery!',
  'Language swap complete!',
  'Translated text incoming!',
  '{name}, your words translated:',
  'Fast translation ready!',
  'Cross-language conversion done!',
  'Text translated at {time}!',
  'Here\'s the translated version:',
  'Translation locked in!',
  'Your request: Translated!',
  'Words converted, {name}!',
  'Translation from BotWave:',
];

// ─── Weather Replies ──────────────────────────────────────────────────────────
export const weatherReplies: string[] = [
  'Weather update for {name}!',
  'Here\'s the current weather:',
  'Weather report ready!',
  'Current conditions:',
  'Weather data fetched!',
  'Your weather forecast:',
  'Weather info at {time}:',
  '{name}, here\'s the weather:',
  'Updated weather report:',
  'Live weather data:',
  'Weather check for {name}!',
  'Forecast fetched at {time}!',
  'Here\'s your weather, {name}!',
  'Weather report for {name}:',
  'Current weather conditions:',
  'Sky update ready!',
  'Your daily weather, {name}:',
  'Fresh weather data:',
  '{name}, weather incoming!',
  'Weather alert for {name}:',
  'Atmospheric update:',
  'Here\'s the latest weather:',
  'Weather fetched for {name}!',
  'Local weather at {time}:',
  'Your forecast is ready!',
  '{name}\'s weather report:',
  'Climate check ready!',
  'Today\'s weather for {name}:',
  'Weather status update:',
  'Forecast delivered!',
  'Current sky conditions:',
  'Real-time weather:',
  'Weather pulled for {name}!',
  '{name}, forecast ready!',
  'Weather snapshot at {time}:',
  'Temperature and conditions:',
  'Your weather at a glance:',
  'Forecast report, {name}!',
  'Up-to-date weather data:',
  'Weather briefing for {name}!',
  'Checking the skies for {name}:',
  'Weather intel ready!',
  'Here comes the forecast:',
  '{name}, weather data loaded:',
  'Conditions report:',
  'Current forecast:',
  'Weather service for {name}!',
  'Atmosphere report ready:',
  'Your local weather:',
  'Conditions checked at {time}:',
];

// ─── Dictionary Replies ───────────────────────────────────────────────────────
export const dictReplies: string[] = [
  'Here\'s the definition, {name}!',
  'Word definition found!',
  'Dictionary lookup complete!',
  'Definition for you:',
  'Found it! Here\'s the meaning:',
  '{name}, here\'s what it means:',
  'Word looked up at {time}:',
  'Definition ready!',
  'Your word definition:',
  'Meaning found!',
  'Dictionary says:',
  'Word meaning fetched!',
  'Here\'s the definition:',
  'Looked it up for you, {name}!',
  'Definition delivered!',
  'Your vocabulary boost, {name}!',
  'Word search complete!',
  'Here\'s what the dictionary says:',
  'Definition for {name}:',
  'Meaning lookup done!',
  'Word explained:',
  'Got the definition, {name}!',
  'Linguistic breakdown:',
  'Here\'s the meaning for {name}:',
  'Word found in dictionary!',
  'Definition at {time}:',
  'Your word, defined:',
  'Dictionary result:',
  '{name}, meaning found!',
  'Vocab check for {name}:',
  'Definition incoming!',
  'Here\'s what it means, {name}:',
  'Word meaning for you:',
  'Look-up complete!',
  '{name}\'s word definition:',
  'Dictionary entry found!',
  'Meaning delivered at {time}!',
  'Word decoded for {name}!',
  'Definition fetched!',
  'Your dictionary result:',
  'Meaning found, {name}!',
  'Word definition at {time}:',
  'Definition report:',
  'Vocabulary update for {name}!',
  'Got the meaning!',
  'Word analyzed for {name}!',
  'Dictionary response:',
  '{name}, definition ready!',
  'Meaning revealed:',
  'Definition served!',
];

// ─── AI Response Intros ───────────────────────────────────────────────────────
export const aiIntros: string[] = [
  'Here\'s what I think, {name}:',
  'Great question! Here\'s my take:',
  '{name}, here you go:',
  'Let me help with that:',
  'Here\'s my response, {name}:',
  'Good one! Here\'s what I got:',
  '{name}, I\'ve got an answer:',
  'Here\'s what I came up with:',
  'Let me think... Here:',
  'AI response for {name}:',
  'Thinking done! Here you go:',
  'Here\'s my answer:',
  '{name}, check this out:',
  'Got it! Here\'s my take:',
  'Response ready, {name}:',
  'Let me answer that:',
  'Here\'s what AI says:',
  '{name}, here\'s my best answer:',
  'Answer incoming!',
  'Here\'s my take on it:',
  'Thought about it. Here:',
  'My response for {name}:',
  '{name}, let me explain:',
  'AI-powered answer:',
  'Quick answer for {name}:',
  'Here\'s what I found:',
  '{name}, here\'s the scoop:',
  'Processing done! Answer:',
  'Interesting question! Here:',
  '{name}, this is what I think:',
  'AI says:',
  'Here you go, {name}!',
  'My answer, {name}:',
  'Let me break it down:',
  'Great question, {name}!',
  'AI answer ready:',
  'Here\'s the answer:',
  '{name}, from my analysis:',
  'Processed your question:',
  'My thought on this:',
  'Answer for you, {name}:',
  'Computed response:',
  '{name}, here it is:',
  'Answering now:',
  'Analysis complete, {name}:',
  'Here\'s my insight:',
  'For {name}:',
  'Done thinking! Here:',
  'Response generated:',
  'My best answer, {name}:',
];

// ─── Game Replies ─────────────────────────────────────────────────────────────
export const gameStartReplies: string[] = [
  'Game on, {name}!',
  'Let\'s play, {name}!',
  'Game started! Good luck!',
  'Ready to play, {name}?',
  '{name}, the game begins!',
  'Starting the game!',
  'Game time, {name}!',
  'Challenge accepted!',
  'Let the game begin!',
  '{name}, are you ready?',
  'Game loaded for {name}!',
  'Your game starts now!',
  'Initiating game mode!',
  '{name}, game is on!',
  'Play time!',
  'The game is afoot, {name}!',
  'Starting up the fun!',
  'Game launch for {name}!',
  'Ready, set, play!',
  '{name} enters the arena!',
  'Game mode activated!',
  'Let\'s get competitive!',
  'Fun time, {name}!',
  'Your challenge awaits!',
  'Game initialized!',
  '{name} joins the game!',
  'Round 1, begin!',
  'The challenge starts now!',
  'Time to play, {name}!',
  'Starting game at {time}!',
  'Your game, {name}!',
  'Get ready to play!',
  'Game session started!',
  '{name}, show me what you got!',
  'Level 1: Start!',
  'Game is live, {name}!',
  'May the best player win!',
  'Your turn, {name}!',
  'Game loaded and ready!',
  'Time for some fun!',
  '{name}, challenge mode: ON',
  'Player {name} has entered!',
  'Let\'s do this, {name}!',
  'Game clock starts now!',
  'Ready player {name}!',
  'Competition begins!',
  'Firing up the game!',
  '{name}\'s game is live!',
  'Game awaits, {name}!',
  'Press start! Oh wait, you already did',
];

// ─── Poll Created Replies ─────────────────────────────────────────────────────
export const pollReplies: string[] = [
  'Poll created, {name}!',
  'Your poll is live!',
  'Vote now! Poll ready',
  'Poll started by {name}!',
  'New poll alert!',
  'Poll is up and running!',
  '{name} started a poll!',
  'Cast your votes!',
  'Poll time!',
  '{name}\'s poll is live!',
  'Poll created at {time}!',
  'Voting starts now!',
  'New poll for the group!',
  'Poll launched, {name}!',
  'Let the voting begin!',
  'Poll ready! Cast your vote',
  'Here\'s your poll, {name}!',
  'Group poll created!',
  'Time to vote, everyone!',
  'Poll is active!',
  'Voting time!',
  '{name} wants your opinion!',
  'Poll opened by {name}!',
  'Quick poll ready!',
  'Vote with !vote [number]!',
  '{name}\'s poll:',
  'New voting session!',
  'Poll deployed!',
  'Your poll awaits votes!',
  'Democracy in action!',
  'Everyone, vote now!',
  'Poll from {name}!',
  'Cast your vote below!',
  'Here comes a poll!',
  'Poll created successfully!',
  '{name} set up a poll!',
  'Time to make your choice!',
  'Vote using !vote [n]',
  'Opinions wanted!',
  'Poll session active!',
  'Group vote time!',
  '{name} is polling!',
  'Share your opinion!',
  'Let\'s decide together!',
  'Your vote matters!',
  'Poll initialized!',
  '{name} asks:',
  'Decision time!',
  'Voting has begun!',
  'Poll engine: Active!',
];

// ─── Leaderboard Replies ──────────────────────────────────────────────────────
export const leaderboardReplies: string[] = [
  'Here\'s the leaderboard, {name}!',
  'Top players!',
  'Leaderboard updated at {time}!',
  'The rankings, {name}!',
  'Hall of fame!',
  'Who\'s on top? Let\'s see!',
  'Leaderboard for {name}!',
  'Current standings:',
  'Player rankings!',
  'Score check time!',
  'Here are the top scorers!',
  'Leaderboard report!',
  '{name}, check the rankings!',
  'The best of the best!',
  'Score leaders:',
  'Updated rankings:',
  'Who\'s winning? Let\'s find out!',
  'Leaderboard snapshot at {time}!',
  '{name}, here are the standings:',
  'Top performers!',
  'Current leaders:',
  'Score update!',
  'Leaderboard loaded!',
  'The competition heats up!',
  'Rankings for {name}:',
  '{name}, see who\'s leading!',
  'Leaderboard live!',
  'Top scores right now:',
  'Who reigns supreme?',
  'Leaderboard fetched!',
  'Current top players:',
  '{name}, the rankings are in!',
  'Score roundup!',
  'Leader standings at {time}:',
  'Top dogs:',
  'Ranking report ready!',
  'Leaderboard check!',
  'The cream of the crop:',
  'Standings as of {time}:',
  'Score leaders, {name}!',
  'Who\'s the champ?',
  'Leaderboard data:',
  '{name}, here\'s who\'s winning:',
  'The current elite:',
  'Score rankings loaded!',
  'Performance leaders:',
  'Leaderboard at a glance:',
  'Top ranks for {name}!',
  'Best players right now:',
  'And the leaders are...',
];

// ─── Download Replies ─────────────────────────────────────────────────────────
export const downloadReplies: string[] = [
  'Download ready, {name}!',
  'Here\'s your download!',
  'Media downloaded!',
  'File is ready, {name}!',
  'Download complete!',
  '{name}, your file!',
  'Downloaded at {time}!',
  'Your media, {name}!',
  'Here\'s the file!',
  'Download delivered!',
  'Media fetched for {name}!',
  'Your download is here!',
  'File downloaded successfully!',
  '{name}, download done!',
  'Media ready!',
  'Got your download!',
  'Here you go, {name}!',
  'Download complete at {time}!',
  'Your requested media:',
  'File fetched!',
  'Download for {name}!',
  'Media download successful!',
  'File ready, {name}!',
  '{name}\'s download:',
  'Downloaded and delivered!',
  'Your media file is here!',
  'Download processed!',
  'File downloaded at {time}!',
  '{name}, file incoming!',
  'Download served!',
  'Media is ready, {name}!',
  'Quick download for {name}!',
  'Got the file!',
  'Here\'s what you requested:',
  'Downloaded for {name}!',
  'File download done!',
  'Media delivered!',
  '{name}, here\'s your media!',
  'Download success!',
  'Your file has arrived!',
  'Download fetched!',
  'Media grabbed for {name}!',
  '{name}, download complete!',
  'File served at {time}!',
  'Media extracted!',
  'Your download, served!',
  'File is downloaded, {name}!',
  'Download report: Success!',
  '{name}, media ready!',
  'Download finalized!',
];

// ─── Welcome Bot Replies ──────────────────────────────────────────────────────
export const welcomeReplies: string[] = [
  'Welcome to the group, {name}!',
  'Hey {name}, welcome aboard!',
  '{name} just joined! Welcome!',
  'Welcome {name}! Glad to have you here',
  'Hey there {name}, welcome to {group}!',
  '{name} has arrived! Welcome!',
  'Welcome welcome, {name}!',
  'A wild {name} has appeared! Welcome!',
  'Glad you could join us, {name}!',
  'Welcome to {group}, {name}!',
  '{name} is here! Let\'s go!',
  'Hey {name}! Make yourself at home',
  'Welcome aboard, {name}!',
  '{name} just dropped in! Hi!',
  'The crew grows! Welcome {name}',
  'Yo {name}, welcome to the squad!',
  'Welcome, {name}! Enjoy your stay',
  '{name} has entered the chat!',
  'Hey {name}! Great to see you here',
  'Welcome {name}, we\'ve been expecting you',
  'New member alert: {name} is here!',
  '{name} just joined {group}!',
  'Hi {name}, welcome to the fam!',
  'Everyone say hi to {name}!',
  'Welcome to the party, {name}!',
  '{name} joined! Welcome to {group}',
  'Look who\'s here! Welcome {name}',
  'Hello {name}, enjoy the group!',
  'Big welcome to {name}!',
  '{name}, glad you\'re here!',
  'Welcome {name}! Have a great time',
  'Another awesome person joined! Hey {name}',
  'Hey hey {name}, welcome!',
  '{name} is in the building!',
  'Welcome! We\'re happy to have you, {name}',
  '{name} has joined the group chat',
  'New member: {name}! Welcome!',
  'Roll out the red carpet for {name}!',
  'Good to have you, {name}!',
  '{name} just arrived at {group}!',
  'Welcome, {name}! Jump right in',
  'Hi there {name}! Welcome to the crew',
  '{name} joined at {time}! Welcome!',
  'Welcome to the gang, {name}!',
  'Cheers {name}, welcome aboard!',
  '{name}, welcome! Glad you made it',
  'Hola {name}! Welcome to {group}',
  'New friend alert! Welcome {name}',
  '{name} is now part of the group!',
  'Welcome {name}, feel at home!',
  'Hey {name}! You picked a great group',
  'Sup {name}, welcome!',
  '{name} just showed up! Welcome!',
  'The more the merrier! Welcome {name}',
  'Welcome to this awesome group, {name}!',
  '{name} has entered {group}!',
  'Welcome, {name}! Use !help for bot commands',
  'Hi {name}! Type !help to see what I can do',
  '{name} is here! Say hi everyone',
  'Welcome {name}! Enjoy the vibes',
  'New addition: {name}! Welcome!',
  'Greetings {name}, welcome to {group}!',
  '{name}, you\'re officially in! Welcome',
  'Warm welcome to {name}!',
  'Welcome to the chat, {name}!',
  'Hey {name}, you\'re gonna love it here!',
  '{name} just joined the family!',
  'Welcome {name}! Ask me anything with !ai',
  'Guess who joined? {name}! Welcome!',
  'Welcome welcome welcome, {name}!',
  'Fresh face alert! {name} is here',
  'Welcome {name}! Make some noise!',
  '{name} checking in! Welcome to {group}',
  'Group just got better! Welcome {name}',
  'Ahoy {name}! Welcome aboard!',
];

// ─── Goodbye Replies ──────────────────────────────────────────────────────────
export const goodbyeReplies: string[] = [
  '{name} has left the group. Goodbye!',
  'See you later, {name}!',
  '{name} just left {group}. Take care!',
  'Bye bye {name}! You\'ll be missed',
  '{name} has departed. Farewell!',
  'Until next time, {name}!',
  '{name} left the chat. Catch you later!',
  'Sad to see you go, {name}!',
  '{name} has left {group}. Peace out!',
  '{name} is gone. Goodbye friend!',
  'We\'ll miss you, {name}!',
  '{name} waved goodbye. See ya!',
  'Farewell {name}, come back anytime!',
  '{name} has exited. Take care out there!',
  'Goodbye {name}! Hope to see you again',
  '{name} just left. Until we meet again!',
  'So long, {name}! Best wishes',
  '{name} bounced. Bye!',
  'Catch you on the flip side, {name}!',
  '{name} has left the building!',
];

// ─── Anti-Spam Warnings ───────────────────────────────────────────────────────
export const spamWarnings: string[] = [
  'Slow down, {name}! Too many messages',
  '{name}, you\'re sending too fast',
  'Easy there {name}, take it easy',
  'Spam detected from {name}',
  '{name}, please slow down',
  'Whoa {name}, chill with the messages',
  '{name}, you\'re flooding the chat',
  'Cool it {name}, too many msgs',
  '{name}, spam is not cool',
  'Hey {name}, one at a time please',
  'Message limit reached, {name}',
  '{name}, you\'re going too fast',
  'Slow down there, {name}!',
  '{name} chill, too many messages',
  'Rate limited, {name}. Wait a bit',
  '{name}, take a breather',
  'Too fast {name}, slow down!',
  'Easy {name}, you\'re flooding!',
  '{name}, pace yourself please',
  'Hold up {name}, too many msgs',
  'Spam alert from {name}!',
  '{name}, please wait between messages',
  'Relax {name}, one at a time',
  '{name}, the chat isn\'t going anywhere',
  'Slow your roll, {name}!',
  '{name}, take it easy on the messages',
  'You\'re on cooldown, {name}',
  '{name}, message limit exceeded',
  'Deep breaths {name}, slow down',
  'Hold on {name}, too fast!',
  '{name}, give others a chance to read',
  'Flood protection activated for {name}',
  'Hey {name}, not so fast!',
  '{name}, the bot needs a second',
  'Timeout for {name} — too many messages',
  '{name}, wait a moment please',
  'Pump the brakes, {name}!',
  'Chat police here! Slow down {name}',
  '{name}, message cooldown active',
  'Chill mode activated for {name}',
  '{name}, too many messages in a row',
  'Easy does it, {name}!',
  'Hey {name}, one message at a time',
  '{name}, give it a rest for a sec',
  'Spam shield activated! {name}, wait',
  '{name}, you\'re typing faster than me!',
  'Cool your jets, {name}!',
  '{name}, take a quick break',
  'Message overflow from {name}!',
  'Slow and steady, {name}!',
];

// ─── Auto-Reply Responses ─────────────────────────────────────────────────────
export const autoReplyDefaults: string[] = [
  'Thanks for your message, {name}! I\'ll get back to you soon',
  'Hey {name}, got your message! Will respond shortly',
  'Message received, {name}!',
  '{name}, thanks for reaching out!',
  'Got it, {name}! I\'ll reply when I can',
  'Thanks {name}, message noted!',
  'Hey {name}! I\'ll get to this soon',
  'Received your message, {name}!',
  '{name}, thanks! I\'m on it',
  'Noted, {name}! Response coming soon',
  'Hi {name}, I see your message!',
  'Thanks for writing, {name}!',
  '{name}, message logged!',
  'Hey there {name}, will reply soon!',
  'Got your msg, {name}!',
  '{name}, I\'ll respond shortly!',
  'Message from {name} received!',
  'Thanks {name}! Give me a moment',
  'Hi {name}, on it!',
  '{name}, appreciate the message!',
  'Received! Thanks {name}',
  'Hey {name}, working on a reply!',
  '{name}, hang tight!',
  'Message noted from {name}!',
  'Thanks {name}, won\'t be long!',
  'Got this, {name}! Replying soon',
  'Hey {name}, I\'m on it!',
  '{name}, sit tight!',
  'Received and noted, {name}!',
  'Hi {name}, I\'ll be with you shortly',
  'Thanks for the message, {name}!',
  '{name}, I see you! Replying soon',
  'On it, {name}!',
  'Hey {name}, message received loud and clear',
  'Gotcha, {name}!',
  '{name}, response incoming!',
  'Will reply soon, {name}!',
  'Hey {name}, give me a sec!',
  '{name}, your message is in my queue!',
  'Received at {time}, {name}!',
  'Message from {name} at {time} — noted!',
  'Thanks {name}, will respond at my earliest!',
  'Got the message, {name}! Be right back',
  '{name}, acknowledged!',
  'Hey {name}, be right with you!',
  'Thanks {name}, processing your message!',
  'I see you {name}, replying soon!',
  '{name}, one moment please!',
  'Received your text, {name}!',
  'Thanks {name}, stay tuned for my reply!',
];
