/**
 * BotWave Response Variation Pools
 *
 * Every command has 50-100 response variations to avoid identical
 * message fingerprints. Dynamic variables {name}, {time}, {date}
 * are injected at send time.
 */

// ─── Sticker Replies ──────────────────────────────────────────────────────────
export const stickerReplies: string[] = [
  "Here's your sticker!",
  'Sticker created!',
  'Done! Your sticker is ready',
  'Sticker delivered, {name}!',
  'Here you go, {name}!',
  'Fresh sticker for you!',
  'Got your sticker right here!',
  'Sticker incoming!',
  'Your sticker is ready!',
  'Made at {time} just for you!',
  'Sticker done, {name}!',
  'One sticker, coming up!',
  'Enjoy your sticker!',
  'Your custom sticker!',
  'Sticker created for {name}',
  'Check out your sticker!',
  'Brand new sticker!',
  'Here it is, {name}!',
  'Done! Sticker sent',
  'Your sticker, served fresh!',
  'Sticker made at {time}',
  'Ready! Your sticker',
  'Sticker is done!',
  'Sent your sticker, {name}!',
  'Sticker complete!',
  'A sticker for {name}!',
  'Got it! Sticker ready',
  'Sticker crafted!',
  'Your sticker has landed!',
  'Here, {name}! Your sticker',
  'Sticker processed!',
  'Done! Here ya go',
  'Your image is now a sticker!',
  'Converted to sticker!',
  'Sticker for you, {name}!',
  'Quick sticker for you!',
  'All done! Sticker ready',
  'Your sticker awaits!',
  'Hot off the press!',
  'Your sticker, as requested!',
  '{name}, your sticker!',
  'New sticker alert!',
  'Sticker mode activated!',
  'One sticker done!',
  'Image converted!',
  'Your sticker is served!',
  'Boom! Sticker ready',
  'Sticker magic done!',
  'Freshly made sticker!',
  'Sticker sent, {name}!',
  'There you go, {name}!',
  'Sticker delivered at {time}!',
  'Look what I made, {name}!',
  'Another sticker for the collection!',
  'Sticker factory says: Done!',
  'Got your sticker ready!',
  'Fresh out of the sticker oven!',
  'Sticker game strong, {name}!',
  '{name}, sticker is locked and loaded!',
  'And boom, sticker!',
  'Your sticker just dropped!',
  'Created on {date} at {time}',
  'Sticker secured!',
  'Made this one just for you, {name}!',
  'Express sticker delivery!',
  'Sticker report: Ready!',
  'Custom sticker for {name} at {time}!',
  'Freshly baked sticker!',
  '{name} sticker is here!',
  'Here comes your sticker!',
  'Sticker loaded and sent!',
  'Your daily sticker, {name}!',
  'Sticker dispatch complete!',
  'Quick delivery for {name}!',
  'Serving up a fresh sticker!',
  'Your sticker request: Fulfilled!',
  'Sticker crafted at {time} for {name}!',
  'Done and dusted, sticker sent!',
  'Art delivered!',
  'Sticker acquired!',
];

// ─── AFK Replies ──────────────────────────────────────────────────────────────
export const afkReplies: string[] = [
  'Hey! {name} is away right now',
  '{name} stepped out, message noted',
  "They're unavailable right now, will notify them",
  '{name} is currently away',
  '{name} is AFK at the moment',
  'Heads up: {name} is not available',
  '{name} went offline for a bit',
  '{name} is busy right now',
  'Message received! {name} is away',
  "{name} can't respond right now",
  '{name} is taking a break',
  '{name} stepped away for a moment',
  "{name} isn't here right now",
  'Got your message! {name} is AFK',
  '{name} is offline temporarily',
  '{name} will be back soon',
  'Noted! {name} is currently away',
  '{name} is unavailable right now',
  'Message saved! {name} is AFK',
  '{name} has gone AFK',
  'Hey, {name} is not around',
  '{name} is out right now',
  "I'll let {name} know!",
  '{name} went AFK a while ago',
  '{name} is doing something else',
  "Don't worry, {name} will see this later",
  '{name} stepped out at {time}',
  '{name} is away since a while',
  'Away notice: {name} is not here',
  '{name} set their status to away',
  'Ping! {name} is offline',
  '{name} has been away for a bit',
  '{name} is currently occupied',
  'Message logged! {name} is AFK',
  'Hey there! {name} is away',
  '{name} is on a break right now',
  '{name} will reply when back',
  'Auto-reply: {name} is away',
  '{name} is not available currently',
  "I'll pass your message to {name}",
  '{name} will get back to you',
  "Heads up, {name} isn't online",
  '{name} left at {time}',
  '{name} is temporarily away',
  '{name} will respond later',
  'Quick note: {name} is AFK',
  '{name} went offline',
  'Away: {name} is not here',
  'Hold tight! {name} is away',
  '{name} is currently AFK',
  '{name} has stepped away. Will notify them!',
  '{name} is not available. Try again later!',
  'Looks like {name} is away at the moment',
  '{name} went AFK. Message stored!',
  'Just a heads up, {name} is away right now',
  'Message received for {name}. They are AFK!',
  '{name} can\'t come to the phone right now',
  'Away alert: {name} is not here at {time}',
  '{name} is offline. Your message was saved',
  '{name} is taking time off. Noted your message!',
  'FYI: {name} is currently not available',
  '{name} is away. I\'ll make sure they see this!',
  '{name} went away at {time}. Message recorded.',
  'Quick update: {name} is AFK right now',
  '{name} is on a break. Will pass your message!',
  'Hey! {name} went AFK. Try later!',
  '{name} is away. Your message is queued!',
  '{name} has gone quiet for now',
  'Notification sent to {name}! They\'re away',
  '{name} is off the grid right now',
];

// ─── Joke Pool ────────────────────────────────────────────────────────────────
export const jokePool: string[] = [
  'Why do programmers prefer dark mode? Because light attracts bugs!',
  "Why was the JavaScript developer sad? Because he didn't Node how to Express himself!",
  "How many programmers does it take to change a light bulb? None, that's a hardware problem!",
  "Why do Java developers wear glasses? Because they can't C#!",
  'A SQL query walks into a bar, walks up to two tables and asks... "Can I join you?"',
  'Why did the developer go broke? Because he used up all his cache!',
  "What's a programmer's favorite hangout place? Foo Bar!",
  'Why do programmers hate nature? It has too many bugs!',
  '!false — it\'s funny because it\'s true',
  'There are 10 types of people: those who understand binary and those who don\'t',
  'A programmer was found dead in the shower. The instructions on the shampoo read: Lather, Rinse, Repeat.',
  "What's a computer's least favorite food? Spam!",
  'Why did the functions stop calling each other? They got into an argument!',
  "I'd tell you a UDP joke, but you might not get it.",
  'I told my computer I needed a break, and now it won\'t stop sending me Kit-Kat ads.',
  "What's the object-oriented way to become rich? Inheritance!",
  'Why do Python programmers have low self-esteem? They\'re constantly comparing themselves to others.',
  'What do you call 8 hobbits? A hobbyte.',
  "An SEO expert walks into a bar, pub, inn, tavern, public house, Irish bar...",
  'How do you comfort a JavaScript bug? You console it!',
  "What's a programmer's favorite tea? Chai-nese tea.",
  'Why was the computer cold? It left its Windows open!',
  'What do computers snack on? Microchips!',
  'Why did the computer go to the doctor? It had a virus!',
  'What did the spider do on the internet? Built a website!',
  "How does a computer get drunk? It takes screenshots!",
  "What do you call a computer that sings? A-Dell!",
  "Why couldn't the computer take its hat off? Because it had its CAPS LOCK on!",
  "What do you call a group of unorganized cats? A cat-alogue!",
  "Why did the PowerPoint cross the road? To get to the other slide!",
  "What's the best way to carve wood? Whittle by whittle.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I asked my dog what's two minus two. He said nothing.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I used to hate facial hair, but then it grew on me.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why do bees hum? Because they don't know the words!",
  "What do you call a fake noodle? An impasta!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I couldn't figure out how to put my seatbelt on. Then it clicked!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Did you hear about the claustrophobic astronaut? He needed more space.",
  "Why don't eggs tell jokes? They'd crack each other up!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a sleeping dinosaur? A dino-snore!",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the scarecrow win an award? He was outstanding in his field!",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I'm friends with 25 letters of the alphabet. I don't know Y.",
  "What do you call a belt made of watches? A waist of time!",
  "Why do cows have hooves instead of feet? Because they lactose!",
  "How does Moses make tea? Hebrews it!",
  "Why can't your nose be 12 inches long? Because then it would be a foot!",
  "What do you call a fish without eyes? A fsh!",
  "Why don't oysters donate? Because they are shellfish!",
  "I just flew in from New York. Boy, are my arms tired!",
  "What's orange and sounds like a parrot? A carrot!",
  "Why did the bicycle fall over? It was two-tired!",
  "I told my friend she drew her eyebrows too high. She seemed surprised.",
  "What do you call a dog that does magic tricks? A Labracadabrador!",
  "Why don't calendars ever get stressed? Because they know their days are numbered!",
  "I have a joke about construction, but I'm still working on it.",
  "What do you call a boomerang that doesn't come back? A stick!",
  "Why did the mushroom go to the party? Because he was a fun-guy!",
  "What's the best thing about Switzerland? The flag is a big plus!",
  "I told a chemistry joke. There was no reaction.",
  "How do trees access the internet? They log in!",
  "Why did the programmer quit his job? Because he didn't get arrays!",
  "How do you know a programmer is extroverted? They stare at YOUR shoes.",
  "What's the difference between a bug and a feature? A deadline.",
  "A QA engineer walks into a bar. Orders 1 beer. Orders 0 beers. Orders 99999 beers. Orders -1 beers. Orders a lizard.",
  "What do you call a programmer from Finland? Nerdic.",
  "Why did the database administrator leave his wife? She had one-to-many relationships.",
  "What's the most used language in programming? Profanity.",
  "What did the router say to the doctor? It hurts when IP.",
  "Why did the Python developer need glasses? Because he couldn't C.",
  "I'd make a DNS joke but it would take too long to resolve.",
  "A TCP packet walks into a bar and says 'I want a beer.' Bartender says 'You want a beer?' TCP packet says 'Yes, I want a beer.'",
  "What did the CSS say to the HTML? You have no style.",
  "Knock knock. Race condition. Who's there?",
  "There's no place like 127.0.0.1",
  "To understand recursion, you must first understand recursion.",
  "A byte walks into a bar looking haggard. Bartender: 'What's wrong?' Byte: 'I've been feeling a bit off lately.'",
  "What's a pirate's favorite programming language? R!",
  "What happens when a programmer goes fishing? He catches exceptions.",
  "Why did the function break up with the variable? It found a better argument.",
  "I would tell you a joke about git, but I'm afraid you wouldn't commit.",
  "What does a network engineer say when they stub their toe? IT hertz!",
  "What did the boolean say to the other boolean? You're true to me.",
  "Why did the commit cry? It got rejected after a push.",
  "Why do programmers always mix up Christmas and Halloween? Because OCT 31 = DEC 25.",
  "Debugging is like being the detective in a crime movie where you're also the murderer.",
  "Why did the cloud break up with the server? It needed more space.",
  "Why do backend developers make bad comedians? Their delivery is terrible.",
  "What's a programmer's favorite key? The Enter key — it always returns.",
  "What do you call a group of programmers? A merge conflict.",
  "Why is JavaScript like a box of chocolates? You never know what type you're gonna get.",
  "An infinite loop walks into a bar. And walks into a bar. And walks into a bar...",
  "Why did the React component feel lonely? It had no state.",
  "What's a hacker's favorite season? Phishing season.",
  "A web developer left a restaurant. He didn't leave a TIP.",
  "What did the server say when it crashed? I need a REST.",
  "Why did the CSS developer go to the gym? To work on their flex.",
  "A programmer's wife tells him 'Go get bread. If they have eggs, get a dozen.' He returns with 12 loaves.",
  "Why was the function so popular? It had great closure.",
  "Why did the junior dev cross the road? To push to production on Friday.",
  "What did the compiler say to the programmer? You missed a semicolon. Again.",
  "What did the backend say to the frontend? Stop being so superficial!",
  "A programmer had a problem, so they used threads. Now they had two problems.",
  "What did one ocean say to the other? Nothing, they just waved.",
  "I tried to catch fog yesterday. I mist.",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I'm afraid of elevators, so I take steps to avoid them.",
  "Did you hear about the kidnapping at school? It's fine, he woke up.",
  "I used to be addicted to soap, but I'm clean now.",
  "What did one wall say to the other wall? I'll meet you at the corner!",
  "What do you call a deer with no eyes? No idea!",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "What do you call a bear in the rain? A drizzly bear!",
  "What did the grape do when it was stepped on? It let out a little wine.",
  "How do you organize a space party? You planet.",
  "What did the fish say when it hit the wall? Dam!",
  "Why did the stadium get hot after the game? All the fans left.",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "What kind of shoes do ninjas wear? Sneakers!",
  "I tried to write with a broken pencil. It was pointless.",
  "What do you call a dinosaur that crashes their car? Tyrannosaurus wrecks!",
  "What did the buffalo say when his kid went to college? Bison!",
  "I'm reading a horror story in Braille. Something bad is about to happen, I can feel it.",
  "What do you call a factory that makes okay products? A satisfactory!",
  "Why did the coffee file a police report? It got mugged!",
  "Did you hear about the restaurant on the Moon? Great food, no atmosphere.",
  "What do lawyers wear to court? Lawsuits!",
  "I asked the librarian if she had books on paranoia. She whispered, 'They're right behind you!'",
  "What do you call a pig that does karate? A pork chop!",
  "Why do we tell actors to break a leg? Because every play has a cast!",
  "What do you call a cow with no legs? Ground beef!",
  "I used to hate math, but then I realized decimals have a point.",
  "What's brown and sticky? A stick!",
  "How do you make a tissue dance? Put a little boogie in it!",
  "What did one hat say to the other? Stay here, I'm going on ahead!",
  "Why did the cookie go to the nurse? Because it felt crummy!",
  "What do you get from a pampered cow? Spoiled milk!",
  "What did the traffic light say to the car? Don't look, I'm about to change!",
  "What do you call an alligator in a vest? An investigator!",
  "I was wondering why the frisbee kept getting bigger. Then it hit me.",
  "What did the big flower say to the little flower? Hi, bud!",
  "What do you call a snowman with a six-pack? An abdominal snowman!",
  "Why can't you give Elsa a balloon? Because she'll let it go!",
  "What did one plate say to the other? Dinner's on me!",
  "What do you call a bee that can't make up its mind? A maybe!",
  "What did the full glass say to the empty glass? You look drunk.",
  "What do you call two birds in love? Tweethearts!",
  "Why was the broom late? It over-swept!",
  "What's the best time to go to the dentist? Tooth-hurty!",
  "What did the stamp say to the envelope? Stick with me and we'll go places!",
  "What do you call an elephant that doesn't matter? Irrelephant!",
  "I stayed up all night wondering where the sun went. Then it dawned on me.",
  "How do you make an octopus laugh? With ten-tickles!",
  "What do you call a duck that gets all A's? A wise quacker!",
  "Why couldn't the pony sing a lullaby? She was a little horse!",
  "What kind of music do mummies listen to? Wrap music!",
  "What do you call a train carrying bubblegum? A chew-chew train!",
  "Why did the banana go to the doctor? Because it wasn't peeling well!",
  "Why are ghosts bad liars? You can see right through them!",
  "What did the nose say to the finger? Stop picking on me!",
  "Why can't a leopard hide? Because he's always spotted!",
  "What do you call a pile of cats? A meow-ntain!",
  "What do you call an angry carrot? A steamed veggie!",
  "Why did the melon jump into the lake? It wanted to be a watermelon!",
  "How do you make a lemon drop? Just let it fall!",
  "What did the mama cow say to the baby cow? It's pasture bedtime!",
  "What kind of tree fits in your hand? A palm tree!",
  "What do you call a group of musical whales? An orca-stra!",
  "Why did the gym close down? It just didn't work out!",
  "What do you call someone who tells dad jokes but isn't a dad? A faux pa!",
  "I have a fear of speed bumps, but I'm slowly getting over it.",
  "What did one toilet say to the other? You look flushed!",
  "Why are elevator jokes so classic? They work on many levels.",
  "Why is Peter Pan always flying? Because he Neverlands!",
  "What did the calculator say to the math student? You can count on me.",
  "What kind of car does a sheep drive? A Lamborghini!",
  "Why did the chicken join a band? Because it had the drumsticks!",
  "What do you call a sad strawberry? A blueberry!",
  "How do celebrities stay cool? They have lots of fans!",
  "Where do fruits go on vacation? Pear-adise!",
  "Why do bees have sticky hair? Because they use honeycombs!",
  "What happened to the dog that swallowed a firefly? It barked with de-light!",
  "What goes up and down but doesn't move? Stairs!",
  "What do you call a sleeping bull? A bulldozer!",
  "I used to be a banker, but I lost interest.",
  "Why did the Oreo go to the dentist? Because it lost its filling!",
  "Why don't melons get married? Because they cantaloupe!",
  "What kind of bagel can fly? A plain bagel!",
  "Why did the teddy bear say no to dessert? She was already stuffed!",
  "If you ever get cold, stand in the corner — they're usually 90 degrees.",
  "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
  "I tried to start a professional hide-and-seek team, but good players are hard to find.",
  "Why did the can crusher quit? It was soda pressing.",
  "I made a pencil with two erasers. It was pointless.",
  "Why do we never tell secrets on a farm? Potatoes have eyes and corn has ears!",
  "The rotation of Earth really makes my day.",
  "6:30 is the best time on a clock, hands down.",
  "I got a reversible jacket for Christmas. Can't wait to see how it turns out.",
  "Did you hear the rumor about butter? I'm not going to spread it!",
  "I was going to tell a pizza joke, but it was too cheesy.",
  "The past, present, and future walked into a bar. It was tense.",
  "I'm going to stand outside. If anyone asks, I'm outstanding.",
  "Where do math teachers go on vacation? Times Square!",
  "What did the clock do when it was hungry? It went back four seconds.",
  "What do elves learn in school? The elf-abet!",
  "Why did the chicken cross the playground? To get to the other slide!",
  "What do you call a shoe made out of a banana? A slipper!",
  "RIP boiling water. You will be mist.",
  "What does a lemon say when it answers the phone? Yellow!",
  "What did the zero say to the eight? Nice belt!",
  "Why did the yogurt go to the art exhibition? Because it was cultured!",
  "Two guys walked into a bar. The third one ducked.",
  "What did the pirate say when he turned 80? Aye matey!",
  "Why did the man get fired from the OJ factory? Lack of concentration.",
  "What did the shark say when he ate the clownfish? This tastes a little funny.",
  "I couldn't remember how to throw a boomerang, but eventually it came back to me.",
  "Why did the belt get arrested? For holding up a pair of pants!",
  "What happens when frogs park illegally? They get toad.",
  "I'm afraid for the calendar. Its days are numbered.",
  "I told my suitcases there will be no vacation this year. Now I'm dealing with emotional baggage.",
  "My boss told me to have a good day, so I went home.",
  "What did one snowman say to the other? Do you smell carrots?",
  "Why did the turkey cross the road? To prove he wasn't chicken.",
  "I ate a clock yesterday. It was very time-consuming.",
  "Why do ducks have tail feathers? To cover their butt quacks!",
  "Where do sheep go on vacation? The Baa-hamas!",
  "Why do French people eat snails? They don't like fast food.",
  "I bought shoes from a drug dealer. I've been tripping all day.",
  "What do dentists call their x-rays? Tooth pics!",
  "What kind of music do planets like? Neptunes!",
  "Mountains aren't just funny. They're hill areas.",
  "Why don't ants ever get sick? They have little anty-bodies!",
  "I just got kicked out of a secret cooking society. I spilled the beans.",
  "Why did the bee get married? Because he found his honey!",
  "What did one pencil say to the other? You're looking sharp!",
  "I went to a seafood disco last week. I pulled a mussel.",
  "Why don't koalas count as bears? They don't meet the koalifications.",
  "What's a pirate's favorite letter? You'd think R, but it's the C!",
  "What do you call a bear with no ears? B.",
  "Why can't you hear a pterodactyl in the bathroom? It has a silent P.",
  "How do you make holy water? You boil the hell out of it.",
  "If athletes get athlete's foot, what do astronauts get? Missile toe.",
  "I tried to write a chemistry joke, but all the good ones argon.",
  "Why are skeletons so calm? Nothing gets under their skin.",
  "People who use selfie sticks really need to take a long, hard look at themselves.",
  "What do sprinters eat before a race? Nothing, they fast.",
  "I know a lot of jokes about retired people, but none of them work.",
  "Where do hamburgers go to dance? The meatball!",
  "What do you call a magician who lost their magic? Ian.",
  "Why don't scientists trust stairs? They're always up to something.",
  "I told my doctor I broke my arm in two places. He told me to stop going there.",
  "What do you call a can opener that doesn't work? A can't opener!",
  "Why did the math book look so sad? It had too many problems.",
  "My dad told me a joke about boxing. I missed the punchline.",
  "Why did the invisible man turn down the job? He couldn't see himself doing it.",
  "What do you call a fibbing cat? A lion.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What do you call fake spaghetti? An impasta!",
  "I thought about an all-almond diet, but that's just nuts.",
  "Where do you learn to make ice cream? Sundae school.",
  "What do you call a cow during an earthquake? A milkshake!",
  "I used to be a personal trainer, but I gave them my too-weak notice.",
  "I asked my French friend if she likes video games. She said Wii.",
  "I bought the world's worst thesaurus. Not only is it terrible, it's terrible.",
  "How do moths swim? Using the butterfly stroke.",
  "If a child refuses to nap, are they guilty of resisting a rest?",
  "Why are spiders great web developers? They know all about the web!",
  "I tried to sue the airline for losing my luggage. I lost my case.",
  "What do you call a man lying on your doorstep? Matt.",
  "What did the mountain climber name his son? Cliff.",
  "I once made a belt out of watches. It was a waist of time.",
  "What do you give the dentist when they're sad? A little crown.",
  "Why did the old man fall in the well? He couldn't see that well!",
  "Want to hear a construction joke? Never mind, I'm still working on it.",
  "What do Alexander the Great and Winnie the Pooh have in common? Same middle name!",
  "I was going to tell a time-traveling joke, but you didn't like it.",
  "Why do chicken coops only have two doors? If they had four, they'd be sedans!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't oysters donate? They are shellfish!",
  "What's orange and sounds like a parrot? A carrot!",
  "What do you call a dog that does magic tricks? A Labracadabrador!",
  "What do you call a boomerang that doesn't come back? A stick!",
  "Why did the mushroom go to the party? Because he was a fun-guy!",
  "I just flew in from New York. Boy, are my arms tired!",
  "What do you call a fish without eyes? A fsh!",
  "What sits at the bottom of the sea and twitches? A nervous wreck!",
  "I just got my doctor's test results. Turns out I'm not a doctor.",
  "Why can't your hand be 12 inches long? Then it'd be a foot!",
  "I'm addicted to collecting vintage Beatles albums. I need Help.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "What's the difference between a hippo and a Zippo? One is heavy, the other is a little lighter.",
  "Why did the chicken go to the seance? To get to the other side.",
  "What do you call a cow with a twitch? Beef jerky.",
  "What do you call a penguin in the desert? Lost.",
  "Why did the rapper carry an umbrella? Fo' drizzle.",
  "Why did the computer break up with the internet? No connection.",
  "What did the volcano say to its neighbor? I lava you.",
  "Why did the tree go to the dentist? It needed a root canal.",
  "What did the science book say to the math book? You've got problems.",
  "Why don't elephants use computers? They're afraid of the mouse.",
  "Why did the scarecrow get a promotion? Outstanding in his field.",
  "What did the plumber say to the singer? Nice pipes.",
  "What did the blanket say to the bed? I've got you covered.",
  "What did the hat say to the scarf? You hang around, I'll go on ahead.",
  "How does a penguin build its house? Igloos it together.",
  "What do you call a fish wearing a bowtie? So-fish-ticated.",
  "Why did the music teacher need a ladder? To reach the high notes.",
  "What do you call a snake wearing a hard hat? A boa constructor.",
  "What did the egg say to the frying pan? You crack me up.",
  "Why did the nose feel sad? It was always getting picked on.",
  "Why did the lamp go to school? It wanted to be brighter.",
  "What did the cheese say in the mirror? Halloumi!",
  "Why did the orange stop halfway up the hill? It ran out of juice.",
  "Why did the teacher wear sunglasses? Her students were so bright.",
  "What do you call a sleeping T-Rex? A dinosnore.",
  "Why did the computer catch a cold? It left its Windows open.",
  "Why don't trees like tests? They get stumped.",
  "Why do programmers prefer dark mode? Light attracts more bugs.",
  "What do you call a computer that sings? A-Dell.",
  "What do you call a chicken staring at lettuce? Chicken sees-a salad.",
  "Why don't basketball players eat dinner? They're always dribbling.",
  "What happens when you anger a brain surgeon? They give you a piece of their mind.",
  "What do you call a snowman in July? A puddle.",
  "Why did the skeleton go to the barbecue? To get another rib.",
  "Why did the robber take a bath? He wanted a clean getaway.",
  "Why was the math book depressed? Too many problems.",
  "What do you call a monkey in a mine field? A ba-boom.",
  "Why can't the music teacher start his car? Keys are always sharp or flat.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What do you call a cow on a trampoline? A milkshake.",
  "Why did the rope go to school? To learn the knots and bolts.",
  "What did one DNA say to the other? Do these genes make me look fat?",
  "Why can't you trust atoms? They literally make up everything.",
  "Why don't eggs play sports? They'd get beaten.",
  "What do you call a bird that's afraid to fly? Chicken.",
  "Why don't robots ever get scared? Nerves of steel.",
  "Why did the astronaut break up with his girlfriend? He needed more space.",
  "Why did the barber win the race? He took a short cut.",
  "How do you fix a broken pumpkin? With a pumpkin patch.",
  "Why do seagulls fly over the ocean? If they flew over the bay, they'd be bagels.",
  "What did one eye say to the other? Between us, something smells.",
  "Why don't some fish play tennis? They're afraid of the net.",
  "What do you call a flower that runs on electricity? A power plant.",
  "What do you call a sleeping dinosaur? A stega-snore-us.",
  "Why did the tomato go out with a prune? It couldn't find a date.",
  "Why did the M&M go to school? It wanted to be a Smartie.",
  "What did the tree say to spring? What a re-leaf!",
  "What's a vampire's favorite fruit? A blood orange.",
  "How many months have 28 days? All of them.",
  "What word is spelled wrong in every dictionary? Wrong.",
  "Why did the cookie cry? Its mom was a wafer so long.",
  "What do you call a bear with no teeth? A gummy bear!",
  "Parallel lines have so much in common. Shame they'll never meet.",
  "I used to hate facial hair, but then it grew on me.",
  "I'm reading a book about anti-gravity. Impossible to put down!",
  "Why do skeletons never go trick-or-treating? No-body to go with.",
  "What do you call a line of men waiting for haircuts? A barberqueue.",
  "What did the ocean say to the shore? Nothing, it just waved.",
  "What do you call a lazy baby kangaroo? A pouch potato.",
  "Why did the photo go to jail? It was framed.",
  "Did you hear about the circus fire? It was in tents.",
  "What's a cat's favorite color? Purr-ple!",
  "What is a computer's first sign of old age? Loss of memory!",
  "I'd tell you an elevator joke, but it has its ups and downs.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "Why couldn't the bicycle stand up by itself? It was two-tired.",
  "I told my cat a joke. It said nothing — just gave me a paws.",
  "I asked my dog what 2 minus 2 is. He said nothing.",
  "Why do cows have hooves? Because they lactose!",
  "How does Moses make tea? Hebrews it!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "I'm on a seafood diet. I see food and I eat it.",
  "I'm friends with 25 letters of the alphabet. I don't know Y.",
  "Why do bees hum? They don't know the words!",
  "I couldn't figure out my seatbelt. Then it clicked!",
  "Did you hear about the claustrophobic astronaut? He needed more space.",
  "Why don't some couples go to the gym? Their relationships don't work out.",
  "Why did the coffee call the police? It got mugged.",
  "My friend says 'What rhymes with orange?' I said 'No it doesn't.'",
  "What do you call an illegally parked frog? Toad.",
  "What do you call a pig that knows karate? A pork chop!",
  "Why did the scarecrow become a motivational speaker? Outstanding in his field!",
  "What do you call a cat on the beach on Christmas Eve? Sandy Claws!",
  "Did you hear about the actor who fell through the floor? Going through a stage.",
  "What animal needs oil? A mouse because it squeaks!",
  "What do you call a person happy on Monday? Retired.",
  "What do you call a lazy spider? A spin doctor.",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
];

// ─── Quote Pool ───────────────────────────────────────────────────────────────
export const quotePool: string[] = [
  '"The only way to do great work is to love what you do." — Steve Jobs',
  '"Innovation distinguishes between a leader and a follower." — Steve Jobs',
  '"Stay hungry, stay foolish." — Steve Jobs',
  '"The future belongs to those who believe in the beauty of their dreams." — Eleanor Roosevelt',
  '"It does not matter how slowly you go as long as you do not stop." — Confucius',
  '"Life is what happens when you\'re busy making other plans." — John Lennon',
  '"In the middle of every difficulty lies opportunity." — Albert Einstein',
  '"The best time to plant a tree was 20 years ago. The second best time is now." — Chinese Proverb',
  '"Be the change you wish to see in the world." — Mahatma Gandhi',
  '"Your time is limited, don\'t waste it living someone else\'s life." — Steve Jobs',
  '"Believe you can and you\'re halfway there." — Theodore Roosevelt',
  '"The only impossible journey is the one you never begin." — Tony Robbins',
  '"Success is not final, failure is not fatal: It is the courage to continue that counts." — Winston Churchill',
  '"What you get by achieving your goals is not as important as what you become by achieving your goals." — Zig Ziglar',
  '"If you want to lift yourself up, lift up someone else." — Booker T. Washington',
  '"Strive not to be a success, but rather to be of value." — Albert Einstein',
  '"You miss 100% of the shots you don\'t take." — Wayne Gretzky',
  '"The purpose of life is not to be happy. It is to be useful." — Ralph Waldo Emerson',
  '"Do what you can, with what you have, where you are." — Theodore Roosevelt',
  '"Act as if what you do makes a difference. It does." — William James',
  '"The mind is everything. What you think you become." — Buddha',
  '"An unexamined life is not worth living." — Socrates',
  '"Everything you\'ve ever wanted is on the other side of fear." — George Addair',
  '"What lies behind us and what lies before us are tiny matters compared to what lies within us." — Ralph Waldo Emerson',
  '"Happiness is not something ready made. It comes from your own actions." — Dalai Lama',
  '"Keep your face always toward the sunshine—and shadows will fall behind you." — Walt Whitman',
  '"If you look at what you have in life, you\'ll always have more." — Oprah Winfrey',
  '"You only live once, but if you do it right, once is enough." — Mae West',
  '"The best revenge is massive success." — Frank Sinatra',
  '"Life is 10% what happens to me and 90% of how I react to it." — Charles Swindoll',
  '"Not all who wander are lost." — J.R.R. Tolkien',
  '"The greatest glory in living lies not in never falling, but in rising every time we fall." — Nelson Mandela',
  '"Life is really simple, but we insist on making it complicated." — Confucius',
  '"It is never too late to be what you might have been." — George Eliot',
  '"When one door of happiness closes, another opens." — Helen Keller',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." — Robert Frost',
  '"Dream big and dare to fail." — Norman Vaughan',
  '"Turn your wounds into wisdom." — Oprah Winfrey',
  '"Simplicity is the ultimate sophistication." — Leonardo da Vinci',
  '"What we think, we become." — Buddha',
  '"Doubt kills more dreams than failure ever will." — Suzy Kassem',
  '"The harder I work, the luckier I get." — Gary Player',
  '"Start where you are. Use what you have. Do what you can." — Arthur Ashe',
  '"The only limit to our realization of tomorrow will be our doubts of today." — Franklin D. Roosevelt',
  '"Don\'t count the days, make the days count." — Muhammad Ali',
  '"Quality is not an act, it is a habit." — Aristotle',
  '"The way to get started is to quit talking and begin doing." — Walt Disney',
  '"Everything has beauty, but not everyone sees it." — Confucius',
  '"Education is the most powerful weapon which you can use to change the world." — Nelson Mandela',
  '"Creativity is intelligence having fun." — Albert Einstein',
  '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." — Aristotle',
  '"The only person you are destined to become is the person you decide to be." — Ralph Waldo Emerson',
  '"Go confidently in the direction of your dreams." — Henry David Thoreau',
  '"Well done is better than well said." — Benjamin Franklin',
  '"Try not to become a person of success, but rather a person of value." — Albert Einstein',
  '"The secret of getting ahead is getting started." — Mark Twain',
  '"It always seems impossible until it is done." — Nelson Mandela',
  '"Nothing is impossible. The word itself says I\'m possible!" — Audrey Hepburn',
  '"Opportunities don\'t happen. You create them." — Chris Grosser',
  '"Don\'t wait. The time will never be just right." — Napoleon Hill',
  '"Hard work beats talent when talent doesn\'t work hard." — Tim Notke',
  '"Success usually comes to those who are too busy to be looking for it." — Henry David Thoreau',
  '"If you really look closely, most overnight successes took a long time." — Steve Jobs',
  '"The only place where success comes before work is in the dictionary." — Vidal Sassoon',
  '"Don\'t be afraid to give up the good to go for the great." — John D. Rockefeller',
  '"I find that the harder I work, the more luck I seem to have." — Thomas Jefferson',
  '"Success is walking from failure to failure with no loss of enthusiasm." — Winston Churchill',
  '"A person who never made a mistake never tried anything new." — Albert Einstein',
  '"Life shrinks or expands in proportion to one\'s courage." — Anais Nin',
  '"Twenty years from now you will be more disappointed by the things you didn\'t do." — Mark Twain',
  '"Happiness is not by chance, but by choice." — Jim Rohn',
  '"The best way to predict the future is to create it." — Peter Drucker',
  '"We become what we think about most of the time." — Earl Nightingale',
  '"Don\'t let yesterday take up too much of today." — Will Rogers',
  '"You learn more from failure than from success." — Unknown',
  '"The only way to achieve the impossible is to believe it is possible." — Charles Kingsleigh',
  '"If you\'re going through hell, keep going." — Winston Churchill',
  '"A champion is defined not by their wins but by how they recover when they fall." — Serena Williams',
  '"Courage is resistance to fear, mastery of fear — not absence of fear." — Mark Twain',
  '"Only those who dare to fail greatly can ever achieve greatly." — Robert F. Kennedy',
  '"Do one thing every day that scares you." — Eleanor Roosevelt',
  '"Limitations live only in our minds." — Jamie Paolinetti',
  '"What you do speaks so loudly that I cannot hear what you say." — Ralph Waldo Emerson',
  '"Whether you think you can or you think you can\'t, you\'re right." — Henry Ford',
  '"If you want to go fast, go alone. If you want to go far, go together." — African Proverb',
  '"In a gentle way, you can shake the world." — Mahatma Gandhi',
  '"Knowing is not enough; we must apply. Wishing is not enough; we must do." — Goethe',
  '"Imagination is more important than knowledge." — Albert Einstein',
  '"We may encounter many defeats but we must not be defeated." — Maya Angelou',
  '"Life is either a daring adventure or nothing at all." — Helen Keller',
  '"The only person you should try to be better than is the person you were yesterday." — Unknown',
  '"Fall seven times, stand up eight." — Japanese Proverb',
  '"Everything you can imagine is real." — Pablo Picasso',
  '"What we achieve inwardly will change outer reality." — Plutarch',
  '"It is during our darkest moments that we must focus to see the light." — Aristotle',
  '"Believe in yourself and all that you are." — Christian D. Larson',
  '"The greatest wealth is to live content with little." — Plato',
  '"No one can make you feel inferior without your consent." — Eleanor Roosevelt',
  '"The future belongs to those who prepare for it today." — Malcolm X',
  '"Darkness cannot drive out darkness; only light can do that." — Martin Luther King Jr.',
  '"Life is short, and it is up to you to make it sweet." — Sarah Louise Delany',
  '"Out of difficulties grow miracles." — Jean de La Bruyere',
  '"Nothing in life is to be feared, it is only to be understood." — Marie Curie',
  '"A journey of a thousand miles begins with a single step." — Lao Tzu',
  '"The best preparation for tomorrow is doing your best today." — H. Jackson Brown Jr.',
  '"With the new day comes new strength and new thoughts." — Eleanor Roosevelt',
  '"I have not failed. I\'ve just found 10,000 ways that won\'t work." — Thomas Edison',
  '"The only journey is the one within." — Rainer Maria Rilke',
  '"Logic will get you from A to B. Imagination will take you everywhere." — Albert Einstein',
  '"Don\'t watch the clock; do what it does. Keep going." — Sam Levenson',
  '"The power of imagination makes us infinite." — John Muir',
  '"What we think, we become." — Buddha',
  '"Life isn\'t about finding yourself. Life is about creating yourself." — George Bernard Shaw',
  '"Kind words can be short and easy to speak, but their echoes are truly endless." — Mother Teresa',
  '"Where there is love, there is life." — Mahatma Gandhi',
  '"Spread love everywhere you go." — Mother Teresa',
  '"The purpose of our lives is to be happy." — Dalai Lama',
  '"Life is what we make it, always has been, always will be." — Grandma Moses',
  '"You are never too old to set another goal or to dream a new dream." — C.S. Lewis',
  '"Change your thoughts and you change your world." — Norman Vincent Peale',
  '"Either write something worth reading or do something worth writing." — Benjamin Franklin',
  '"If you cannot do great things, do small things in a great way." — Napoleon Hill',
  '"To live is the rarest thing in the world. Most people exist, that is all." — Oscar Wilde',
  '"The mind is everything. What you think you become." — Buddha',
  '"An investment in knowledge pays the best interest." — Benjamin Franklin',
  '"Be so good they can\'t ignore you." — Steve Martin',
  '"The greatest glory in living lies not in never falling, but in rising every time we fall." — Nelson Mandela',
  '"Your limitation — it\'s only your imagination." — Unknown',
  '"Push yourself, because no one else is going to do it for you." — Unknown',
  '"Great things never come from comfort zones." — Unknown',
  '"Dream it. Wish it. Do it." — Unknown',
  '"Success doesn\'t just find you. You have to go out and get it." — Unknown',
  '"The harder you work, the greater you\'ll feel when you achieve it." — Unknown',
  '"Don\'t stop when you\'re tired. Stop when you\'re done." — Unknown',
  '"Wake up with determination. Go to bed with satisfaction." — Unknown',
  '"Do something today that your future self will thank you for." — Unknown',
  '"Little things make big days." — Unknown',
  '"It\'s going to be hard, but hard does not mean impossible." — Unknown',
  '"Don\'t wait for opportunity. Create it." — Unknown',
  '"The key to success is to focus on goals, not obstacles." — Unknown',
  '"Dream bigger. Do bigger." — Unknown',
  '"Stay positive. Work hard. Make it happen." — Unknown',
  '"The struggle you\'re in today is developing the strength you need for tomorrow." — Robert Tew',
  '"Don\'t be pushed around by fears. Be led by dreams in your heart." — Roy T. Bennett',
  '"If opportunity doesn\'t knock, build a door." — Milton Berle',
  '"Everything negative is an opportunity for me to rise." — Kobe Bryant',
  '"I never dreamed about success. I worked for it." — Estee Lauder',
  '"Success is not the key to happiness. Happiness is the key to success." — Albert Schweitzer',
  '"The secret of getting ahead is getting started." — Mark Twain',
  '"It always seems impossible until it is done." — Nelson Mandela',
];

// ─── Horoscope Data ───────────────────────────────────────────────────────────
export const horoscopeSigns: Record<string, { emoji: string; element: string }> = {
  aries:       { emoji: '', element: 'Fire' },
  taurus:      { emoji: '', element: 'Earth' },
  gemini:      { emoji: '', element: 'Air' },
  cancer:      { emoji: '', element: 'Water' },
  leo:         { emoji: '', element: 'Fire' },
  virgo:       { emoji: '', element: 'Earth' },
  libra:       { emoji: '', element: 'Air' },
  scorpio:     { emoji: '', element: 'Water' },
  sagittarius: { emoji: '', element: 'Fire' },
  capricorn:   { emoji: '', element: 'Earth' },
  aquarius:    { emoji: '', element: 'Air' },
  pisces:      { emoji: '', element: 'Water' },
};

export const horoscopeReadings: string[] = [
  'Today is a great day for new beginnings. Trust your instincts and take that first step.',
  'The stars align in your favor. Focus on personal growth and creative expression.',
  'A surprising opportunity may come your way today. Stay open-minded.',
  'Communication is key today. Express your feelings honestly and listen carefully.',
  'Financial matters require attention. Be cautious with spending today.',
  'Love is in the air! If single, keep your eyes open. If taken, plan something special.',
  'Your energy levels are high today. Channel that into productive activities.',
  'Take a moment to reflect on your goals. Adjust your path if needed.',
  'Social connections bring joy today. Reach out to old friends.',
  'Patience is your greatest ally today. Good things come to those who wait.',
  'Your creativity is peaking. Use it to solve a lingering problem.',
  'Health matters deserve your attention today. Take a walk or try something new.',
  'A mentor figure may appear in your life. Be receptive to their guidance.',
  'Today favors collaboration over solo efforts. Teamwork makes the dream work.',
  'Let go of past grudges. Forgiveness will bring you peace.',
  'An unexpected conversation could change your perspective today.',
  'Trust the process. What feels uncertain now will make sense soon.',
  'Your determination is your superpower today. Push through obstacles.',
  'Romance and passion are highlighted. Express your feelings boldly.',
  'Financial decisions made today will have long-term impact. Choose wisely.',
  'Adventure calls! Step out of your comfort zone.',
  'Family matters need attention. Show your loved ones you care.',
  'Your intuition is particularly strong today. Trust your gut feelings.',
  'A creative project could gain momentum. Dedicate time to your passions.',
  'Balance work and play. Burnout is a real risk if you push too hard.',
  'Positive energy surrounds you. Spread it to those around you.',
  'Learning something new today could open unexpected doors.',
  'Your kindness will be rewarded. Keep being generous.',
  'Change is coming. Embrace it rather than resist.',
  'Today is perfect for setting long-term goals. Dream big!',
  'Spiritual growth is favored. Meditate or spend time in nature.',
  'Your words carry extra power today. Use them wisely.',
  'A financial surprise could brighten your day. Stay positive.',
  'Relationships deepen when you show vulnerability. Be authentic.',
  'Physical activity will boost your mood and clarity today.',
  'Old patterns may resurface. Choose differently this time.',
  'A chance encounter could lead to a lasting connection.',
  'Focus on self-care. You deserve time to recharge.',
  'Your hard work is about to pay off. Keep going!',
  'Today brings clarity to a confusing situation. Answers emerge.',
  'Be mindful of your spending habits today.',
  'A friend needs your support. Be there for them.',
  'Travel plans or adventures are favored today.',
  'Your charm is magnetic today. Use it for good.',
  'Take a leap of faith. The universe has your back.',
  'Organize your space, organize your mind. Declutter today.',
  'A creative breakthrough awaits. Keep experimenting.',
  'Gratitude shifts your energy. Count your blessings.',
  'Exciting news could arrive. Stay alert and ready.',
  'Today is about progress, not perfection. Move forward.',
  'New friendships may blossom if you open up to new experiences.',
  'A minor setback is actually redirecting you to something better.',
  'Your emotional intelligence is your gift today. Use it wisely.',
  'Career opportunities are knocking. Prepare to answer.',
  'A heartfelt conversation can heal old wounds today.',
  'Numbers are lucky for you today. Pay attention to patterns.',
  'Rest is productive too. Allow yourself to slow down.',
  'Someone from your past may reach out. Handle with grace.',
  'Your natural leadership shines today. Guide others confidently.',
  'Today favors bold moves and brave decisions.',
];

// ─── Promo Messages ───────────────────────────────────────────────────────────
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://www.botwave.online';

const CHANNEL_URL = 'https://whatsapp.com/channel/0029Vb89xfPCMY0IvFWi6B0X';

export const promoMessages: string[] = [
  `\n─────────────────────────────\nWant your own WhatsApp bot?\nCreate yours FREE at ${APP_URL}/signup\n📢 Follow us: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nLove this feature?\nGet your own bot FREE at ${APP_URL}/signup\n📢 Updates: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nPowered by BotWave\nCreate yours FREE at ${APP_URL}/signup\n📢 Channel: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nMade with BotWave\nGet your own bot at ${APP_URL}/signup\n📢 Follow: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nBotWave — Free WhatsApp Bot\nStart yours at ${APP_URL}/signup\n📢 Join our channel: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nImpressed? Build your own!\nFREE at ${APP_URL}/signup\n📢 Follow BotWave: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nThis bot runs on BotWave\nMake yours: ${APP_URL}/signup\n📢 Updates & tips: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nBotWave powers this bot\nYour own bot: ${APP_URL}/signup\n📢 Follow us: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nAutomate WhatsApp for free\n${APP_URL}/signup\n📢 Channel: ${CHANNEL_URL}`,
  `\n─────────────────────────────\nBotWave — by Decisive Analyst\nGet started: ${APP_URL}/signup\n📢 Follow: ${CHANNEL_URL}`,
];

// ─── Ping Replies ─────────────────────────────────────────────────────────────
export const pingReplies: string[] = [
  'PONG! Bot is online and running',
  'I\'m alive! Responding from BotWave HQ',
  'Online and ready, {name}!',
  'PONG! All systems operational',
  'Hey {name}! Bot is active',
  'I\'m here! Latency looking good',
  'System check: All green!',
  'Bot is running smoothly!',
  'Connected and ready!',
  'PONG! Response time excellent',
  'I\'m awake and working!',
  'Status: Operational',
  'All systems go, {name}!',
  'Bot reporting for duty!',
  'Here and ready!',
  'Systems online, {name}!',
  'Active and listening!',
  'PONG! Everything is good',
  'Running strong!',
  'Bot status: Online',
  'I read you loud and clear!',
  'Here! What do you need?',
  'PONG! Running at {time}',
  'Up and running since startup!',
  'Bot is healthy and responsive!',
  'Present and accounted for!',
  'All engines running!',
  'PONG! Quick response!',
  'Bot is live, {name}!',
  'Check complete: All OK',
  'Still here, still working!',
  'PONG! No issues detected',
  'Bot health: Excellent',
  'Online status confirmed!',
  'System heartbeat: Normal',
  'Running without issues!',
  'Here and operational!',
  'PONG! Server time: {time}',
  'All good on my end!',
  'Active since last restart!',
  'Yep, I\'m here!',
  'PONG! Ready for commands',
  'Still kicking!',
  'Bot engine running fine!',
  'Operational at {time}',
  'PONG! All clear',
  'I\'m online, {name}!',
  'Working perfectly!',
  'PONG! Everything\'s fine',
  'Bot is responsive!',
];

// ─── Help Intro Lines ─────────────────────────────────────────────────────────
export const helpIntros: string[] = [
  'Here are all available commands, {name}!',
  'Command list coming up!',
  'Check out what I can do, {name}!',
  'Here\'s everything I can do!',
  'Your command menu, {name}!',
  'All commands at your service, {name}!',
  'Here\'s the full list of what I offer!',
  'Need help? Here are all my commands!',
  'BotWave commands for you, {name}!',
  'Here\'s my feature list!',
  'What can I do? Let me show you, {name}!',
  'Your BotWave guide, {name}!',
  'Commands ready! Here you go, {name}!',
  'The full command list, {name}!',
  'Everything I can do, {name}:',
  'My capabilities for you, {name}!',
  'Check these out, {name}!',
  'Command reference ready!',
  '{name}, here\'s what\'s available!',
  'All features and commands, {name}!',
  'Here\'s your BotWave manual!',
  'My full feature list, {name}!',
  '{name}, here\'s what I can do for you!',
  'Command guide coming right up!',
  'Here\'s your help menu!',
  'Available commands, {name}:',
  'Let me show you everything!',
  'Your BotWave cheat sheet!',
  'Here\'s the full menu, {name}!',
  '{name}, check out all these features!',
  'Ready to help! Here are the commands:',
  'BotWave feature guide for {name}!',
  'All systems and commands listed below!',
  'Here you go, {name}! Full command list:',
  'BotWave help menu ready!',
  'What I can do for you, {name}:',
  'Full list of available commands:',
  'Need something? Here\'s what I\'ve got!',
  'Check it, {name}! All my commands:',
  '{name}, your help guide is here!',
  'Here\'s every command I know!',
  'Bot commands at a glance, {name}!',
  'All features unlocked, {name}!',
  'Help menu loaded!',
  'Commands, features, and more:',
  'Your personal command guide!',
  'Here\'s the rundown, {name}!',
  '{name}, take a look at my commands!',
  'Everything I\'m capable of!',
  'BotWave: Full command list for {name}!',
];

// ─── Unknown Command Replies ──────────────────────────────────────────────────
export const unknownCommandReplies: string[] = [
  'Hmm, I don\'t know that command. Try !help',
  'Unknown command! Use !help to see available commands',
  'That\'s not a command I recognize. Type !help',
  'Sorry, didn\'t catch that. Try !help for the full list',
  'Command not found. Check !help for options',
  'I don\'t understand that one. Use !help',
  'That command doesn\'t exist yet! Try !help',
  'Oops, unknown command. !help has the full list',
  'Hmm? Try !help to see what I can do',
  'Not sure what you mean. !help might help!',
  'Can\'t find that command, {name}. Try !help',
  'Invalid command! Type !help for options',
  '{name}, that\'s not a valid command. Use !help',
  'Nope, don\'t have that one. Check !help',
  'That one\'s not in my playbook. Try !help',
  'I wish I could do that! For now, try !help',
  'Command not recognized, {name}. Use !help',
  'Hmm, never heard of that. Try !help?',
  'I\'m confused! Try !help for my command list',
  'That doesn\'t ring a bell. Type !help',
  'Not a valid command. !help to the rescue!',
  'I can\'t do that one. Check !help, {name}!',
  'Doesn\'t look like a command. Try !help',
  '{name}, use !help to see what I can do!',
  'Command what? Try !help for the menu',
  'I don\'t have that feature. See !help',
  'Sorry {name}, unknown command. !help works!',
  'That\'s new to me! Check out !help',
  'Unknown input. Type !help for commands',
  'Hmm, nope. But !help has everything!',
  '{name}, check !help for all my commands',
  'Not in my repertoire! Try !help',
  'I can\'t process that. Use !help, {name}',
  'That command is missing. Try !help',
  'Unrecognized! See !help for the list',
  'What was that? !help shows everything I do',
  'Command error. Type !help for the menu',
  'I don\'t know that yet. Try !help!',
  'Lost? !help will show you the way, {name}!',
  'Can\'t find it. Use !help for guidance',
  'Not a thing! But !help has plenty of things',
  'Sorry, that\'s not available. !help for options',
  'Draw a blank on that one. Try !help',
  'No match found. Type !help for commands',
  '{name}, try !help to discover my features',
  'That went over my head. Use !help!',
  'Unknown territory! Navigate with !help',
  'I didn\'t get that, {name}. Use !help',
  'What? Use !help for command options',
  'That\'s beyond me for now. Check !help!',
];

// ─── Doc Created Replies ──────────────────────────────────────────────────────
export const docReplies: string[] = [
  'Your document is ready, {name}!',
  'Document created successfully!',
  'Here\'s your document!',
  'Doc generated at {time}',
  'Your .docx file is ready!',
  'Document created for {name}!',
  'File ready! Here you go',
  'Document done!',
  'Your formatted document',
  '{name}, here\'s your doc!',
  'Created your document!',
  'Document is served!',
  'Fresh document for you!',
  'File created at {time}',
  'Your document, as requested!',
  'Doc ready, {name}!',
  'Done! Here\'s your document',
  'Document prepared!',
  'Your file is ready!',
  'Doc generated for {name}!',
  'Text converted to document!',
  'Your .docx is ready!',
  'Document complete!',
  'Here\'s your file, {name}!',
  'Document delivered!',
  'Created at {time}',
  'Your formatted doc!',
  'File is ready, {name}!',
  'Document made!',
  'Here you go, {name}!',
  'Fresh doc incoming!',
  'Your text as a document!',
  'Done! Document attached',
  '{name}\'s document is ready!',
  'File generated successfully!',
  'Document for {name}, done!',
  'Ready! Your .docx file',
  'Text to doc complete!',
  'Your new document!',
  'Doc is done, {name}!',
  'Created your file!',
  'Your document was created!',
  'Document exported!',
  'File created for {name}!',
  'Doc generated!',
  'Formatted and ready!',
  'Your doc file!',
  'Done, {name}! Document attached',
  'Document saved!',
  'Here it is, {name}! Your document',
  'Hot off the press, {name}! Your doc',
  'Doc file delivered at {time}!',
  'Your professional document is here!',
  'Converted to .docx for {name}!',
  '{name}, document incoming!',
  'Check your document, {name}!',
  'File packaged and sent!',
  'Your text, now a proper document!',
  'Document created on {date}!',
  'Your .docx has been generated!',
];

// ─── Translate Replies ────────────────────────────────────────────────────────
export const translateReplies: string[] = [
  'Translation ready!',
  'Here\'s your translation, {name}!',
  'Translated at {time}',
  'Translation complete!',
  'Done! Here\'s the translation',
  'Your translated text:',
  'Translation for {name}!',
  'Translated successfully!',
  'Here you go, {name}! Translated:',
  'Translation done!',
  'Text translated for {name}!',
  'Your translation is ready!',
  'Language converted!',
  '{name}, here\'s the translation!',
  'Translated in a flash!',
  'Quick translation ready!',
  'Your text, translated:',
  'Translation completed at {time}!',
  '{name}, translation delivered!',
  'Here\'s what it says:',
  'Language barrier broken!',
  'Translated just for you, {name}!',
  'Translation served at {time}!',
  'Got the translation!',
  'Your translated message:',
  'Words translated successfully!',
  'Translated and ready, {name}!',
  '{name}\'s translation is here!',
  'Quick translate done!',
  'Conversion complete!',
  'Here\'s your text in the new language:',
  'Translation magic done!',
  'Linguistically converted, {name}!',
  'Text transformed!',
  'Your multilingual message:',
  'Fresh translation, {name}!',
  'Translation output ready!',
  'Done translating for {name}!',
  'Translation express delivery!',
  'Language swap complete!',
  'Translated text incoming!',
  '{name}, your words translated:',
  'Fast translation ready!',
  'Cross-language conversion done!',
  'Text translated at {time}!',
  'Here\'s the translated version:',
  'Translation locked in!',
  'Your request: Translated!',
  'Words converted, {name}!',
  'Translation from BotWave:',
];

// ─── Weather Replies ──────────────────────────────────────────────────────────
export const weatherReplies: string[] = [
  'Weather update for {name}!',
  'Here\'s the current weather:',
  'Weather report ready!',
  'Current conditions:',
  'Weather data fetched!',
  'Your weather forecast:',
  'Weather info at {time}:',
  '{name}, here\'s the weather:',
  'Updated weather report:',
  'Live weather data:',
  'Weather check for {name}!',
  'Forecast fetched at {time}!',
  'Here\'s your weather, {name}!',
  'Weather report for {name}:',
  'Current weather conditions:',
  'Sky update ready!',
  'Your daily weather, {name}:',
  'Fresh weather data:',
  '{name}, weather incoming!',
  'Weather alert for {name}:',
  'Atmospheric update:',
  'Here\'s the latest weather:',
  'Weather fetched for {name}!',
  'Local weather at {time}:',
  'Your forecast is ready!',
  '{name}\'s weather report:',
  'Climate check ready!',
  'Today\'s weather for {name}:',
  'Weather status update:',
  'Forecast delivered!',
  'Current sky conditions:',
  'Real-time weather:',
  'Weather pulled for {name}!',
  '{name}, forecast ready!',
  'Weather snapshot at {time}:',
  'Temperature and conditions:',
  'Your weather at a glance:',
  'Forecast report, {name}!',
  'Up-to-date weather data:',
  'Weather briefing for {name}!',
  'Checking the skies for {name}:',
  'Weather intel ready!',
  'Here comes the forecast:',
  '{name}, weather data loaded:',
  'Conditions report:',
  'Current forecast:',
  'Weather service for {name}!',
  'Atmosphere report ready:',
  'Your local weather:',
  'Conditions checked at {time}:',
];

// ─── Dictionary Replies ───────────────────────────────────────────────────────
export const dictReplies: string[] = [
  'Here\'s the definition, {name}!',
  'Word definition found!',
  'Dictionary lookup complete!',
  'Definition for you:',
  'Found it! Here\'s the meaning:',
  '{name}, here\'s what it means:',
  'Word looked up at {time}:',
  'Definition ready!',
  'Your word definition:',
  'Meaning found!',
  'Dictionary says:',
  'Word meaning fetched!',
  'Here\'s the definition:',
  'Looked it up for you, {name}!',
  'Definition delivered!',
  'Your vocabulary boost, {name}!',
  'Word search complete!',
  'Here\'s what the dictionary says:',
  'Definition for {name}:',
  'Meaning lookup done!',
  'Word explained:',
  'Got the definition, {name}!',
  'Linguistic breakdown:',
  'Here\'s the meaning for {name}:',
  'Word found in dictionary!',
  'Definition at {time}:',
  'Your word, defined:',
  'Dictionary result:',
  '{name}, meaning found!',
  'Vocab check for {name}:',
  'Definition incoming!',
  'Here\'s what it means, {name}:',
  'Word meaning for you:',
  'Look-up complete!',
  '{name}\'s word definition:',
  'Dictionary entry found!',
  'Meaning delivered at {time}!',
  'Word decoded for {name}!',
  'Definition fetched!',
  'Your dictionary result:',
  'Meaning found, {name}!',
  'Word definition at {time}:',
  'Definition report:',
  'Vocabulary update for {name}!',
  'Got the meaning!',
  'Word analyzed for {name}!',
  'Dictionary response:',
  '{name}, definition ready!',
  'Meaning revealed:',
  'Definition served!',
];

// ─── AI Response Intros ───────────────────────────────────────────────────────
export const aiIntros: string[] = [
  'Here\'s what I think, {name}:',
  'Great question! Here\'s my take:',
  '{name}, here you go:',
  'Let me help with that:',
  'Here\'s my response, {name}:',
  'Good one! Here\'s what I got:',
  '{name}, I\'ve got an answer:',
  'Here\'s what I came up with:',
  'Let me think... Here:',
  'AI response for {name}:',
  'Thinking done! Here you go:',
  'Here\'s my answer:',
  '{name}, check this out:',
  'Got it! Here\'s my take:',
  'Response ready, {name}:',
  'Let me answer that:',
  'Here\'s what AI says:',
  '{name}, here\'s my best answer:',
  'Answer incoming!',
  'Here\'s my take on it:',
  'Thought about it. Here:',
  'My response for {name}:',
  '{name}, let me explain:',
  'AI-powered answer:',
  'Quick answer for {name}:',
  'Here\'s what I found:',
  '{name}, here\'s the scoop:',
  'Processing done! Answer:',
  'Interesting question! Here:',
  '{name}, this is what I think:',
  'AI says:',
  'Here you go, {name}!',
  'My answer, {name}:',
  'Let me break it down:',
  'Great question, {name}!',
  'AI answer ready:',
  'Here\'s the answer:',
  '{name}, from my analysis:',
  'Processed your question:',
  'My thought on this:',
  'Answer for you, {name}:',
  'Computed response:',
  '{name}, here it is:',
  'Answering now:',
  'Analysis complete, {name}:',
  'Here\'s my insight:',
  'For {name}:',
  'Done thinking! Here:',
  'Response generated:',
  'My best answer, {name}:',
];

// ─── Game Replies ─────────────────────────────────────────────────────────────
export const gameStartReplies: string[] = [
  'Game on, {name}!',
  'Let\'s play, {name}!',
  'Game started! Good luck!',
  'Ready to play, {name}?',
  '{name}, the game begins!',
  'Starting the game!',
  'Game time, {name}!',
  'Challenge accepted!',
  'Let the game begin!',
  '{name}, are you ready?',
  'Game loaded for {name}!',
  'Your game starts now!',
  'Initiating game mode!',
  '{name}, game is on!',
  'Play time!',
  'The game is afoot, {name}!',
  'Starting up the fun!',
  'Game launch for {name}!',
  'Ready, set, play!',
  '{name} enters the arena!',
  'Game mode activated!',
  'Let\'s get competitive!',
  'Fun time, {name}!',
  'Your challenge awaits!',
  'Game initialized!',
  '{name} joins the game!',
  'Round 1, begin!',
  'The challenge starts now!',
  'Time to play, {name}!',
  'Starting game at {time}!',
  'Your game, {name}!',
  'Get ready to play!',
  'Game session started!',
  '{name}, show me what you got!',
  'Level 1: Start!',
  'Game is live, {name}!',
  'May the best player win!',
  'Your turn, {name}!',
  'Game loaded and ready!',
  'Time for some fun!',
  '{name}, challenge mode: ON',
  'Player {name} has entered!',
  'Let\'s do this, {name}!',
  'Game clock starts now!',
  'Ready player {name}!',
  'Competition begins!',
  'Firing up the game!',
  '{name}\'s game is live!',
  'Game awaits, {name}!',
  'Press start! Oh wait, you already did',
];

// ─── Poll Created Replies ─────────────────────────────────────────────────────
export const pollReplies: string[] = [
  'Poll created, {name}!',
  'Your poll is live!',
  'Vote now! Poll ready',
  'Poll started by {name}!',
  'New poll alert!',
  'Poll is up and running!',
  '{name} started a poll!',
  'Cast your votes!',
  'Poll time!',
  '{name}\'s poll is live!',
  'Poll created at {time}!',
  'Voting starts now!',
  'New poll for the group!',
  'Poll launched, {name}!',
  'Let the voting begin!',
  'Poll ready! Cast your vote',
  'Here\'s your poll, {name}!',
  'Group poll created!',
  'Time to vote, everyone!',
  'Poll is active!',
  'Voting time!',
  '{name} wants your opinion!',
  'Poll opened by {name}!',
  'Quick poll ready!',
  'Vote with !vote [number]!',
  '{name}\'s poll:',
  'New voting session!',
  'Poll deployed!',
  'Your poll awaits votes!',
  'Democracy in action!',
  'Everyone, vote now!',
  'Poll from {name}!',
  'Cast your vote below!',
  'Here comes a poll!',
  'Poll created successfully!',
  '{name} set up a poll!',
  'Time to make your choice!',
  'Vote using !vote [n]',
  'Opinions wanted!',
  'Poll session active!',
  'Group vote time!',
  '{name} is polling!',
  'Share your opinion!',
  'Let\'s decide together!',
  'Your vote matters!',
  'Poll initialized!',
  '{name} asks:',
  'Decision time!',
  'Voting has begun!',
  'Poll engine: Active!',
];

// ─── Leaderboard Replies ──────────────────────────────────────────────────────
export const leaderboardReplies: string[] = [
  'Here\'s the leaderboard, {name}!',
  'Top players!',
  'Leaderboard updated at {time}!',
  'The rankings, {name}!',
  'Hall of fame!',
  'Who\'s on top? Let\'s see!',
  'Leaderboard for {name}!',
  'Current standings:',
  'Player rankings!',
  'Score check time!',
  'Here are the top scorers!',
  'Leaderboard report!',
  '{name}, check the rankings!',
  'The best of the best!',
  'Score leaders:',
  'Updated rankings:',
  'Who\'s winning? Let\'s find out!',
  'Leaderboard snapshot at {time}!',
  '{name}, here are the standings:',
  'Top performers!',
  'Current leaders:',
  'Score update!',
  'Leaderboard loaded!',
  'The competition heats up!',
  'Rankings for {name}:',
  '{name}, see who\'s leading!',
  'Leaderboard live!',
  'Top scores right now:',
  'Who reigns supreme?',
  'Leaderboard fetched!',
  'Current top players:',
  '{name}, the rankings are in!',
  'Score roundup!',
  'Leader standings at {time}:',
  'Top dogs:',
  'Ranking report ready!',
  'Leaderboard check!',
  'The cream of the crop:',
  'Standings as of {time}:',
  'Score leaders, {name}!',
  'Who\'s the champ?',
  'Leaderboard data:',
  '{name}, here\'s who\'s winning:',
  'The current elite:',
  'Score rankings loaded!',
  'Performance leaders:',
  'Leaderboard at a glance:',
  'Top ranks for {name}!',
  'Best players right now:',
  'And the leaders are...',
];

// ─── Download Replies ─────────────────────────────────────────────────────────
export const downloadReplies: string[] = [
  'Download ready, {name}!',
  'Here\'s your download!',
  'Media downloaded!',
  'File is ready, {name}!',
  'Download complete!',
  '{name}, your file!',
  'Downloaded at {time}!',
  'Your media, {name}!',
  'Here\'s the file!',
  'Download delivered!',
  'Media fetched for {name}!',
  'Your download is here!',
  'File downloaded successfully!',
  '{name}, download done!',
  'Media ready!',
  'Got your download!',
  'Here you go, {name}!',
  'Download complete at {time}!',
  'Your requested media:',
  'File fetched!',
  'Download for {name}!',
  'Media download successful!',
  'File ready, {name}!',
  '{name}\'s download:',
  'Downloaded and delivered!',
  'Your media file is here!',
  'Download processed!',
  'File downloaded at {time}!',
  '{name}, file incoming!',
  'Download served!',
  'Media is ready, {name}!',
  'Quick download for {name}!',
  'Got the file!',
  'Here\'s what you requested:',
  'Downloaded for {name}!',
  'File download done!',
  'Media delivered!',
  '{name}, here\'s your media!',
  'Download success!',
  'Your file has arrived!',
  'Download fetched!',
  'Media grabbed for {name}!',
  '{name}, download complete!',
  'File served at {time}!',
  'Media extracted!',
  'Your download, served!',
  'File is downloaded, {name}!',
  'Download report: Success!',
  '{name}, media ready!',
  'Download finalized!',
];

// ─── Welcome Bot Replies ──────────────────────────────────────────────────────
export const welcomeReplies: string[] = [
  'Welcome to the group, {name}!',
  'Hey {name}, welcome aboard!',
  '{name} just joined! Welcome!',
  'Welcome {name}! Glad to have you here',
  'Hey there {name}, welcome to {group}!',
  '{name} has arrived! Welcome!',
  'Welcome welcome, {name}!',
  'A wild {name} has appeared! Welcome!',
  'Glad you could join us, {name}!',
  'Welcome to {group}, {name}!',
  '{name} is here! Let\'s go!',
  'Hey {name}! Make yourself at home',
  'Welcome aboard, {name}!',
  '{name} just dropped in! Hi!',
  'The crew grows! Welcome {name}',
  'Yo {name}, welcome to the squad!',
  'Welcome, {name}! Enjoy your stay',
  '{name} has entered the chat!',
  'Hey {name}! Great to see you here',
  'Welcome {name}, we\'ve been expecting you',
  'New member alert: {name} is here!',
  '{name} just joined {group}!',
  'Hi {name}, welcome to the fam!',
  'Everyone say hi to {name}!',
  'Welcome to the party, {name}!',
  '{name} joined! Welcome to {group}',
  'Look who\'s here! Welcome {name}',
  'Hello {name}, enjoy the group!',
  'Big welcome to {name}!',
  '{name}, glad you\'re here!',
  'Welcome {name}! Have a great time',
  'Another awesome person joined! Hey {name}',
  'Hey hey {name}, welcome!',
  '{name} is in the building!',
  'Welcome! We\'re happy to have you, {name}',
  '{name} has joined the group chat',
  'New member: {name}! Welcome!',
  'Roll out the red carpet for {name}!',
  'Good to have you, {name}!',
  '{name} just arrived at {group}!',
  'Welcome, {name}! Jump right in',
  'Hi there {name}! Welcome to the crew',
  '{name} joined at {time}! Welcome!',
  'Welcome to the gang, {name}!',
  'Cheers {name}, welcome aboard!',
  '{name}, welcome! Glad you made it',
  'Hola {name}! Welcome to {group}',
  'New friend alert! Welcome {name}',
  '{name} is now part of the group!',
  'Welcome {name}, feel at home!',
  'Hey {name}! You picked a great group',
  'Sup {name}, welcome!',
  '{name} just showed up! Welcome!',
  'The more the merrier! Welcome {name}',
  'Welcome to this awesome group, {name}!',
  '{name} has entered {group}!',
  'Welcome, {name}! Use !help for bot commands\n📢 Follow BotWave: https://whatsapp.com/channel/0029Vb89xfPCMY0IvFWi6B0X',
  'Hi {name}! Type !help to see what I can do\n📢 Updates: https://whatsapp.com/channel/0029Vb89xfPCMY0IvFWi6B0X',
  '{name} is here! Say hi everyone',
  'Welcome {name}! Enjoy the vibes',
  'New addition: {name}! Welcome!',
  'Greetings {name}, welcome to {group}!',
  '{name}, you\'re officially in! Welcome',
  'Warm welcome to {name}!',
  'Welcome to the chat, {name}!',
  'Hey {name}, you\'re gonna love it here!',
  '{name} just joined the family!',
  'Welcome {name}! Ask me anything with !ai\n📢 Follow our channel: https://whatsapp.com/channel/0029Vb89xfPCMY0IvFWi6B0X',
  'Guess who joined? {name}! Welcome!',
  'Welcome welcome welcome, {name}!',
  'Fresh face alert! {name} is here',
  'Welcome {name}! Make some noise!',
  '{name} checking in! Welcome to {group}',
  'Group just got better! Welcome {name}',
  'Ahoy {name}! Welcome aboard!',
];

// ─── Goodbye Replies ──────────────────────────────────────────────────────────
export const goodbyeReplies: string[] = [
  '{name} has left the group. Goodbye!',
  'See you later, {name}!',
  '{name} just left {group}. Take care!',
  'Bye bye {name}! You\'ll be missed',
  '{name} has departed. Farewell!',
  'Until next time, {name}!',
  '{name} left the chat. Catch you later!',
  'Sad to see you go, {name}!',
  '{name} has left {group}. Peace out!',
  '{name} is gone. Goodbye friend!',
  'We\'ll miss you, {name}!',
  '{name} waved goodbye. See ya!',
  'Farewell {name}, come back anytime!',
  '{name} has exited. Take care out there!',
  'Goodbye {name}! Hope to see you again',
  '{name} just left. Until we meet again!',
  'So long, {name}! Best wishes',
  '{name} bounced. Bye!',
  'Catch you on the flip side, {name}!',
  '{name} has left the building!',
];

// ─── Anti-Spam Warnings ───────────────────────────────────────────────────────
export const spamWarnings: string[] = [
  'Slow down, {name}! Too many messages',
  '{name}, you\'re sending too fast',
  'Easy there {name}, take it easy',
  'Spam detected from {name}',
  '{name}, please slow down',
  'Whoa {name}, chill with the messages',
  '{name}, you\'re flooding the chat',
  'Cool it {name}, too many msgs',
  '{name}, spam is not cool',
  'Hey {name}, one at a time please',
  'Message limit reached, {name}',
  '{name}, you\'re going too fast',
  'Slow down there, {name}!',
  '{name} chill, too many messages',
  'Rate limited, {name}. Wait a bit',
  '{name}, take a breather',
  'Too fast {name}, slow down!',
  'Easy {name}, you\'re flooding!',
  '{name}, pace yourself please',
  'Hold up {name}, too many msgs',
  'Spam alert from {name}!',
  '{name}, please wait between messages',
  'Relax {name}, one at a time',
  '{name}, the chat isn\'t going anywhere',
  'Slow your roll, {name}!',
  '{name}, take it easy on the messages',
  'You\'re on cooldown, {name}',
  '{name}, message limit exceeded',
  'Deep breaths {name}, slow down',
  'Hold on {name}, too fast!',
  '{name}, give others a chance to read',
  'Flood protection activated for {name}',
  'Hey {name}, not so fast!',
  '{name}, the bot needs a second',
  'Timeout for {name} — too many messages',
  '{name}, wait a moment please',
  'Pump the brakes, {name}!',
  'Chat police here! Slow down {name}',
  '{name}, message cooldown active',
  'Chill mode activated for {name}',
  '{name}, too many messages in a row',
  'Easy does it, {name}!',
  'Hey {name}, one message at a time',
  '{name}, give it a rest for a sec',
  'Spam shield activated! {name}, wait',
  '{name}, you\'re typing faster than me!',
  'Cool your jets, {name}!',
  '{name}, take a quick break',
  'Message overflow from {name}!',
  'Slow and steady, {name}!',
];

// ─── Auto-Reply Responses ─────────────────────────────────────────────────────
export const autoReplyDefaults: string[] = [
  'Thanks for your message, {name}! I\'ll get back to you soon',
  'Hey {name}, got your message! Will respond shortly',
  'Message received, {name}!',
  '{name}, thanks for reaching out!',
  'Got it, {name}! I\'ll reply when I can',
  'Thanks {name}, message noted!',
  'Hey {name}! I\'ll get to this soon',
  'Received your message, {name}!',
  '{name}, thanks! I\'m on it',
  'Noted, {name}! Response coming soon',
  'Hi {name}, I see your message!',
  'Thanks for writing, {name}!',
  '{name}, message logged!',
  'Hey there {name}, will reply soon!',
  'Got your msg, {name}!',
  '{name}, I\'ll respond shortly!',
  'Message from {name} received!',
  'Thanks {name}! Give me a moment',
  'Hi {name}, on it!',
  '{name}, appreciate the message!',
  'Received! Thanks {name}',
  'Hey {name}, working on a reply!',
  '{name}, hang tight!',
  'Message noted from {name}!',
  'Thanks {name}, won\'t be long!',
  'Got this, {name}! Replying soon',
  'Hey {name}, I\'m on it!',
  '{name}, sit tight!',
  'Received and noted, {name}!',
  'Hi {name}, I\'ll be with you shortly',
  'Thanks for the message, {name}!',
  '{name}, I see you! Replying soon',
  'On it, {name}!',
  'Hey {name}, message received loud and clear',
  'Gotcha, {name}!',
  '{name}, response incoming!',
  'Will reply soon, {name}!',
  'Hey {name}, give me a sec!',
  '{name}, your message is in my queue!',
  'Received at {time}, {name}!',
  'Message from {name} at {time} — noted!',
  'Thanks {name}, will respond at my earliest!',
  'Got the message, {name}! Be right back',
  '{name}, acknowledged!',
  'Hey {name}, be right with you!',
  'Thanks {name}, processing your message!',
  'I see you {name}, replying soon!',
  '{name}, one moment please!',
  'Received your text, {name}!',
  'Thanks {name}, stay tuned for my reply!',
];
