/**
 * BotWave Response Variation Pools
 *
 * Every command has 50-100 response variations to avoid identical
 * message fingerprints. Dynamic variables {name}, {time}, {date}
 * are injected at send time.
 */

// ─── Sticker Replies ──────────────────────────────────────────────────────────
export const stickerReplies: string[] = [
  "Here's your sticker!",
  'Sticker created!',
  'Done! Your sticker is ready',
  'Sticker delivered, {name}!',
  'Here you go, {name}!',
  'Fresh sticker for you!',
  'Got your sticker right here!',
  'Sticker incoming!',
  'Your sticker is ready!',
  'Made at {time} just for you!',
  'Sticker done, {name}!',
  'One sticker, coming up!',
  'Enjoy your sticker!',
  'Your custom sticker!',
  'Sticker created for {name}',
  'Check out your sticker!',
  'Brand new sticker!',
  'Here it is, {name}!',
  'Done! Sticker sent',
  'Your sticker, served fresh!',
  'Sticker made at {time}',
  'Ready! Your sticker',
  'Sticker is done!',
  'Sent your sticker, {name}!',
  'Sticker complete!',
  'A sticker for {name}!',
  'Got it! Sticker ready',
  'Sticker crafted!',
  'Your sticker has landed!',
  'Here, {name}! Your sticker',
  'Sticker processed!',
  'Done! Here ya go',
  'Your image is now a sticker!',
  'Converted to sticker!',
  'Sticker for you, {name}!',
  'Quick sticker for you!',
  'All done! Sticker ready',
  'Your sticker awaits!',
  'Hot off the press!',
  'Your sticker, as requested!',
  '{name}, your sticker!',
  'New sticker alert!',
  'Sticker mode activated!',
  'One sticker done!',
  'Image converted!',
  'Your sticker is served!',
  'Boom! Sticker ready',
  'Sticker magic done!',
  'Freshly made sticker!',
  'Sticker sent, {name}!',
];

// ─── AFK Replies ──────────────────────────────────────────────────────────────
export const afkReplies: string[] = [
  'Hey! {name} is away right now',
  '{name} stepped out, message noted',
  "They're unavailable right now, will notify them",
  '{name} is currently away',
  '{name} is AFK at the moment',
  'Heads up: {name} is not available',
  '{name} went offline for a bit',
  '{name} is busy right now',
  'Message received! {name} is away',
  "{name} can't respond right now",
  '{name} is taking a break',
  '{name} stepped away for a moment',
  "{name} isn't here right now",
  'Got your message! {name} is AFK',
  '{name} is offline temporarily',
  '{name} will be back soon',
  'Noted! {name} is currently away',
  '{name} is unavailable right now',
  'Message saved! {name} is AFK',
  '{name} has gone AFK',
  'Hey, {name} is not around',
  '{name} is out right now',
  "I'll let {name} know!",
  '{name} went AFK a while ago',
  '{name} is doing something else',
  "Don't worry, {name} will see this later",
  '{name} stepped out at {time}',
  '{name} is away since a while',
  'Away notice: {name} is not here',
  '{name} set their status to away',
  'Ping! {name} is offline',
  '{name} has been away for a bit',
  '{name} is currently occupied',
  'Message logged! {name} is AFK',
  'Hey there! {name} is away',
  '{name} is on a break right now',
  '{name} will reply when back',
  'Auto-reply: {name} is away',
  '{name} is not available currently',
  "I'll pass your message to {name}",
  '{name} will get back to you',
  "Heads up, {name} isn't online",
  '{name} left at {time}',
  '{name} is temporarily away',
  '{name} will respond later',
  'Quick note: {name} is AFK',
  '{name} went offline',
  'Away: {name} is not here',
  'Hold tight! {name} is away',
  '{name} is currently AFK',
];

// ─── Joke Pool ────────────────────────────────────────────────────────────────
export const jokePool: string[] = [
  'Why do programmers prefer dark mode? Because light attracts bugs!',
  "Why was the JavaScript developer sad? Because he didn't Node how to Express himself!",
  "How many programmers does it take to change a light bulb? None, that's a hardware problem!",
  "Why do Java developers wear glasses? Because they can't C#!",
  'A SQL query walks into a bar, walks up to two tables and asks... "Can I join you?"',
  'Why did the developer go broke? Because he used up all his cache!',
  "What's a programmer's favorite hangout place? Foo Bar!",
  'Why do programmers hate nature? It has too many bugs!',
  '!false — it\'s funny because it\'s true',
  'There are 10 types of people: those who understand binary and those who don\'t',
  'A programmer was found dead in the shower. The instructions on the shampoo read: Lather, Rinse, Repeat.',
  "What's a computer's least favorite food? Spam!",
  'Why did the functions stop calling each other? They got into an argument!',
  "I'd tell you a UDP joke, but you might not get it.",
  'I told my computer I needed a break, and now it won\'t stop sending me Kit-Kat ads.',
  "What's the object-oriented way to become rich? Inheritance!",
  'Why do Python programmers have low self-esteem? They\'re constantly comparing themselves to others.',
  'What do you call 8 hobbits? A hobbyte.',
  "An SEO expert walks into a bar, pub, inn, tavern, public house, Irish bar...",
  'How do you comfort a JavaScript bug? You console it!',
  "What's a programmer's favorite tea? Chai-nese tea.",
  'Why was the computer cold? It left its Windows open!',
  'What do computers snack on? Microchips!',
  'Why did the computer go to the doctor? It had a virus!',
  'What did the spider do on the internet? Built a website!',
  "How does a computer get drunk? It takes screenshots!",
  "What do you call a computer that sings? A-Dell!",
  "Why couldn't the computer take its hat off? Because it had its CAPS LOCK on!",
  "What do you call a group of unorganized cats? A cat-alogue!",
  "Why did the PowerPoint cross the road? To get to the other slide!",
  "What's the best way to carve wood? Whittle by whittle.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I asked my dog what's two minus two. He said nothing.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I used to hate facial hair, but then it grew on me.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why do bees hum? Because they don't know the words!",
  "What do you call a fake noodle? An impasta!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I couldn't figure out how to put my seatbelt on. Then it clicked!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Did you hear about the claustrophobic astronaut? He needed more space.",
  "Why don't eggs tell jokes? They'd crack each other up!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a sleeping dinosaur? A dino-snore!",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the scarecrow win an award? He was outstanding in his field!",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "What do you call a lazy kangaroo? A pouch potato!",
];

// ─── Quote Pool ───────────────────────────────────────────────────────────────
export const quotePool: string[] = [
  '"The only way to do great work is to love what you do." — Steve Jobs',
  '"Innovation distinguishes between a leader and a follower." — Steve Jobs',
  '"Stay hungry, stay foolish." — Steve Jobs',
  '"The future belongs to those who believe in the beauty of their dreams." — Eleanor Roosevelt',
  '"It does not matter how slowly you go as long as you do not stop." — Confucius',
  '"Life is what happens when you\'re busy making other plans." — John Lennon',
  '"In the middle of every difficulty lies opportunity." — Albert Einstein',
  '"The best time to plant a tree was 20 years ago. The second best time is now." — Chinese Proverb',
  '"Be the change you wish to see in the world." — Mahatma Gandhi',
  '"Your time is limited, don\'t waste it living someone else\'s life." — Steve Jobs',
  '"Believe you can and you\'re halfway there." — Theodore Roosevelt',
  '"The only impossible journey is the one you never begin." — Tony Robbins',
  '"Success is not final, failure is not fatal: It is the courage to continue that counts." — Winston Churchill',
  '"What you get by achieving your goals is not as important as what you become by achieving your goals." — Zig Ziglar',
  '"If you want to lift yourself up, lift up someone else." — Booker T. Washington',
  '"Strive not to be a success, but rather to be of value." — Albert Einstein',
  '"You miss 100% of the shots you don\'t take." — Wayne Gretzky',
  '"The purpose of life is not to be happy. It is to be useful." — Ralph Waldo Emerson',
  '"Do what you can, with what you have, where you are." — Theodore Roosevelt',
  '"Act as if what you do makes a difference. It does." — William James',
  '"The mind is everything. What you think you become." — Buddha',
  '"An unexamined life is not worth living." — Socrates',
  '"Everything you\'ve ever wanted is on the other side of fear." — George Addair',
  '"What lies behind us and what lies before us are tiny matters compared to what lies within us." — Ralph Waldo Emerson',
  '"Happiness is not something ready made. It comes from your own actions." — Dalai Lama',
  '"Keep your face always toward the sunshine—and shadows will fall behind you." — Walt Whitman',
  '"If you look at what you have in life, you\'ll always have more." — Oprah Winfrey',
  '"You only live once, but if you do it right, once is enough." — Mae West',
  '"The best revenge is massive success." — Frank Sinatra',
  '"Life is 10% what happens to me and 90% of how I react to it." — Charles Swindoll',
  '"Not all who wander are lost." — J.R.R. Tolkien',
  '"The greatest glory in living lies not in never falling, but in rising every time we fall." — Nelson Mandela',
  '"Life is really simple, but we insist on making it complicated." — Confucius',
  '"It is never too late to be what you might have been." — George Eliot',
  '"When one door of happiness closes, another opens." — Helen Keller',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." — Robert Frost',
  '"Dream big and dare to fail." — Norman Vaughan',
  '"Turn your wounds into wisdom." — Oprah Winfrey',
  '"Simplicity is the ultimate sophistication." — Leonardo da Vinci',
  '"What we think, we become." — Buddha',
  '"Doubt kills more dreams than failure ever will." — Suzy Kassem',
  '"The harder I work, the luckier I get." — Gary Player',
  '"Start where you are. Use what you have. Do what you can." — Arthur Ashe',
  '"The only limit to our realization of tomorrow will be our doubts of today." — Franklin D. Roosevelt',
  '"Don\'t count the days, make the days count." — Muhammad Ali',
  '"Quality is not an act, it is a habit." — Aristotle',
  '"The way to get started is to quit talking and begin doing." — Walt Disney',
  '"Everything has beauty, but not everyone sees it." — Confucius',
  '"Education is the most powerful weapon which you can use to change the world." — Nelson Mandela',
  '"Creativity is intelligence having fun." — Albert Einstein',
];

// ─── Horoscope Data ───────────────────────────────────────────────────────────
export const horoscopeSigns: Record<string, { emoji: string; element: string }> = {
  aries:       { emoji: '', element: 'Fire' },
  taurus:      { emoji: '', element: 'Earth' },
  gemini:      { emoji: '', element: 'Air' },
  cancer:      { emoji: '', element: 'Water' },
  leo:         { emoji: '', element: 'Fire' },
  virgo:       { emoji: '', element: 'Earth' },
  libra:       { emoji: '', element: 'Air' },
  scorpio:     { emoji: '', element: 'Water' },
  sagittarius: { emoji: '', element: 'Fire' },
  capricorn:   { emoji: '', element: 'Earth' },
  aquarius:    { emoji: '', element: 'Air' },
  pisces:      { emoji: '', element: 'Water' },
};

export const horoscopeReadings: string[] = [
  'Today is a great day for new beginnings. Trust your instincts and take that first step.',
  'The stars align in your favor. Focus on personal growth and creative expression.',
  'A surprising opportunity may come your way today. Stay open-minded.',
  'Communication is key today. Express your feelings honestly and listen carefully.',
  'Financial matters require attention. Be cautious with spending today.',
  'Love is in the air! If single, keep your eyes open. If taken, plan something special.',
  'Your energy levels are high today. Channel that into productive activities.',
  'Take a moment to reflect on your goals. Adjust your path if needed.',
  'Social connections bring joy today. Reach out to old friends.',
  'Patience is your greatest ally today. Good things come to those who wait.',
  'Your creativity is peaking. Use it to solve a lingering problem.',
  'Health matters deserve your attention today. Take a walk or try something new.',
  'A mentor figure may appear in your life. Be receptive to their guidance.',
  'Today favors collaboration over solo efforts. Teamwork makes the dream work.',
  'Let go of past grudges. Forgiveness will bring you peace.',
  'An unexpected conversation could change your perspective today.',
  'Trust the process. What feels uncertain now will make sense soon.',
  'Your determination is your superpower today. Push through obstacles.',
  'Romance and passion are highlighted. Express your feelings boldly.',
  'Financial decisions made today will have long-term impact. Choose wisely.',
  'Adventure calls! Step out of your comfort zone.',
  'Family matters need attention. Show your loved ones you care.',
  'Your intuition is particularly strong today. Trust your gut feelings.',
  'A creative project could gain momentum. Dedicate time to your passions.',
  'Balance work and play. Burnout is a real risk if you push too hard.',
  'Positive energy surrounds you. Spread it to those around you.',
  'Learning something new today could open unexpected doors.',
  'Your kindness will be rewarded. Keep being generous.',
  'Change is coming. Embrace it rather than resist.',
  'Today is perfect for setting long-term goals. Dream big!',
  'Spiritual growth is favored. Meditate or spend time in nature.',
  'Your words carry extra power today. Use them wisely.',
  'A financial surprise could brighten your day. Stay positive.',
  'Relationships deepen when you show vulnerability. Be authentic.',
  'Physical activity will boost your mood and clarity today.',
  'Old patterns may resurface. Choose differently this time.',
  'A chance encounter could lead to a lasting connection.',
  'Focus on self-care. You deserve time to recharge.',
  'Your hard work is about to pay off. Keep going!',
  'Today brings clarity to a confusing situation. Answers emerge.',
  'Be mindful of your spending habits today.',
  'A friend needs your support. Be there for them.',
  'Travel plans or adventures are favored today.',
  'Your charm is magnetic today. Use it for good.',
  'Take a leap of faith. The universe has your back.',
  'Organize your space, organize your mind. Declutter today.',
  'A creative breakthrough awaits. Keep experimenting.',
  'Gratitude shifts your energy. Count your blessings.',
  'Exciting news could arrive. Stay alert and ready.',
  'Today is about progress, not perfection. Move forward.',
];

// ─── Promo Messages ───────────────────────────────────────────────────────────
export const promoMessages: string[] = [
  '\n─────────────────────────────\nWant your own WhatsApp bot?\nCreate yours FREE at botwave.com/start',
  '\n─────────────────────────────\nLove this feature?\nGet your own bot FREE at botwave.com/start',
  '\n─────────────────────────────\nPowered by BotWave\nCreate yours FREE at botwave.com/start',
  '\n─────────────────────────────\nMade with BotWave\nGet your own bot at botwave.com/start',
  '\n─────────────────────────────\nBotWave — Free WhatsApp Bot\nStart yours at botwave.com/start',
];

// ─── Ping Replies ─────────────────────────────────────────────────────────────
export const pingReplies: string[] = [
  'PONG! Bot is online and running',
  'I\'m alive! Responding from BotWave HQ',
  'Online and ready, {name}!',
  'PONG! All systems operational',
  'Hey {name}! Bot is active',
  'I\'m here! Latency looking good',
  'System check: All green!',
  'Bot is running smoothly!',
  'Connected and ready!',
  'PONG! Response time excellent',
  'I\'m awake and working!',
  'Status: Operational',
  'All systems go, {name}!',
  'Bot reporting for duty!',
  'Here and ready!',
  'Systems online, {name}!',
  'Active and listening!',
  'PONG! Everything is good',
  'Running strong!',
  'Bot status: Online',
  'I read you loud and clear!',
  'Here! What do you need?',
  'PONG! Running at {time}',
  'Up and running since startup!',
  'Bot is healthy and responsive!',
  'Present and accounted for!',
  'All engines running!',
  'PONG! Quick response!',
  'Bot is live, {name}!',
  'Check complete: All OK',
  'Still here, still working!',
  'PONG! No issues detected',
  'Bot health: Excellent',
  'Online status confirmed!',
  'System heartbeat: Normal',
  'Running without issues!',
  'Here and operational!',
  'PONG! Server time: {time}',
  'All good on my end!',
  'Active since last restart!',
  'Yep, I\'m here!',
  'PONG! Ready for commands',
  'Still kicking!',
  'Bot engine running fine!',
  'Operational at {time}',
  'PONG! All clear',
  'I\'m online, {name}!',
  'Working perfectly!',
  'PONG! Everything\'s fine',
  'Bot is responsive!',
];

// ─── Help Intro Lines ─────────────────────────────────────────────────────────
export const helpIntros: string[] = [
  'Here are all available commands, {name}!',
  'Command list coming up!',
  'Check out what I can do, {name}!',
  'Here\'s everything I can do!',
  'Your command menu, {name}!',
];

// ─── Unknown Command Replies ──────────────────────────────────────────────────
export const unknownCommandReplies: string[] = [
  'Hmm, I don\'t know that command. Try !help',
  'Unknown command! Use !help to see available commands',
  'That\'s not a command I recognize. Type !help',
  'Sorry, didn\'t catch that. Try !help for the full list',
  'Command not found. Check !help for options',
  'I don\'t understand that one. Use !help',
  'That command doesn\'t exist yet! Try !help',
  'Oops, unknown command. !help has the full list',
  'Hmm? Try !help to see what I can do',
  'Not sure what you mean. !help might help!',
];

// ─── Doc Created Replies ──────────────────────────────────────────────────────
export const docReplies: string[] = [
  'Your document is ready, {name}!',
  'Document created successfully!',
  'Here\'s your document!',
  'Doc generated at {time}',
  'Your .docx file is ready!',
  'Document created for {name}!',
  'File ready! Here you go',
  'Document done!',
  'Your formatted document',
  '{name}, here\'s your doc!',
  'Created your document!',
  'Document is served!',
  'Fresh document for you!',
  'File created at {time}',
  'Your document, as requested!',
  'Doc ready, {name}!',
  'Done! Here\'s your document',
  'Document prepared!',
  'Your file is ready!',
  'Doc generated for {name}!',
  'Text converted to document!',
  'Your .docx is ready!',
  'Document complete!',
  'Here\'s your file, {name}!',
  'Document delivered!',
  'Created at {time}',
  'Your formatted doc!',
  'File is ready, {name}!',
  'Document made!',
  'Here you go, {name}!',
  'Fresh doc incoming!',
  'Your text as a document!',
  'Done! Document attached',
  '{name}\'s document is ready!',
  'File generated successfully!',
  'Document for {name}, done!',
  'Ready! Your .docx file',
  'Text to doc complete!',
  'Your new document!',
  'Doc is done, {name}!',
  'Created your file!',
  'Your document was created!',
  'Document exported!',
  'File created for {name}!',
  'Doc generated!',
  'Formatted and ready!',
  'Your doc file!',
  'Done, {name}! Document attached',
  'Document saved!',
  'Here it is, {name}! Your document',
];

// ─── Translate Replies ────────────────────────────────────────────────────────
export const translateReplies: string[] = [
  'Translation ready!',
  'Here\'s your translation, {name}!',
  'Translated at {time}',
  'Translation complete!',
  'Done! Here\'s the translation',
  'Your translated text:',
  'Translation for {name}!',
  'Translated successfully!',
  'Here you go, {name}! Translated:',
  'Translation done!',
];

// ─── Weather Replies ──────────────────────────────────────────────────────────
export const weatherReplies: string[] = [
  'Weather update for {name}!',
  'Here\'s the current weather:',
  'Weather report ready!',
  'Current conditions:',
  'Weather data fetched!',
  'Your weather forecast:',
  'Weather info at {time}:',
  '{name}, here\'s the weather:',
  'Updated weather report:',
  'Live weather data:',
];

// ─── Dictionary Replies ───────────────────────────────────────────────────────
export const dictReplies: string[] = [
  'Here\'s the definition, {name}!',
  'Word definition found!',
  'Dictionary lookup complete!',
  'Definition for you:',
  'Found it! Here\'s the meaning:',
  '{name}, here\'s what it means:',
  'Word looked up at {time}:',
  'Definition ready!',
  'Your word definition:',
  'Meaning found!',
];
