export interface UseCase {
  slug: string;
  title: string;
  headline: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string[];
  painPoints: string[];
  solutions: { title: string; description: string; command?: string }[];
  testimonialQuote?: string;
  ctaText: string;
}

export const useCases: UseCase[] = [
  {
    slug: 'schools',
    title: 'BotWave for Schools',
    headline: 'Manage school WhatsApp groups without the chaos',
    description: 'Class groups, department groups, faculty groups. Schools run on WhatsApp but moderation is a nightmare. BotWave fixes that.',
    seoTitle: 'WhatsApp Bot for Schools - Manage Class Groups | BotWave',
    seoDescription: 'Manage school WhatsApp groups with automated moderation, anti-spam, welcome messages, and AI assistance. Free for Nigerian schools.',
    seoKeywords: ['whatsapp bot for schools', 'school group management', 'whatsapp class group bot', 'school whatsapp moderation'],
    painPoints: [
      'Students spamming irrelevant content in class groups',
      'Admins manually removing off-topic messages',
      'New students not knowing group rules',
      'Important announcements getting lost in chat noise',
      'No way to track who is being disruptive',
    ],
    solutions: [
      { title: 'Auto-Welcome with Rules', description: 'Every new student gets a welcome message with the group rules. No more repeating yourself.', command: '!welcome' },
      { title: 'Anti-Spam Protection', description: 'Auto-detect and warn users who flood the group. 5 messages in 10 seconds? Warning issued.', command: '!antidelete' },
      { title: 'Warning System', description: 'Track rule violations per student. 3 warnings and they can be removed automatically.', command: '!warn' },
      { title: 'Announcements', description: 'Tag every group member at once for important announcements. No one misses it.', command: '!tagall' },
      { title: 'AI Homework Help', description: 'Students can ask the AI bot questions directly in the group. Saves lecturers time.', command: '!ai' },
      { title: 'Trivia Games', description: 'Keep engagement high with educational quizzes. Works great for revision sessions.', command: '!trivia' },
    ],
    ctaText: 'Set up BotWave for your school',
  },
  {
    slug: 'businesses',
    title: 'BotWave for Businesses',
    headline: 'Automate customer replies on WhatsApp',
    description: 'Small businesses in Nigeria live on WhatsApp. BotWave handles customer questions, order inquiries, and support automatically so you can focus on running your business.',
    seoTitle: 'WhatsApp Bot for Business - Auto-Reply & Customer Support | BotWave',
    seoDescription: 'Automate WhatsApp customer support for your Nigerian business. Auto-reply, FAQ bot, order management. Free to start.',
    seoKeywords: ['whatsapp bot for business', 'whatsapp business automation', 'whatsapp auto reply bot', 'business whatsapp bot nigeria'],
    painPoints: [
      'Replying to the same customer questions over and over',
      'Missing messages while you sleep',
      'No way to send bulk announcements to customers',
      'Customers asking for prices, availability, location repeatedly',
      'Managing multiple groups for different product categories',
    ],
    solutions: [
      { title: 'AI Auto-Replies', description: 'The AI learns your business info and answers customer questions 24/7. Price inquiries, location, hours, all handled.', command: '!ai' },
      { title: 'AFK Auto-Response', description: 'Set a custom away message when you are busy or sleeping. Customers know you will reply soon.', command: '!afk' },
      { title: 'Broadcast Messages', description: 'Send announcements to all group members. New product? Sale? Let everyone know at once.', command: '!tagall' },
      { title: 'Group Moderation', description: 'Keep customer groups clean. Auto-warn spammers, delete off-topic content.', command: '!warn' },
      { title: 'Translation', description: 'Auto-translate messages for customers who speak different languages.', command: '!translate' },
      { title: 'Receipt Scanning', description: 'Customers can send payment receipts and the bot extracts the details automatically.', command: '!scan' },
    ],
    ctaText: 'Automate your business WhatsApp',
  },
  {
    slug: 'creators',
    title: 'BotWave for Creators',
    headline: 'Manage your fan community without burning out',
    description: 'Content creators, musicians, and influencers use WhatsApp groups to stay close to fans. BotWave keeps the vibes high and the spam low.',
    seoTitle: 'WhatsApp Bot for Creators - Community Management | BotWave',
    seoDescription: 'Manage creator WhatsApp fan groups with automated moderation, engagement tools, games, and AI. Keep fans engaged without the burnout.',
    seoKeywords: ['whatsapp bot for creators', 'creator community bot', 'fan group management whatsapp', 'influencer whatsapp bot'],
    painPoints: [
      'Fan groups getting too noisy to manage',
      'Spam links and scammers in your community',
      'Fans asking repetitive questions about your work',
      'Keeping engagement high between content drops',
      'Managing multiple groups across platforms',
    ],
    solutions: [
      { title: 'Anti-Spam', description: 'Block spam, scam links, and self-promotion automatically. Keep the group focused on your community.', command: '!antidelete' },
      { title: 'Games and Engagement', description: 'Trivia, hangman, word chains, polls. Keep fans entertained between your posts.', command: '!trivia' },
      { title: 'Sticker Maker', description: 'Fans can create stickers from your content. Memes spread your brand.', command: '!sticker' },
      { title: 'Music Sharing', description: 'Share your tracks or any music directly in the group.', command: '!music' },
      { title: 'Media Downloads', description: 'Download TikTok, YouTube, and Instagram content for your fans.', command: '!download' },
      { title: 'AI FAQ Bot', description: 'Let the AI answer fan questions about your schedule, releases, and collabs.', command: '!ai' },
    ],
    ctaText: 'Set up BotWave for your community',
  },
  {
    slug: 'churches',
    title: 'BotWave for Churches',
    headline: 'Keep your church WhatsApp group organized',
    description: 'Church groups need order, not chaos. BotWave helps pastors and admins keep groups focused, share announcements, and engage members respectfully.',
    seoTitle: 'WhatsApp Bot for Churches - Group Management | BotWave',
    seoDescription: 'Manage church WhatsApp groups with automated welcome messages, announcements, moderation, and devotional content. Free.',
    seoKeywords: ['whatsapp bot for churches', 'church group management', 'church whatsapp bot', 'religious group bot'],
    painPoints: [
      'Members sharing irrelevant content in church groups',
      'New members not knowing the group purpose and rules',
      'Important announcements from pastors getting buried',
      'Managing multiple units and departments on WhatsApp',
      'Late-night messages disturbing members',
    ],
    solutions: [
      { title: 'Welcome Messages', description: 'Greet new members with the group purpose and rules. Set the right tone from the start.', command: '!welcome' },
      { title: 'Announcements', description: 'Tag all members for service updates, prayer meetings, and events.', command: '!tagall' },
      { title: 'Moderation', description: 'Gentle warning system for off-topic posts. Keep discussions respectful.', command: '!warn' },
      { title: 'Polls', description: 'Vote on event dates, program choices, and group decisions.', command: '!poll' },
      { title: 'AI Assistance', description: 'Members can ask questions about service times, locations, and programs.', command: '!ai' },
      { title: 'Group Digest', description: 'Get a summary of what was discussed for members who missed the conversation.', command: '!digest' },
    ],
    ctaText: 'Set up BotWave for your church',
  },
  {
    slug: 'crypto',
    title: 'BotWave for Crypto Communities',
    headline: 'Protect your crypto group from scammers',
    description: 'Crypto WhatsApp and Telegram groups are spam magnets. BotWave locks them down with anti-scam protection, moderation, and engagement tools.',
    seoTitle: 'WhatsApp & Telegram Bot for Crypto Groups | BotWave',
    seoDescription: 'Protect crypto community groups from scammers and spam. Anti-flood, global bans, CAPTCHA verification. Free for WhatsApp and Telegram.',
    seoKeywords: ['crypto group bot', 'whatsapp crypto bot', 'telegram crypto group management', 'anti scam bot crypto'],
    painPoints: [
      'Scammers joining and sending fake investment links',
      'Impersonators pretending to be admins',
      'Spam bots flooding the group',
      'Managing bans across multiple community groups',
      'New members falling for scam messages before admins can delete them',
    ],
    solutions: [
      { title: 'Anti-Flood', description: 'Auto-mute users who spam messages rapidly. Stops flood attacks instantly.', command: '!antidelete' },
      { title: 'CAPTCHA (Telegram)', description: 'New members must pass a challenge to post. Blocks automated bots.', command: '/captcha' },
      { title: 'Global Bans', description: 'Ban a scammer once, banned in ALL your groups. One command.', command: '.gban' },
      { title: 'Federation (Telegram)', description: 'Link multiple groups together. Share ban lists across your network.', command: '/federation' },
      { title: 'Blacklist', description: 'Auto-delete messages containing known scam keywords.', command: '/blacklist' },
      { title: 'PM Permit (Userbot)', description: 'Block unknown DMs to prevent scammers from messaging you directly.', command: '.pmpermit' },
    ],
    ctaText: 'Protect your crypto community',
  },
  {
    slug: 'vendors',
    title: 'BotWave for Online Vendors',
    headline: 'Turn your WhatsApp into a storefront',
    description: 'Nigerian vendors use WhatsApp for everything: listing products, taking orders, customer support. BotWave automates the repetitive parts so you can sell more.',
    seoTitle: 'WhatsApp Bot for Vendors - Auto-Reply & Order Management | BotWave',
    seoDescription: 'Automate your WhatsApp vendor business. Auto-reply to customer inquiries, manage groups, share product media. Free for Nigerian vendors.',
    seoKeywords: ['whatsapp bot for vendors', 'online vendor bot', 'whatsapp selling bot', 'nigerian vendor whatsapp bot'],
    painPoints: [
      'Answering "How much?" hundreds of times a day',
      'Missing customer messages while packaging orders',
      'No way to broadcast new product arrivals to all customers',
      'Customers deleting payment proof after sending',
      'Managing different customer groups for different products',
    ],
    solutions: [
      { title: 'AI Price Bot', description: 'AI answers common questions like pricing, sizes, availability, and location automatically.', command: '!ai' },
      { title: 'AFK Auto-Reply', description: 'Set "packing orders, will reply soon" messages. Customers know you are busy, not ignoring them.', command: '!afk' },
      { title: 'Broadcast', description: 'New arrivals? Restocks? Flash sales? Tag all members in your customer group.', command: '!tagall' },
      { title: 'Anti-Delete', description: 'Catch payment screenshots that get deleted. No more "I already paid" disputes.', command: '!antidelete' },
      { title: 'Receipt Scanning', description: 'Customer sends payment receipt, bot extracts amount and details automatically.', command: '!scan' },
      { title: 'Logo Maker', description: 'Create quick branding and product labels right in WhatsApp.', command: '!logo' },
    ],
    ctaText: 'Automate your vendor WhatsApp',
  },
  {
    slug: 'customer-support',
    title: 'BotWave for Customer Support',
    headline: 'Automate WhatsApp customer support without hiring',
    description: 'Small teams cannot answer every WhatsApp message manually. BotWave handles FAQs, sends auto-replies when you are away, and keeps support groups organized.',
    seoTitle: 'WhatsApp Bot for Customer Support - Auto-Reply and FAQ | BotWave',
    seoDescription: 'Automate WhatsApp customer support. AI FAQ bot, auto-replies, group management. Handle support without hiring more staff.',
    seoKeywords: ['whatsapp customer support bot', 'whatsapp faq bot', 'auto reply customer support', 'whatsapp support automation'],
    painPoints: [
      'Answering the same questions from different customers every day',
      'Customers messaging at 2am expecting instant replies',
      'Support conversations getting mixed up in busy groups',
      'No record of what was asked and answered',
      'Hiring dedicated support staff is too expensive',
    ],
    solutions: [
      { title: 'AI FAQ Responses', description: 'AI learns from your business context and answers common customer questions automatically.', command: '!ai' },
      { title: 'AFK Auto-Reply', description: 'Set custom away messages outside business hours. Customers know when to expect a reply.', command: '!afk' },
      { title: 'Welcome Messages', description: 'New customers get a greeting with your service menu, hours, and contact options.', command: '!welcome' },
      { title: 'Anti-Spam', description: 'Block spam in customer groups. Keep conversations focused and professional.', command: '!antidelete' },
      { title: 'Announcements', description: 'Broadcast service updates, new offerings, or important notices to all customers at once.', command: '!tagall' },
      { title: 'Translation', description: 'Serve customers in different languages. Auto-translate messages.', command: '!translate' },
    ],
    ctaText: 'Set up BotWave for customer support',
  },
  {
    slug: 'gaming-groups',
    title: 'BotWave for Gaming Groups',
    headline: 'Run your gaming community on WhatsApp or Telegram',
    description: 'Gaming groups need leaderboards, matchmaking coordination, and engagement between sessions. BotWave brings trivia, games, XP tracking, and moderation to your gaming community.',
    seoTitle: 'WhatsApp & Telegram Bot for Gaming Groups | BotWave',
    seoDescription: 'Manage gaming communities on WhatsApp and Telegram. Trivia, leaderboards, XP tracking, team coordination. Free gaming bot.',
    seoKeywords: ['gaming group bot', 'whatsapp gaming bot', 'telegram gaming bot', 'gaming community management'],
    painPoints: [
      'No engagement between game sessions',
      'Coordinating match times across time zones',
      'Toxic members ruining the vibe',
      'No way to track who is the best player',
      'Spam from non-gamers in the group',
    ],
    solutions: [
      { title: 'Trivia Games', description: 'Play trivia between sessions. Gaming, anime, tech, and custom categories.', command: '!trivia' },
      { title: 'Leaderboards', description: 'Track XP and see who tops the group. Competitive motivation.', command: '!leaderboard' },
      { title: 'Polls', description: 'Vote on game times, which game to play next, tournament brackets.', command: '!poll' },
      { title: 'Word Games', description: 'Hangman, word chain, and other quick games for between matches.', command: '!hangman' },
      { title: 'Moderation', description: 'Warning system for toxic behavior. Fair rules enforcement.', command: '!warn' },
      { title: 'Sticker Maker', description: 'Turn memes and highlights into custom stickers for the group.', command: '!sticker' },
    ],
    ctaText: 'Set up BotWave for your gaming group',
  },
  {
    slug: 'study-groups',
    title: 'BotWave for Study Groups',
    headline: 'Turn your study group into a focused learning machine',
    description: 'Study groups work best when distractions are low and resources are shared. BotWave helps with AI tutoring, quiz practice, note sharing, and keeping conversations on topic.',
    seoTitle: 'WhatsApp Bot for Study Groups - AI Tutor and Quiz | BotWave',
    seoDescription: 'Manage study groups on WhatsApp. AI tutoring, quiz practice, note sharing, anti-spam. Keep study sessions productive.',
    seoKeywords: ['study group bot', 'whatsapp study bot', 'ai tutor whatsapp', 'study group management'],
    painPoints: [
      'Group members posting memes instead of studying',
      'Hard to quiz each other before exams',
      'Important notes and resources getting buried in chat',
      'No way to summarize long discussion threads',
      'Members asking questions that were already answered',
    ],
    solutions: [
      { title: 'AI Tutor', description: 'Ask the AI any study question. Explanations, examples, and definitions on demand.', command: '!ai' },
      { title: 'Trivia Quiz', description: 'Run quiz sessions on any topic. Great for exam prep and revision.', command: '!trivia' },
      { title: 'Anti-Spam', description: 'Keep the group focused. Auto-warn off-topic posters during study hours.', command: '!antidelete' },
      { title: 'Define Words', description: 'Quick dictionary lookup for terms and definitions.', command: '!define' },
      { title: 'Translation', description: 'Translate study material or explanations between languages.', command: '!translate' },
      { title: 'Document Creation', description: 'Create formatted study notes and share as Word documents.', command: '!doc' },
    ],
    ctaText: 'Set up BotWave for your study group',
  },
  {
    slug: 'delivery-services',
    title: 'BotWave for Delivery Services',
    headline: 'Manage delivery orders and riders on WhatsApp',
    description: 'Delivery services in Nigeria and across Africa run on WhatsApp. BotWave helps manage rider groups, automate order confirmations, and keep customer communication professional.',
    seoTitle: 'WhatsApp Bot for Delivery Services - Order Automation | BotWave',
    seoDescription: 'Automate delivery service communication on WhatsApp. Rider coordination, order updates, customer auto-replies. Free automation.',
    seoKeywords: ['delivery service whatsapp bot', 'rider group bot', 'delivery automation whatsapp', 'dispatch bot whatsapp'],
    painPoints: [
      'Coordinating multiple riders in a single group',
      'Customers asking "where is my order" constantly',
      'No organized way to confirm pickups and deliveries',
      'Spam and off-topic messages in rider groups',
      'Managing different zones and routes',
    ],
    solutions: [
      { title: 'AI Auto-Reply', description: 'Handle common customer questions about delivery times, coverage areas, and pricing automatically.', command: '!ai' },
      { title: 'AFK Status', description: 'Set your availability. Let customers know when you are offline or between deliveries.', command: '!afk' },
      { title: 'Broadcasts', description: 'Send route updates, new policies, or zone changes to all riders at once.', command: '!tagall' },
      { title: 'Anti-Spam', description: 'Keep rider groups professional. No spam, no irrelevant content.', command: '!antidelete' },
      { title: 'Polls', description: 'Vote on shift preferences, route assignments, and scheduling.', command: '!poll' },
      { title: 'Welcome Messages', description: 'New riders get onboarding info, rules, and zone assignments automatically.', command: '!welcome' },
    ],
    ctaText: 'Set up BotWave for your delivery service',
  },
];

export function getUseCaseBySlug(slug: string): UseCase | undefined {
  return useCases.find(u => u.slug === slug);
}
