/**
 * HYPOTHALAMO-PITUITARY CONNECTION — Pre-loaded Study Material
 * Source: Hypothalamo-Pituitary Connection PPT (34 slides)
 */

export const hypothalamoPituitaryMaterial = {
  title: 'Hypothalamo-Pituitary Connection',
  fileType: 'ppt',
  wordCount: 2800,
  status: 'analyzed' as const,

  summary: {
    definitions: [
      { term: 'Hypothalamus', definition: 'Bilateral diencephalic structure situated below the thalamus (~2.5cm long, ~4g). Master co-ordinator of hormonal action and the most important organ for homeostatic control of the internal environment. Provides the link between the endocrine and nervous systems.' },
      { term: 'Hypothalamo-Pituitary Unit', definition: 'The most dominant portion of the entire endocrine system. Regulates thyroid, adrenal, and reproductive glands; controls somatic growth, lactation, milk secretion, and water metabolism.' },
      { term: 'Hypothalamo-Hypophyseal Portal System', definition: 'Vascular connection between hypothalamus and anterior pituitary. Almost ALL blood supplied to the anterior pituitary must first drain through this portal system, allowing minute amounts of hypothalamic hormones to achieve biologically effective concentrations.' },
      { term: 'Hypothalamo-Hypophyseal Neural Tract', definition: 'Axons of large neurosecretory cells from the supraoptic and paraventricular nuclei that pass to the neurohypophysis through the infundibular stem, forming dilated terminals called Herring bodies.' },
      { term: 'Herring Bodies', definition: 'Dilated nerve terminals in the neurohypophysis (posterior pituitary) that store ADH and Oxytocin. Formed by the axonal endings of neurosecretory cells from the supraoptic and paraventricular nuclei.' },
      { term: 'CRH (Corticotropin-Releasing Hormone)', definition: '41 amino acid peptide from the parvocellular region of paraventricular nuclei. Induces ACTH and beta-endorphin release from anterior pituitary. Half-life: 60 min.' },
      { term: 'TRH (Thyrotropin-Releasing Hormone)', definition: '3 amino acid peptide from paraventricular nuclei and preoptic area. Induces TSH and Prolactin release from the pituitary. Initiates the thyroid response pathway.' },
      { term: 'GHRH (Growth Hormone-Releasing Hormone)', definition: '44 amino acid peptide (also called somatocrinin) from arcuate nuclei and ventromedial nuclei. Induces GH release from anterior pituitary. Half-life: 50 min.' },
      { term: 'Somatostatin (SST)', definition: '14 amino acid peptide from anterior periventricular region. AKA Growth Hormone Release-Inhibiting Hormone. Inhibits GH and TSH secretion. Also secreted from CNS, gut, and pancreas. Inhibits glucagon, gastrin, insulin, and secretin.' },
      { term: 'GnRH (Gonadotropin-Releasing Hormone)', definition: '10 amino acid peptide from preoptic area and suprachiasmatic nucleus. Induces FSH and LH release from anterior pituitary. Released in pulsatile fashion. Receptors also found in ovary and uterus.' },
      { term: 'GnIH (Gonadotropin-Inhibiting Hormone)', definition: 'Produced by the paraventricular nuclei. Inhibits LH release. GnIH-secreting neurons are found outside hypothalamus. Release influenced by stress, developmental state, and photoperiod.' },
      { term: 'Dopamine (as PIH)', definition: 'Found in hypophysial portal system, released from arcuate nuclei. Acts as Prolactin-Release-Inhibiting Factor (PIF). Also functions as a neurotransmitter. Without dopamine, prolactin would be continuously released.' },
      { term: 'Prolactin', definition: 'Polypeptide with 199 amino acids. Promotes milk secretion after oestrogen and progesterone priming. Inhibits gonadotropins peripherally. Secretion increased by sleep, nursing, breast stimulation, stress, hypoglycaemia, exercise, sexual intercourse. Decreased by L-Dopa, bromocriptine, PIH.' },
      { term: 'TSH (Thyroid-Stimulating Hormone)', definition: 'Glycoprotein (also called thyrotropin). Stimulates thyroid gland to make and release T₄ and T₃. Released when TRH from hypothalamus detects low thyroid hormone levels. Inhibited by negative feedback.' },
      { term: 'ACTH (Adrenocorticotropic Hormone)', definition: 'Polypeptide with 39 amino acids. Targets adrenal cortex. Stimulates release of corticosteroid hormones (mainly cortisol) for stress response. Stimulated by CRH from hypothalamus.' },
      { term: 'ADH (Antidiuretic Hormone / Vasopressin)', definition: 'Nanopeptide (9 amino acids) from supraoptic nuclei. Targets: kidneys (increases water reabsorption), blood vessels (contraction at high concentration), liver (glycogenolysis), brain (improves memory). Stimulus: dehydration. Inhibited by hydration and alcohol.' },
      { term: 'Oxytocin', definition: 'Nanopeptide (9 amino acids) from paraventricular nuclei. Functions: uterine contractions during labour, milk ejection (lactation), emotional bonding. Stimulus: positive feedback via stretch receptors in vagina and touch receptors around nipple.' },
      { term: 'Kallmann Syndrome', definition: 'Olfactory-genital dysplasia caused by GnRH deficiency. A hypothalamic disorder resulting from defective GnRH neuron migration.' },
      { term: 'Short-Loop Feedback', definition: 'Anterior pituitary hormone feeds back to the hypothalamus to inhibit its own releasing hormone.' },
      { term: 'Long-Loop Feedback', definition: 'Target gland hormone feeds back to both the hypothalamus and anterior pituitary to inhibit the releasing and stimulating hormones respectively.' },
      { term: 'Ultra-Short (Auto) Feedback', definition: 'A hypothalamic hormone feeds back on the hypothalamus itself to regulate its own secretion.' },
    ],

    keyPoints: [
      'The hypothalamus is the master co-ordinator of hormonal action and the final common pathway for signals to reach the pituitary.',
      'The hypothalamus includes: optic chiasma, tuber cinereum, infundibulum, and mammillary bodies. In humans: ~2.5cm long, ~4g.',
      'All hypothalamic hormone products are protein hormones. They are secreted rhythmically.',
      'The hypothalamus is regulated by: internal hormonal signals AND neural inputs from other sources (many from outside the organism).',
      'The hypothalamus is involved in non-endocrine functions such as food intake (indirectly impacts GH secretion).',
      'KEY ANATOMY: Connection to ANTERIOR pituitary is VASCULAR (hypothalamo-hypophyseal portal system). Connection to POSTERIOR pituitary is NEURAL (hypothalamo-hypophyseal neural tract).',
      'KEY PHYSIOLOGY: Hypothalamic hormones REGULATE anterior pituitary secretion. The posterior pituitary is merely a STORAGE site for hypothalamic hormones (ADH, Oxytocin).',
      'Advantage of portal system: minute amounts of hypothalamic hormones can achieve biologically effective concentrations in pituitary blood because blood must first drain through the portal system.',
      'Major hypothalamic hormones: CRH, GnRH, GHRH, Somatostatin (GHIH), PIH (Dopamine), TRH, Prolactin Releasing Factor, GnIH.',
      'TRH (3 aa) → releases TSH AND Prolactin from pituitary.',
      'Somatostatin (14 aa) → inhibits GH AND TSH. Also inhibits glucagon, gastrin, insulin, secretin. Secreted from CNS, gut, AND pancreas.',
      'GHRH (44 aa, somatocrinin) → releases GH. From arcuate and ventromedial nuclei. Half-life: 50 min.',
      'GnRH (10 aa) → releases FSH AND LH. Pulsatile release. Receptors also in ovary and uterus.',
      'CRH (41 aa) → releases ACTH AND beta-endorphin. From parvocellular paraventricular nuclei. Half-life: 60 min.',
      'Dopamine → inhibits prolactin (PIF). From arcuate nuclei. Without dopamine inhibition, prolactin is continuously released.',
      'GnIH → inhibits LH. From paraventricular nuclei. Influenced by stress, developmental state, photoperiod.',
      'Feedback mechanisms: Long-loop (target gland → hypothalamus/pituitary), Short-loop (pituitary → hypothalamus), Auto/Ultra-short (hypothalamic hormone → hypothalamus itself).',
      'Posterior pituitary hormones: Oxytocin (from paraventricular nuclei) and ADH/Vasopressin (from supraoptic nuclei). Both are nanopeptides (9 amino acids) with identical structure.',
      'ADH targets: kidneys (water reabsorption), blood vessels (contraction), liver (glycogenolysis), brain (memory). Stimulus: dehydration. Inhibited by alcohol and hydration.',
      'Oxytocin targets: uterus (labour contractions), breast (milk ejection), emotional bonding. Stimulus: positive feedback from vaginal stretch receptors and nipple touch receptors.',
      'Anterior Pituitary hormones: Prolactin (199 aa), LH, FSH (glycoproteins with same alpha subunit as TSH and hCG), TSH, ACTH (39 aa), GH (191 aa).',
      'FSH half-life = 3-4 hours. LH half-life = 50 minutes.',
      'FSH in ovaries: stimulates granulosa cell growth, controls oestrogen formation. LH in ovaries: stimulates theca cells to produce androgens.',
      'FSH in testes (with testosterone): stimulates Sertoli cells for sperm production. LH in testes: controls testosterone production in Leydig cells.',
      'Both LH and FSH are inhibited by sex steroids. In males: testosterone and inhibin. In females: oestrogen and progesterone.',
      'Hypothalamic disorders can be caused by: tumours, trauma, infections, congenital deformations, genetic defects, and vascular alterations.',
      'Hypothalamic hypothyroidism = TRH deficient. Kallmann syndrome = GnRH deficient (olfactory-genital dysplasia).',
    ],

    examHighlights: [
      'Connection to anterior pituitary = VASCULAR (portal system). Connection to posterior pituitary = NEURAL (tract). This is a TOP exam question.',
      'Posterior pituitary = STORAGE site only. It does NOT synthesise hormones. ADH and Oxytocin are made in HYPOTHALAMUS.',
      'Dopamine INHIBITS prolactin. Without dopamine, prolactin is continuously released. Important for understanding prolactinomas and dopamine agonist treatment (bromocriptine).',
      'Somatostatin inhibits BOTH GH and TSH. Also inhibits pancreatic and gut hormones (glucagon, gastrin, insulin, secretin). Produced in hypothalamus, CNS, gut, and pancreas.',
      'TRH releases BOTH TSH and Prolactin — not just TSH. This explains why hypothyroidism can cause hyperprolactinaemia.',
      'GnRH release is PULSATILE — continuous GnRH actually suppresses FSH/LH (used therapeutically as GnRH agonists).',
      'FSH and LH share the same alpha subunit with TSH and hCG — important for cross-reactivity in pregnancy tests.',
      'ADH from SUPRAOPTIC nuclei. Oxytocin from PARAVENTRICULAR nuclei. Don\'t reverse these.',
      'ADH is inhibited by ALCOHOL — explains why alcohol causes diuresis.',
      'Oxytocin uses POSITIVE feedback (only example along with LH surge). All other hormone regulation uses negative feedback.',
      'Prolactin is the ONLY anterior pituitary hormone under tonic INHIBITION (by dopamine). All others are under stimulatory control.',
    ],

    clinicalCorrelations: [
      'Prolactinoma: Pituitary tumour secreting excess prolactin. Treated with dopamine agonists (bromocriptine, cabergoline) because dopamine inhibits prolactin.',
      'Kallmann syndrome: GnRH deficiency causing hypogonadism + anosmia. Treat with pulsatile GnRH or gonadotropin replacement.',
      'Diabetes Insipidus (Central): ADH deficiency → kidneys cannot reabsorb water → massive polyuria and polydipsia. Treat with desmopressin (ADH analogue).',
      'SIADH (Syndrome of Inappropriate ADH): Excess ADH → water retention → hyponatremia. Causes include lung cancer, CNS disorders, drugs.',
      'Hypothalamic hypothyroidism: TRH deficiency → low TSH → low T₃/T₄. Distinguished from primary hypothyroidism by low (not elevated) TSH.',
      'Pituitary stalk transection: Removes dopamine inhibition → prolactin RISES (because it\'s the only hormone under tonic inhibition). All other anterior pituitary hormones FALL.',
      'GnRH agonist therapy: Continuous (non-pulsatile) GnRH administration paradoxically SUPPRESSES LH/FSH — used to treat prostate cancer, endometriosis, precocious puberty.',
      'Acromegaly (adults) / Gigantism (children): Excess GH, usually from pituitary adenoma. Treated with somatostatin analogues (octreotide) which inhibit GH.',
      'Alcohol and ADH: Alcohol inhibits ADH release → increased urine output (diuresis) → dehydration → hangover.',
    ],

    processes: [
      {
        name: 'Hypothalamo-Anterior Pituitary Axis (Vascular)',
        steps: [
          'Hypothalamic nuclei synthesise releasing/inhibiting hormones',
          'Hormones secreted into the primary capillary plexus in the median eminence',
          'Blood carrying hormones travels down portal veins in the pituitary stalk',
          'Arrives at secondary capillary plexus in the anterior pituitary',
          'Releasing hormones bind to anterior pituitary cells and stimulate/inhibit hormone secretion',
          'Anterior pituitary hormones enter systemic circulation to reach target organs',
        ],
      },
      {
        name: 'Hypothalamo-Posterior Pituitary Axis (Neural)',
        steps: [
          'Large neurosecretory cells in supraoptic (ADH) and paraventricular (Oxytocin) nuclei synthesise hormones',
          'Hormones packaged in neurosecretory granules within the cell body',
          'Granules travel down the axons via axoplasmic transport through the infundibular stem',
          'Granules stored in dilated axon terminals (Herring bodies) in the neurohypophysis',
          'Nerve impulse reaches the terminal → exocytosis releases stored hormones into blood',
        ],
      },
      {
        name: 'Feedback Regulation Loops',
        steps: [
          'Long-loop: Target gland hormone (e.g., cortisol) feeds back to BOTH hypothalamus and anterior pituitary to reduce CRH and ACTH respectively',
          'Short-loop: Anterior pituitary hormone (e.g., ACTH) feeds back to hypothalamus to reduce CRH',
          'Ultra-short/Auto feedback: Hypothalamic hormone feeds back on the hypothalamus itself to regulate its own secretion',
          'Net result: Tight regulation of hormone levels preventing oversecretion or undersecretion',
        ],
      },
    ],

    mnemonics: [
      { topic: 'Posterior Pituitary Hormones — Which Nucleus?', mnemonic: 'SO sweet (ADH) and PVN loving (Oxytocin)', explanation: 'SupraOptic → ADH (Vasopressin). ParaVentricular Nuclei → Oxytocin. SO = supraoptic. PVN = paraventricular.' },
      { topic: 'Hypothalamic Releasing Hormones', mnemonic: 'Go Create The Great Pies Surely', explanation: 'GnRH, CRH, TRH, GHRH, Prolactin Releasing Factor, Somatostatin — the major hypothalamic hormones.' },
      { topic: 'Connection Type', mnemonic: 'Anterior = Artery (Vascular), Posterior = Post (Neural)', explanation: 'Anterior pituitary connection to hypothalamus is vascular (portal system). Posterior pituitary connection is neural (nerve tract).' },
      { topic: 'Dopamine\'s Role', mnemonic: 'Dopamine Dams Prolactin', explanation: 'Dopamine inhibits (dams) prolactin release. Remove the dam (dopamine) and prolactin floods out.' },
    ],

    quickReview: [
      'Hypothalamus → Anterior pituitary: VASCULAR (portal system). Hypothalamus → Posterior pituitary: NEURAL (tract with Herring bodies).',
      'Anterior pituitary: regulated by hypothalamic hormones. Posterior pituitary: just a STORE for hypothalamic hormones (ADH, Oxytocin).',
      'ADH from supraoptic nuclei (kidneys, water reabsorption, inhibited by alcohol). Oxytocin from paraventricular nuclei (labour, lactation, positive feedback).',
      'Prolactin is the ONLY hormone under tonic INHIBITION (by dopamine). TRH stimulates both TSH AND prolactin.',
      'Feedback: Long-loop (target gland → hypothalamus/pituitary), Short-loop (pituitary → hypothalamus), Auto (hypothalamus → itself).',
    ],
  },

  questions: [
    // LIKELIHOOD / MOST LIKELY / LEAST LIKELY
    { questionType: 'mcq', question: 'A patient has a pituitary stalk transection. Which hormone level is MOST LIKELY to INCREASE?', options: ['A) GH', 'B) TSH', 'C) Prolactin', 'D) ACTH'], correctAnswer: 'C) Prolactin', explanation: 'Prolactin is the ONLY anterior pituitary hormone under tonic INHIBITION by dopamine. Cutting the stalk removes dopamine delivery → prolactin rises. All other anterior pituitary hormones (under stimulatory control) would decrease.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which connection type MOST LIKELY describes the hypothalamus-anterior pituitary relationship?', options: ['A) Neural connection via nerve tract', 'B) Vascular connection via portal system', 'C) Direct cell-to-cell contact', 'D) Lymphatic drainage'], correctAnswer: 'B) Vascular connection via portal system', explanation: 'The hypothalamus connects to the anterior pituitary via the hypothalamo-hypophyseal PORTAL SYSTEM (vascular). The posterior pituitary connection is neural.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'A patient presents with polyuria and polydipsia that improves with desmopressin administration. The MOST LIKELY diagnosis is:', options: ['A) Diabetes Mellitus Type 2', 'B) Central Diabetes Insipidus', 'C) Nephrogenic Diabetes Insipidus', 'D) Primary polydipsia'], correctAnswer: 'B) Central Diabetes Insipidus', explanation: 'Central DI is caused by ADH deficiency. Desmopressin (synthetic ADH) replaces the missing hormone and reduces polyuria. In nephrogenic DI, the kidneys resist ADH so desmopressin would NOT work.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which hormone is MOST LIKELY to be elevated in a patient with ectopic ACTH syndrome?', options: ['A) TSH', 'B) Cortisol', 'C) Prolactin', 'D) ADH'], correctAnswer: 'B) Cortisol', explanation: 'Ectopic ACTH (e.g., from small cell lung cancer) stimulates the adrenal cortex to produce excess cortisol. This causes Cushing\'s syndrome.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A male patient has hypogonadism and anosmia. The MOST LIKELY deficient hypothalamic hormone is:', options: ['A) CRH', 'B) TRH', 'C) GnRH', 'D) GHRH'], correctAnswer: 'C) GnRH', explanation: 'Kallmann syndrome = GnRH deficiency causing hypogonadism + anosmia (olfactory-genital dysplasia). GnRH neurons fail to migrate from the olfactory placode.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Continuous (non-pulsatile) GnRH administration MOST LIKELY results in:', options: ['A) Increased FSH and LH', 'B) Decreased FSH and LH', 'C) Increased prolactin', 'D) No change'], correctAnswer: 'B) Decreased FSH and LH', explanation: 'GnRH is normally released in a PULSATILE fashion. Continuous non-pulsatile administration paradoxically DOWN-REGULATES GnRH receptors and SUPPRESSES FSH/LH. This is used therapeutically in prostate cancer and endometriosis.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which substance MOST LIKELY causes increased urine output after alcohol consumption?', options: ['A) Increased ADH release', 'B) Inhibition of ADH release', 'C) Increased aldosterone', 'D) Direct renal vasodilation'], correctAnswer: 'B) Inhibition of ADH release', explanation: 'Alcohol inhibits ADH (vasopressin) release from the posterior pituitary. Without ADH, kidneys cannot reabsorb water, leading to diuresis (increased urine output) and dehydration.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'A patient with hypothyroidism due to hypothalamic disease would MOST LIKELY have:', options: ['A) High TSH, low T₄', 'B) Low TSH, low T₄', 'C) High TSH, high T₄', 'D) Normal TSH, low T₄'], correctAnswer: 'B) Low TSH, low T₄', explanation: 'Hypothalamic hypothyroidism means TRH deficiency → no stimulation of anterior pituitary → low TSH → low thyroid hormones. In PRIMARY hypothyroidism, TSH would be HIGH (negative feedback).', difficulty: 'hard' },

    // STANDARD MCQs
    { questionType: 'mcq', question: 'The hypothalamus is located:', options: ['A) Above the thalamus', 'B) Below the thalamus', 'C) Lateral to the thalamus', 'D) Behind the thalamus'], correctAnswer: 'B) Below the thalamus', explanation: 'The hypothalamus (hypo = below) is a bilateral diencephalic structure situated BELOW the thalamus.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which of the following is NOT a hypothalamic hormone?', options: ['A) TRH', 'B) GnRH', 'C) Insulin', 'D) CRH'], correctAnswer: 'C) Insulin', explanation: 'Insulin is produced by the beta cells of the pancreas, not the hypothalamus. TRH, GnRH, CRH, GHRH, Somatostatin, and Dopamine are all hypothalamic hormones.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Somatostatin inhibits all of the following EXCEPT:', options: ['A) Growth Hormone', 'B) TSH', 'C) Insulin', 'D) Prolactin'], correctAnswer: 'D) Prolactin', explanation: 'Somatostatin inhibits GH, TSH, glucagon, gastrin, insulin, and secretin. It does NOT inhibit prolactin — prolactin is inhibited by dopamine.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Herring bodies are found in the:', options: ['A) Hypothalamus', 'B) Anterior pituitary', 'C) Posterior pituitary (neurohypophysis)', 'D) Pineal gland'], correctAnswer: 'C) Posterior pituitary (neurohypophysis)', explanation: 'Herring bodies are dilated nerve terminals in the neurohypophysis (posterior pituitary) where ADH and Oxytocin are stored before release.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'How many amino acids does GnRH contain?', options: ['A) 3', 'B) 10', 'C) 41', 'D) 44'], correctAnswer: 'B) 10', explanation: 'GnRH = 10 amino acids. For reference: TRH = 3 aa, Somatostatin = 14 aa, ACTH = 39 aa, CRH = 41 aa, GHRH = 44 aa, GH = 191 aa, Prolactin = 199 aa.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'LH and FSH share the same alpha subunit with:', options: ['A) GH and Prolactin', 'B) TSH and hCG', 'C) ACTH and ADH', 'D) Insulin and Glucagon'], correctAnswer: 'B) TSH and hCG', explanation: 'FSH, LH, TSH, and hCG are all glycoproteins that share the same alpha subunit. They differ in their beta subunits, which confer biological specificity.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The half-life of FSH is approximately:', options: ['A) 50 minutes', 'B) 60 minutes', 'C) 3-4 hours', 'D) 24 hours'], correctAnswer: 'C) 3-4 hours', explanation: 'FSH has a half-life of 3-4 hours. LH has a much shorter half-life of approximately 50 minutes. This difference affects the pattern of their action.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'ADH (Vasopressin) is produced in which hypothalamic nucleus?', options: ['A) Arcuate nucleus', 'B) Paraventricular nucleus', 'C) Supraoptic nucleus', 'D) Ventromedial nucleus'], correctAnswer: 'C) Supraoptic nucleus', explanation: 'ADH is produced in the supraoptic nuclei and Oxytocin in the paraventricular nuclei of the hypothalamus. Both are transported to and stored in the posterior pituitary.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'In the testes, LH acts on:', options: ['A) Sertoli cells', 'B) Leydig cells', 'C) Spermatogonia', 'D) Seminiferous tubules'], correctAnswer: 'B) Leydig cells', explanation: 'LH controls testosterone production in the Leydig cells (interstitial cells) of the testes. FSH (together with testosterone) stimulates the Sertoli cells for sperm production.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'FSH in the ovaries primarily stimulates:', options: ['A) Theca cells to produce androgens', 'B) Granulosa cells and oestrogen formation', 'C) Corpus luteum to produce progesterone', 'D) Ovulation'], correctAnswer: 'B) Granulosa cells and oestrogen formation', explanation: 'FSH stimulates the growth of granulosa cells in ovarian follicles and controls oestrogen formation. LH stimulates ovarian theca cells to produce androgens.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which hypothalamic hormone has the longest half-life?', options: ['A) TRH', 'B) GHRH (50 min)', 'C) CRH (60 min)', 'D) Dopamine'], correctAnswer: 'C) CRH (60 min)', explanation: 'CRH has a half-life of 60 minutes. GHRH has a half-life of 50 minutes. Most other hypothalamic hormones have shorter half-lives.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Prolactin secretion is increased by all of the following EXCEPT:', options: ['A) Sleep', 'B) Bromocriptine', 'C) Breast stimulation', 'D) Stress'], correctAnswer: 'B) Bromocriptine', explanation: 'Bromocriptine is a dopamine agonist that INHIBITS prolactin secretion. It is used to treat prolactinomas. Sleep, nursing/breast stimulation, stress, hypoglycaemia, and exercise all increase prolactin.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The advantage of the portal system is:', options: ['A) Hormones bypass the liver', 'B) Minute amounts of hormones achieve effective concentrations', 'C) Blood flows faster', 'D) Hormones are stored longer'], correctAnswer: 'B) Minute amounts of hormones achieve effective concentrations', explanation: 'Almost all blood supplied to the anterior pituitary drains through the portal system. This means hypothalamic releasing/inhibiting hormones are concentrated directly at the pituitary, so only minute amounts are needed.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'GnIH (Gonadotropin-Inhibiting Hormone) release is influenced by:', options: ['A) Only blood glucose', 'B) Stress, developmental state, and photoperiod', 'C) Only temperature', 'D) Dietary protein intake'], correctAnswer: 'B) Stress, developmental state, and photoperiod', explanation: 'GnIH release is influenced by stress, developmental state, and photoperiod (light exposure). This helps explain seasonal and stress-related reproductive dysfunction.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which hormone is described as a nanopeptide with identical structure to ADH?', options: ['A) Prolactin', 'B) GH', 'C) Oxytocin', 'D) TSH'], correctAnswer: 'C) Oxytocin', explanation: 'Both ADH and Oxytocin are nanopeptides (9 amino acids) with identical structure. They differ by only 2 amino acids and are both produced in the hypothalamus and stored in the posterior pituitary.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'GHRH is also known as:', options: ['A) Somatostatin', 'B) Somatocrinin', 'C) Somatotropin', 'D) Somatomedin'], correctAnswer: 'B) Somatocrinin', explanation: 'GHRH is also called somatocrinin. Somatostatin = GHIH (inhibits GH). Somatotropin = GH itself. Somatomedin = IGF-I (mediates GH effects).', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Testicular inhibin primarily suppresses:', options: ['A) LH', 'B) FSH', 'C) GnRH', 'D) Testosterone'], correctAnswer: 'B) FSH', explanation: 'Testicular inhibin selectively suppresses FSH secretion from the anterior pituitary. LH is primarily suppressed by testosterone. Together, these form the male HPG axis feedback.', difficulty: 'medium' },

    // TRUE/FALSE
    { questionType: 'true_false', question: 'The posterior pituitary synthesises its own hormones. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'The posterior pituitary does NOT synthesise hormones. ADH and Oxytocin are synthesised in the hypothalamus and only STORED and RELEASED from the posterior pituitary.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Hypothalamic hormones are all protein hormones. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'All hypothalamic hormone products are protein/peptide hormones. They range from 3 amino acids (TRH) to 44 amino acids (GHRH).', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Somatostatin is produced only in the hypothalamus. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Somatostatin is produced in the hypothalamus, CNS, gut, AND pancreas (delta cells). It has widespread inhibitory effects on multiple hormones.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'GnRH must be released in a pulsatile fashion to stimulate FSH and LH. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'GnRH must be pulsatile to be effective. Continuous (non-pulsatile) GnRH paradoxically down-regulates receptors and SUPPRESSES FSH/LH.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Alcohol stimulates ADH release. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Alcohol INHIBITS ADH release from the posterior pituitary. This leads to increased water loss (diuresis), dehydration, and contributes to hangovers.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'TRH stimulates the release of both TSH and Prolactin. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'TRH induces release of both TSH and Prolactin from the anterior pituitary. This is why primary hypothyroidism (high TRH) can cause hyperprolactinaemia.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'LH has a longer half-life than FSH. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'FSH has a half-life of 3-4 hours while LH has a much shorter half-life of only 50 minutes. FSH is more stable in circulation.', difficulty: 'medium' },

    // FILL IN THE BLANK
    { questionType: 'fill_blank', question: 'ADH is produced in the _____ nuclei and Oxytocin in the _____ nuclei of the hypothalamus.', options: [], correctAnswer: 'supraoptic; paraventricular', explanation: 'ADH (Vasopressin) is produced in the supraoptic nuclei. Oxytocin is produced in the paraventricular nuclei. Both are transported down axons to the posterior pituitary.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The dilated nerve terminals in the posterior pituitary that store ADH and Oxytocin are called _____.', options: [], correctAnswer: 'Herring bodies', explanation: 'Herring bodies are the dilated nerve terminals (axon endings) in the neurohypophysis where ADH and Oxytocin are stored until release by exocytosis.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'Prolactin is inhibited by _____, which is also known as Prolactin-Release-Inhibiting Factor (PIF).', options: [], correctAnswer: 'Dopamine', explanation: 'Dopamine from the arcuate nuclei of the hypothalamus acts as the Prolactin-Release-Inhibiting Factor. Without dopamine, prolactin would be continuously released.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'GHRH is also called _____ and has a half-life of _____ minutes.', options: [], correctAnswer: 'Somatocrinin; 50', explanation: 'GHRH (Growth Hormone-Releasing Hormone) is also called somatocrinin. It is a 44 amino acid peptide with a half-life of 50 minutes, produced from arcuate and ventromedial nuclei.', difficulty: 'hard' },

    // CLINICAL SCENARIO
    { questionType: 'mcq', question: 'A woman with a pituitary tumour is found to have elevated prolactin levels and galactorrhoea. The BEST initial treatment is:', options: ['A) Surgery', 'B) Bromocriptine (dopamine agonist)', 'C) Radiation therapy', 'D) GnRH antagonist'], correctAnswer: 'B) Bromocriptine (dopamine agonist)', explanation: 'Prolactinomas are treated FIRST with dopamine agonists (bromocriptine, cabergoline) because dopamine is the natural inhibitor of prolactin. Surgery is reserved for drug-resistant cases.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A child with precocious puberty is started on continuous GnRH agonist therapy. The expected effect after 2-4 weeks is:', options: ['A) Further acceleration of puberty', 'B) Suppression of LH and FSH', 'C) Increased growth rate', 'D) Prolactin elevation'], correctAnswer: 'B) Suppression of LH and FSH', explanation: 'Continuous GnRH agonist administration down-regulates GnRH receptors, paradoxically suppressing FSH and LH after an initial brief stimulation. This halts pubertal progression.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A patient with primary hypothyroidism has elevated TSH. Surprisingly, she also has galactorrhoea. This is BEST explained by:', options: ['A) Concurrent prolactinoma', 'B) TRH stimulates both TSH and Prolactin', 'C) Elevated T₄', 'D) GnRH excess'], correctAnswer: 'B) TRH stimulates both TSH and Prolactin', explanation: 'In primary hypothyroidism, low T₄ → elevated TRH (to try to stimulate more TSH). Since TRH stimulates BOTH TSH and Prolactin, hyperprolactinaemia and galactorrhoea can occur.', difficulty: 'hard' },

    // ADDITIONAL MCQs
    { questionType: 'mcq', question: 'The hypothalamo-hypophyseal portal system is a connection between:', options: ['A) Hypothalamus and posterior pituitary', 'B) Hypothalamus and anterior pituitary', 'C) Anterior and posterior pituitary', 'D) Hypothalamus and pineal gland'], correctAnswer: 'B) Hypothalamus and anterior pituitary', explanation: 'The hypothalamo-hypophyseal portal system is the VASCULAR connection between the hypothalamus and the ANTERIOR pituitary. The posterior pituitary has a NEURAL connection.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'All hypothalamic hormones are secreted in which pattern?', options: ['A) Continuous steady release', 'B) Rhythmic/pulsatile secretion', 'C) Only during sleep', 'D) Only during stress'], correctAnswer: 'B) Rhythmic/pulsatile secretion', explanation: 'All hypothalamic hormone products are protein hormones and they are secreted rhythmically/in pulsatile fashion. This pulsatility is especially important for GnRH.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which anterior pituitary hormone is the ONLY one under tonic inhibitory control?', options: ['A) GH', 'B) ACTH', 'C) Prolactin', 'D) TSH'], correctAnswer: 'C) Prolactin', explanation: 'Prolactin is uniquely under tonic INHIBITION by dopamine from the hypothalamus. All other anterior pituitary hormones are primarily under stimulatory control by hypothalamic releasing hormones.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'In SIADH (Syndrome of Inappropriate ADH), the MOST characteristic finding is:', options: ['A) Hypernatraemia', 'B) Hyponatraemia', 'C) Hyperkalaemia', 'D) Polyuria'], correctAnswer: 'B) Hyponatraemia', explanation: 'SIADH causes excess ADH → excess water reabsorption → dilutional hyponatraemia (low sodium). The blood becomes diluted with too much water retained.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which of the following causes of SIADH is MOST commonly tested?', options: ['A) Liver cirrhosis', 'B) Small cell lung cancer', 'C) Diabetes mellitus', 'D) Hyperthyroidism'], correctAnswer: 'B) Small cell lung cancer', explanation: 'Small cell lung cancer is the classic ectopic source of ADH production, causing SIADH. Other causes include CNS disorders, certain drugs, and pulmonary diseases.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The weight of the hypothalamus is approximately:', options: ['A) 0.5g', 'B) 4g', 'C) 20g', 'D) 50g'], correctAnswer: 'B) 4g', explanation: 'The hypothalamus weighs approximately 4 grams and is about 2.5 cm long. Despite its small size, it is the master coordinator of hormonal action.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The median eminence is important because:', options: ['A) It stores oxytocin', 'B) It is where hypothalamic hormones enter the portal capillaries', 'C) It synthesises prolactin', 'D) It filters blood reaching the pituitary'], correctAnswer: 'B) It is where hypothalamic hormones enter the portal capillaries', explanation: 'The median eminence contains the primary capillary plexus where hypothalamic releasing/inhibiting hormones are secreted into the portal blood to be carried to the anterior pituitary.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'CRH stimulates the release of ACTH AND:', options: ['A) TSH', 'B) Prolactin', 'C) Beta-endorphin', 'D) GH'], correctAnswer: 'C) Beta-endorphin', explanation: 'CRH stimulates the release of both ACTH and beta-endorphin from the anterior pituitary. Both are derived from the same precursor molecule (POMC).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which hypothalamic hormone is also found widely in the CNS, gut, and pancreas?', options: ['A) GnRH', 'B) CRH', 'C) Somatostatin', 'D) TRH'], correctAnswer: 'C) Somatostatin', explanation: 'Somatostatin is produced not only in the hypothalamus but also in the CNS, gastrointestinal tract, and pancreas (delta cells). It has widespread inhibitory effects.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The MOST important factor regulating ADH secretion is:', options: ['A) Blood glucose', 'B) Plasma osmolality', 'C) Heart rate', 'D) Body temperature'], correctAnswer: 'B) Plasma osmolality', explanation: 'The primary stimulus for ADH release is increased plasma osmolality (detected by osmoreceptors in the hypothalamus). Dehydration increases osmolality → ADH release → water reabsorption.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Desmopressin (DDAVP) is a synthetic analogue of:', options: ['A) Oxytocin', 'B) ADH (Vasopressin)', 'C) GnRH', 'D) CRH'], correctAnswer: 'B) ADH (Vasopressin)', explanation: 'Desmopressin is a synthetic ADH analogue used to treat central diabetes insipidus (ADH deficiency). It has longer duration of action than natural ADH and minimal vasopressor effects.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'In males, testosterone negatively feeds back to inhibit:', options: ['A) FSH only', 'B) LH only', 'C) Both LH and FSH', 'D) Neither LH nor FSH'], correctAnswer: 'C) Both LH and FSH', explanation: 'Testosterone inhibits both LH (directly at pituitary) and FSH (at pituitary and hypothalamus). However, FSH is ALSO specifically inhibited by inhibin from Sertoli cells.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which anatomical structures are part of the hypothalamus?', options: ['A) Optic chiasma, tuber cinereum, mammillary bodies', 'B) Pineal gland, pons, medulla', 'C) Thalamus, basal ganglia, hippocampus', 'D) Cerebellum, vermis, dentate nucleus'], correctAnswer: 'A) Optic chiasma, tuber cinereum, mammillary bodies', explanation: 'The hypothalamus includes the optic chiasma, tuber cinereum, infundibulum, and mammillary bodies. It is a bilateral diencephalic structure below the thalamus.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A patient who cannot dilute urine despite drinking excess water MOST LIKELY has:', options: ['A) Central diabetes insipidus', 'B) SIADH', 'C) Diabetes mellitus', 'D) Addison disease'], correctAnswer: 'B) SIADH', explanation: 'In SIADH, ADH is inappropriately high, causing the kidneys to constantly reabsorb water. The patient cannot dilute urine normally despite water excess, leading to hyponatraemia.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Nephrogenic diabetes insipidus differs from central DI because:', options: ['A) ADH levels are low', 'B) Kidneys are resistant to ADH', 'C) It responds to desmopressin', 'D) It is caused by pituitary surgery'], correctAnswer: 'B) Kidneys are resistant to ADH', explanation: 'In nephrogenic DI, ADH is produced normally but the kidneys are resistant to its action (receptor or aquaporin defect). Desmopressin does NOT work. Central DI is ADH deficiency.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'The inhibitory hypothalamic hormone for GH release is:', options: ['A) Dopamine', 'B) Somatostatin (GHIH)', 'C) GnIH', 'D) CRH'], correctAnswer: 'B) Somatostatin (GHIH)', explanation: 'Somatostatin (also called Growth Hormone Inhibiting Hormone or GHIH) inhibits GH release. Dopamine inhibits prolactin. GnIH inhibits LH.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'GnIH (Gonadotropin-Inhibiting Hormone) primarily inhibits:', options: ['A) FSH', 'B) LH', 'C) GH', 'D) Prolactin'], correctAnswer: 'B) LH', explanation: 'GnIH produced by the paraventricular nuclei primarily inhibits LH release. Its secretion is influenced by stress, developmental state, and photoperiod.', difficulty: 'hard' },

    // ADDITIONAL TRUE/FALSE
    { questionType: 'true_false', question: 'The hypothalamus is involved in non-endocrine functions such as food intake. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'The hypothalamus is involved in many non-endocrine functions including appetite/food intake, thermoregulation, circadian rhythms, and emotional behaviour. Food intake indirectly impacts GH secretion.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'ADH and Oxytocin have completely different amino acid structures. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'ADH and Oxytocin are both nanopeptides with 9 amino acids and have very similar (nearly identical) structure. They differ by only 2 amino acids.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Prolactin inhibits gonadotropins at the peripheral level. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Prolactin inhibits gonadotropins peripherally. This is why hyperprolactinaemia (e.g., from prolactinoma) causes amenorrhea and infertility.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Desmopressin would be effective in treating nephrogenic diabetes insipidus. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Desmopressin (ADH analogue) only works in CENTRAL DI where ADH is deficient. In nephrogenic DI, the kidneys are resistant to ADH, so giving more ADH/desmopressin is futile.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'The hypothalamus receives neural inputs from sources outside the organism. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'The hypothalamus is regulated by both internal hormonal signals AND neural inputs from many sources, including some from outside the organism (e.g., light/photoperiod affecting circadian rhythms).', difficulty: 'medium' },

    // ADDITIONAL FILL IN THE BLANK
    { questionType: 'fill_blank', question: 'CRH has _____ amino acids and a half-life of _____ minutes.', options: [], correctAnswer: '41; 60', explanation: 'CRH is a 41 amino acid peptide from the parvocellular region of paraventricular nuclei. Its half-life is 60 minutes. It stimulates ACTH and beta-endorphin release.', difficulty: 'hard' },
    { questionType: 'fill_blank', question: 'GnRH has _____ amino acids and is released in a _____ fashion.', options: [], correctAnswer: '10; pulsatile', explanation: 'GnRH is a 10 amino acid peptide released in pulsatile fashion from the preoptic area. Pulsatile release is essential — continuous GnRH paradoxically suppresses FSH/LH.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'In _____ diabetes insipidus, ADH is deficient. In _____ diabetes insipidus, kidneys are resistant to ADH.', options: [], correctAnswer: 'Central; Nephrogenic', explanation: 'Central DI: ADH deficiency (hypothalamic/pituitary problem). Nephrogenic DI: kidneys resistant to ADH (renal problem). Both present with polyuria and polydipsia.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'FSH and LH share the same _____ subunit with TSH and hCG, but differ in their _____ subunits.', options: [], correctAnswer: 'alpha; beta', explanation: 'FSH, LH, TSH, and hCG are glycoprotein hormones sharing an identical alpha subunit. The beta subunit is unique to each and confers biological specificity.', difficulty: 'medium' },

    // ADDITIONAL CLINICAL SCENARIOS
    { questionType: 'mcq', question: 'A 45-year-old man presents with headache, visual field defect (bitemporal hemianopia), and erectile dysfunction. Prolactin level is 200 ng/mL. The MOST LIKELY diagnosis is:', options: ['A) Craniopharyngioma', 'B) Prolactinoma (macroprolactinoma)', 'C) GH-secreting adenoma', 'D) Meningioma'], correctAnswer: 'B) Prolactinoma (macroprolactinoma)', explanation: 'Very high prolactin (>200 ng/mL) + mass effects (headache, bitemporal hemianopia from optic chiasm compression) + hypogonadal symptoms = macroprolactinoma. Treat with dopamine agonists first.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A patient with severe head trauma develops massive water output (8L/day) with very dilute urine. Serum osmolality is high and urine osmolality is low. The BEST initial treatment is:', options: ['A) Fluid restriction', 'B) Desmopressin (DDAVP)', 'C) Thiazide diuretics', 'D) Demeclocycline'], correctAnswer: 'B) Desmopressin (DDAVP)', explanation: 'Post-traumatic central diabetes insipidus (damage to hypothalamus/pituitary stalk) → ADH deficiency → massive dilute urine. Treatment is desmopressin (synthetic ADH) replacement.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A woman with infertility has elevated prolactin, low FSH, and low LH. MRI shows a pituitary microadenoma. After starting cabergoline, her prolactin normalises. What outcome is expected?', options: ['A) Permanent infertility', 'B) Restoration of FSH/LH and return of menstrual cycles', 'C) Need for surgical excision', 'D) Development of diabetes insipidus'], correctAnswer: 'B) Restoration of FSH/LH and return of menstrual cycles', explanation: 'Lowering prolactin with dopamine agonists removes prolactin\'s inhibition of gonadotropins → FSH/LH normalise → menstrual cycles resume → fertility restored.', difficulty: 'hard' },
  ],

  flashcards: [
    { front: 'Hypothalamus to Anterior Pituitary: Vascular or Neural?', back: 'VASCULAR — via the Hypothalamo-Hypophyseal Portal System. Blood carrying releasing/inhibiting hormones flows from hypothalamus directly to anterior pituitary.', difficulty: 'easy' },
    { front: 'Hypothalamus to Posterior Pituitary: Vascular or Neural?', back: 'NEURAL — via the Hypothalamo-Hypophyseal Neural Tract. Axons from supraoptic and paraventricular nuclei carry ADH and Oxytocin down to posterior pituitary for storage.', difficulty: 'easy' },
    { front: 'Where is ADH made? Where is it stored?', back: 'MADE in supraoptic nuclei of hypothalamus. STORED in posterior pituitary (in Herring bodies). The posterior pituitary does NOT synthesise ADH.', difficulty: 'medium' },
    { front: 'What happens to prolactin if the pituitary stalk is cut?', back: 'Prolactin INCREASES. It is the only anterior pituitary hormone under tonic INHIBITION by dopamine. Cutting the stalk removes dopamine delivery → prolactin rises. All other hormones decrease.', difficulty: 'hard' },
    { front: 'Somatostatin inhibits which hormones?', back: 'GH, TSH, glucagon, gastrin, insulin, and secretin. Produced in hypothalamus, CNS, gut, and pancreas. Does NOT inhibit prolactin.', difficulty: 'medium' },
    { front: 'Why does continuous GnRH suppress LH/FSH?', back: 'GnRH normally acts in PULSATILE fashion. Continuous administration causes receptor down-regulation → paradoxical suppression. Used therapeutically for prostate cancer, endometriosis.', difficulty: 'hard' },
    { front: 'TRH stimulates which two hormones?', back: 'TSH and Prolactin. This explains why primary hypothyroidism (high TRH) can cause hyperprolactinaemia and galactorrhoea.', difficulty: 'medium' },
    { front: 'What is Kallmann syndrome?', back: 'GnRH deficiency (olfactory-genital dysplasia): hypogonadism + anosmia. GnRH neurons fail to migrate from olfactory placode during development.', difficulty: 'hard' },
    { front: 'FSH vs LH in testes — which cells do they target?', back: 'LH → Leydig cells (testosterone production). FSH → Sertoli cells (with testosterone, stimulates spermatogenesis). Testicular inhibin suppresses FSH.', difficulty: 'medium' },
    { front: 'What are the 3 types of feedback loops?', back: 'Long-loop: target gland → hypothalamus/pituitary. Short-loop: pituitary hormone → hypothalamus. Ultra-short/Auto: hypothalamic hormone → hypothalamus itself.', difficulty: 'medium' },
    { front: 'Why does alcohol cause diuresis?', back: 'Alcohol INHIBITS ADH release from posterior pituitary → kidneys cannot reabsorb water → increased urine output → dehydration.', difficulty: 'easy' },
    { front: 'Which glycoprotein hormones share the same alpha subunit?', back: 'FSH, LH, TSH, and hCG all share the same alpha subunit. They differ in their beta subunits which confer specificity.', difficulty: 'medium' },
    { front: 'Central DI vs Nephrogenic DI?', back: 'Central DI: ADH deficiency (pituitary/hypothalamic damage), responds to desmopressin. Nephrogenic DI: kidney resistance to ADH, does NOT respond to desmopressin.', difficulty: 'hard' },
    { front: 'SIADH — key features?', back: 'Excess ADH → water retention → hyponatraemia. Classic cause: small cell lung cancer. Euvolaemic hyponatraemia with concentrated urine.', difficulty: 'hard' },
    { front: 'What is the median eminence?', back: 'Region at the base of the hypothalamus where hypothalamic releasing/inhibiting hormones enter the primary capillary plexus of the portal system to reach the anterior pituitary.', difficulty: 'medium' },
    { front: 'CRH — what does it release?', back: 'CRH (41 aa, from parvocellular paraventricular nuclei, half-life 60 min) releases ACTH AND beta-endorphin from the anterior pituitary. Both derived from POMC.', difficulty: 'hard' },
    { front: 'GnIH — what does it do?', back: 'Gonadotropin-Inhibiting Hormone from paraventricular nuclei — inhibits LH release. Influenced by stress, developmental state, and photoperiod.', difficulty: 'hard' },
  ],
};
