/**
 * INTRODUCTION TO ENDOCRINOLOGY — Pre-loaded Study Material
 * Source: Introduction to Endocrinology PPT (64 slides)
 */

export const introEndocrinologyMaterial = {
  title: 'Introduction to Endocrinology',
  fileType: 'ppt',
  wordCount: 3200,
  status: 'analyzed' as const,

  summary: {
    // ─── THEORY & DEFINITION BANK ────────────────────────────────────
    definitions: [
      { term: 'Endocrinology', definition: 'Study of the endocrine system — a communication system in which glands or specialised cells release hormones into circulating blood that influence function of cells at another location in the body.' },
      { term: 'Hormone', definition: 'Chemical signal secreted into the circulatory system that communicates regulatory messages within the body. Hormones reach all parts of the body but only target cells with specific receptors respond.' },
      { term: 'Classical Hormone', definition: 'Hormone secreted from endocrine cells directly into interstitial fluid, diffuses into the blood stream and is distributed to all parts of the body through the circulatory system.' },
      { term: 'Neurohormone', definition: 'Hormone secreted from nerve cells (not glandular cells), diffuses into blood stream and distributed throughout the body via the circulatory system. E.g. Oxytocin, GnRH.' },
      { term: 'Local Hormone', definition: 'Hormone secreted into interstitial fluid that acts locally — either on neighbouring cells (paracrine) or on the cell that secreted it (autocrine).' },
      { term: 'Paracrine Signaling', definition: 'Form of cell communication where the target cells lie near the secreting cells. E.g. insulin from pancreatic beta cells affecting glucagon production in alpha cells.' },
      { term: 'Autocrine Signaling', definition: 'Form of cell communication where the target cell is also the secreting cell. E.g. IGF stimulating cell division in tumour cells that produced it.' },
      { term: 'Synaptic Signaling', definition: 'Communication where neurons form specialised junctions (synapses) with target cells and secrete neurotransmitters that diffuse short distances to bind receptors on target cells.' },
      { term: 'Neuroendocrine Signaling', definition: 'Specialised neurosecretory cells secrete neurohormones that can act in paracrine or endocrine fashion. E.g. oxytocin (paracrine), GnRH (endocrine).' },
      { term: 'Pheromone Signaling', definition: 'Chemical communication between members of the same species via chemicals released into the environment for functions like marking trails, defining territories, warning of predators, or attracting mates.' },
      { term: 'Peptide Hormone', definition: 'Most common hormone class. Range from 3 amino acids (TRH) to 200 amino acids (GH). Synthesised as preprohormone → prohormone → hormone in rough ER. Stored in cytoplasm. Secreted by exocytosis. Water-soluble.' },
      { term: 'Steroid Hormone', definition: 'Hormone synthesised from cholesterol (from plasma or de novo). Lipid-soluble, easily crosses cell membranes. NOT stored in cytoplasm. Small in size. Includes adrenal cortical and gonadal hormones.' },
      { term: 'Amine Hormone', definition: 'Hormone derived from tyrosine. Includes thyroid hormones and adrenal medulla hormones (epinephrine, norepinephrine) and dopamine. Stored in cytoplasm and released when needed.' },
      { term: 'Second Messenger', definition: 'Intracellular signaling molecule whose presence acts as a signal. Synthesised or released from storage. Used in G protein-coupled receptor signaling. Examples: cAMP, cGMP, Ca²⁺, IP₃, DAG.' },
      { term: 'Signal Amplification', definition: 'Process where one molecule of extracellular ligand activates several G proteins, each effector makes many second messenger molecules, resulting in a large intracellular signal from a single ligand.' },
      { term: 'Down-regulation', definition: 'Decrease in receptor number or response on target tissue, reducing sensitivity to a hormone.' },
      { term: 'Up-regulation', definition: 'Formation of more receptors on target tissue, increasing sensitivity to a hormone.' },
      { term: 'Negative Feedback', definition: 'Most common hormonal control mechanism. The level of hormone in blood or body\'s return to homeostasis shuts off the loop at hypothalamus and pituitary.' },
      { term: 'Positive Feedback', definition: 'Rare mechanism where a stimulus produces an even greater response. E.g. oxytocin causing milk release → more suckling → more oxytocin release.' },
      { term: 'Antagonistic Regulation', definition: 'Two hormones with opposite effects that maintain homeostasis. E.g. insulin (decreases blood glucose) and glucagon (increases blood glucose).' },
      { term: 'Radioimmunoassay (RIA)', definition: 'In vitro immunometric assay using competitive binding of radiolabelled and natural hormone to antibodies. Very sensitive but does not measure biological activity. Can overestimate by measuring precursors/degradation products.' },
      { term: 'ELISA', definition: 'Enzyme-Linked ImmunoSorbent Assay. Spin-off of RIA. Binding of hormone to antibody reported by colour rather than radiation. Non-radioactive, high specificity, qualitative and quantitative, automated.' },
      { term: 'Radioreceptor Assay', definition: 'Similar to RIA except intact cells or membranes are used. Tests for receptors on cells. Assesses total binding activity but provides no information about biological activity.' },
      { term: 'Bioassay', definition: 'In vivo assay using animals or tissues to assess presence of active substance based on known physiological effects. Lacks sensitivity, precision, specificity. Advantage: measures biological response.' },
      { term: 'Hormone Clearance', definition: 'Removal of hormones from the body by: metabolic destruction by tissues, binding with tissues, excretion by liver into bile, or excretion by kidneys into urine. Water-soluble hormones are cleared faster.' },
      { term: 'Permissive Effect', definition: 'When one hormone must be present for another hormone to exert its full effect. One of the types of hormone interactions alongside stimulatory, inhibitory, additive, and synergistic.' },
    ],

    // ─── KEY POINTS (NOTHING SKIPPED) ────────────────────────────────
    keyPoints: [
      '## ENDOCRINE SYSTEM OVERVIEW',
      '>> The endocrine system is a "wireless" communication system using chemical signals (hormones) via the blood. It works alongside the nervous system to maintain homeostasis.',
      '### Types of Cell Communication',
      '1) Endocrine — hormone travels through blood to distant target',
      '2) Paracrine — hormone acts on neighbouring cells',
      '3) Autocrine — hormone acts on the same cell that secreted it',
      '4) Synaptic — neurotransmitter crosses a synapse',
      '5) Neuroendocrine — nerve cell secretes hormone into blood',
      '6) Pheromone — chemical communication between organisms',
      '### Classification by Origin',
      '1) Classical hormones — from endocrine glands',
      '2) Neurohormones — from nerve cells (e.g. Oxytocin, GnRH)',
      '3) Local hormones — paracrine/autocrine',
      '### Classification by Structure',
      '1) Peptide/Protein — most common, water-soluble, stored in cytoplasm, secreted by exocytosis. Synthesised as preprohormone → prohormone → hormone',
      '2) Steroid — from cholesterol, lipid-soluble, cross membranes easily, NOT stored in cytoplasm. Includes adrenal cortical and gonadal hormones',
      '3) Amine — derived from tyrosine. Includes thyroid hormones (T₃, T₄), catecholamines (epinephrine, norepinephrine), dopamine',
      '4) Vitamin derivatives — retinoids, vitamin D',
      '## MAJOR ENDOCRINE GLANDS & THEIR HORMONES',
      '>> Each gland produces specific hormones. Know which hormone comes from which gland.',
      '### Hypothalamus',
      'TRH, CRH, GHRH, Somatostatin (GHIH), GnRH, Dopamine (PIH), Prolactin releasing factor',
      '### Anterior Pituitary',
      'GH, TSH, ACTH, Prolactin, FSH, LH',
      '### Posterior Pituitary',
      'ADH (Vasopressin), Oxytocin — these are made in hypothalamus but stored/released from posterior pituitary',
      '### Thyroid',
      'T₃, T₄ (from follicular cells), Calcitonin (from C cells)',
      '### Adrenals',
      'Cortex: Cortisol + Aldosterone. Medulla: Epinephrine + Norepinephrine',
      '### Pancreas',
      'Insulin (from beta cells), Glucagon (from alpha cells)',
      '## HORMONE SIGNALLING & TRANSPORT',
      '>> How hormones reach their targets, bind receptors, and produce effects inside cells.',
      '### Transport in Blood',
      'Water-soluble hormones (peptides, catecholamines): dissolve freely in plasma',
      'Lipid-soluble hormones (steroids, thyroid): bind carrier proteins, <10% free. Only FREE hormone is biologically active',
      '### Receptor Types',
      'Hormone receptors: large proteins, 2,000-100,000 per cell, highly specific',
      'Peptide hormones → surface receptors → SECOND MESSENGER system (cAMP, cGMP, Ca²⁺, IP₃, DAG)',
      'Steroid hormones → cytoplasmic/nuclear receptors → change gene expression and protein synthesis',
      '### Receptor Regulation',
      'Up-regulation: more receptors → increased sensitivity',
      'Down-regulation: fewer receptors → decreased sensitivity',
      '## REGULATION & FEEDBACK',
      '>> How the body controls hormone levels to maintain balance.',
      '### Feedback Mechanisms',
      'Negative feedback: MOST COMMON — ↑hormone → ↓stimulating hormone (shuts off the loop)',
      'Positive feedback: RARE — e.g. oxytocin in labour, LH surge in ovulation',
      'Antagonistic regulation: e.g. Insulin (↓glucose) vs Glucagon (↑glucose) maintain blood glucose at 70-110 mg/100mL',
      '### Hormone Clearance',
      'Cleared by: degradation, oxidation, reduction, methylation, conjugation',
      'Excreted via liver (bile) or kidneys (urine)',
      'Water-soluble hormones cleared FASTER than lipid-soluble',
      '### Hormone Assays',
      '1) Bioassay — in vivo, measures biological response, least sensitive',
      '2) RIA — most SENSITIVE, uses radiation, does NOT measure biological activity',
      '3) ELISA — non-radioactive, high specificity, quantitative, automated (preferred modern assay)',
      '4) Radioreceptor assay — tests receptor binding',
      '## CAUSES OF ENDOCRINE DISEASE',
      '>> Endocrine disorders result from too much (hyperfunction) or too little (hypofunction) hormone, or hormone resistance.',
      '### Causes of Hyperfunction',
      '1) Neoplastic — benign/malignant tumours',
      '2) Ectopic production',
      '3) Autoimmune — e.g. Graves\' disease',
      '4) Iatrogenic — e.g. steroid therapy → Cushing\'s',
      '5) Infectious — e.g. subacute thyroiditis',
      '### Causes of Hypofunction',
      '1) Autoimmune — Hashimoto\'s, Type 1 DM, Addison\'s',
      '2) Iatrogenic — radiation, surgery',
      '3) Enzyme defects — 21-hydroxylase deficiency (CAH)',
      '4) Developmental — Kallmann syndrome, Turner syndrome',
      '5) Nutritional — Vitamin D deficiency, iodine deficiency',
      '6) Hemorrhage — Sheehan\'s syndrome (postpartum pituitary necrosis)',
      '### Types of Hormone Resistance',
      '1) Membrane receptor defect — GH, vasopressin, LH, FSH, ACTH',
      '2) Nuclear receptor defect — androgen, thyroid, vitamin D, estrogen, glucocorticoid',
      '3) Signaling pathway defect — Albright\'s hereditary osteodystrophy',
      '4) Post-receptor defect — Type 2 DM, leptin resistance',
    ],

    // ─── EXAM HIGHLIGHTS ─────────────────────────────────────────────
    examHighlights: [
      '## INTRO ENDOCRINOLOGY — EXAM FACTS',
      '>> These foundational concepts are the most commonly tested.',
      '### Signalling Mechanisms',
      'Peptide hormones → SECOND MESSENGER system (surface receptors). Steroid hormones → INTRACELLULAR receptors (change protein synthesis)',
      'Bound hormones are biologically INACTIVE — only FREE hormones act on target cells',
      '### Regulation',
      'Negative feedback = MOST COMMON regulatory mechanism (always the answer)',
      'Positive feedback examples to memorize: 1) Oxytocin in labour, 2) LH surge in ovulation',
      'Insulin + Glucagon = classic ANTAGONISTIC regulation',
      '### Assays',
      'RIA = most SENSITIVE but does NOT measure biological activity',
      'ELISA = preferred modern assay (non-radioactive, high specificity, automated)',
      '### Classic Disease Associations',
      'Graves\' = Autoimmune HYPER-function. Hashimoto\'s = Autoimmune HYPO-function',
      'Sheehan\'s syndrome = postpartum pituitary necrosis (hemorrhage)',
      'Kallmann syndrome = GnRH deficiency (anosmia + hypogonadism)',
      '21-Hydroxylase deficiency = most common cause of CAH',
      'Type 2 DM = POST-RECEPTOR hormone resistance',
    ],

    // ─── CLINICAL CORRELATIONS ───────────────────────────────────────
    clinicalCorrelations: [
      '## AUTOIMMUNE ENDOCRINE DISEASES',
      '>> Autoimmunity is the most common cause of endocrine dysfunction. Know whether it causes hyper- or hypo-function.',
      '### Hyperfunction (Autoimmune)',
      'Graves\' disease: antibodies stimulate TSH receptor → excess T₃/T₄ production',
      '### Hypofunction (Autoimmune)',
      'Hashimoto\'s thyroiditis: antibodies destroy thyroid tissue → hypothyroidism',
      'Type 1 DM: destruction of pancreatic beta cells → absolute insulin deficiency',
      'Addison\'s disease: destruction of adrenal cortex → cortisol and aldosterone deficiency',
      '## OTHER ENDOCRINE DISEASES',
      '>> These conditions result from non-autoimmune causes.',
      '### Iatrogenic',
      'Cushing\'s syndrome: caused by exogenous glucocorticoid administration',
      '### Post-Receptor Resistance',
      'Type 2 DM: cells don\'t respond to insulin properly despite insulin presence',
      '### Developmental',
      'Kallmann syndrome: GnRH neurons fail to migrate → anosmia + hypogonadism',
      '### Enzyme Defects',
      'Congenital Adrenal Hyperplasia (CAH): 21-hydroxylase deficiency → blocks cortisol → excess ACTH → adrenal androgen overproduction',
      '### Vascular',
      'Sheehan\'s syndrome: postpartum pituitary necrosis (hemorrhage) → panhypopituitarism',
      '### Tumours',
      'Pheochromocytoma: adrenal medulla tumour → excess catecholamines → paroxysmal hypertension, headache, sweating',
      '### Signalling Pathway Defects',
      'Albright\'s hereditary osteodystrophy: Gs protein defect → hormone resistance',
    ],

    // ─── PROCESSES & PATHWAYS ────────────────────────────────────────
    processes: [
      {
        name: 'Peptide Hormone Synthesis Pathway',
        steps: [
          'Gene transcription in nucleus → mRNA',
          'Translation on ribosomes of rough ER → Preprohormone',
          'Signal peptide cleaved → Prohormone',
          'Further processing (folding, cleavage) → Active Hormone',
          'Packaged into secretory granules and stored in cytoplasm',
          'Released by exocytosis when cell is stimulated',
        ],
      },
      {
        name: 'Second Messenger Signaling (cAMP Pathway)',
        steps: [
          'Hormone (first messenger) binds to 7-transmembrane domain receptor on cell surface',
          'Receptor activates Gs protein (transducer)',
          'Gs protein activates adenylate cyclase (effector)',
          'Adenylate cyclase converts ATP → cAMP (second messenger)',
          'cAMP activates Protein Kinase A (PKA)',
          'PKA phosphorylates target proteins → cellular response',
          'Signal amplification occurs at each step — one ligand generates many modified proteins',
        ],
      },
      {
        name: 'Steroid Hormone Mechanism of Action',
        steps: [
          'Steroid hormone (lipid-soluble) crosses cell membrane freely',
          'Binds to cytoplasmic or nuclear receptor',
          'Hormone-receptor complex acts as transcription factor',
          'Enters nucleus and binds to specific DNA response elements',
          'Activates or represses gene transcription',
          'New mRNA produced → translated into new proteins',
          'Cellular response occurs (slower onset but longer duration than peptide hormones)',
        ],
      },
      {
        name: 'Negative Feedback Loop (Thyroid Example)',
        steps: [
          'Low thyroid hormone levels detected by hypothalamus',
          'Hypothalamus releases TRH (Thyrotropin-Releasing Hormone)',
          'TRH stimulates anterior pituitary to release TSH',
          'TSH stimulates thyroid gland to produce and release T₃ and T₄',
          'Rising T₃/T₄ levels inhibit both hypothalamus (TRH) and pituitary (TSH)',
          'Loop is shut off when thyroid hormone levels normalise',
        ],
      },
      {
        name: 'Blood Glucose Regulation (Antagonistic Hormones)',
        steps: [
          'After a meal: blood glucose rises above 110 mg/100mL',
          'Beta cells of pancreas release INSULIN',
          'Insulin causes: cells take up glucose, liver stores glucose as glycogen',
          'Blood glucose declines back to 70-110 mg/100mL (homeostasis)',
          'After skipping a meal: blood glucose falls below 70 mg/100mL',
          'Alpha cells of pancreas release GLUCAGON',
          'Glucagon causes: liver breaks down glycogen and releases glucose into blood',
          'Blood glucose rises back to 70-110 mg/100mL (homeostasis)',
        ],
      },
    ],

    // ─── MNEMONICS ───────────────────────────────────────────────────
    mnemonics: [
      { topic: 'Anterior Pituitary Hormones', mnemonic: 'FLAT PiG', explanation: 'FSH, LH, ACTH, TSH, Prolactin, GH — the 6 hormones of the anterior pituitary.' },
      { topic: 'Hypothalamic Releasing Hormones', mnemonic: 'Go Create The Great Pies', explanation: 'GnRH, CRH, TRH, GHRH, PIH (Dopamine) — the main hypothalamic hormones.' },
      { topic: 'Second Messengers', mnemonic: 'CADILLAC', explanation: 'cAMP, DAG, IP₃, Ca²⁺ — the main second messengers in signal transduction.' },
      { topic: 'Steroid vs Peptide Hormone Action', mnemonic: 'Steroids go IN, Peptides stay OUT', explanation: 'Steroid hormones enter the cell (intracellular receptors). Peptide hormones stay outside (surface receptors + second messengers).' },
      { topic: 'Causes of Endocrine Hypofunction', mnemonic: 'HIDE HEN', explanation: 'Hemorrhage/Infarction, Iatrogenic, Developmental, Enzyme defects, Hormone mutations, Enzyme defects, Nutritional deficiency — causes of hypofunction.' },
    ],

    quickReview: [
      'Endocrine = "wireless" chemical communication via blood; Nervous = "wired" via synapses.',
      'Three hormone classes: Peptide (water-soluble, second messenger), Steroid (lipid-soluble, nuclear receptor), Amine (from tyrosine).',
      'Negative feedback = most common regulation. Positive feedback = rare (oxytocin in labour, LH surge).',
      'Peptide hormones → surface receptor → second messengers (cAMP, IP₃, DAG, Ca²⁺). Steroid hormones → cross membrane → intracellular receptor → change gene transcription.',
      'Key clinical: Graves (autoimmune hyper), Hashimoto (autoimmune hypo), Sheehan (postpartum hemorrhage), Kallmann (GnRH deficiency + anosmia), Type 2 DM (post-receptor resistance).',
    ],
  },

  // ─── MCQ QUESTIONS (55 questions) ──────────────────────────────────
  questions: [
    // --- LIKELIHOOD / MOST LIKELY / LEAST LIKELY STYLE ---
    { questionType: 'mcq', question: 'Which is the MOST LIKELY mechanism of hormone regulation in the body?', options: ['A) Positive feedback', 'B) Negative feedback', 'C) Autocrine regulation', 'D) Pheromone signaling'], correctAnswer: 'B) Negative feedback', explanation: 'Negative feedback is the most common control mechanism for hormone regulation. The level of hormone in blood shuts off the loop at the hypothalamus and pituitary.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'A patient presents with postpartum hemorrhage followed by failure to lactate and amenorrhea. The MOST LIKELY diagnosis is:', options: ['A) Graves\' disease', 'B) Addison\'s disease', 'C) Sheehan\'s syndrome', 'D) Kallmann syndrome'], correctAnswer: 'C) Sheehan\'s syndrome', explanation: 'Sheehan\'s syndrome is postpartum pituitary necrosis due to hemorrhage/infarction, causing panhypopituitarism — failure to lactate (no prolactin) and amenorrhea (no FSH/LH).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which assay is MOST LIKELY to give a false-high reading by measuring hormone precursors and degradation products?', options: ['A) ELISA', 'B) Bioassay', 'C) Radioimmunoassay (RIA)', 'D) Radioreceptor assay'], correctAnswer: 'C) Radioimmunoassay (RIA)', explanation: 'RIA can overestimate hormone levels because it measures precursors and degradation products in addition to the active hormone. It is very sensitive but does not measure biological activity.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A male patient has anosmia (loss of smell) and delayed puberty. The MOST LIKELY diagnosis is:', options: ['A) Turner syndrome', 'B) Sheehan\'s syndrome', 'C) Kallmann syndrome', 'D) Congenital Adrenal Hyperplasia'], correctAnswer: 'C) Kallmann syndrome', explanation: 'Kallmann syndrome is olfactory-genital dysplasia — GnRH deficiency causing hypogonadism (delayed puberty) + anosmia (failure of GnRH neurons to migrate from olfactory placode).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which hormone class is MOST LIKELY to be found bound to plasma proteins in circulation?', options: ['A) Peptide hormones', 'B) Catecholamines', 'C) Steroid hormones', 'D) Prostaglandins'], correctAnswer: 'C) Steroid hormones', explanation: 'Steroid hormones and thyroid hormones are lipid-soluble and travel bound to plasma proteins (usually <10% free). Water-soluble peptide hormones dissolve freely in plasma.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which is the LEAST LIKELY second messenger in G protein-coupled receptor signaling?', options: ['A) cAMP', 'B) IP₃', 'C) mRNA', 'D) Ca²⁺'], correctAnswer: 'C) mRNA', explanation: 'mRNA is NOT a second messenger. The main second messengers are cAMP, cGMP, Ca²⁺, IP₃, and DAG. mRNA is a product of gene transcription used in steroid hormone pathways.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A child with ambiguous genitalia and salt wasting is MOST LIKELY to have a deficiency of:', options: ['A) 11-beta-hydroxylase', 'B) 21-hydroxylase', 'C) 17-alpha-hydroxylase', 'D) Aromatase'], correctAnswer: 'B) 21-hydroxylase', explanation: '21-hydroxylase deficiency is the most common cause of Congenital Adrenal Hyperplasia (CAH). It blocks cortisol and aldosterone synthesis, leading to salt wasting and excess adrenal androgens causing virilisation.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which condition is MOST LIKELY caused by autoimmune stimulation of hormone receptors?', options: ['A) Hashimoto\'s thyroiditis', 'B) Graves\' disease', 'C) Addison\'s disease', 'D) Type 1 Diabetes Mellitus'], correctAnswer: 'B) Graves\' disease', explanation: 'Graves\' disease is caused by autoantibodies (TSI - Thyroid Stimulating Immunoglobulins) that STIMULATE TSH receptors on the thyroid, causing hyperthyroidism. The others involve autoimmune DESTRUCTION.', difficulty: 'medium' },

    // --- STANDARD MCQs ---
    { questionType: 'mcq', question: 'Which of the following is NOT a form of cellular communication?', options: ['A) Paracrine signaling', 'B) Autocrine signaling', 'C) Mitotic signaling', 'D) Neuroendocrine signaling'], correctAnswer: 'C) Mitotic signaling', explanation: 'The forms of cellular communication are: Endocrine, Paracrine, Autocrine, Synaptic, Neuroendocrine, and Pheromone signaling. "Mitotic signaling" is not one of them.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Insulin from beta cells affecting glucagon production in alpha cells is an example of:', options: ['A) Endocrine signaling', 'B) Paracrine signaling', 'C) Autocrine signaling', 'D) Synaptic signaling'], correctAnswer: 'B) Paracrine signaling', explanation: 'Paracrine signaling involves target cells lying near the secreting cells. Beta cells and alpha cells are adjacent in the Islets of Langerhans.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Peptide hormones are synthesised in which order?', options: ['A) Prohormone → Preprohormone → Hormone', 'B) Preprohormone → Prohormone → Hormone', 'C) Hormone → Prohormone → Preprohormone', 'D) Prohormone → Hormone → Preprohormone'], correctAnswer: 'B) Preprohormone → Prohormone → Hormone', explanation: 'Peptide hormones are synthesised as preprohormone first (with signal peptide), then cleaved to prohormone, then finally to active hormone in the rough ER.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which of the following hormones is derived from cholesterol?', options: ['A) Insulin', 'B) Growth Hormone', 'C) Cortisol', 'D) ADH'], correctAnswer: 'C) Cortisol', explanation: 'Cortisol is a steroid hormone synthesised from cholesterol. Insulin, GH, and ADH are peptide hormones synthesised from amino acids.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Thyroid hormones are derived from which amino acid?', options: ['A) Tryptophan', 'B) Tyrosine', 'C) Histidine', 'D) Leucine'], correctAnswer: 'B) Tyrosine', explanation: 'Amine hormones (thyroid hormones and catecholamines) are derived from the amino acid tyrosine.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The receptor for steroid hormones is located:', options: ['A) On the cell surface membrane', 'B) In the cytoplasm or nucleus', 'C) In the endoplasmic reticulum', 'D) On mitochondria'], correctAnswer: 'B) In the cytoplasm or nucleus', explanation: 'Steroid hormones are lipid-soluble and can cross the cell membrane. Their receptors are in the cytoplasm (for most steroids) or nucleus (for thyroid hormones).', difficulty: 'easy' },
    { questionType: 'mcq', question: 'How many receptors per cell are typically present for a specific hormone?', options: ['A) 10-100', 'B) 200-2,000', 'C) 2,000-100,000', 'D) Over 1,000,000'], correctAnswer: 'C) 2,000-100,000', explanation: 'Hormone receptors are large proteins numbering about 2,000 to 100,000 per cell. They are highly specific for a single hormone.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which of the following is an advantage of ELISA over RIA?', options: ['A) Measures biological activity', 'B) Non-radioactive', 'C) More sensitive', 'D) Cheaper'], correctAnswer: 'B) Non-radioactive', explanation: 'ELISA uses colour change rather than radiation to detect hormone-antibody binding. It is non-radioactive, high specificity, quantitative and qualitative, and automated.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The nervous system differs from the endocrine system in that the nervous system is:', options: ['A) Wireless and slow', 'B) Wired, rapid, and brief in duration', 'C) Uses chemical signals exclusively', 'D) Has long duration effects'], correctAnswer: 'B) Wired, rapid, and brief in duration', explanation: 'The nervous system is "wired" (close anatomical proximity), rapid, and brief in duration. The endocrine system is "wireless", slow, and long in duration. Both use chemical signals.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Normal blood glucose homeostasis is maintained between:', options: ['A) 50-70 mg/100mL', 'B) 70-110 mg/100mL', 'C) 110-150 mg/100mL', 'D) 150-200 mg/100mL'], correctAnswer: 'B) 70-110 mg/100mL', explanation: 'Blood glucose homeostasis is maintained between 70-110 mg/100mL through the antagonistic actions of insulin and glucagon.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'In the cAMP signaling pathway, which enzyme converts ATP to cAMP?', options: ['A) Protein Kinase A', 'B) Phospholipase C', 'C) Adenylate cyclase', 'D) Guanylate cyclase'], correctAnswer: 'C) Adenylate cyclase', explanation: 'Adenylate cyclase is the effector enzyme activated by Gs protein that converts ATP to cAMP (the second messenger) in the cAMP signaling pathway.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which hormone is secreted by the posterior pituitary?', options: ['A) Growth Hormone', 'B) ACTH', 'C) ADH (Vasopressin)', 'D) TSH'], correctAnswer: 'C) ADH (Vasopressin)', explanation: 'The posterior pituitary stores and releases ADH and Oxytocin. GH, ACTH, TSH, Prolactin, FSH, and LH are all anterior pituitary hormones.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Vitamin D is classified as which type of hormone?', options: ['A) Peptide hormone', 'B) Steroid hormone', 'C) Amine hormone', 'D) Vitamin derivative'], correctAnswer: 'D) Vitamin derivative', explanation: 'Hormones are classified into Peptide, Steroid, Amine, and Vitamin derivatives. Vitamin D (along with retinoids from vitamin A) falls under vitamin derivatives.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which type of hormone is NOT stored in the cytoplasm?', options: ['A) Peptide hormone', 'B) Steroid hormone', 'C) Amine hormone', 'D) Both A and C are stored'], correctAnswer: 'B) Steroid hormone', explanation: 'Steroid hormones are NOT stored in the cytoplasm because they are lipid-soluble and easily cross cell membranes. They are synthesised and released immediately. Peptide and amine hormones are stored.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The transducer in the cAMP signal transduction pathway is:', options: ['A) The hormone', 'B) The receptor', 'C) The Gs protein', 'D) Adenylate cyclase'], correctAnswer: 'C) The Gs protein', explanation: 'In the cAMP pathway: Receptor (7-TM domain protein) → Transducer (Gs protein) → Effector (adenylate cyclase) → Second messenger (cAMP) → Response (PKA phosphorylations).', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Dopamine released from the hypothalamus acts primarily as:', options: ['A) Growth hormone releasing hormone', 'B) Prolactin-release-inhibiting factor', 'C) TSH stimulant', 'D) ACTH releasing factor'], correctAnswer: 'B) Prolactin-release-inhibiting factor', explanation: 'Dopamine from the hypothalamus (arcuate nuclei) acts as Prolactin-Release-Inhibiting Factor (PIF). Without dopamine inhibition, prolactin would be continuously released.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which type of feedback is exemplified by the LH surge during ovulation?', options: ['A) Negative feedback', 'B) Positive feedback', 'C) Paracrine regulation', 'D) Antagonistic regulation'], correctAnswer: 'B) Positive feedback', explanation: 'The LH surge during ovulation is one of the classic examples of positive feedback — rising estrogen levels stimulate (not inhibit) more LH release from the pituitary.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Thyroid hormones are bound to plasma proteins to what extent?', options: ['A) About 50%', 'B) About 75%', 'C) About 90%', 'D) Greater than 99%'], correctAnswer: 'D) Greater than 99%', explanation: 'Thyroid hormones are >99% bound to plasma proteins, with very little free hormone in circulation. Only the free fraction is biologically active.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Type 2 Diabetes Mellitus is an example of hormone dysfunction at which level?', options: ['A) Membrane receptor mutation', 'B) Nuclear receptor defect', 'C) Post-receptor resistance', 'D) Hormone production failure'], correctAnswer: 'C) Post-receptor resistance', explanation: 'Type 2 DM involves post-receptor insulin resistance — insulin is produced and binds its receptor, but the intracellular signaling cascade is impaired, so cells don\'t respond properly.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Albright\'s hereditary osteodystrophy is caused by:', options: ['A) Receptor mutation', 'B) Hormone deficiency', 'C) Signaling pathway mutation (Gs protein)', 'D) Nutritional deficiency'], correctAnswer: 'C) Signaling pathway mutation (Gs protein)', explanation: 'Albright\'s hereditary osteodystrophy involves a mutation in the Gs protein signaling pathway, causing resistance to multiple hormones (PTH, TSH, etc.).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which gland produces calcitonin?', options: ['A) Parathyroid gland', 'B) Thyroid gland', 'C) Adrenal gland', 'D) Pituitary gland'], correctAnswer: 'B) Thyroid gland', explanation: 'The thyroid gland produces T₃ (triiodothyronine), T₄ (thyroxine), AND Calcitonin (from C cells/parafollicular cells). Calcitonin lowers blood calcium.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Hormone clearance is FASTER for:', options: ['A) Steroid hormones', 'B) Thyroid hormones', 'C) Water-soluble hormones', 'D) Protein-bound hormones'], correctAnswer: 'C) Water-soluble hormones', explanation: 'Water-soluble hormones (peptides, catecholamines) are removed faster than lipid-soluble hormones (steroids, thyroid hormones), which are protein-bound and cleared more slowly.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A bioassay differs from RIA in that a bioassay:', options: ['A) Is more sensitive', 'B) Measures biological response', 'C) Uses radiation', 'D) Is more specific'], correctAnswer: 'B) Measures biological response', explanation: 'Bioassays measure the actual biological response using animals/tissues. RIA measures immunological binding (concentration) but not biological activity. Bioassays lack sensitivity and precision.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'TRH (Thyrotropin-Releasing Hormone) is composed of how many amino acids?', options: ['A) 3', 'B) 10', 'C) 41', 'D) 191'], correctAnswer: 'A) 3', explanation: 'TRH is the smallest peptide hormone with only 3 amino acids. For comparison: GnRH = 10 aa, CRH = 41 aa, GH = 191 aa.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which of the following is NOT produced by the adrenal cortex?', options: ['A) Cortisol', 'B) Aldosterone', 'C) Epinephrine', 'D) Androgens'], correctAnswer: 'C) Epinephrine', explanation: 'Epinephrine (Adrenaline) is produced by the adrenal MEDULLA, not the cortex. The adrenal cortex produces cortisol (glucocorticoid), aldosterone (mineralocorticoid), and androgens.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Signal amplification in second messenger systems means:', options: ['A) The signal gets weaker at each step', 'B) One ligand molecule can generate many modified proteins inside the cell', 'C) Multiple ligands are needed for one response', 'D) Only steroid hormones show amplification'], correctAnswer: 'B) One ligand molecule can generate many modified proteins inside the cell', explanation: 'Signal amplification: one receptor activates several G proteins → each effector makes many second messenger molecules → each second messenger activates many kinases. Result: massive intracellular response from a single ligand.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which hormone is released in response to low blood glucose?', options: ['A) Insulin', 'B) Glucagon', 'C) Somatostatin', 'D) Calcitonin'], correctAnswer: 'B) Glucagon', explanation: 'Glucagon is released by alpha cells of the pancreas when blood glucose falls. It promotes glycogenolysis (glycogen → glucose) in the liver to raise blood glucose.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The endocrine pancreas produces all EXCEPT:', options: ['A) Insulin', 'B) Glucagon', 'C) Somatostatin', 'D) Trypsin'], correctAnswer: 'D) Trypsin', explanation: 'Trypsin is a digestive enzyme produced by the EXOCRINE pancreas. The endocrine pancreas (Islets of Langerhans) produces insulin (beta cells), glucagon (alpha cells), somatostatin (delta cells), and pancreatic polypeptide (PP cells).', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Down-regulation of receptors results in:', options: ['A) Increased hormone sensitivity', 'B) Decreased hormone sensitivity', 'C) Increased hormone production', 'D) Decreased hormone clearance'], correctAnswer: 'B) Decreased hormone sensitivity', explanation: 'Down-regulation decreases the number of receptors on target tissue, reducing the cell\'s response to the hormone (decreased sensitivity).', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Diurnal rhythm in hormone secretion means:', options: ['A) Seasonal variation', 'B) Daily cyclical pattern', 'C) Monthly cycle', 'D) Random secretion'], correctAnswer: 'B) Daily cyclical pattern', explanation: 'Diurnal rhythm refers to daily cyclical variations in hormone release. For example, cortisol peaks in the morning and is lowest at midnight.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which type of assay is automated, non-radioactive, and can be both qualitative and quantitative?', options: ['A) Bioassay', 'B) RIA', 'C) ELISA', 'D) In vitro bioassay'], correctAnswer: 'C) ELISA', explanation: 'ELISA is non-radioactive, uses colour change, is high specificity, can be qualitative and quantitative, and is automated — making it the preferred modern assay.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Gonadotropin-Releasing Hormone (GnRH) receptors have been found outside the brain in:', options: ['A) Liver and kidneys', 'B) Ovary and uterus', 'C) Lungs and heart', 'D) Skeletal muscle'], correctAnswer: 'B) Ovary and uterus', explanation: 'GnRH receptors outside the brain are found in the ovary and uterus of mammals, suggesting local regulatory roles of GnRH in reproductive organs.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Hypertrophy of an endocrine gland indicates:', options: ['A) Reduced function', 'B) Cell death', 'C) Enlargement and hyperactivity', 'D) Normal function'], correctAnswer: 'C) Enlargement and hyperactivity', explanation: 'In endocrine assessment, hypertrophy = enlarged and hyperactive gland. Hyperplasia = increased cell number. Atrophy = reduced size and hypoactive.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The "first messenger" in signal transduction is:', options: ['A) cAMP', 'B) IP₃', 'C) The hormone itself', 'D) Protein Kinase A'], correctAnswer: 'C) The hormone itself', explanation: 'The first messenger is the extracellular ligand (the hormone). It binds to the receptor, which activates G protein, which activates effector enzymes to produce second messengers (cAMP, IP₃, etc.).', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which of the following is a cause of endocrine HYPERFUNCTION?', options: ['A) Hemorrhage/infarction', 'B) Enzyme defects', 'C) Graves\' disease', 'D) Nutritional deficiency'], correctAnswer: 'C) Graves\' disease', explanation: 'Graves\' disease is an autoimmune cause of hyperthyroidism (hyperfunction). The others — hemorrhage, enzyme defects, nutritional deficiency — all cause hypofunction.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Hormones are metabolised and cleared from the body by all EXCEPT:', options: ['A) Degradation and oxidation', 'B) Conjugation with glucuronic acid', 'C) Excretion by kidneys into urine', 'D) Storage in adipose tissue permanently'], correctAnswer: 'D) Storage in adipose tissue permanently', explanation: 'Hormones are cleared by degradation, oxidation, reduction, methylation, conjugation, excretion via liver (bile) or kidneys (urine). They are not permanently stored in adipose tissue.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which pituitary hormone has the longest amino acid chain?', options: ['A) ACTH (39 aa)', 'B) ADH (9 aa)', 'C) GH (191 aa)', 'D) Prolactin (199 aa)'], correctAnswer: 'D) Prolactin (199 aa)', explanation: 'Prolactin has 199 amino acids, making it the longest among the listed pituitary hormones. GH has 191 aa, ACTH has 39 aa, and ADH/Oxytocin are nanopeptides (9 aa).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'IGF-I stimulating the same cell that produced it is an example of:', options: ['A) Endocrine signaling', 'B) Paracrine signaling', 'C) Autocrine signaling', 'D) Synaptic signaling'], correctAnswer: 'C) Autocrine signaling', explanation: 'Autocrine signaling is when the target cell is also the secreting cell. IGF stimulating cell division in the tumour cells that produced it is the classic example.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which pathway does the Gs protein activate in second messenger signaling?', options: ['A) Phospholipase C → IP₃ + DAG', 'B) Adenylate cyclase → cAMP', 'C) Guanylate cyclase → cGMP', 'D) Tyrosine kinase → phosphorylation'], correctAnswer: 'B) Adenylate cyclase → cAMP', explanation: 'The Gs (stimulatory G) protein activates adenylate cyclase, which converts ATP to cAMP. Gq protein activates Phospholipase C → IP₃ + DAG pathway.', difficulty: 'medium' },

    // --- TRUE/FALSE ---
    { questionType: 'true_false', question: 'Bound hormones in the blood are biologically active. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Bound hormones are biologically INACTIVE. Only FREE (unbound) hormones can diffuse across capillaries and bind to target cell receptors.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Steroid hormones are stored in secretory granules in the cytoplasm before release. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Steroid hormones are NOT stored in the cytoplasm. They are lipid-soluble and easily cross cell membranes, so they are synthesised and released immediately. Only peptide and amine hormones are stored.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Negative feedback is the most common mechanism of hormone regulation. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Negative feedback is indeed the most common control mechanism. The level of hormone in blood shuts off the stimulatory loop at the hypothalamus and pituitary.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'The posterior pituitary synthesises ADH and Oxytocin. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'The posterior pituitary STORES and RELEASES ADH and Oxytocin, but they are SYNTHESISED in the hypothalamus (supraoptic and paraventricular nuclei). The posterior pituitary does not synthesise hormones.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'Epinephrine and norepinephrine can develop full action within seconds. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Epinephrine and norepinephrine are secreted within seconds of gland stimulation and develop full action within another few seconds. This is in contrast to GH and thyroid hormones which take months.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'ELISA can measure both the presence and quantity of hormones. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'ELISA is both qualitative (detects presence) and quantitative (measures amount). It uses colour change/fluorescence reported by photometroscopy.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Peptide hormones act via intracellular receptors. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Peptide hormones are water-soluble and CANNOT cross the cell membrane. They bind to SURFACE receptors and use second messenger systems (cAMP, IP₃, DAG, Ca²⁺). Steroid hormones use intracellular receptors.', difficulty: 'easy' },
    { questionType: 'true_false', question: 'Prolactin is continuously released unless inhibited by dopamine. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Prolactin secretion is unique — it is tonically INHIBITED by dopamine (PIH) from the hypothalamus. If dopamine is removed (e.g., pituitary stalk transection), prolactin levels rise.', difficulty: 'medium' },

    // --- FILL IN THE BLANK ---
    { questionType: 'fill_blank', question: 'The three structural classes of hormones are Peptide, _____, and Amine.', options: [], correctAnswer: 'Steroid', explanation: 'Hormones are classified by structure into three main classes: Peptide/Protein, Steroid (from cholesterol), and Amine (from tyrosine). Vitamin derivatives are sometimes listed as a fourth class.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'The second messenger cAMP is produced from ATP by the enzyme _____.', options: [], correctAnswer: 'Adenylate cyclase', explanation: 'Adenylate cyclase (also called adenylyl cyclase) is the effector enzyme that converts ATP to cAMP when activated by Gs protein in the signal transduction pathway.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: '_____ syndrome is postpartum pituitary necrosis caused by hemorrhage, resulting in panhypopituitarism.', options: [], correctAnswer: 'Sheehan\'s', explanation: 'Sheehan\'s syndrome occurs when severe postpartum hemorrhage causes ischemic necrosis of the enlarged pituitary gland, leading to deficiency of all anterior pituitary hormones.', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'In antagonistic regulation of blood glucose, _____ from beta cells lowers glucose while glucagon from alpha cells raises it.', options: [], correctAnswer: 'Insulin', explanation: 'Insulin and glucagon are the classic antagonistic hormone pair. Insulin (from beta cells) lowers blood glucose; glucagon (from alpha cells) raises it to maintain homeostasis at 70-110 mg/100mL.', difficulty: 'easy' },
    { questionType: 'fill_blank', question: 'The most common enzyme defect causing Congenital Adrenal Hyperplasia is _____ deficiency.', options: [], correctAnswer: '21-Hydroxylase', explanation: '21-Hydroxylase deficiency accounts for >90% of CAH cases. It blocks cortisol and aldosterone synthesis in the adrenal cortex, leading to ACTH elevation and adrenal androgen excess.', difficulty: 'hard' },

    // --- CLINICAL SCENARIO ---
    { questionType: 'mcq', question: 'A 35-year-old woman presents with weight loss, tremors, heat intolerance, and exophthalmos. Lab shows suppressed TSH and elevated free T₄. Which antibody is MOST LIKELY responsible?', options: ['A) Anti-TPO antibodies', 'B) Thyroid-Stimulating Immunoglobulin (TSI)', 'C) Anti-thyroglobulin antibodies', 'D) Anti-TSH receptor blocking antibodies'], correctAnswer: 'B) Thyroid-Stimulating Immunoglobulin (TSI)', explanation: 'This is Graves\' disease — autoimmune hyperthyroidism. TSI antibodies stimulate the TSH receptor, causing excess thyroid hormone production. Anti-TPO and anti-thyroglobulin antibodies are more associated with Hashimoto\'s thyroiditis (hypothyroidism).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A patient on long-term high-dose prednisolone develops moon face, central obesity, and purple striae. This is an example of:', options: ['A) Autoimmune hyperfunction', 'B) Iatrogenic hyperfunction', 'C) Neoplastic hyperfunction', 'D) Post-receptor resistance'], correctAnswer: 'B) Iatrogenic hyperfunction', explanation: 'Iatrogenic Cushing\'s syndrome is caused by exogenous glucocorticoid administration (prednisolone). It is listed under causes of endocrine hyperfunction — iatrogenic category.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'A newborn with ambiguous genitalia is found to have elevated 17-hydroxyprogesterone levels. The enzyme deficiency MOST LIKELY involves:', options: ['A) 11-beta-hydroxylase', 'B) 21-hydroxylase', 'C) 17-alpha-hydroxylase', 'D) 3-beta-hydroxysteroid dehydrogenase'], correctAnswer: 'B) 21-hydroxylase', explanation: '21-hydroxylase deficiency is the most common cause of CAH. Elevated 17-hydroxyprogesterone is the diagnostic marker. It blocks conversion to cortisol and aldosterone, shunting precursors to androgen pathway causing virilisation.', difficulty: 'hard' },

    // ADDITIONAL MCQs
    { questionType: 'mcq', question: 'Which of the following is an example of neuroendocrine signaling?', options: ['A) Insulin acting on muscle', 'B) ADH released from nerve endings into blood', 'C) IGF acting on the same cell', 'D) Prostaglandin acting on adjacent cells'], correctAnswer: 'B) ADH released from nerve endings into blood', explanation: 'Neuroendocrine signaling involves neurons releasing hormones into the bloodstream. ADH produced by hypothalamic neurons and released from posterior pituitary into blood is a classic example.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Permissive action of hormones means:', options: ['A) One hormone blocks another', 'B) One hormone enhances the effect of another', 'C) Two hormones have opposite effects', 'D) One hormone replaces another'], correctAnswer: 'B) One hormone enhances the effect of another', explanation: 'Permissive action: one hormone must be present for another to exert its full effect. Example: cortisol permits catecholamines to cause vasoconstriction. Without cortisol, catecholamines are less effective.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Synergistic action of hormones means:', options: ['A) Hormones cancel each other out', 'B) Combined effect is greater than the sum of individual effects', 'C) One hormone inhibits another', 'D) Hormones act on different organs'], correctAnswer: 'B) Combined effect is greater than the sum of individual effects', explanation: 'Synergism: the combined effect of two hormones exceeds the sum of their individual effects. Example: FSH + Testosterone on spermatogenesis produce a greater effect together than either alone.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Which of the following is an example of antagonistic hormone action?', options: ['A) FSH and testosterone on spermatogenesis', 'B) Cortisol permitting catecholamine action', 'C) Insulin and glucagon on blood glucose', 'D) GH and IGF-I on growth'], correctAnswer: 'C) Insulin and glucagon on blood glucose', explanation: 'Antagonistic action: two hormones have opposite effects on the same target. Insulin lowers blood glucose while glucagon raises it. This maintains glucose homeostasis between 70-110 mg/100mL.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'The IP₃/DAG second messenger pathway is activated by which G protein?', options: ['A) Gs', 'B) Gi', 'C) Gq', 'D) Go'], correctAnswer: 'C) Gq', explanation: 'Gq protein activates Phospholipase C (PLC), which cleaves PIP₂ into IP₃ (releases Ca²⁺ from ER) and DAG (activates Protein Kinase C). Gs activates adenylate cyclase/cAMP pathway.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Pheromone signaling involves:', options: ['A) Hormones acting on the same cell', 'B) Chemical signals between organisms of the same species', 'C) Neural transmission across synapses', 'D) Hormones transported via blood'], correctAnswer: 'B) Chemical signals between organisms of the same species', explanation: 'Pheromone signaling involves chemical signals released by one organism that affect the behaviour or physiology of another organism of the same species. It is the 6th form of cellular communication.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Testosterone acting on breast tissue in males causing gynecomastia is an example of a hormone acting on a:', options: ['A) Primary target tissue', 'B) Secondary target tissue', 'C) Non-target tissue', 'D) Endocrine tissue'], correctAnswer: 'B) Secondary target tissue', explanation: 'Hormones can act on primary target tissues (main site of action) and secondary target tissues (other tissues with receptors). Breast tissue is a secondary target for testosterone/estrogen.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The Gi protein in signal transduction:', options: ['A) Stimulates adenylate cyclase', 'B) Inhibits adenylate cyclase', 'C) Activates phospholipase C', 'D) Opens ion channels directly'], correctAnswer: 'B) Inhibits adenylate cyclase', explanation: 'Gi (inhibitory G protein) inhibits adenylate cyclase, reducing cAMP production. This is opposite to Gs which stimulates adenylate cyclase and increases cAMP.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which of the following hormones has the SHORTEST half-life?', options: ['A) Thyroxine (T₄)', 'B) Cortisol', 'C) Epinephrine', 'D) Growth Hormone'], correctAnswer: 'C) Epinephrine', explanation: 'Epinephrine (a catecholamine) has a half-life of only seconds to minutes. T₄ has a half-life of ~7 days, cortisol ~90 minutes, and GH ~20 minutes. Water-soluble hormones are cleared fastest.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'Radioreceptor assay differs from RIA because it:', options: ['A) Uses radiation', 'B) Measures actual receptor binding', 'C) Is less sensitive', 'D) Cannot be quantified'], correctAnswer: 'B) Measures actual receptor binding', explanation: 'Radioreceptor assay uses receptor preparations instead of antibodies. It measures receptor binding capacity, making it a middle ground between RIA (immunological) and bioassay (biological response).', difficulty: 'hard' },
    { questionType: 'mcq', question: 'Which type of hormone has the LONGEST duration of action?', options: ['A) Peptide hormones', 'B) Catecholamines', 'C) Steroid hormones', 'D) Prostaglandins'], correctAnswer: 'C) Steroid hormones', explanation: 'Steroid hormones alter gene expression, which takes hours to days to produce effects and the effects persist long after the hormone is cleared. Peptides and catecholamines act quickly but briefly.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'In endocrine assessment, atrophy of an endocrine gland indicates:', options: ['A) Hyperfunction', 'B) Normal function', 'C) Hypofunction (reduced size and activity)', 'D) Neoplasia'], correctAnswer: 'C) Hypofunction (reduced size and activity)', explanation: 'Atrophy = reduced size and hypoactive gland. Hypertrophy = enlarged and hyperactive. Hyperplasia = increased cell number. These terms are used in endocrine gland assessment.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Up-regulation of hormone receptors results in:', options: ['A) Decreased hormone sensitivity', 'B) Increased hormone sensitivity', 'C) No change in sensitivity', 'D) Hormone degradation'], correctAnswer: 'B) Increased hormone sensitivity', explanation: 'Up-regulation increases the number of receptors on target tissue, making the cell MORE sensitive to the hormone. This is opposite to down-regulation which decreases sensitivity.', difficulty: 'easy' },
    { questionType: 'mcq', question: 'Which of the following endocrine glands is of neural crest origin?', options: ['A) Thyroid gland', 'B) Adrenal cortex', 'C) Adrenal medulla', 'D) Gonads'], correctAnswer: 'C) Adrenal medulla', explanation: 'The adrenal medulla is derived from neural crest cells (ectoderm). The adrenal cortex is mesodermal. This explains why the medulla produces catecholamines (modified neurons) and the cortex produces steroid hormones.', difficulty: 'medium' },
    { questionType: 'mcq', question: 'The term "hormone" was first used by:', options: ['A) Claude Bernard', 'B) Ernest Starling', 'C) William Bayliss', 'D) Thomas Addison'], correctAnswer: 'B) Ernest Starling', explanation: 'The term "hormone" (from Greek "hormon" = to set in motion) was coined by Ernest Starling in 1905 to describe secretin, discovered by Bayliss and Starling.', difficulty: 'hard' },

    // ADDITIONAL TRUE/FALSE
    { questionType: 'true_false', question: 'Permissive action means one hormone must be present for another to work fully. True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Permissive action: cortisol must be present for catecholamines to exert full vasoconstrictor effects. Without cortisol (as in Addison\'s disease), catecholamines are less effective.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'All hormones are produced exclusively by endocrine glands. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Hormones are also produced by non-endocrine tissues. Examples: kidneys (erythropoietin), heart (ANP), adipose tissue (leptin), GI tract (gastrin, secretin). These organs have endocrine functions.', difficulty: 'medium' },
    { questionType: 'true_false', question: 'The cGMP pathway is activated by Natriuretic Peptides (ANP, BNP). True or False?', options: ['True', 'False'], correctAnswer: 'True', explanation: 'Natriuretic peptides activate guanylate cyclase receptors, which produce cGMP as the second messenger. cGMP causes vasodilation and natriuresis (sodium excretion).', difficulty: 'hard' },
    { questionType: 'true_false', question: 'Gi protein stimulates adenylate cyclase. True or False?', options: ['True', 'False'], correctAnswer: 'False', explanation: 'Gi (inhibitory G protein) INHIBITS adenylate cyclase, reducing cAMP levels. Gs (stimulatory G protein) activates adenylate cyclase and increases cAMP.', difficulty: 'medium' },

    // ADDITIONAL FILL IN THE BLANK
    { questionType: 'fill_blank', question: 'The 6 forms of cellular communication are Endocrine, Paracrine, Autocrine, Synaptic, Neuroendocrine, and _____.', options: [], correctAnswer: 'Pheromone signaling', explanation: 'The 6 forms are: Endocrine (via blood), Paracrine (nearby cells), Autocrine (self), Synaptic (across synapse), Neuroendocrine (neuron to blood), and Pheromone (between organisms).', difficulty: 'medium' },
    { questionType: 'fill_blank', question: 'The Gq protein activates the enzyme _____ which produces IP₃ and DAG.', options: [], correctAnswer: 'Phospholipase C (PLC)', explanation: 'Gq activates Phospholipase C, which cleaves PIP₂ into two second messengers: IP₃ (mobilises Ca²⁺ from ER) and DAG (activates Protein Kinase C).', difficulty: 'hard' },
    { questionType: 'fill_blank', question: 'When one hormone enhances the effect of another beyond their sum, it is called _____ action.', options: [], correctAnswer: 'Synergistic', explanation: 'Synergistic action: the combined effect of two hormones is greater than the sum of their individual effects. Example: FSH + testosterone on spermatogenesis.', difficulty: 'medium' },

    // ADDITIONAL CLINICAL SCENARIOS
    { questionType: 'mcq', question: 'A patient with Addison\'s disease (cortisol deficiency) develops hypotension that is poorly responsive to catecholamines. This is explained by loss of:', options: ['A) Synergistic action', 'B) Permissive action of cortisol', 'C) Antagonistic action', 'D) Autocrine signaling'], correctAnswer: 'B) Permissive action of cortisol', explanation: 'Cortisol has a permissive effect on catecholamine-mediated vasoconstriction. Without cortisol (Addison\'s disease), catecholamines cannot effectively constrict blood vessels → refractory hypotension.', difficulty: 'hard' },
    { questionType: 'mcq', question: 'A patient with a pituitary adenoma presents with visual field defects. The MOST LIKELY visual field defect is:', options: ['A) Homonymous hemianopia', 'B) Bitemporal hemianopia', 'C) Central scotoma', 'D) Total blindness'], correctAnswer: 'B) Bitemporal hemianopia', explanation: 'Pituitary adenomas compress the optic chiasm from below, damaging the crossing nasal fibres. This causes loss of both temporal visual fields (bitemporal hemianopia).', difficulty: 'hard' },
  ],

  // ─── FLASHCARDS ────────────────────────────────────────────────────
  flashcards: [
    { front: 'What are the 3 structural classes of hormones?', back: 'Peptide/Protein (water-soluble, second messenger), Steroid (from cholesterol, lipid-soluble, intracellular receptor), Amine (from tyrosine — thyroid hormones and catecholamines).', difficulty: 'easy' },
    { front: 'What is the difference between paracrine and autocrine signaling?', back: 'Paracrine: acts on nearby/neighbouring cells (e.g., insulin on adjacent alpha cells). Autocrine: acts on the SAME cell that secreted it (e.g., IGF on producing cell).', difficulty: 'easy' },
    { front: 'Name the 6 anterior pituitary hormones (FLAT PiG)', back: 'FSH, LH, ACTH, TSH, Prolactin, GH.', difficulty: 'easy' },
    { front: 'What are the 2 posterior pituitary hormones?', back: 'ADH (Vasopressin) and Oxytocin. Note: they are SYNTHESISED in hypothalamus but STORED and RELEASED from posterior pituitary.', difficulty: 'easy' },
    { front: 'How does the cAMP second messenger pathway work?', back: 'Hormone binds surface receptor → Gs protein activated → Adenylate cyclase activated → ATP → cAMP → Protein Kinase A (PKA) → phosphorylates target proteins → cellular response. Signal is amplified at each step.', difficulty: 'medium' },
    { front: 'Why are bound hormones biologically inactive?', back: 'Bound hormones cannot cross capillary walls or bind target cell receptors. Only FREE (unbound) hormone is active. E.g., thyroid hormones are >99% protein-bound.', difficulty: 'medium' },
    { front: 'What is Sheehan\'s syndrome?', back: 'Postpartum pituitary necrosis caused by severe hemorrhage. The enlarged pituitary during pregnancy is vulnerable to ischemia. Results in panhypopituitarism: failure to lactate, amenorrhea, fatigue, etc.', difficulty: 'hard' },
    { front: 'What is Kallmann syndrome?', back: 'Developmental failure of GnRH neurons to migrate from olfactory placode. Results in: GnRH deficiency → hypogonadism (delayed puberty) + anosmia (loss of smell). Also called olfactory-genital dysplasia.', difficulty: 'hard' },
    { front: 'Graves\' disease vs Hashimoto\'s thyroiditis?', back: 'Graves\': Autoimmune HYPER-thyroidism (TSI antibodies stimulate TSH receptor). Hashimoto\'s: Autoimmune HYPO-thyroidism (antibodies destroy thyroid tissue).', difficulty: 'medium' },
    { front: 'What is the most common cause of Congenital Adrenal Hyperplasia?', back: '21-hydroxylase deficiency (>90% of cases). Blocks cortisol/aldosterone synthesis → excess ACTH → adrenal androgen overproduction → virilisation + salt wasting.', difficulty: 'hard' },
    { front: 'Steroid hormones vs Peptide hormones — mechanism of action?', back: 'Steroid: lipid-soluble → crosses membrane → binds intracellular receptor → acts as transcription factor → changes gene expression (slow, long-lasting). Peptide: water-soluble → surface receptor → second messengers (cAMP, Ca²⁺, etc.) → rapid response.', difficulty: 'medium' },
    { front: 'Name the main second messengers', back: 'cAMP, cGMP, Ca²⁺, IP₃ (inositol trisphosphate), DAG (diacylglycerol). Remember: CADILLAC mnemonic.', difficulty: 'medium' },
    { front: 'What are the 4 levels of hormone resistance?', back: '1) Membrane receptor mutation (GH, LH, FSH, ACTH), 2) Nuclear receptor defect (AR, TR, VDR, ER, GR), 3) Signaling pathway mutation (Albright\'s — Gs protein), 4) Post-receptor (Type 2 DM, leptin resistance).', difficulty: 'hard' },
    { front: 'Difference between RIA and ELISA?', back: 'RIA: uses radiation, very sensitive, can overestimate. ELISA: uses colour change, non-radioactive, high specificity, quantitative + qualitative, automated. Both are in vitro immunometric assays.', difficulty: 'medium' },
    { front: 'What is signal amplification?', back: 'One ligand molecule → activates several G proteins → each effector makes many second messengers → each activates many kinases = massive intracellular response from a single hormone molecule.', difficulty: 'medium' },
    { front: 'What is permissive hormone action?', back: 'One hormone must be present for another to work fully. Example: cortisol permits catecholamines to cause vasoconstriction. Without cortisol (Addison\'s), catecholamines are less effective.', difficulty: 'medium' },
    { front: 'What is synergistic hormone action?', back: 'Combined effect > sum of individual effects. Example: FSH + testosterone on spermatogenesis together produce a greater effect than either hormone alone.', difficulty: 'medium' },
    { front: 'Gs vs Gi vs Gq proteins?', back: 'Gs → stimulates adenylate cyclase → ↑cAMP. Gi → inhibits adenylate cyclase → ↓cAMP. Gq → activates phospholipase C → IP₃ + DAG.', difficulty: 'hard' },
    { front: 'What is up-regulation vs down-regulation?', back: 'Up-regulation: ↑receptors → ↑sensitivity to hormone. Down-regulation: ↓receptors → ↓sensitivity. Chronic hormone excess → down-regulation. Chronic deficiency → up-regulation.', difficulty: 'medium' },
    { front: 'Name the endocrine glands from neural crest origin', back: 'Adrenal medulla is of neural crest (ectoderm) origin. It produces catecholamines and is basically a modified sympathetic ganglion. Adrenal cortex is mesodermal.', difficulty: 'hard' },
  ],
};
