export type Platform = 'whatsapp' | 'telegram' | 'userbot';

export interface CommandData {
  slug: string;
  name: string;
  prefix: string;
  syntax: string;
  description: string;
  category: string;
  examples: string[];
  permissions: string;
  useCases: string[];
  relatedCommands: string[];
  aliases?: string[];
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string[];
}

export const whatsappCommands: CommandData[] = [
  {
    slug: 'sticker',
    name: 'sticker',
    prefix: '!',
    syntax: '!sticker | !sticker crop | !sticker circle | !sticker rounded',
    description: 'Converts any image, video, or GIF into a WhatsApp sticker. Send or reply to media with !sticker to create a full-size sticker. Use crop for square, circle for circular, or rounded for rounded corners.',
    category: 'Media',
    examples: ['Send an image and type !sticker', '!sticker crop to auto-crop to square', '!sticker circle for a circular mask', 'Reply to a GIF with !sticker'],
    permissions: 'Everyone',
    useCases: ['Creating custom stickers from photos', 'Making meme stickers for group chats', 'Converting GIFs into animated stickers'],
    relatedCommands: ['toimg', 'togif', 'removebg'],
    seoTitle: 'WhatsApp Sticker Bot Command - Create Stickers Instantly',
    seoDescription: 'Create WhatsApp stickers from any image, video, or GIF with the !sticker command. Free sticker maker bot with crop, circle, and rounded options.',
    seoKeywords: ['whatsapp sticker bot', 'whatsapp sticker maker', 'create whatsapp stickers', 'sticker bot free'],
  },
  {
    slug: 'ai',
    name: 'ai',
    prefix: '!',
    syntax: '!ai [your message] | reply to a message with !ai',
    description: 'Chat with an AI assistant directly in WhatsApp. Send any question and get an intelligent response. You can also reply to any message with !ai to ask the AI about that text.',
    category: 'AI',
    examples: ['!ai explain quantum computing', '!ai write a poem about Lagos', 'Reply to a message with !ai to ask about it', '!ai translate this to French: good morning'],
    permissions: 'Everyone (10 queries/day on free plan)',
    useCases: ['Getting instant answers to questions', 'Writing assistance and content generation', 'Translating and summarizing messages', 'Homework help in student groups'],
    relatedCommands: ['translate', 'define', 'digest', 'ask'],
    seoTitle: 'WhatsApp AI Chatbot Command - Free AI Assistant',
    seoDescription: 'Chat with AI directly in WhatsApp using the !ai command. Ask questions, get answers, generate content. Free to use.',
    seoKeywords: ['whatsapp ai bot', 'whatsapp ai chatbot', 'whatsapp ai assistant', 'free whatsapp ai'],
  },
  {
    slug: 'download',
    name: 'download',
    prefix: '!',
    syntax: '!download [URL]',
    description: 'Download videos from YouTube, TikTok, Instagram Reels, and other platforms directly into your WhatsApp chat. Videos are sent without watermarks.',
    category: 'Media',
    examples: ['!download https://youtube.com/watch?v=...', '!download https://tiktok.com/@user/video/...', '!download https://instagram.com/reel/...'],
    permissions: 'Everyone',
    useCases: ['Downloading TikTok videos without watermark', 'Saving YouTube videos to chat', 'Sharing Instagram Reels in groups'],
    relatedCommands: ['music', 'save', 'savestatus'],
    seoTitle: 'WhatsApp Video Downloader Bot - YouTube, TikTok, Instagram',
    seoDescription: 'Download YouTube, TikTok, and Instagram videos directly in WhatsApp. No watermarks, no apps needed. Free media downloader bot command.',
    seoKeywords: ['whatsapp video downloader bot', 'tiktok download whatsapp', 'youtube download whatsapp bot'],
  },
  {
    slug: 'trivia',
    name: 'trivia',
    prefix: '!',
    syntax: '!trivia',
    description: 'Start a trivia quiz game in your group. The bot sends a question with multiple-choice answers. Members reply with the letter to answer. Tracks scores on the leaderboard.',
    category: 'Games',
    examples: ['!trivia to start a question', 'Reply with A, B, C, or D to answer', '!leaderboard to see top scorers'],
    permissions: 'Everyone',
    useCases: ['Keeping groups active and engaged', 'Fun quiz nights in school groups', 'Team building activities', 'Educational quizzes'],
    relatedCommands: ['hangman', 'wordchain', 'leaderboard', '8ball'],
    seoTitle: 'WhatsApp Trivia Bot - Play Quiz Games in Groups',
    seoDescription: 'Play trivia quiz games directly in WhatsApp groups. Multiple choice questions, score tracking, leaderboards. Free trivia bot command.',
    seoKeywords: ['whatsapp trivia bot', 'whatsapp quiz bot', 'whatsapp game bot', 'trivia bot for groups'],
  },
  {
    slug: 'warn',
    name: 'warn',
    prefix: '!',
    syntax: '!warn @user [reason] | !warns @user | !unwarn @user',
    description: 'Issue warnings to group members who break rules. Track warning history per user. After a set number of warnings, the user can be automatically kicked or muted.',
    category: 'Moderation',
    examples: ['!warn @user spamming links', '!warns @user to check warning count', '!unwarn @user to remove a warning'],
    permissions: 'Group Admins only',
    useCases: ['Managing rule violations in large groups', 'Tracking repeat offenders', 'Enforcing group rules consistently'],
    relatedCommands: ['kick', 'promote', 'demote', 'tagall'],
    seoTitle: 'WhatsApp Group Warning System - Moderation Bot',
    seoDescription: 'Warn, track, and manage group members with the !warn command. Automatic moderation for WhatsApp groups. Free warning system bot.',
    seoKeywords: ['whatsapp moderation bot', 'whatsapp warn command', 'whatsapp group management', 'whatsapp admin bot'],
  },
  {
    slug: 'translate',
    name: 'translate',
    prefix: '!',
    syntax: '!translate [lang] [text] | reply with !translate [lang]',
    description: 'Translate text to any language. Reply to a message or type text after the language code. Supports 20+ languages including Yoruba, Hindi, Arabic, French, Spanish, and more.',
    category: 'Tools',
    examples: ['!translate fr Good morning everyone', '!translate es Hello, how are you?', 'Reply to a message with !translate yo'],
    permissions: 'Everyone',
    useCases: ['Communicating with members who speak different languages', 'Translating messages in multilingual groups', 'Learning new languages'],
    relatedCommands: ['ai', 'define', 'lang'],
    seoTitle: 'WhatsApp Translation Bot - Translate Messages Instantly',
    seoDescription: 'Translate WhatsApp messages to any language with !translate. Supports 20+ languages including Yoruba, French, Spanish, Arabic. Free translation bot.',
    seoKeywords: ['whatsapp translate bot', 'whatsapp translation', 'translate messages whatsapp'],
  },
  {
    slug: 'weather',
    name: 'weather',
    prefix: '!',
    syntax: '!weather [city name]',
    description: 'Get current weather for any city worldwide. Shows temperature, conditions, humidity, and wind speed.',
    category: 'Tools',
    examples: ['!weather Lagos', '!weather New York', '!weather London'],
    permissions: 'Everyone',
    useCases: ['Quick weather checks', 'Planning group events', 'Daily weather updates'],
    relatedCommands: ['ai', 'define', 'horoscope'],
    seoTitle: 'WhatsApp Weather Bot - Check Weather in Chat',
    seoDescription: 'Check weather for any city directly in WhatsApp with the !weather command. Temperature, humidity, wind speed. Free weather bot.',
    seoKeywords: ['whatsapp weather bot', 'weather bot command', 'check weather whatsapp'],
  },
  {
    slug: 'poll',
    name: 'poll',
    prefix: '!',
    syntax: '!poll [question] | [option1] | [option2] | ...',
    description: 'Create interactive polls in your WhatsApp group. Members vote using the !vote command. Results are tracked and displayed.',
    category: 'Engagement',
    examples: ['!poll Best food? | Jollof Rice | Fried Rice | Amala', '!vote 1 to vote for the first option'],
    permissions: 'Everyone can create, everyone can vote',
    useCases: ['Group decision making', 'Gathering opinions', 'Fun engagement in communities'],
    relatedCommands: ['vote', 'leaderboard', 'stats'],
    seoTitle: 'WhatsApp Poll Bot - Create Polls in Groups',
    seoDescription: 'Create polls in WhatsApp groups with !poll. Members vote, results tracked live. Free poll bot for WhatsApp groups.',
    seoKeywords: ['whatsapp poll bot', 'whatsapp voting bot', 'create polls whatsapp', 'poll bot free'],
  },
  {
    slug: 'welcome',
    name: 'welcome',
    prefix: '!',
    syntax: '!welcome [message] | !welcome off',
    description: 'Set a custom welcome message for new group members. The bot automatically greets anyone who joins. Use {name} to include the new member\'s name.',
    category: 'Group Management',
    examples: ['!welcome Welcome to the group, {name}!', '!welcome off to disable'],
    permissions: 'Group Admins only',
    useCases: ['Welcoming new members automatically', 'Sharing group rules on join', 'Making groups feel active and friendly'],
    relatedCommands: ['goodbye', 'settings', 'tagall'],
    seoTitle: 'WhatsApp Welcome Bot - Auto-Greet New Members',
    seoDescription: 'Automatically welcome new WhatsApp group members with custom messages. Free welcome bot with name personalization.',
    seoKeywords: ['whatsapp welcome bot', 'auto welcome whatsapp', 'welcome message bot', 'greet new members whatsapp'],
  },
  {
    slug: 'antispam',
    name: 'antidelete',
    prefix: '!',
    syntax: '!antidelete on | !antidelete off',
    description: 'Detect and recover deleted messages in your group. When enabled, the bot saves messages and re-posts them if the sender deletes them.',
    category: 'Moderation',
    examples: ['!antidelete on to enable', '!antidelete off to disable'],
    permissions: 'Group Admins only',
    useCases: ['Catching rule-breaking messages that get deleted', 'Accountability in group chats', 'Preventing evidence deletion'],
    relatedCommands: ['recover', 'warn', 'kick'],
    seoTitle: 'WhatsApp Anti-Delete Bot - Recover Deleted Messages',
    seoDescription: 'Recover deleted WhatsApp messages with the anti-delete bot command. Prevent members from hiding rule-breaking messages. Free moderation tool.',
    seoKeywords: ['whatsapp anti delete bot', 'recover deleted messages whatsapp', 'whatsapp moderation bot'],
  },
  {
    slug: 'tagall',
    name: 'tagall',
    prefix: '!',
    syntax: '!tagall [message]',
    description: 'Tag every member in the group with a single command. Useful for important announcements that everyone needs to see.',
    category: 'Group Management',
    examples: ['!tagall Meeting at 3pm today', '!tagall Check the new rules'],
    permissions: 'Group Admins only',
    useCases: ['Important group announcements', 'Event reminders', 'Emergency notifications'],
    relatedCommands: ['welcome', 'goodbye', 'settings'],
    seoTitle: 'WhatsApp Tag All Bot - Mention Everyone in Group',
    seoDescription: 'Tag all members in a WhatsApp group with one command. Perfect for announcements and important messages. Free admin bot.',
    seoKeywords: ['whatsapp tag all bot', 'mention everyone whatsapp', 'whatsapp group announcement bot'],
  },
  {
    slug: 'music',
    name: 'music',
    prefix: '!',
    syntax: '!music [song name]',
    description: 'Search for a song and get it sent as an audio file directly in chat. Just type the song name and optionally the artist.',
    category: 'Media',
    examples: ['!music Shape of You', '!music Burna Boy Last Last', '!music Wizkid Essence'],
    permissions: 'Everyone',
    aliases: ['song', 'findsong'],
    useCases: ['Finding and sharing music in groups', 'Quick song downloads', 'Music discovery'],
    relatedCommands: ['download', 'play', 'lyrics'],
    seoTitle: 'WhatsApp Music Bot - Download Songs in Chat',
    seoDescription: 'Download and share music directly in WhatsApp with the !music command. Search any song, get audio files instantly. Free music bot.',
    seoKeywords: ['whatsapp music bot', 'whatsapp song download bot', 'music download whatsapp'],
  },
  {
    slug: 'logo',
    name: 'logo',
    prefix: '!',
    syntax: '!logo [style] [name] | [tagline] #hex --size',
    description: 'Generate professional logos with 45+ styles. Supports taglines, custom hex colors, and size presets (square, wide, tall, banner, story). 10 styles free, remaining require Pro.',
    category: 'Tools',
    examples: ['!logo neon MyBrand', '!logo gradient CoolApp | Your Tagline #3498DB --wide', '!logo preview to see all styles'],
    permissions: 'Everyone (10 styles free, Pro for all)',
    aliases: ['logogen', 'logocreate', 'logomaker'],
    useCases: ['Creating logos for small businesses', 'Brand identity for social media', 'Quick logo drafts for projects'],
    relatedCommands: ['brandkit', 'carbon', 'img'],
    seoTitle: 'WhatsApp Logo Generator Bot - Create Logos in Chat',
    seoDescription: 'Generate professional logos with 45+ styles directly in WhatsApp. Custom colors, taglines, multiple sizes. Free logo maker bot.',
    seoKeywords: ['whatsapp logo generator', 'logo maker bot', 'create logo whatsapp', 'free logo bot'],
  },
  {
    slug: 'digest',
    name: 'digest',
    prefix: '!',
    syntax: '!digest | !digest today | !digest 50',
    description: 'Generate an AI summary of recent group messages. Great for catching up on busy groups. Shows key topics, active participants, and highlights.',
    category: 'AI',
    examples: ['!digest for last few hours', '!digest today for full day', '!digest 50 for last 50 messages'],
    permissions: 'Everyone (groups only)',
    aliases: ['summary', 'tldr'],
    useCases: ['Catching up on missed group conversations', 'Getting daily group summaries', 'Finding key discussions quickly'],
    relatedCommands: ['ai', 'recap', 'spy'],
    seoTitle: 'WhatsApp Group Summary Bot - AI Chat Digest',
    seoDescription: 'Get AI-powered summaries of WhatsApp group chats with !digest. Catch up on missed messages, see key topics and active members. Free.',
    seoKeywords: ['whatsapp summary bot', 'whatsapp group digest', 'ai group summary whatsapp'],
  },
  {
    slug: 'scan',
    name: 'scan',
    prefix: '!',
    syntax: '!scan (reply to receipt/invoice photo)',
    description: 'Scan a receipt or invoice photo using AI vision. Extracts store name, items, prices, subtotal, tax, total, and payment method automatically.',
    category: 'AI',
    examples: ['Reply to a receipt photo with !scan', '!scan this is in euros (add context)'],
    permissions: 'Everyone',
    aliases: ['receipt', 'invoice'],
    useCases: ['Expense tracking from receipts', 'Splitting bills in group chats', 'Digitizing paper receipts'],
    relatedCommands: ['ai', 'ocr', 'calc'],
    seoTitle: 'WhatsApp Receipt Scanner Bot - AI Invoice Reader',
    seoDescription: 'Scan receipts and invoices directly in WhatsApp using AI. Extract items, prices, totals automatically. Free receipt scanner bot.',
    seoKeywords: ['whatsapp receipt scanner', 'whatsapp invoice bot', 'scan receipt whatsapp'],
  },
];

export const telegramCommands: CommandData[] = [
  {
    slug: 'start',
    name: 'start',
    prefix: '/',
    syntax: '/start',
    description: 'Initialize the bot and get a welcome message with quick-start instructions. This is the first command you run after adding the bot to your group.',
    category: 'General',
    examples: ['/start in a private chat with the bot', 'Add bot to group, then /start'],
    permissions: 'Everyone',
    useCases: ['Setting up the bot for the first time', 'Getting help and instructions'],
    relatedCommands: ['help', 'ping', 'settings'],
    seoTitle: 'Telegram Group Management Bot - Get Started Free',
    seoDescription: 'Set up a free Telegram group management bot with /start. Anti-spam, moderation, games, AI chat. No coding required.',
    seoKeywords: ['telegram group bot', 'telegram management bot', 'telegram bot setup'],
  },
  {
    slug: 'antiflood',
    name: 'antiflood',
    prefix: '/',
    syntax: '/antiflood [number] | /antiflood off',
    description: 'Set flood detection limit. When a user sends more than the set number of messages in 10 seconds, they get auto-muted. Protects your group from spam attacks.',
    category: 'Moderation',
    examples: ['/antiflood 5 to mute after 5 rapid messages', '/antiflood off to disable'],
    permissions: 'Group Admins only',
    useCases: ['Stopping spam bots', 'Preventing flood attacks', 'Keeping group chat readable'],
    relatedCommands: ['antilink', 'antiraid', 'blacklist'],
    seoTitle: 'Telegram Anti-Flood Bot - Stop Spam Attacks',
    seoDescription: 'Protect Telegram groups from flood and spam attacks with /antiflood. Auto-mute rapid message senders. Free anti-spam bot.',
    seoKeywords: ['telegram anti flood bot', 'telegram anti spam', 'telegram group protection', 'stop spam telegram'],
  },
  {
    slug: 'ban',
    name: 'ban',
    prefix: '/',
    syntax: '/ban @user [reason] | /unban @user',
    description: 'Ban a user from the group. They will be removed and unable to rejoin until unbanned. Optionally provide a reason for the ban.',
    category: 'Moderation',
    examples: ['/ban @spammer', '/ban @user breaking rules', '/unban @user'],
    permissions: 'Group Admins only',
    useCases: ['Removing spammers permanently', 'Enforcing group rules', 'Managing toxic members'],
    relatedCommands: ['mute', 'kick', 'warn', 'federation'],
    seoTitle: 'Telegram Ban Bot - Remove Users from Groups',
    seoDescription: 'Ban and unban users in Telegram groups with the /ban command. Free group moderation bot with reason tracking.',
    seoKeywords: ['telegram ban bot', 'telegram moderation', 'ban user telegram group'],
  },
  {
    slug: 'welcome',
    name: 'welcome',
    prefix: '/',
    syntax: '/welcome [message] | /welcome off',
    description: 'Set a custom welcome message for new group members. Supports variables like {name}, {group}, and {count} for personalization.',
    category: 'Group Management',
    examples: ['/welcome Hey {name}, welcome to {group}!', '/welcome off to disable'],
    permissions: 'Group Admins only',
    useCases: ['Greeting new members', 'Sharing rules on join', 'Building community culture'],
    relatedCommands: ['captcha', 'rules', 'joinapproval'],
    seoTitle: 'Telegram Welcome Bot - Auto-Greet New Members',
    seoDescription: 'Automatically welcome new Telegram group members with custom messages. Free welcome bot with name, group, and count variables.',
    seoKeywords: ['telegram welcome bot', 'auto welcome telegram', 'telegram group welcome message'],
  },
  {
    slug: 'captcha',
    name: 'captcha',
    prefix: '/',
    syntax: '/captcha on | /captcha off',
    description: 'Enable CAPTCHA verification for new members. New joiners must solve a simple challenge before they can post. Stops automated spam bots from flooding your group.',
    category: 'Moderation',
    examples: ['/captcha on to enable', '/captcha off to disable'],
    permissions: 'Group Admins only',
    useCases: ['Blocking automated spam bots', 'Verifying human members', 'Preventing raid attacks'],
    relatedCommands: ['welcome', 'antiflood', 'joinapproval'],
    seoTitle: 'Telegram CAPTCHA Bot - Verify New Members',
    seoDescription: 'Add CAPTCHA verification to your Telegram group. Block spam bots, verify humans. Free anti-bot protection.',
    seoKeywords: ['telegram captcha bot', 'telegram verify members', 'telegram anti bot', 'telegram group security'],
  },
  {
    slug: 'federation',
    name: 'federation',
    prefix: '/',
    syntax: '/newfed [name] | /joinfed [id] | /fban @user',
    description: 'Create and manage ban federations across multiple groups. When you ban someone in one group, they get banned in all federated groups automatically.',
    category: 'Moderation',
    examples: ['/newfed My Network', '/joinfed abc123', '/fban @spammer'],
    permissions: 'Group Admins / Federation Owner',
    useCases: ['Managing bans across multiple groups', 'Network-wide spam protection', 'Coordinated moderation for communities'],
    relatedCommands: ['ban', 'gban', 'blacklist'],
    seoTitle: 'Telegram Ban Federation - Cross-Group Moderation',
    seoDescription: 'Create ban federations across Telegram groups. Ban a spammer once, banned everywhere. Free cross-group moderation bot.',
    seoKeywords: ['telegram federation bot', 'telegram cross group ban', 'telegram multi group moderation'],
  },
  {
    slug: 'notes',
    name: 'notes',
    prefix: '/',
    syntax: '/save [name] [content] | #name | /notes | /clear [name]',
    description: 'Save and retrieve group notes. Create reusable messages that any member can trigger by typing #notename. Great for FAQs, rules, and announcements.',
    category: 'Group Management',
    examples: ['/save rules Please read the pinned message', 'Type #rules to retrieve it', '/notes to list all', '/clear rules to delete'],
    permissions: 'Admins to save/clear, everyone to retrieve',
    useCases: ['Group FAQs', 'Quick access to rules and info', 'Reusable announcements'],
    relatedCommands: ['filters', 'rules', 'pins'],
    seoTitle: 'Telegram Notes Bot - Save Group Messages',
    seoDescription: 'Save and retrieve group notes in Telegram with #triggers. Create FAQs, rules, announcements. Free group notes bot.',
    seoKeywords: ['telegram notes bot', 'telegram save messages', 'telegram group faq bot'],
  },
  {
    slug: 'ai',
    name: 'ai',
    prefix: '/',
    syntax: '/ai [question] | reply to a message with /ai',
    description: 'Ask the AI assistant any question. Powered by advanced language models. Reply to any message to ask the AI about it. Works in groups and private chats.',
    category: 'AI',
    examples: ['/ai explain machine learning', '/ai write a poem', 'Reply to a message with /ai'],
    permissions: 'Everyone',
    useCases: ['Getting instant answers', 'Content generation', 'Language help', 'Homework assistance'],
    relatedCommands: ['translate', 'stickers', 'fun'],
    seoTitle: 'Telegram AI Bot - Free AI Chat Assistant',
    seoDescription: 'Chat with AI directly in Telegram using /ai. Ask questions, generate content, get help. Free AI assistant bot.',
    seoKeywords: ['telegram ai bot', 'telegram chatbot ai', 'free telegram ai', 'telegram ai assistant'],
  },
  {
    slug: 'stickers',
    name: 'stickers',
    prefix: '/',
    syntax: '/kang | /stickerpack | /getsticker',
    description: 'Steal stickers to your own pack, create new sticker packs, and convert stickers to images. Full sticker management toolkit.',
    category: 'Media',
    examples: ['/kang to steal a sticker', '/stickerpack to see your pack', '/getsticker to convert to image'],
    permissions: 'Everyone',
    useCases: ['Building custom sticker packs', 'Converting stickers to images', 'Sticker collection management'],
    relatedCommands: ['fun', 'mediatools', 'imageedit'],
    seoTitle: 'Telegram Sticker Bot - Create Custom Sticker Packs',
    seoDescription: 'Create and manage Telegram sticker packs. Steal stickers, convert to images, build custom packs. Free sticker bot.',
    seoKeywords: ['telegram sticker bot', 'telegram sticker pack', 'create telegram stickers', 'telegram sticker maker'],
  },
  {
    slug: 'xp',
    name: 'xp',
    prefix: '/',
    syntax: '/xp | /leaderboard | /rank',
    description: 'Gamified XP system for your group. Members earn XP by chatting, level up, and compete on the leaderboard. Encourages group activity.',
    category: 'Engagement',
    examples: ['/xp to check your level', '/leaderboard to see top members', '/rank @user to check their rank'],
    permissions: 'Everyone',
    useCases: ['Encouraging group participation', 'Gamifying community engagement', 'Rewarding active members'],
    relatedCommands: ['karma', 'games', 'fun'],
    seoTitle: 'Telegram XP Bot - Gamify Group Engagement',
    seoDescription: 'Add an XP and leveling system to your Telegram group. Leaderboards, ranks, levels. Free engagement bot.',
    seoKeywords: ['telegram xp bot', 'telegram level bot', 'telegram leaderboard', 'telegram engagement bot'],
  },
];

export const userbotCommands: CommandData[] = [
  {
    slug: 'alive',
    name: 'alive',
    prefix: '.',
    syntax: '.alive',
    description: 'Check if the userbot is running. Sends a status message with uptime, version, and system info. Also resets the deadman switch timer if active.',
    category: 'System',
    examples: ['.alive to check status'],
    permissions: 'Owner / Sudo users',
    useCases: ['Verifying the userbot is online', 'Checking system uptime', 'Resetting deadman switch'],
    relatedCommands: ['ping', 'setprefix', 'setalive'],
    seoTitle: 'Telegram Userbot Alive Command - Check Bot Status',
    seoDescription: 'Check if your Telegram userbot is running with the .alive command. Shows uptime, version, system info. Free userbot.',
    seoKeywords: ['telegram userbot alive', 'telegram userbot commands', 'check userbot status'],
  },
  {
    slug: 'ping',
    name: 'ping',
    prefix: '.',
    syntax: '.ping',
    description: 'Quick ping to check response time of the userbot. Shows latency in milliseconds. Fastest way to verify the bot is responsive.',
    category: 'System',
    examples: ['.ping'],
    permissions: 'Owner / Sudo users',
    useCases: ['Testing connection speed', 'Verifying bot responsiveness'],
    relatedCommands: ['alive', 'setprefix'],
    seoTitle: 'Telegram Userbot Ping Command',
    seoDescription: 'Check your Telegram userbot response time with .ping. Shows latency in milliseconds.',
    seoKeywords: ['telegram userbot ping', 'userbot latency check'],
  },
  {
    slug: 'ban',
    name: 'ban',
    prefix: '.',
    syntax: '.ban @user [reason] | .unban @user',
    description: 'Ban a user from the current group using your Telegram account. Works as if you manually banned them. No bot permissions needed since it uses your admin rights.',
    category: 'Admin',
    examples: ['.ban @spammer', '.ban @user breaking rules', '.unban @user'],
    permissions: 'Owner / Sudo users with admin rights',
    useCases: ['Quick moderation from any device', 'Banning users without opening Telegram app', 'Automated moderation scripts'],
    relatedCommands: ['mute', 'kick', 'gban', 'warn'],
    seoTitle: 'Telegram Userbot Ban Command - Quick Moderation',
    seoDescription: 'Ban users instantly in Telegram groups with the .ban userbot command. Uses your admin rights directly. Free userbot.',
    seoKeywords: ['telegram userbot ban', 'telegram userbot moderation', 'userbot admin commands'],
  },
  {
    slug: 'gban',
    name: 'gban',
    prefix: '.',
    syntax: '.gban @user [reason] | .ungban @user | .gbanlist',
    description: 'Globally ban a user across ALL groups where you are admin. One command bans them everywhere. The userbot iterates through your groups and bans the user in each one.',
    category: 'Admin',
    examples: ['.gban @spammer', '.gban @user crypto scammer', '.ungban @user', '.gbanlist to see all gbanned users'],
    permissions: 'Owner only',
    useCases: ['Banning persistent spammers across all groups', 'Network-wide spam protection', 'Coordinated anti-scam actions'],
    relatedCommands: ['ban', 'kick', 'mute'],
    seoTitle: 'Telegram Global Ban (GBan) - Ban Across All Groups',
    seoDescription: 'Ban a user across ALL your Telegram groups with one .gban command. Network-wide spam protection. Free userbot.',
    seoKeywords: ['telegram gban', 'telegram global ban', 'ban across all groups telegram', 'userbot gban'],
  },
  {
    slug: 'purge',
    name: 'purge',
    prefix: '.',
    syntax: '.purge [count] | .purgeme [count]',
    description: 'Mass delete messages in a chat. Reply to a message and use .purge to delete everything from that message to the latest. Or use .purgeme to delete only your own messages.',
    category: 'Admin',
    examples: ['Reply to a message then .purge', '.purge 50 to delete last 50', '.purgeme 10 to delete your last 10'],
    permissions: 'Owner / Sudo users with delete rights',
    useCases: ['Cleaning up spam in groups', 'Removing accidental messages', 'Clearing chat history'],
    relatedCommands: ['ban', 'mute', 'kick'],
    seoTitle: 'Telegram Purge Command - Mass Delete Messages',
    seoDescription: 'Mass delete messages in Telegram with the .purge userbot command. Clean spam, remove unwanted messages. Free userbot.',
    seoKeywords: ['telegram purge messages', 'telegram mass delete', 'delete messages telegram userbot'],
  },
  {
    slug: 'afk',
    name: 'afk',
    prefix: '.',
    syntax: '.afk [reason] | .afk off',
    description: 'Set yourself as Away From Keyboard. When someone tags you or sends you a message, the userbot automatically replies with your AFK reason. Auto-clears when you type .afk off.',
    category: 'Utility',
    examples: ['.afk studying', '.afk busy in meeting', '.afk off to disable'],
    permissions: 'Owner / Sudo users',
    useCases: ['Auto-replying when you are busy', 'Letting contacts know you are unavailable', 'Automatic status management'],
    relatedCommands: ['pmpermit', 'setalive', 'settings'],
    seoTitle: 'Telegram AFK Bot - Auto Reply When Away',
    seoDescription: 'Set AFK status on Telegram with auto-reply. Let contacts know you are busy. Free userbot AFK command.',
    seoKeywords: ['telegram afk bot', 'telegram auto reply away', 'telegram userbot afk'],
  },
  {
    slug: 'pmpermit',
    name: 'pmpermit',
    prefix: '.',
    syntax: '.permit @user | .unpermit @user | .pmpermit on/off',
    description: 'Control who can PM you. When enabled, unknown users get a warning message when they DM you. After multiple ignored warnings, they get blocked automatically. Whitelist trusted users with .permit.',
    category: 'Privacy',
    examples: ['.pmpermit on to enable', '.permit @friend to whitelist', '.unpermit @user to remove', '.block @user to block directly'],
    permissions: 'Owner only',
    useCases: ['Blocking spam DMs', 'Controlling who can message you', 'Anti-scam protection for your account'],
    relatedCommands: ['afk', 'gban', 'settings'],
    seoTitle: 'Telegram PM Permit - Control Who Messages You',
    seoDescription: 'Control who can DM you on Telegram with PM Permit. Auto-warn and block unknown senders. Free privacy userbot.',
    seoKeywords: ['telegram pm permit', 'telegram block spam dms', 'telegram privacy bot', 'userbot pm control'],
  },
  {
    slug: 'sticker',
    name: 'sticker',
    prefix: '.',
    syntax: '.kang | .sticker | .stickerpack',
    description: 'Steal stickers to your personal pack, create new sticker packs, and manage your sticker collection. Reply to any sticker with .kang to add it to your pack.',
    category: 'Media',
    examples: ['Reply to sticker with .kang', '.stickerpack to view your pack'],
    permissions: 'Owner / Sudo users',
    useCases: ['Building sticker collections', 'Stealing stickers from other packs', 'Creating custom sticker packs'],
    relatedCommands: ['media', 'fun'],
    seoTitle: 'Telegram Userbot Sticker Commands',
    seoDescription: 'Steal and manage Telegram stickers with userbot commands. Build custom sticker packs. Free userbot.',
    seoKeywords: ['telegram userbot sticker', 'telegram kang sticker', 'userbot sticker pack'],
  },
  {
    slug: 'translate',
    name: 'translate',
    prefix: '.',
    syntax: '.tr [lang] [text] | reply with .tr [lang]',
    description: 'Translate any text to another language. Reply to a message or type text after the language code. Supports all major languages.',
    category: 'Utility',
    examples: ['.tr es Hello everyone', 'Reply to message with .tr fr', '.tr yo Good morning'],
    permissions: 'Owner / Sudo users',
    useCases: ['Quick translations in multilingual chats', 'Understanding foreign messages', 'Communicating across languages'],
    relatedCommands: ['ai', 'search', 'texttools'],
    seoTitle: 'Telegram Userbot Translate - Instant Translation',
    seoDescription: 'Translate messages instantly in Telegram with the .tr userbot command. All major languages supported. Free.',
    seoKeywords: ['telegram userbot translate', 'telegram translation bot', 'translate messages telegram'],
  },
  {
    slug: 'antiflood',
    name: 'antiflood',
    prefix: '.',
    syntax: '.antiflood [limit] | .antiflood off',
    description: 'Set flood protection for groups. When a user sends more messages than the limit within 10 seconds, they get auto-muted. Protects groups from spam attacks using your admin rights.',
    category: 'Moderation',
    examples: ['.antiflood 5 to mute after 5 rapid messages', '.antiflood off to disable'],
    permissions: 'Owner / Sudo users with admin rights',
    useCases: ['Protecting groups from flood attacks', 'Auto-muting spammers', 'Keeping chat readable during raids'],
    relatedCommands: ['gban', 'ban', 'mute'],
    seoTitle: 'Telegram Userbot Anti-Flood - Stop Spam Attacks',
    seoDescription: 'Protect Telegram groups from spam floods with .antiflood userbot command. Auto-mute rapid senders. Free.',
    seoKeywords: ['telegram userbot antiflood', 'telegram spam protection', 'userbot anti spam'],
  },
];

export const allCommands = {
  whatsapp: whatsappCommands,
  telegram: telegramCommands,
  userbot: userbotCommands,
};

export function getCommandBySlug(platform: Platform, slug: string): CommandData | undefined {
  return allCommands[platform].find(c => c.slug === slug);
}

export function getCommandsByCategory(platform: Platform, category: string): CommandData[] {
  return allCommands[platform].filter(c => c.category === category);
}

export function getAllCategories(platform: Platform): string[] {
  return [...new Set(allCommands[platform].map(c => c.category))];
}

export const platformMeta: Record<Platform, { name: string; prefix: string; description: string; icon: string }> = {
  whatsapp: {
    name: 'WhatsApp Bot',
    prefix: '!',
    description: 'Connect via QR code scan. 80+ commands for group automation, AI chat, media tools, games, and moderation.',
    icon: 'W',
  },
  telegram: {
    name: 'Telegram Bot',
    prefix: '/',
    description: 'Official Bot API via @BotFather token. Zero ban risk. Group management, anti-spam, games, AI, and 50+ commands.',
    icon: 'T',
  },
  userbot: {
    name: 'Telegram Userbot',
    prefix: '.',
    description: 'Automate your real Telegram account via MTProto (GramJS). Admin actions, global bans, purge, PM permit, and advanced tools.',
    icon: 'U',
  },
};
