export interface LandingPage {
  slug: string;
  title: string;
  heading: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  keywords: string[];
  category: 'country' | 'audience' | 'feature' | 'platform';
}

export const landingPages: LandingPage[] = [
  // Country pages - WhatsApp
  { slug: 'whatsapp-bot-nigeria', title: 'WhatsApp Bot Nigeria', heading: 'Best WhatsApp Bot for Nigeria', description: 'Free WhatsApp bot for Nigerian groups and businesses. Naira pricing, local payment, community-focused features.', seoTitle: 'Best Free WhatsApp Bot in Nigeria (2026)', seoDescription: 'Free WhatsApp bot for Nigeria. Group management, AI replies, stickers, games. Naira pricing starting at N500/month.', keywords: ['whatsapp bot nigeria', 'free whatsapp bot nigeria', 'best whatsapp bot naija'], category: 'country' },
  { slug: 'whatsapp-bot-south-africa', title: 'WhatsApp Bot South Africa', heading: 'WhatsApp Bot for South Africa', description: 'WhatsApp automation for South African groups and businesses. Community management and AI assistant.', seoTitle: 'WhatsApp Bot South Africa - Free Group Automation', seoDescription: 'WhatsApp bot for South African groups. Free AI assistant, stickers, games, moderation. Community automation.', keywords: ['whatsapp bot south africa', 'whatsapp automation south africa', 'free bot south africa'], category: 'country' },
  { slug: 'whatsapp-bot-india', title: 'WhatsApp Bot India', heading: 'WhatsApp Bot for India', description: 'WhatsApp automation for Indian groups. Hindi translation, community management, and AI assistant.', seoTitle: 'WhatsApp Bot India - Free Group Automation Tool', seoDescription: 'WhatsApp bot for Indian groups. Hindi support, AI assistant, group management. Free automation tool.', keywords: ['whatsapp bot india', 'whatsapp automation india', 'free whatsapp bot india'], category: 'country' },
  { slug: 'whatsapp-bot-kenya', title: 'WhatsApp Bot Kenya', heading: 'WhatsApp Bot for Kenya', description: 'Free WhatsApp bot for Kenyan communities and businesses. Group automation and AI.', seoTitle: 'Best WhatsApp Bot Kenya - Free Group Automation', seoDescription: 'Free WhatsApp bot for Kenya. Group management, AI replies, games. Perfect for Kenyan communities.', keywords: ['whatsapp bot kenya', 'free whatsapp bot kenya', 'whatsapp automation kenya'], category: 'country' },
  { slug: 'whatsapp-bot-ghana', title: 'WhatsApp Bot Ghana', heading: 'WhatsApp Bot for Ghana', description: 'Free WhatsApp bot for Ghanaian groups. Community management, AI, and engagement tools.', seoTitle: 'WhatsApp Bot Ghana - Free Group Automation', seoDescription: 'Free WhatsApp bot for Ghana. Group management, AI chat, games, stickers. Community automation.', keywords: ['whatsapp bot ghana', 'free whatsapp bot ghana', 'whatsapp automation ghana'], category: 'country' },
  { slug: 'whatsapp-bot-usa', title: 'WhatsApp Bot USA', heading: 'WhatsApp Bot for USA', description: 'WhatsApp automation for US businesses and groups. AI assistant and group management.', seoTitle: 'WhatsApp Bot USA - Automation for Groups and Business', seoDescription: 'WhatsApp bot for US groups and businesses. AI assistant, moderation, games. Free tier available.', keywords: ['whatsapp bot usa', 'whatsapp automation usa', 'whatsapp group bot america'], category: 'country' },
  { slug: 'whatsapp-bot-uk', title: 'WhatsApp Bot UK', heading: 'WhatsApp Bot for UK', description: 'WhatsApp automation for UK communities. Group management, AI chat, and engagement.', seoTitle: 'WhatsApp Bot UK - Free Group Automation Tool', seoDescription: 'WhatsApp bot for UK groups and communities. AI assistant, moderation, games. Free to start.', keywords: ['whatsapp bot uk', 'whatsapp automation uk', 'free whatsapp bot uk'], category: 'country' },
  { slug: 'whatsapp-bot-brazil', title: 'WhatsApp Bot Brazil', heading: 'WhatsApp Bot for Brazil', description: 'WhatsApp automation for Brazilian groups. Portuguese translation, community tools.', seoTitle: 'WhatsApp Bot Brazil - Free Group Automation', seoDescription: 'WhatsApp bot for Brazilian groups. Portuguese support, AI, games, moderation. Free automation.', keywords: ['whatsapp bot brazil', 'bot whatsapp brasil', 'whatsapp automation brazil'], category: 'country' },
  { slug: 'whatsapp-bot-egypt', title: 'WhatsApp Bot Egypt', heading: 'WhatsApp Bot for Egypt', description: 'WhatsApp automation for Egyptian groups. Arabic translation, community management.', seoTitle: 'WhatsApp Bot Egypt - Arabic Group Automation', seoDescription: 'WhatsApp bot for Egypt. Arabic support, AI assistant, group moderation. Free to use.', keywords: ['whatsapp bot egypt', 'whatsapp automation egypt', 'arabic whatsapp bot'], category: 'country' },
  { slug: 'whatsapp-bot-philippines', title: 'WhatsApp Bot Philippines', heading: 'WhatsApp Bot for Philippines', description: 'WhatsApp automation for Filipino communities. Group management and AI assistant.', seoTitle: 'WhatsApp Bot Philippines - Free Group Automation', seoDescription: 'WhatsApp bot for Filipino groups. AI assistant, games, stickers, moderation. Free tier available.', keywords: ['whatsapp bot philippines', 'free whatsapp bot philippines'], category: 'country' },
  // Country pages - Telegram
  { slug: 'telegram-bot-nigeria', title: 'Telegram Bot Nigeria', heading: 'Telegram Bot for Nigerian Groups', description: 'Free Telegram bot for Nigerian communities. Anti-spam, AI, games, and group management.', seoTitle: 'Best Telegram Bot Nigeria - Free Group Management', seoDescription: 'Free Telegram bot for Nigerian groups. Anti-spam, moderation, games, AI chat. Zero ban risk.', keywords: ['telegram bot nigeria', 'free telegram bot nigeria', 'telegram group bot naija'], category: 'country' },
  { slug: 'telegram-bot-india', title: 'Telegram Bot India', heading: 'Telegram Bot for Indian Groups', description: 'Telegram bot for Indian communities. Hindi translation, anti-spam, games, and AI.', seoTitle: 'Telegram Bot India - Free Group Management Bot', seoDescription: 'Telegram bot for Indian groups. Hindi support, anti-spam, games, AI. Free group management.', keywords: ['telegram bot india', 'telegram group bot india', 'free telegram bot india'], category: 'country' },
  { slug: 'telegram-bot-usa', title: 'Telegram Bot USA', heading: 'Telegram Bot for US Groups', description: 'Telegram bot for American communities. Moderation, AI, and engagement tools.', seoTitle: 'Telegram Bot USA - Group Management and Automation', seoDescription: 'Telegram bot for US groups. Anti-spam, moderation, AI chat, games. Free to use.', keywords: ['telegram bot usa', 'telegram group bot america', 'free telegram bot usa'], category: 'country' },
  // Audience pages
  { slug: 'whatsapp-bot-for-schools', title: 'WhatsApp Bot for Schools', heading: 'WhatsApp Bot for School Groups', description: 'Manage school and campus WhatsApp groups with AI quiz, moderation, and study tools.', seoTitle: 'WhatsApp Bot for Schools - Campus Group Management (Free)', seoDescription: 'Free WhatsApp bot for school groups. AI quiz, study notes, moderation, engagement. Perfect for campus communities.', keywords: ['whatsapp bot for schools', 'school whatsapp bot', 'campus group bot', 'student whatsapp bot'], category: 'audience' },
  { slug: 'whatsapp-bot-for-business', title: 'WhatsApp Bot for Business', heading: 'WhatsApp Bot for Business Automation', description: 'Automate customer support, FAQ responses, and business communications on WhatsApp.', seoTitle: 'WhatsApp Bot for Business - Free Customer Automation', seoDescription: 'Automate WhatsApp for your business. AI customer support, auto-replies, FAQ bot. Free tier with 300 messages/month.', keywords: ['whatsapp bot business', 'whatsapp business automation', 'whatsapp customer bot', 'business whatsapp bot'], category: 'audience' },
  { slug: 'whatsapp-bot-for-creators', title: 'WhatsApp Bot for Creators', heading: 'WhatsApp Bot for Content Creators', description: 'Manage fan communities, automate engagement, and grow your WhatsApp audience.', seoTitle: 'WhatsApp Bot for Creators - Community Management', seoDescription: 'Manage creator communities on WhatsApp. Auto-engagement, games, polls, AI chat. Free community management bot.', keywords: ['whatsapp bot creators', 'creator community bot', 'whatsapp fan group bot'], category: 'audience' },
  { slug: 'whatsapp-bot-for-churches', title: 'WhatsApp Bot for Churches', heading: 'WhatsApp Bot for Church Groups', description: 'Manage church and fellowship WhatsApp groups with devotionals, reminders, and moderation.', seoTitle: 'WhatsApp Bot for Churches - Fellowship Group Management', seoDescription: 'WhatsApp bot for church groups. Automated devotionals, prayer reminders, event polls, moderation. Free.', keywords: ['whatsapp bot church', 'church whatsapp bot', 'fellowship group bot'], category: 'audience' },
  { slug: 'whatsapp-bot-for-crypto', title: 'WhatsApp Bot for Crypto', heading: 'WhatsApp Bot for Crypto Communities', description: 'Manage crypto trading and discussion groups. Price alerts, anti-spam, and AI analysis.', seoTitle: 'WhatsApp Bot for Crypto Groups - Trading Community Management', seoDescription: 'WhatsApp bot for crypto communities. Price commands, anti-spam, AI analysis, group moderation. Free for trading groups.', keywords: ['whatsapp bot crypto', 'crypto whatsapp bot', 'trading group bot'], category: 'audience' },
  { slug: 'whatsapp-bot-for-gaming', title: 'WhatsApp Bot for Gaming', heading: 'WhatsApp Bot for Gaming Groups', description: 'Manage gaming communities with trivia, leaderboards, and team coordination.', seoTitle: 'WhatsApp Bot for Gaming Groups - Trivia and Leaderboards', seoDescription: 'WhatsApp bot for gaming communities. Trivia, leaderboards, team polls, event scheduling. Free gaming bot.', keywords: ['whatsapp bot gaming', 'gaming whatsapp bot', 'game bot whatsapp'], category: 'audience' },
  { slug: 'telegram-bot-for-groups', title: 'Telegram Bot for Groups', heading: 'Best Telegram Bot for Group Management', description: 'Manage Telegram groups with anti-spam, moderation, captcha, and engagement tools.', seoTitle: 'Best Telegram Bot for Groups - Anti-Spam and Moderation (Free)', seoDescription: 'Free Telegram group management bot. Anti-spam, captcha, moderation, warnings, XP system. Protect your group.', keywords: ['telegram bot for groups', 'telegram group management bot', 'telegram anti spam bot'], category: 'audience' },
  // Feature landing pages
  { slug: 'whatsapp-sticker-bot', title: 'WhatsApp Sticker Bot', heading: 'Free WhatsApp Sticker Maker Bot', description: 'Create stickers from any image, GIF, or video directly in WhatsApp. No app download needed.', seoTitle: 'Free WhatsApp Sticker Bot - Create Stickers Instantly', seoDescription: 'Make WhatsApp stickers from any image. Send media, type !sticker, get sticker. Crop, circle, rounded modes. Free.', keywords: ['whatsapp sticker bot', 'sticker maker bot free', 'create whatsapp stickers', 'sticker bot'], category: 'feature' },
  { slug: 'whatsapp-ai-bot', title: 'WhatsApp AI Bot', heading: 'Free WhatsApp AI Chatbot', description: 'AI assistant in WhatsApp powered by Google Gemini. Ask questions, write content, get help with anything.', seoTitle: 'Free WhatsApp AI Bot - AI Chat Assistant (Gemini Powered)', seoDescription: 'Free AI chatbot for WhatsApp. Ask questions, write content, translate, summarize. Powered by Google Gemini 2.0 Flash.', keywords: ['whatsapp ai bot', 'whatsapp ai chatbot free', 'ai assistant whatsapp', 'whatsapp chatgpt alternative'], category: 'feature' },
  { slug: 'whatsapp-download-bot', title: 'WhatsApp Download Bot', heading: 'WhatsApp Video Downloader Bot', description: 'Download TikTok, YouTube, and Instagram videos directly in WhatsApp chat without watermarks.', seoTitle: 'WhatsApp Video Downloader Bot - TikTok, YouTube, Instagram', seoDescription: 'Download videos from TikTok, YouTube, Instagram directly in WhatsApp. No watermark, no app. Free video downloader bot.', keywords: ['whatsapp download bot', 'whatsapp video downloader', 'tiktok download whatsapp', 'youtube download bot'], category: 'feature' },
  { slug: 'whatsapp-moderation-bot', title: 'WhatsApp Moderation Bot', heading: 'WhatsApp Group Moderation Bot', description: 'Anti-spam, anti-delete, warnings, kicks, and full group moderation for WhatsApp.', seoTitle: 'WhatsApp Moderation Bot - Anti-Spam Group Protection (Free)', seoDescription: 'Free WhatsApp moderation bot. Anti-spam, anti-delete, warnings, kick, promote. Protect your WhatsApp group.', keywords: ['whatsapp moderation bot', 'whatsapp anti spam', 'whatsapp group protection', 'whatsapp admin bot'], category: 'feature' },
  { slug: 'whatsapp-trivia-bot', title: 'WhatsApp Trivia Bot', heading: 'WhatsApp Trivia and Games Bot', description: 'Play trivia, hangman, word chain, and more in WhatsApp groups. Leaderboards and XP tracking.', seoTitle: 'WhatsApp Trivia Bot - Play Games in Groups (Free)', seoDescription: 'Play trivia games in WhatsApp groups. Multiple categories, leaderboards, hangman, word chain. Free game bot.', keywords: ['whatsapp trivia bot', 'whatsapp game bot', 'whatsapp quiz bot', 'trivia bot free'], category: 'feature' },
  { slug: 'whatsapp-music-bot', title: 'WhatsApp Music Bot', heading: 'WhatsApp Music Download Bot', description: 'Search and download songs directly in WhatsApp chat. Just type the song name.', seoTitle: 'WhatsApp Music Bot - Download Songs in Chat (Free)', seoDescription: 'Download music in WhatsApp. Search any song, get MP3 files instantly. Free music download bot command.', keywords: ['whatsapp music bot', 'whatsapp song download', 'music bot free', 'download music whatsapp'], category: 'feature' },
  { slug: 'whatsapp-translate-bot', title: 'WhatsApp Translate Bot', heading: 'WhatsApp Translation Bot', description: 'Translate messages to 20+ languages directly in WhatsApp. Works with replies.', seoTitle: 'WhatsApp Translate Bot - 20+ Languages (Free)', seoDescription: 'Translate WhatsApp messages instantly. 20+ languages including Yoruba, Hindi, Arabic, French, Spanish. Free.', keywords: ['whatsapp translate bot', 'whatsapp translation', 'translate in whatsapp', 'language bot'], category: 'feature' },
  { slug: 'whatsapp-reminder-bot', title: 'WhatsApp Reminder Bot', heading: 'WhatsApp Reminder and Scheduler Bot', description: 'Set reminders and schedule messages in WhatsApp. Never forget important tasks.', seoTitle: 'WhatsApp Reminder Bot - Schedule Messages and Tasks', seoDescription: 'Set reminders in WhatsApp. Schedule messages, create countdowns, get notified. Free reminder bot.', keywords: ['whatsapp reminder bot', 'whatsapp scheduler', 'schedule message whatsapp', 'reminder bot'], category: 'feature' },
  { slug: 'whatsapp-poll-bot', title: 'WhatsApp Poll Bot', heading: 'WhatsApp Poll and Voting Bot', description: 'Create polls in WhatsApp groups. Members vote, results tracked live.', seoTitle: 'WhatsApp Poll Bot - Create Group Polls (Free)', seoDescription: 'Create polls in WhatsApp groups. Multiple choice, live voting, results display. Free poll bot for groups.', keywords: ['whatsapp poll bot', 'whatsapp voting', 'poll in whatsapp group', 'create poll whatsapp'], category: 'feature' },
  { slug: 'whatsapp-welcome-bot', title: 'WhatsApp Welcome Bot', heading: 'WhatsApp Auto-Welcome Bot', description: 'Automatically welcome new group members with custom messages and rules.', seoTitle: 'WhatsApp Welcome Bot - Auto-Greet New Members (Free)', seoDescription: 'Automatically welcome new WhatsApp group members. Custom messages, name variables, rules display. Free.', keywords: ['whatsapp welcome bot', 'auto welcome whatsapp', 'welcome message bot', 'greet new members'], category: 'feature' },
  { slug: 'telegram-anti-spam-bot', title: 'Telegram Anti-Spam Bot', heading: 'Telegram Anti-Spam and Moderation Bot', description: 'Protect Telegram groups from spam with captcha, anti-flood, blacklist, and smart detection.', seoTitle: 'Telegram Anti-Spam Bot - Group Protection (Free)', seoDescription: 'Free Telegram anti-spam bot. Captcha verification, flood detection, blacklist, warn system. Protect your group.', keywords: ['telegram anti spam bot', 'telegram spam protection', 'telegram group protection', 'anti spam telegram'], category: 'feature' },
  { slug: 'telegram-ai-bot', title: 'Telegram AI Bot', heading: 'Telegram AI Chat Bot', description: 'AI assistant for Telegram groups. Ask questions, generate content, and get intelligent replies.', seoTitle: 'Telegram AI Bot - Free AI Assistant for Groups', seoDescription: 'Free AI bot for Telegram. Ask questions, generate content, summarize chats. Powered by Gemini.', keywords: ['telegram ai bot', 'telegram ai chatbot', 'telegram ai assistant', 'free telegram ai'], category: 'feature' },
  // Platform overview pages
  { slug: 'whatsapp-automation', title: 'WhatsApp Automation', heading: 'WhatsApp Automation Platform', description: 'Complete WhatsApp automation with 150+ commands, AI, moderation, media tools, and games.', seoTitle: 'WhatsApp Automation Platform - 150+ Commands (Free Tier)', seoDescription: 'Automate WhatsApp with 150+ commands. AI chat, moderation, stickers, games, downloads. Free tier available. No coding.', keywords: ['whatsapp automation', 'whatsapp automation tool', 'whatsapp automation platform', 'automate whatsapp'], category: 'platform' },
  { slug: 'telegram-automation', title: 'Telegram Automation', heading: 'Telegram Bot Automation Platform', description: 'Complete Telegram bot and userbot automation. Group management, AI, and 100+ commands.', seoTitle: 'Telegram Automation Platform - Bot and Userbot (Free)', seoDescription: 'Automate Telegram with bot and userbot. Group management, anti-spam, AI, 100+ commands. Free tier.', keywords: ['telegram automation', 'telegram bot automation', 'telegram automation tool', 'automate telegram'], category: 'platform' },
  { slug: 'telegram-userbot-commands', title: 'Telegram Userbot Commands', heading: 'Telegram Userbot Command List', description: 'Complete list of Telegram userbot commands. MTProto automation for your account.', seoTitle: 'Telegram Userbot Commands List - MTProto Automation', seoDescription: 'Full Telegram userbot command list. Admin, moderation, media, tools. MTProto automation guide.', keywords: ['telegram userbot commands', 'telegram userbot list', 'mtproto commands', 'userbot commands'], category: 'platform' },
  { slug: 'deploy-telegram-bot', title: 'Deploy Telegram Bot', heading: 'Deploy Your Telegram Bot', description: 'Deploy and host your Telegram bot with BotWave. No server management needed.', seoTitle: 'Deploy Telegram Bot - Free Hosting with BotWave', seoDescription: 'Deploy and host Telegram bot free. No server management, automatic restarts, 99.9% uptime. Connect via BotFather token.', keywords: ['deploy telegram bot', 'host telegram bot', 'telegram bot hosting free', 'run telegram bot'], category: 'platform' },
  { slug: 'what-is-botwave', title: 'What is BotWave', heading: 'What is BotWave?', description: 'BotWave is a multi-platform chat automation system for WhatsApp and Telegram. No coding required.', seoTitle: 'What is BotWave? - Chat Automation Platform Explained', seoDescription: 'BotWave is a WhatsApp and Telegram automation platform. 150+ commands, AI, moderation, games. No coding needed. Free tier.', keywords: ['what is botwave', 'botwave explained', 'botwave platform', 'botwave review'], category: 'platform' },
];
